### ISSUE TITLE
Using "flash" mode

### ISSUE THREAD

**Issue by SunboX** [phonegap/phonegap-plugin-barcodescanner#10]
Please add a method to enable/disable the flash mode. By now the Windows Phone implementation "flashes" all the time but there's no "flash-mode" using the android implementation.

**Comment by caipirginka** [comment]
On Android you can turn flash on/off using volume keys up/down, while this doesn't work on iOS and I can't find any other means to control the flash on iOS. 

**Comment by JpCapdevila** [comment]
+1 It would be nice to have the option to force the flash, I'm scanning QRs in a metallic plate and using the flash improves the readability (flash gives me a "uniform" reflection).

**Comment by simonpapworth6742** [comment]
+1

**Comment by fmmsilva** [comment]
+1

**Comment by dabontv** [comment]
+1, IOS scanner doesn't work well in low light situations

**Comment by bau720123** [comment]
hi all
is the "flash" mean "flashlight" ?
if yes
well...

if you are using PGB
https://build.phonegap.com/plugins/904

if you are using cordova
https://github.com/EddyVerbruggen/Flashlight-PhoneGap-Plugin

**Comment by Alplob** [comment]
Yes, this would be a good idea. Or even better, an 'auto' mode, if the contrast is not good enough, the light would be switched on automatically 😃

**Comment by JamesYuCN** [comment]
+1, Please add a option "FLASH":"ON"  , thanks .

**Comment by heshan-nibaya** [comment]
+1

**Comment by halmechanic** [comment]
+1

**Comment by vladpke** [comment]
+1

**Comment by rafwell** [comment]
+1

**Comment by EddyVerbruggen** [comment]
Landed in 6.0.4 on both iOS and Android. Just pass in showTorchButton : true as an option of the scan function.
