### ISSUE TITLE
Improvement readme.md

### ISSUE THREAD

**Issue by spottuit** [phonegap/phonegap-plugin-barcodescanner#100]
I already created an issue here:
https://github.com/wildabeast/BarcodeScanner/issues/314
but, I saw that repo was no longer maintained.

I have a suggestion:
- add the configuration line below because it isn't added to the config.xml automaticly. I had to go to https://build.phonegap.com/plugins/2421 to get the line, but before that I had to search alot to find it.

``` xml
 <gap:plugin name="com.phonegap.plugins.barcodescanner" version="2.2.0" /> 
```

**Comment by SunboX** [comment]
Shouldn't it be `4.1.0`?

https://github.com/phonegap/phonegap-plugin-barcodescanner/releases

**Comment by spottuit** [comment]
You are right. The PhoneGap Build Plugins Repository is deprecated. I found the plugin in npm: https://www.npmjs.com/package/phonegap-plugin-barcodescanner

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
