### ISSUE TITLE
Duplicate resource beep

### ISSUE THREAD

**Issue by bitflower** [phonegap/phonegap-plugin-barcodescanner#102]
Hi, I'm getting this error on an IONIC app:
- What went wrong:
  Execution failed for task ':mergeArmv7DebugResources'.
  > /platforms/android/res/raw/beep.ogg: Error: Duplicate resources: /platforms/android/res/raw/beep.ogg:raw/beep, /platforms/android/res/raw/beep.wav:raw/beep

Cordova 5.4.0
IONIC 1.7.8
Node 0.12.7

It seems the file extension is being ignored and so the 2 files are interpreted as one.

Any ideas?

**Comment by macdonst** [comment]
@bitflower that is correct Android behaviour. You can't have two resources with the same name but different file extensions. You have to give different files, different names before the extension.
