### ISSUE TITLE
not focus on windows phone 8

### ISSUE THREAD

**Issue by maffioli92** [phonegap/phonegap-plugin-barcodescanner#104]
Hi everyone,
this plugin doesn't work correctly on wp8. The camera light flashes intermittently and doesn't focus the qrcode or focus after much time. On android and IOS works correctly.

some help?

greetings.

**Comment by vladimir-kotikov** [comment]
@maffioli92, are you running this on windows phone device using cordova-wp8 or cordova-windows platform? Also, what device are you using?

**Comment by vladimir-kotikov** [comment]
Closing as no repro. @maffioli92 , in case if the issue still exists, please reopen this and add repro steps and information about cordova, platform(windows/wp8) and plugin versions and device model.

**Comment by arieldgiovanni** [comment]
Hi, I have the same problem with the cordova-wp8 platform, the device is a Nokia Lumia 720. 
Thanks
