### ISSUE TITLE
iOS: memory leaks, division by zero and the like in zxing-all-in-one.cpp?

### ISSUE THREAD

**Issue by convey-mane** [phonegap/phonegap-plugin-barcodescanner#106]
When opening the completed project of our App, which contains the barcodescanner plugin, for testing/debugging in Xcode (Version 7.1.1), and there doing "Product/Analyze", I get some (many) warnings – those in CDVBarcodeScanner.mm I already fixed (see #97).

But in zxing-all-in-one.cpp there are also some 27 problems – which I won't fix myself, not "speaking" C++. So I would like to post them here, not knowing, if those are real problems:
- `Use of memory after it is freed (within a call to '[…]')` – 15 times,
- `The result of the '<<' expression is undefined` – three times,
- `Potential memory leak  (within a call to '[…]')` – one time,
- `Potential leak of memory pointed to by '[…]'` – six times,
- `The right operand of '+' is a garbage value` – one time,
- `Division by zero` - one time.

Well, for me this all sounds unsettling (but as mentioned, without C++ experience, who knows if these are real bugs), and in Objective-C I always take _all_ compiler-messages and warnings seriously.

If anybody would like to take a look on this … if there's need for more information (e.g. exact positions of the warnings), let me know.

**Comment by macdonst** [comment]
@convey-mane the best thing to do is to send a PR to the official ZXing project so everyone who uses it can benefit.

https://github.com/zxing/zxing
