### ISSUE TITLE
How to use german translation?

### ISSUE THREAD

**Issue by kaju74** [phonegap/phonegap-plugin-barcodescanner#107]
Hi.

I'm using the plugin to scan a QR-code in my app. As soon as the camera window opens, the button to cancel the operation is named to...a well..."cancel" ;-) Is it possible to change it to german? I took a look into the source files an found a file called "strings.xml" in the "res"-folder, but don't know how to active it...

Regards,
Marc

**Comment by convey-mane** [comment]
@kaju74 (_the following is only valid for iOS!_): you won't find something translatable for this button, for it is a standard iOS one (UIBarButtonSystemItemCancel), which is displayed in the language the App itself runs in … if your App would be "allowed" to run German (and – of course – it does run on a German iOS device :wink:), then this button would automatically read "Abbrechen".

In your Info.plist you have to include something like this:
```
    <key>CFBundleLocalizations</key>
    <array>
      <string>en</string>
      <string>de</string>
    </array>
```

(or if ``CFBundleLocalizations`` is already there, extend it accordingly).
