### ISSUE TITLE
Blackberry10 - Both on error and on success functions execute

### ISSUE THREAD

**Issue by jmaster10** [phonegap/phonegap-plugin-barcodescanner#108]
Hello,

I'm experiencing strange activity when using the bar code scanner on a blackberry10 device (z10). Both the on error and on success calls are being trigger. Here is what is happening.
1. Scan bar code
2.onError function is called. Returns an error message of undefined
3.onSuccess function is called. Returns bar code information. 

Project details:
Cordova: 3.7
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
OS: Mac OS X Yosemite
Node Version: v0.12.7

Sample Code:

```
   cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      }, 
      function (error) {
          alert("Scanning failed: " + error);
      }
   );
```

Any idea how to prevent this behavior? 

Thanks,
J

**Comment by timwindsor** [comment]
Try with the latest Cordova and BlackBerry platforms. That should resolve it.
