### ISSUE TITLE
turning off camera icon

### ISSUE THREAD

**Issue by Frosty2** [phonegap/phonegap-plugin-barcodescanner#110]
When you scan a code on IOS there is a camera icon in the footer. This switches the camera view to be the front camera. Can this be remove. I'm guessing it's part of IOS

**Comment by S8ER01Z** [comment]
If you edit the CDVBarcodeScanner.mm file you can remove it from the toolbar.items array.

**Comment by jcesarmobile** [comment]
On iOS and Android you can use the option "showFlipCameraButton", set it to false to not show the button.
