### ISSUE TITLE
android barcode display chineese characters ?

### ISSUE THREAD

**Issue by scramatte** [phonegap/phonegap-plugin-barcodescanner#112]
Hello,

Any idea why barcode display chineese characters  on top / bottom bar ? 
I'm using Nexus 7 tablet with android 5. Please see attached screenshot.

Than you for your help

![screenshot_2015-11-24-16-11-56](https://cloud.githubusercontent.com/assets/188766/11370988/64537ccc-92c6-11e5-8c67-5846f87df61b.png)

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
