### ISSUE TITLE
Windows 8 plugin not working

### ISSUE THREAD

**Issue by tusharchutani** [phonegap/phonegap-plugin-barcodescanner#114]
Added the plugin using the CLI and hooked up a basic html button to the sample code for testing purposes. Built the app using cmd using cordova prepare windows8. When I try to run the app on a device I get the following error: 

could not copy the file ....winrtbarcodereader.winmd because it was not found 

Am I missing something or is this a known issue?

**Comment by vladimir-kotikov** [comment]
@tusharchutani, It works for me out-of-the box with latest cordova. Could you please post a repro steps and some details about your environment (at least cordova and windows platform versions).

**Comment by vladimir-kotikov** [comment]
Closing as no repro. @tusharchutani, in case if the issue still exists, please reopen this and add repro steps and information about cordova, platform and plugin versions.
