### ISSUE TITLE
Cancel scan In android device ,application go back two page.Does anyone know how to avoid it？

### ISSUE THREAD

**Issue by JoyceYy** [phonegap/phonegap-plugin-barcodescanner#115]

**Comment by lordgreg** [comment]
I'm having the exact same issue. We'll try to fix this internally and I'll provide possible workaround (if succeeded)

**Comment by JoyceYy** [comment]
I have fix it through update barcodescanner version from 2.0.1 to 4.0.1.Maybe can have a try.




------------------ 原始邮件 ------------------
发件人: "Gregor";<notifications@github.com>;
发送时间: 2016年1月28日(星期四) 下午4:20
收件人: "phonegap/phonegap-plugin-barcodescanner"<phonegap-plugin-barcodescanner@noreply.github.com>; 
抄送: ""<572333564@qq.com>; 
主题: Re: [phonegap-plugin-barcodescanner] Cancel scan In android device ,application go back two page.Does anyone know how to avoid it？ (#115)




I'm having the exact same issue. We'll try to fix this internally and I'll provide possible workaround (if succeeded)

**Comment by Fever905** [comment]
Was this ever resolved?
