### ISSUE TITLE
Scanning is too slow on iOS compared to Android

### ISSUE THREAD

**Issue by SunboX** [phonegap/phonegap-plugin-barcodescanner#118]
I'm using a iPhone 6 and a Sony Z1. The iOS scanner takes a lot more time to recognize a QR Code than the Android one. I didn't measure it, but I would say 5 to 10 times more time. Compared to other iOS QR Code reader apps, it's also a lot slower.

Maybe someone with iOS programming experience can take a look at the code, there must be some potential for improvement.

**Comment by bitflower** [comment]
I agree with this. 

Also I have made some tests ans disabled everything but QR and Data matrix but it didn't help.

It feels like the optical analyzing takes much longer.

**Comment by lj222kj** [comment]
Hey guys! I'm experiencing the same issue. Have you found a way to speed up the reading process?

**Comment by bitflower** [comment]
Nope, not yet, as mentioned.

**Comment by deepakanupalli** [comment]
We are experiencing the same issue, Iphone 6 scans the EAN 13 (ISBN) barcode very slowly when compared to Android.

**Comment by wesleywesley** [comment]
It is laughable / embarrassing how slow this is compared to https://github.com/tjwoon/csZBar

**Comment by Gp2mv3** [comment]
It's very slow on iphone 4s (ios 8.2) as well. 

I know he is getting old though... :smiley:

**Comment by lukyn-cz** [comment]
try to use AVCaptureSessionPresetMedium instead of AVCaptureSessionPresetHigh
in CDVBarcodeScanner.mm file

   // captureSession.sessionPreset = AVCaptureSessionPresetHigh;
    captureSession.sessionPreset = AVCaptureSessionPresetMedium;

**Comment by ChezFre** [comment]
I came here because scanning was incredibly slow on my iPhone 6S and I had to get the app very close in order to finally have it recognize a barcode (if it recognized it at all). Funny enough, it was the opposite of @lukyn-cz's comment that helped (albeit a little), changing the setting from Medium to High.

**Comment by EddyVerbruggen** [comment]
Version 6.0.4 didn't change the Medium/High setting mentioned in the previous post (because of varying results), but it did change a switch where the camera is hinted to look for objects 'near' the camera (as opposed to 'anywhere'). Hope that makes a bit of a difference..
