### ISSUE TITLE
ASCII 232 for recognizing GS1 not read on Android but on iOS

### ISSUE THREAD

**Issue by bitflower** [phonegap/phonegap-plugin-barcodescanner#121]
iOS recognizes the GS1 initial char 232 correctly (this line: https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/src/ios/zxing-all-in-one.cpp#L4697)

However on Android nothing is returned and the corresponding line is never hit. Meaning the byte stream of raw bytes does not include it.

Anyone around knowing in detail about the ZXing codec for Android?

**Comment by bitflower** [comment]
Why was this cloaed? Is there a solution?

I have implemented the fix in my fork. If this is not solved I will open a PR.

**Comment by vladimir-kotikov** [comment]
@bitflower, see #222 and please re-validate that issue is still actual after the latest changes in the plugin. If yes, feel free to reopen this.

And your PR is welcome :)
