### ISSUE TITLE
Is the zxing version used years away from the original zxing lib?

### ISSUE THREAD

**Issue by bitflower** [phonegap/phonegap-plugin-barcodescanner#124]
The maintained zxing lib is way more up to date than the one included in the android branch of the plugin:
https://github.com/zxing/zxing/tree/master/core/src/main/java/com/google/zxing

Why is this the case? Is it possible to include the latest or even better - stay up to date?

**Comment by dually8** [comment]
That has been my experience with this.  The data matrix scanner doesn't work accurately with iOS, so I forked the original repo and added in a more recent ZXing library (See here: https://github.com/dually8/BarcodeScanner).  I would like to see this repo get up-to-date on this.

**Comment by cougarten** [comment]
@dually8 which version of zxing did you use?

**Comment by dually8** [comment]
@cougarten the one from the TheLevelUp repo here: https://github.com/TheLevelUp/ZXingObjC

**Comment by jcesarmobile** [comment]
Closing as out of date, on iOS ZXing is not used, on Android it has been updated a few times since the issue was created
