### ISSUE TITLE
Using a usb-connected scanner?

### ISSUE THREAD

**Issue by lj222kj** [phonegap/phonegap-plugin-barcodescanner#126]
Hi!

I'm curious to see if there's been any testing using a usb-connected or bluetooth connected scanner to read barcodes?

**Comment by macdonst** [comment]
@lj222kj No, that is out of scope of this plugin.

**Comment by jfbloom22** [comment]
I am also looking for a usb-connected scanner Cordova plugin.  I found this one:  https://github.com/mribbons/cordova-plugin-cipherlab-rs30
but I was hoping to find a more generic one.  

The scanner acts like a keyboard for the most part and I am able to capture input via a form input field.  However, for my use case I would like to avoid using a form input box to capture the input.
