### ISSUE TITLE
When I use 'phonegap plugin add phonegap-plugin-barcodescanner' in my www folder under the original file is overwritten, I can revert to the original file?

### ISSUE THREAD

**Issue by Seekcy** [phonegap/phonegap-plugin-barcodescanner#129]
When I use 'phonegap plugin add phonegap-plugin-barcodescanner' in my www folder under the original file is overwritten, I can revert to the original file?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
