### ISSUE TITLE
Screen upside down on tablet device

### ISSUE THREAD

**Issue by NgYueHong** [phonegap/phonegap-plugin-barcodescanner#138]
I am using this plugin to add qr-code scanning function to my hybrid app build with Ionic framework. The plugin works well, except on tablet when the app is display in portrait, the screen is displayed upside down. This only happen on tablet, and no issue on phone. I have tried with several devices, but it all happen upside down on tablet device.

Hope there is a fix for this soon.

**Comment by certifiedloud** [comment]
+1, I get the same thing on an android handset.

**Comment by certifiedloud** [comment]
My issue seems to be described (and fixed) here: https://github.com/zxing/zxing/issues/484

I'm guessing that the release of zxing that fixes this issue for nexus 5x is newer than the release used in the cordova plugin.

**Comment by kozmanbalint** [comment]
+1, is there a chance to update zxing lib soon?

**Comment by mikejones3** [comment]
mike-eason pointed out on my ticket that I opened that this is the same thing. So I am adding my vote to have the upside down camera bug fixed.

**Comment by okonon** [comment]
Same thing is happening for us

**Comment by xynon** [comment]
I have the same issue on SM-T520 tablet with Android 4.4.2.

**Comment by edicius6** [comment]
Same issue of upside down camera when barcode scanning on my Nexus 5x w/ Android 6.0.1.

**Comment by okonon** [comment]
We decided not to support this Nexus 5x in production :(

**Comment by rudza** [comment]
@okonon But why? Is Nexus 5x is different than other devices with Android 6.*.*. version??

**Comment by mikejones3** [comment]
The camera was built upside-down in the 5x.

**Comment by rudza** [comment]
@mikejones3 What does that mean?

**Comment by edicius6** [comment]
Is there a way to put a simple button on the screen when in scan mode that allows the user to toggle between right-side-up and up-side-down presentation of the camera? This should have minimal impact on the existing code and support future hardware with the same reverse camera issue.

**Comment by edicius6** [comment]
Also, not sure if this helps or not, but it seems to just be an issue of using an outdated Google Camera API:
**http://www.theverge.com/2015/11/9/9696774/google-nexus-5x-upside-down-camera**

**Comment by mikejones3** [comment]
Exactly, there are apis to flip the camera. But I haven't found any plugins
that use or incorporate them yet

**Comment by voodoodrul** [comment]
+1

**Comment by EddyVerbruggen** [comment]
This issue shouls be fixed when you pull from the master branch of this repo as we've just merged the Telerik fork with this one.

**Comment by sarangan12** [comment]
This should be fixed with the latest merge from Telerik commit. I am closing this issue. If you still see the issue, feel free to reopen. Thanks

**Comment by kozmanbalint** [comment]
Works fine on Nexus 5X, Android 6.0.1.  :-)
Thanks!

**Comment by edicius6** [comment]
Works for me as well on Nexus 5X, Android 6.0.1. Thank you SO MUCH, guys!! =]

**Comment by Sundar-Ram** [comment]
Works for me as well on Nexus5X with this Telerik Plugin: http://plugins.telerik.com/cordova/plugin/barcodescanner . Thank you!
