### ISSUE TITLE
Problem with Android 6.0.1

### ISSUE THREAD

**Issue by debugerr** [phonegap/phonegap-plugin-barcodescanner#139]
I get an error on Android 6.0.1 saying that there was an error with the "Android Camera", (the message is in German, but it may translate to:

Unfortunately there was an error with the Android-Camera. It could be that you need to restart your device.

Does anyone see this?

**Comment by vrushankshukla** [comment]
I created an app using this same plugin but it's only works in android 4, I tested my app on android 5.1.1 and android 6.0.1, but it's not doing anything on a scan button click. Not opening the camera. Even I found none of my functions are working on those platform. 

Also I found following link, which may be help you:
https://cordova.apache.org/announcements/2015/11/09/cordova-android-5.0.0.html

**Comment by vrushankshukla** [comment]
I have the same error in Android 6.x.x. Unfortunately there was an error with the Android-Camera. It could be that you need to restart your device. Till Android 5.x.x, it's working but not for the Android 6. 

So how can I test with this Android zxing integration? I am totally new to this. What steps I need to follow?

Sicerely

**Comment by debugerr** [comment]
For me, this problem only shows when I add the facebook4 plugin (https://www.npmjs.com/package/cordova-plugin-facebook4).

If I remove this from my package, the camera starts working again. I'm not sure if that's a compatibility problem on the fb plugin side, or on this plugins side...

**Comment by VicM** [comment]
I am also facing this problem. I was developing an app with a Android Lollipop phone as test device and the scanner was working, after the update to marshmallow it throws the noted error. Also updated to the latest cordova, android platform with no success. Any temporal fixes or work arounds?

**Comment by vdamyanov** [comment]
A potential workaround is to change your target sdk version to 22 (Lollipop) instead of 23 (Marshmallow).
In `platforms/android/AndroidManifest.xml` change to:
```
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />
```
In `platforms/android/prodject.properties` change to:
```
target=android-22
```
I had the same problems as above. Updated cordova to 6, Cordova Android to 5.1 and nothing worked. Then I dowgraded my sdk and that fixed it. Building to Android 5 and Android 6 devices with the old sdk works fine.

**Comment by poshaughnessy** [comment]
Thanks for the suggestion @vdamyanov!

I'm regenerating the platform directories as part of our build process, so I added the config to our config.xml:

<platform name="android">
        <preference name="android-targetSdkVersion" value="22"/>
</platform>

Seems to have done the trick for now!

**Comment by waelkdouh** [comment]
Same here. Cannot get it to work when installing with VS 2015 with TACO update 7. I am deploying it on a nexus 6p. Used to work before getting the latest TACO update.

**Comment by KapuzenSohn** [comment]
I had the same Problem. I looked in the link from @vrushankshukla and like it says I updated my Android version with `cordova platform update android@5.0.0`.
That fixed the problem on my Nexus 7 with Android 6.

**Comment by loyalpocket** [comment]
For Android 6+, because of the "permission" issue, If you got the message "Sorry, the camera encountered a problem. You may need to restart the device.", go to Settings - Apps - find "your app name" - select Permissions and switch on "Camera".

**Comment by cuiti** [comment]
I have the same problem here. It's related to the new Android 6 (API 23) permissions. Setting the targetSdkVersion to "22" solves the problem for now, but this should be fixed.

This is the exception in logcat:
W/ServiceManager: Permission failure: android.permission.CAMERA from uid=10293 pid=1417
E/CameraService: Permission Denial: can't use the camera pid=1417, uid=10293
com.ionicframework.fm176018 W/CameraBase: An error occurred while connecting to camera: 0
com.ionicframework.fm176018 W/CaptureActivity: Unexpected error initializing camera java.lang.RuntimeException: Fail to connect to camera service

**Comment by rudza** [comment]
Any progress on this?

**Comment by M-k-03** [comment]
@loyalpocket :  I need to set that exact permission u specified Programatically.. is it possible?????

**Comment by azn1viet** [comment]
I got the same issue. This permission in Android 6 needs to be set programmatically before compiling the app. Any one knows where it could be set for this matter?

**Comment by lx4r** [comment]
Is there any fix for this yet?

**Comment by azn1viet** [comment]
I got a fix by installing a plugin:

https://github.com/dpa99c/cordova-diagnostic-plugin#requestcameraauthorization

with requestCameraAuthorization() function

You gotta detect the user Android OS version then call this plugin when it's greater than 6.0 to pop up system native permission so that the user can interact with your app to allow or deny. This action can't be overridden problematically.

For more info. regarding to this matter, follow the link from Google:

http://developer.android.com/training/permissions/requesting.html

Hope this help.

**Comment by Smohanapriya** [comment]
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />

Is helped me to solve my issue. Thank You :)

**Comment by poychang** [comment]
This plugin work with me.
https://github.com/dpa99c/cordova-diagnostic-plugin#requestcameraauthorization
It's android device permissions problem.

**Comment by robertklein** [comment]
I solved this with https://github.com/NeoLSN/cordova-plugin-android-permission by checking (and requesting /if needed/) permissions in my onDeviceReady callback. It's all about android 6 requests permissions at runtime not during the installation.

**Comment by Smohanapriya** [comment]
Is there any new plugin available?

**Comment by pke** [comment]
Another proper fix to this problem, without changing the plugin at all, is to use another, more general [Android permissions plugin](https://github.com/NeoLSN/cordova-plugin-android-permission) and request the CAMERA permission from your javascript like this:

```es6
var permissions = cordova.plugins.permissions;
permissions.hasPermission(permissions.CAMERA, checkPermissionCallback, null);

function checkPermissionCallback(status) {
  if(!status.hasPermission) {
    var errorCallback = function() {
      console.warn('Camera permission is not turned on');
    }

    permissions.requestPermission(
      permissions.CAMERA,
      function(status) {
        if(!status.hasPermission) errorCallback();
      },
      errorCallback);
  }
}
```
That works good for me, as I have to stay on `3.1.0` of this scanner plugin because all the newer versions have awful QR detection rates/speeds.

**Comment by Smohanapriya** [comment]
After lower the SDK version to 22,

<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />

also not working for me? Any other solution is there?

**Comment by pke** [comment]
I commented the solution just above ur post

**Comment by yokeshvaradhan** [comment]
I am getting the same issue, i designed a audio recorder app it works good in lolli-pop, kit-kat and in naugat but that same is not working in marshmallow, i use cordova media plugin

`cordova-plugin-compat 1.1.0 
cordova-plugin-console 1.0.5 
cordova-plugin-device 1.1.4 
cordova-plugin-file 4.3.2 
cordova-plugin-file-transfer 1.6.2
cordova-plugin-media 3.0.0 
cordova-plugin-splashscreen 4.0.2
cordova-plugin-statusbar 2.2.1 
cordova-plugin-whitelist 1.3.1 
cordova-sqlite-storage 2.0.2 
ionic-plugin-keyboard 2.2.1 
`
could someone help me.

**Comment by alherrera42** [comment]
I confirm the issue and being solved by downgrading/changing the SDK version. In my case, from 23 to 22.

In my case, I require to use cordova-plugin-barcodescanner and camera. The first one just throws an alert, the second one asks for screen overlap permission (which is granted, but Android doesnt care anyways). 

config.xml
```
<platform name="android">
        <preference name="android-targetSdkVersion" value="22"/>
</platform>
```

**Comment by koshypcherian** [comment]
Guess it's the camera permission setting for the application(allowing to use the camera). it worked for Samsung edge(Android 7)

**Comment by hoachan** [comment]
I met same the problem in cordova, and I think phonepgap also run same cordova, 
I fix in cordova by install plugin cordova-plugin-android-permissions, then request
permission accessing camera to device with : 
         var permissions = cordova.plugins.permissions;
        permissions.requestPermission(permissions.CAMERA, success, error);

after request permisson , u can check permission access camera and if it has no problem.
device would be scan with :
        function success( status ) {
    if( !status.hasPermission ) error();
           cordova.plugins.barcodeScanner.scan(......)
    }
