### ISSUE TITLE
Add config option to only scan a specific Barcode type

### ISSUE THREAD

**Issue by SunboX** [phonegap/phonegap-plugin-barcodescanner#14]
Add a option to only scan (for example) EAN_13 Barcodes and ignore all others. This should speed up Barcode recognition and should avoid false positives.

**Comment by newebug** [comment]
Yes, we need this option also, and an option to determine landscape mode or portait.

**Comment by SunboX** [comment]
:+1:

**Comment by nofxx** [comment]
+1

**Comment by javifr** [comment]
+10000

**Comment by jschmiede** [comment]
+1

**Comment by nofxx** [comment]
I've found it, undocumented but working on android and iOS!! Very nice!

https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/src/android/LibraryProject/src/com/google/zxing/client/android/Intents.java#L44

The plugin applies options with `intentScan.putExtra` on BarcodeScanner.java.

```
    /**
     * By default, sending this will decode all barcodes that we understand. However it
     * may be useful to limit scanning to certain formats. Use
     * {@link android.content.Intent#putExtra(String, String)} with one of the values below.
     *
     * Setting this is effectively shorthand for setting explicit formats with {@link #FORMATS}.
     * It is overridden by that setting.
     */
    public static final String MODE = "SCAN_MODE";
    public static final String PRODUCT_MODE = "PRODUCT_MODE";
    public static final String ONE_D_MODE = "ONE_D_MODE";
    public static final String QR_CODE_MODE = "QR_CODE_MODE";
    public static final String DATA_MATRIX_MODE = "DATA_MATRIX_MODE";

    /**
     * Comma-separated list of formats to scan for. The values must match the names of
     * {@link com.google.zxing.BarcodeFormat}s, e.g. {@link com.google.zxing.BarcodeFormat#EAN_13}.
     * Example: "EAN_13,EAN_8,QR_CODE". This overrides {@link #MODE}.
     */
    public static final String FORMATS = "SCAN_FORMATS";
```

Did suffice my needs: only QR.

Javascript  code:

```js
cordova.plugins.barcodeScanner.scan(good_scan, bad_scan, {'SCAN_MODE': 'QR_CODE_MODE'})

```

**Comment by nofxx** [comment]
Ok, there's a lil issue.  Options is implemented totally different on iOS.
That should be why it's undocumented. 
On iOS there's actually only one option, that you can pass by text: overlayXib.

It's very easy to make this in the code by just commenting out: 
First this overlay (the argument will get a json).
And comment decodeHints you don't want.

Now, just lost the last 4 hours of life with objective C. In a hope it wasn't in vain, to receive the json nicely: (inside CDVBarcodeScanner.mm scan:)

```
    NSDictionary *opts = [command.arguments objectAtIndex:0];

    NSString *overlayXib = [opts valueForKey:@"overlayXib"];
    NSString *scanMode = [opts valueForKey:@"SCAN_MODE"];

    NSLog(@"options mode %@", opts);
```
That works nice, so you we can pass the same options in iOS and Android in the view:

```
cordova.plugins.barcodeScanner.scan(good_scan, bad_scan, {'SCAN_MODE': 'QR_CODE_MODE', 'XIB_WHATEVER})
```

What my limited obj c knowledge doesn't now is how to pass that scanMode nsstring to the hints.
Add a lot of IF's ??

I've also changed the flip camera to flash. Going to post the link soon, clean up.

**Comment by Fyod** [comment]
@nofxx Please update. I'm looking for a tut to change flip to flash.

**Comment by nofxx** [comment]
@Fyod https://github.com/umcanto/phonegap-plugin-barcodescanner/commit/5c19c10c2083c389107024d430aa873ea30bdeed

I should have commited styling apart, but anyways devs here should be linting the code in the first place ;)

**Comment by BiswasKhayargoli** [comment]
Hi guys,
Can you help me with the problem, I too want to scan only the qr codes and I did the following
  Intent intentScan = new Intent(SCAN_INTENT);
 intentScan.putExtra("SCAN_MODE", QR_CODE_MODE);

But, it is not working, it still scans barcodes along with qr codes. What am I doing wrong here? If possible can you provide an example code to meet my requirements. Thank you

**Comment by EddyVerbruggen** [comment]
With version 5.0.0 you can now also pass a `formats` param see the readme for an example (don't add spaces between the formats).
