### ISSUE TITLE
Not working with android 5 and 6

### ISSUE THREAD

**Issue by vrushankshukla** [phonegap/phonegap-plugin-barcodescanner#141]
I have developed an app using this plugin but it is not working newer version of android 5 and 6. Up to android 4, its working fine. What would be the problem? Looking forward for the guidance.

**Comment by lj222kj** [comment]
I'm using currently using Android 6.0 and previously used 5.0 and have not experienced any problems. Do you get any output when using the plugin on 5.x or 6.x?

**Comment by vrushankshukla** [comment]
I am developing mobile app for the first time using Cordova. I follow this path to develop Cordova app:
1. Installed node.js and npm
2. Installed git client
3. Installed JDK and Android SDK tool
4. then in node.js utility:
 -> npm install -g cordova@latest(Which install Cordova@5.4.1)
 -> cordova create DirectoryName APPID APPName
 -> cordova plugin add (Add all require plugin for my app)
 -> cordova platform add android@5.0.0
 -> cordova build android
5. Installed created .apk into android version 4.2.2, 5.1.1, 6.0.1.
6. In android 4.2.2 app is running as expected but  in 5.1.1 and 6.0.1 it's not running. Not running even simple javascript function to clear the form element.  None of the JavaScript functions are working. 

I don't understand,anybody have same issue?

**Comment by vrushankshukla** [comment]
I have the same error in Android 6.x.x. Unfortunately there was an error with the Android-Camera. It could be that you need to restart your device. Till Android 5.x.x, it's working but not for the Android 6.

So how can I test with this Android zxing integration? I am totally new to this. What steps I need to follow?

Sicerely

**Comment by mohit00** [comment]
i got the same problem how do you solve it
