### ISSUE TITLE
Windows Mobile - Issue with Orientation in Portrait

### ISSUE THREAD

**Issue by SunboX** [phonegap/phonegap-plugin-barcodescanner#142]
Wrong View Finder Orientation on Lumia 950 with latest build:

![img_0016](https://cloud.githubusercontent.com/assets/83344/12086721/062eb4b4-b2cd-11e5-83fe-744c9d94902e.jpg)

**Comment by lj222kj** [comment]
Are you using the latest unstable build?

**Comment by SunboX** [comment]
jep

**Comment by pospa78** [comment]
I have the same problem on the Windows 10 device Lumia 550

**Comment by SunboX** [comment]
> Are you using the latest unstable build?

To clarify it a bit more: I'm using `cordova plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner.git`

**Comment by kerosin** [comment]
thanks your fix worked for rotation problems on my Lumia 550!
