### ISSUE TITLE
No Viewfinder Overlay on BlackBerry10 platform

### ISSUE THREAD

**Issue by Balgam** [phonegap/phonegap-plugin-barcodescanner#146]
There should bee an Viewfinder overlay on BlackBerry 10 as on the other platforms as well.

**Comment by Balgam** [comment]
@sarangan12 
Would like to contribute any ideas howto implement an overlay with the C [camera_api](https://developer.blackberry.com/native/reference/core/com.qnx.doc.camera.lib_ref/topic/manual/camera_api.h_functions_overview.html) from QNX as the plugin uses.

**Comment by macdonst** [comment]
Not supporting BB10 anymore.
