### ISSUE TITLE
Visual Studio install fail

### ISSUE THREAD

**Issue by nemo3000** [phonegap/phonegap-plugin-barcodescanner#148]
When I install from visual studio I have an error in plugin.xml. I have already check in other issues but plugin.xml is already patched.

**Comment by iandonov** [comment]
It is due to this line (they are 2 like that):
        <framework src="src/windows/lib/WinRTBarcodeReader.csproj" custom="true" type="projectReference" versions="<=8.1"/>

'<' -  not a valid attribute character
replaced with    &lt;  and installs but not sure if it works correctly.

**Comment by mike-eason** [comment]
Can confirm. Replace:

<framework src="src/windows/lib/WinRTBarcodeReader.csproj" custom="true" type="projectReference" versions="<=8.1"/>

With:

<framework src="src/windows/lib/WinRTBarcodeReader.csproj" custom="true" type="projectReference" versions="&lt;=8.1"/>

**Comment by mike-eason** [comment]
The above works. Although there does not need to be a space between & and lt; Just use **&lt;**.

**Comment by iandonov** [comment]
I put space as I don't know how to format it :(
