### ISSUE TITLE
Missing object

### ISSUE THREAD

**Issue by morcegon** [phonegap/phonegap-plugin-barcodescanner#15]
Hello, first of all, thanks for the plugin!

I've tried to use this on iPhone through phonegapp, but i got this error:

> [console.error] Error: undefined is not an object (evaluating 'cordova.plugins.barcodeScanner')

**Comment by surajpindoria** [comment]
Hi @morcegon, are you still seeing this behavior? I just tried it myself and was not able to reproduce.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
