### ISSUE TITLE
Always return cancelled=true on Android 4.2.2

### ISSUE THREAD

**Issue by carlosbc84** [phonegap/phonegap-plugin-barcodescanner#150]
Hi everyone,

I'm having a problem on android 4.2.2, compiling with cordova 5.4.1. When it detects a barcode, the first time it freezes half a second, but the scanner still running and the second time return all values null, except atribute canceled=true.

I have tried to change the AndroidLaunchMode on config.xml with all its possible values, because I'm thinking it's related to this, but not working yet.

Can anyone help me?

Thanks.

**Comment by flint002** [comment]
I have the same error

**Comment by kbytesys** [comment]
Please refer to https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/137 and https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/143

**Comment by mikaoelitiana** [comment]
My app will exit when launching QR scan on 4.2 but the same code works fine in Android 5. Any idea?

**Comment by kbytesys** [comment]
@mikaoelitiana try my fork please

cordova plugin rm com.phonegap.plugins.barcodescanner
cordova plugin add https://github.com/kbytesys/phonegap-plugin-barcodescanner.git#android-zxing-integration

and test again.

**Comment by mikaoelitiana** [comment]
Thanks, I will check this.

**Comment by mikaoelitiana** [comment]
@kbytesys it works fine with this plugin!!! Thanks

**Comment by koga73** [comment]
@kbytesys I tried your fork but it didn't solve the issue for us.
What did work however is switching "ng-click" to "on-touch". See this:
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/38?_pjax=%23js-repo-pjax-container#issuecomment-161598604

**Comment by mcmemam** [comment]
Also, tried wrapping the scan function call inside setTimeout and it works, but it may not work on ios. The 'on-touch' solution works fine.
