### ISSUE TITLE
not compatibale with "cordova-plugin-crosswalk-webview" 1.5.0 when using PGB

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-barcodescanner#158]
hi all
for now
this plugin not compatibale with "cordova-plugin-crosswalk-webview" 1.5.0 when using PGB

when using Cordova Cli，the problem appear too
but can use a build-extras.gradle to solve it
build-extras.gradle 
![screenshot](https://cloud.githubusercontent.com/assets/5110085/12504810/2a85f518-c11c-11e5-90b5-7252b71df32b.png)

but PGB seem have no way can do that...for now...
here is the log
http://justpaste.it/qrol

**Comment by debugerr** [comment]
See this for discussion on the build error you are having now [Phonegap community](http://community.phonegap.com/nitobi/topics/build-fails-due-to-translation-error?utm_source=notification&utm_medium=email&utm_campaign=new_comment&utm_content=reply_button&reply[id]=16549194#reply_16549194)
