### ISSUE TITLE
on windows platform preview freezes

### ISSUE THREAD

**Issue by VladyslavGoloshchapov** [phonegap/phonegap-plugin-barcodescanner#161]
Hello.

I faced the following issue on windows8.1 -
1) you open barcodescanner,
2)  switch to another app
3) switch back to your app with barcodescanner opened

Error: preview is frozen. Though you can click on cancel button
Expected result: preview is not frozen.

Problem is that I am not very familiar with WinJS, so I don`t know how to fix this issue by myself.

So please either fix it or tell me how to do that and I will create a pull request.

Thanks,
VLad

**Comment by vladimir-kotikov** [comment]
Probably this is related to application's lifetime events. For more details see [MSDN article](https://msdn.microsoft.com/en-us/library/windows/apps/mt243896.aspx), section "Handle app lifetime and page navigation events".

In terms of Cordova it appears that you'll need to subscribe to document's `pause` and `resume` events - shutdown scanner's preview on `pause` event and restore it on `resume`.
