### ISSUE TITLE
Issues on PhoneGap v5.4.1

### ISSUE THREAD

**Issue by ElGabbu** [phonegap/phonegap-plugin-barcodescanner#163]
Was anyone able to get this working on phoneGap v5.4.1 ?

I have added the code as instructed in the readme but nothing happens when the function is invoked. I can see the console log, but nothing else happens.

Any help would be appreciated :)

**Comment by ElGabbu** [comment]
What I noticed so far is cordova.plugins is null ... so I thought maybe I am missing something in the config.xml .... so I tried adding <gap:plugin name="phonegap-plugin-barcodescanner" /> to the config ... but still no luck

**Comment by hsoehalim** [comment]
yeah, I have the same problem too. I wonder if the readme is up-to-date.
