### ISSUE TITLE
Scanning with vertical mode on Win 10 Mobile not working

### ISSUE THREAD

**Issue by kerosin** [phonegap/phonegap-plugin-barcodescanner#165]
Hey guys,

Horizontally everything works as expected, but on vertical mode no successful result can be found (really tried hard aiming with different focus and distance for a very long time).

Tested on Lumia 550 with Windows 10 Mobile.
Using current github repo with SunboX pull #155 for fixing orientation.

Anyone solutions so far?

**Comment by iandonov** [comment]
Same thing here with 550, 950 and 950XL

**Comment by kerosin** [comment]
this didn't fix the problem - like mentioned above I was already using orientation fix and couldn't scan on potrait mode
