### ISSUE TITLE
Windows Phone 8.1 App crashes after suspend -> resume

### ISSUE THREAD

**Issue by Mischa1610** [phonegap/phonegap-plugin-barcodescanner#166]
Hello,

i have the problem that the windows phone app crashes after I used the barcode-scanner and than suspend and resume the app. The windows phone shows the black screen with resume... message and crashes than.

I can suspend and resume the app without errors if i didn't used the barcode-scanner, but after i used it (suspend while the barcode-scanner is active or also after I closed the barcode-scanner) it crashes after suspend -> resume.

I use the newest version von the barcode-scanner-plugin from this repo.
I tried it with a Windows Phone 8.1 project, also retargeted the WinRTBarcodeReader to Windows 8.1.
I tried it with a Lumia 830 and a Lumia 930, both crash.
I also created a empty new cordova project (on cordova version 5.4.1 and 6.0.0), with both same error.

It seems like some of the resource that the barcode-scanner uses are not removed/closed/stopped correctly.

If I suspend and resume app, the app crashes before the app resume event is thrown (I set an app resume event handler functions and it doesn't run in the function, it crashes before).

It seems like it has something to do with the `capture` element/variable in the BarcodeScannerProxy.js file in the `destroyPreview()` function. With the code line about 419:
`capture && capture.stopRecordAsync()`
Because if I set a functions `done()` event it always runs the the fail function with the error message: "WinRTError: The request is invalid in the current state"
When i try to call `capture.close()` after the `stopRecordAsync()` (in the `done()` event function) the app don't crashes anymore after I closed the barcode-scanner and suspend and resume it.

`capture && capture.stop.done(function (result) {`
        `console.log("stop capture success: " + success);`
        `capture.close();`
        `capture = null;`
`}, function (error) {`
        `console.error("stop capture error: " + error);`
        `capture.close();`
        `capture = null;`
`});`

But the app still crashes (also with the code change write above) if the app is suspended and resume when the barcode-scanner is active and if I set a function for the app pause event that calls the `cancelPreview()` and opens the barcode-scanner in the resume event the app still crashes.

I hope someone has more experience/knowledge about the resource cleaning.

**Comment by k7hulu** [comment]
I am having exact same issues on win 8.1.

**Comment by ahokkonen** [comment]
Same issue in my project also. Tried on different Nokia WP8.1 phones, same behavior.
Also noted that during debug (when my phone wired connected to debugger instance on VS2015) its working good, no crashes what so ever.

**Comment by k7hulu** [comment]
Hello, i managed to fix this by adding the below function in the **Reader.cs** :

 
```
public void Dispose()
        {
            this.capture.Dispose();
            this.capture = null;
        }


```

then got some ideas from here: https://github.com/wildabeast/BarcodeScanner/pull/193/files?diff=split on how to determine is camera is still in use: 

then added this in my **barcodeScanner.js** file below:

```
BarcodeScanner.prototype.stopScanning = function (successCallback, errorCallback, config) {

        exec(successCallback, errorCallback, 'BarcodeScanner', 'stopScanning', config);

    };
```

and the below inside **barcodeScannerProxy.js** :

```
 function stopScanning() {
        if (capture) {
            capturePreview.pause();
            capturePreview.src = null;

            capture && capture.stopRecordAsync();
            capturePreview.pause();
            capturePreview.src = null;

            [capturePreview, capturePreviewAlignmentMark, captureCancelButton].forEach(function (elem) {
                elem && document.body.removeChild(elem);
            });
            if (reader) {
                reader && reader.stop();
                reader && reader.dispose();
                reader.readCode().cancel();
                reader = null;
                captureCanceled = true;
            }

            capture.stopRecordAsync();
            capture = null;
        }
    }

```

and call from angular using the below line when **back **button or **suspend** is pressed: 

`cordova.plugins.barcodeScanner.stopScanning();`

and it works just fine! i think the "reader=null" isnt enough for the windows phone and .dispose() is also needed but isolated and outside the existing implementation specifically for when back button and suspend are triggered only... hope this helps.

**Comment by Mischa1610** [comment]
Seems like this topic is not a problem anymore since the resources (capture, ...) are released and closed now correct.
Also since this commit: [Windows - Cleanup camera on app suspension](http://github.com/phonegap/phonegap-plugin-barcodescanner/commit/49489db0678e6e80a3b0744533d432681b9cfdb7) to suspend the App should also work correct.
