### ISSUE TITLE
Android M issues. Due to new intent/permissions

### ISSUE THREAD

**Issue by ianisted** [phonegap/phonegap-plugin-barcodescanner#167]
I've been having a lot of issues getting the scanner working on Marshmallow, and it all seems to be due to the use on Intent rather than requesting Permissions.

The people working on the **cordova-plugin-camera** project hit the same issue. https://github.com/apache/cordova-plugin-camera/pull/142

Is this something that can be easily resolved?

**Comment by poshaughnessy** [comment]
:+1: 

I'm getting "Sorry, the Android camera encountered a problem..." The logs say:

```
02-09 14:32:35.589   198   822 W ServiceManager: Permission failure: android.permission.CAMERA from uid=10178 pid=13777
02-09 14:32:35.589   198   822 E CameraService: Permission Denial: can't use the camera pid=13777, uid=10178
02-09 14:32:35.589 13777 13777 W CameraBase: An error occurred while connecting to camera: 0

02-09 14:32:35.590 13777 13777 W CaptureActivity: Unexpected error initializing camera
02-09 14:32:35.590 13777 13777 W CaptureActivity: java.lang.RuntimeException: Fail to connect to camera service
...
```

**Comment by poshaughnessy** [comment]
I believe this is the same bug as https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/139

**Comment by ianisted** [comment]
@poshaughnessy that is indeed the same issue. Fixed using the same temporary fix. Wondering what we can do to provide a more bulletproof fix for the longterm.

**Comment by barryvdh** [comment]
I've resolved this by using the fork from https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/143
```
cordova plugin add https://github.com/kbytesys/phonegap-plugin-barcodescanner.git#android-zxing-integration
```

**Comment by SammyIsra** [comment]
I seem to have no issues with the barcode scanner when I used Visual Studio and Cordova to use it. Once I use Ionic and ngCordova, the plugin does not seem to work, maybe that can provide some help?

**Comment by SammyIsra** [comment]
Using that fork (https://github.com/kbytesys/phonegap-plugin-barcodescanner.git#android-zxing-integration) will require the installation of another Play Store app that scans barcodes. Whenever the scan function is called, it will instead open the secondary application. Is there no other way to have a lightweight QR code scanner, instead of a pluging that requires another app to work?

**Comment by JrontEnd** [comment]
I rewrited the plugin and resolved this problem.
```
cordova plugin add https://github.com/jrontend/phonegap-plugin-barcodescanner
```

**Comment by guardezi** [comment]
@JrontEnd +1

**Comment by SammyIsra** [comment]
@JrontEnd does this work with ngCordova?

**Comment by JrontEnd** [comment]
@SammyIsra I don't have the environment of ngCordova,but you can try it.

**Comment by SammyIsra** [comment]
@JrontEnd I just did, it worked nicely (I edited the last message too late)

Are there any settings on the reader?

**Comment by JrontEnd** [comment]
@SammyIsra Nothing,the permission is requested automatically.

**Comment by SammyIsra** [comment]
@JrontEnd so there is no way to avoid the "beep" the reader makes?
Thank you for your contribution, I had forgotten about this plugin!

**Comment by JrontEnd** [comment]
@SammyIsra Haha, I am glad to see the plugin helpful to you.

**Comment by ten80** [comment]
@JrontEnd  you are awesome :D THX !!!

**Comment by Vishwasraj** [comment]
works like a charm..thank you @JrontEnd

**Comment by Gp2mv3** [comment]
@JrontEnd Maybe try to propose a PR of your plugin, it can be really useful !

**Comment by JrontEnd** [comment]
@Gp2mv3 I created a PR ,but not accepted.

**Comment by JrontEnd** [comment]
@guardezi 
I have a good news.The pull request is merged, you can add the plugin of latest version in phonegap repository.

**Comment by fmiboy** [comment]
@JrontEnd thanks your plugin resolved the issue.

**Comment by Smohanapriya** [comment]
Is there any plugin available without installing another supporting app in device?

**Comment by mobicraft-am** [comment]
Hi, i have found an issue if you have this pb (10/2016 !).
Don't use cordova plugin add phonegap-plugin-barcodescanner -> 4.0.2 !!! 
but cordova plugin add https://github.com/jrontend/phonegap-plugin-barcodescanner -> 4.1.0

**Comment by Smohanapriya** [comment]
I am using ionic with ngcordova. By using,
   `cordova plugin add https://github.com/jrontend/phonegap-plugin-barcodescanner`

this plugin for me barcode scanner is opening. but i am not able get the scan it...

any solution???

**Comment by mobicraft-am** [comment]
Use this one : 
Remove the old
ionic plugin add https://github.com/Telerik-Verified-Plugins/BarcodeScanner <https://github.com/Telerik-Verified-Plugins/BarcodeScanner> —save
ionic platform remove ios
ionic platform remove android
ionic add platform ios
ionic add platform android
ionic state save

**Comment by Smohanapriya** [comment]
This plugin,
 
  `ionic plugin add https://github.com/Telerik-Verified-Plugins/BarcodeScanner`

also not working for me. I am using android marshmallow...

`<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="23" />`

**Comment by mobicraft-am** [comment]
Im using nougat ... But can you explain with more details and your code ?
The camera is oppening or not ?
