### ISSUE TITLE
Cannot scan in portrait mode on Win10 after fix for #155

### ISSUE THREAD

**Issue by iandonov** [phonegap/phonegap-plugin-barcodescanner#172]
This change:
Fixes Windows Mobile - Issue with Orientation
#155 
rotates only encoding preview.

Barcode still needs to be in landscape to be successfully scanned.
This version of ZXing library doesn't scan in both directions or at least this is what I get.

**Comment by pospa78** [comment]
I agree, orientation preview is now ok, but the bar code can be scanned only with a rotation of 90 degrees.
