### ISSUE TITLE
Doesn't work with Phonegap Build on iOS devices

### ISSUE THREAD

**Issue by ilvalerione** [phonegap/phonegap-plugin-barcodescanner#173]
Hello,
I'm trying to use this plugin in my ionic project compiled with PhoneGap Build.

When i try to use barcode scanner on iOS devices, my app open barcode correctly but doesn't scan (capture) qrcode.

My config.xml declaration is
gap:plugin name="phonegap-plugin-barcodescanner" source="npm"

and my test code is:

```
cordova.plugins.barcodeScanner.scan( 
 function (result) {
   if(result.cancelled) 
      return; 
    alert(result.text); 
}, function (error) { 
   alert("Error scan"); 
});
```

In my app on PGB i see

**PhoneGap (iOS / Android / Windows)
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)**

for identify correct version

Have you notice of the same problem for the same situation?

**Comment by ilvalerione** [comment]
I tried using old version of cli (5.1.1). 

In my PGB app there is
**PhoneGap (iOS / Android / Windows)
cli-5.1.1 (3.8.0 / 4.0.2 / 3.8.1)**

Nothing change. When i try to use barcode scanner on iOS device, my app open barcode correctly but don't scan (capture) qrcode.

**Comment by lab6net** [comment]
It works partialy for me.

I included it in config file differenty:
plugin name="phonegap-plugin-barcodescanner" spec="3.1.0"

It is working on my ipad, however it opens scanner only once, if i cancel it doesnt fire success method and i can't fire scaner again for some reason.

**Comment by ilvalerione** [comment]
I tried with 

spec="3.1.0"

But nothing change.

What'is your iOS version?

I'm using last version 9.2 and it doesn't work.

**Comment by lab6net** [comment]
I'm also using latest version of IOS on Ipad Air.
I think you should look into "success" function i got feeling that some error might happen there.

I've currently switched to different plugin (https://github.com/tjwoon/csZBar) that works fine, but i think my problem was due to some error in success function code. Try wrapping function body in try {} and use alert to show errors.

**Comment by ilvalerione** [comment]
my function contain only

`cordova.plugins.barcodeScanner.scan( 
 function (result) {
   alert("SUCCESS!!!!"); 
}, function (error) { 
   alert("Error scan"); 
});`

and in any case I tried to use try {}.

This code opens QrCode scanner correctly, but when i aim it in front of QrCode it doesn't do scan.

I change inclination and distance, i try with differents QrCode.... nothig... it doesn't capture code.

**Comment by ilvalerione** [comment]
Unfortunately this plugin
https://github.com/tjwoon/csZBar

is not available for Phonegap Build.

**Comment by lab6net** [comment]
It is available for Phonegap Build. I'm using this service too. Here's config.xml entry:

plugin name="org.cloudsky.cordovaplugins.zbar" spec="tjwoon/csZBar" source="git"

But if plugin you're using currently doesn't want to scan anything, maybe it is problem with your camera device or image with qr-code.

**Comment by ilvalerione** [comment]
@lab6net thanks for your support and your time.

**I inserted the plugin used by you and it's working fine! Finally!**

I also think that this is very strange, but i don't know why.

I tested app with two devices:
iphone 6 with iOS 9.2
iphone 5s with iOS 9.2

and them behavior is the same.

**Comment by steffchep** [comment]
I've got a similar problem. The plugin works like a charm on Android, but on iOS 7.1.2, the scanner does not open. 
Not sure if a bug, or a problem between keyboard and chair, as I am very new to iOS :(

**Comment by ilvalerione** [comment]
I suggest you to use "gradle" to build Android package.

**Comment by steffchep** [comment]
I don't understand. It is iOS that is causing the problems, not the Android build. That is working perfectly.

I seem to have found out that the plugin is somehow inactive. It looks to be all in the build project, but when triggering the scan in iOS, I get a javascriptError that the barcodeScanner object can't be found.

**Comment by priyanka-vaishnav** [comment]
Its working fine with android but when triggering the scan in iOS, I get an error that the barcodeScanner object is undefined

**Comment by hasLoren** [comment]
I am consoling errors in the terminal. When I try to bring up the barcode scanner with my app using Ionic 1.2.4, it freezes and throws this error in the console. 

 461469   error    Error: Can't find variable: cordovascan@http://192..............

How can I tell if this plugin will be compatible with Ionic 1.2.4?

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
