### ISSUE TITLE
Windows 10 Store upload

### ISSUE THREAD

**Issue by bampakoa** [phonegap/phonegap-plugin-barcodescanner#179]
Hi,

I am trying to upload a Cordova application at the Windows 10 App Store, that includes BarcodeScanner plugin, but I get the following error: 

> Package acceptance validation error: You cannot submit pre-compiled .NET Native packages. Please upload the Store appxupload file and try again.

If I remove the plugin, the application package uploads succesfully. Please note that I have tried either the ARM version or the x64 version of my application and both of them fail.

My setup is:

- Visual Studio 2015 Community Edition Update 2
- Cordova Tools Update 10
- Cordova 6.1.1
- BarcodeScanner 5.0.1

**Comment by Mikey1982** [comment]
Do you still have this problem?

**Comment by bampakoa** [comment]
@Mikey1982 I tried with version 5.0.0 and the error is still there.

**Comment by daserge** [comment]
@bampakoa, could you please try switching the `Generate app bundle` to `Always` and try again?
I've tested it and it works - package is being created, it passes the WACK and uploads to the Store.

**Comment by bampakoa** [comment]
@daserge I tried creating a new VS solution from scratch with the plugin added and the problem persists. I have updated the description of the issue to be aligned with my new configuration. Can you please share your configuration and/or additional details on how you achieved that?

**Comment by daserge** [comment]
@bampakoa, I meant this VS setting:
![bundle](https://cloud.githubusercontent.com/assets/4272078/16267743/05884190-3894-11e6-8ac6-a3b711dd3492.PNG)

**Comment by bampakoa** [comment]
@daserge I have also set **Generate app bundle** to **Always** with no luck.

**Comment by daserge** [comment]
@bampakoa, could you upload and share a blank project with that issue on some online drive?

**Comment by bampakoa** [comment]
@daserge Sure, no problem. I will upload it in Google Drive and let you know. Thanks very much for your help.

**Comment by bampakoa** [comment]
@daserge https://drive.google.com/open?id=0B9H4CfCJzrtGWmljak83RHVBMTA

**Comment by daserge** [comment]
Tested your project - added barcode scanner plugin from git, added simple code to verify it works, created Store packages from VS, WACK passed, bundle successfully uploaded to Store (Windows 10 x86, x64, ARM).
VS version: 2015 Community, 14.0.25123.00 Update 2
VS tools for Apache Cordova - Update 10

@bampakoa, could you describe your steps in detail?

**Comment by bampakoa** [comment]
@daserge I have made two [PSRs](https://drive.google.com/folderview?id=0B9H4CfCJzrtGQ042aC1zeWpUYXc&usp=sharing), for you, that show the steps that I followed in detail.

**Comment by daserge** [comment]
Thanks @bampakoa! 
Could you try to change the plugin id on `Step 14` to Git url `https://github.com/phonegap/phonegap-plugin-barcodescanner`?

**Comment by bampakoa** [comment]
@daserge I tried your suggestion but the problem persists. Some notes though:

1. As my application is already in the Store, I create a new submission that contains **already** the previous packages.
2. During build of each platform I get this warning:  

> C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(934,5): warning :   Your application is missing a Runtime Directives (rd.xml) file. Runtime Directives are used to describe the dynamic behavior of your application and control the .NET Native optimizer. It is recommended to have at least one rd.xml file in your project. [C:\Users\aris\Documents\Visual Studio 2015\Projects\BlankCordovaApp1\platforms\windows\CordovaApp.Windows10.jsproj]

I do not know if the above are related with my problem but I thought it would be ok to know it.

**Comment by iamvau** [comment]
@bampakoa: I had exactly the same problem.  For me it was fixed after updating VS tools for Apache Cordova - from Update 9 to **update 10**

**Comment by daserge** [comment]
@bampakoa, I've published a test app to the Windows Store - tested x64 and arm versions via promotional codes and it works OK.
Try upgrading to [VS 2015 update 3](https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs) (if you have the software versions the same as I reported [here](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/179#issuecomment-228307550)).

**Comment by bampakoa** [comment]
@daserge @iamvau  I tried your suggestions with no potential effect. Please note that I have VS 2015 **Community Edition** and I am running it on a Windows 10 build (**Insider**) in a **Virtual Box** machine. Could this be a problem? 
I am starting to think of re-install everything from the beginning as a last resort...

Thanks

**Comment by bampakoa** [comment]
Hi folks,

I have not find any potential solution yet to this problem, and since our product roadmap does not include this feature in the near future, I will close this issue. 

Thank you all for your help. In case something changes, I will come back to this.
