### ISSUE TITLE
Will this work with cordova?

### ISSUE THREAD

**Issue by cyclonmaster** [phonegap/phonegap-plugin-barcodescanner#18]
I use cordova for my app instead of phonegap. Will it work?

**Comment by tnyeanderson** [comment]
Phonegap is built on Cordova, so yes it will work. Just use the Cordova commands for plugins instead of the phonegap ones.

**Comment by cyclonmaster** [comment]
So, should I run:

cordova plugin add phonegap-plugin-barcodescanner

or 

cordova plugin add cordova-plugin-barcodescanner

I try to add QRreader in my sample sencha touch app based on this tutorial:
https://modeve.wordpress.com/2012/11/19/android-development-qr-barcode/

I get this error:

C:\xampp\htdocs\QRSample>sencha app build native
Sencha Cmd v6.0.0.154
[INF] Processing Build Descriptor : native
[INF] Starting server on port : 1841
[INF] Mapping http://localhost:1841/~cmd to C:\Users\cyclonmaster\bin\Sencha\Cmd
\6.0.0.154...
[INF] Mapping http://localhost:1841/ to C:\xampp\htdocs\QRSample...
[INF] Application available at http://localhost:1841
[INF] Loading app json manifest...
[INF] Writing output to file C:\xampp\htdocs\QRSample/build/temp/production/QRSa
mple/sencha-compiler/cmd-packages.js
[INF] writing content to C:\xampp\htdocs\QRSample\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\bootstrap.js
[INF] Appending content to C:\xampp\htdocs\QRSample\bootstrap.json
[WRN] C1014: callParent has no target (me.callParent in Ext.dataview.DataView.on
AfterRender) -- C:\xampp\htdocs\QRSample\touch\src\dataview\DataView.js:892
[WRN] C1014: callParent has no target (this.callParent in Ext.Decorator.setDisab
led) -- C:\xampp\htdocs\QRSample\touch\src\Decorator.js:157
[WRN] C1014: callParent has no target (this.callParent in Ext.data.ArrayStore.lo
adData) -- C:\xampp\htdocs\QRSample\touch\src\data\ArrayStore.js:64
[WRN] C1014: callParent has no target (this.callParent in Ext.fx.animation.Wipe.
getData) -- C:\xampp\htdocs\QRSample\touch\src\fx\animation\Wipe.js:119:7
[INF] Writing concatenated output to file C:\xampp\htdocs\QRSample\cordova\www\a
pp.js
[INF] merging 0 input resources into C:\xampp\htdocs\QRSample\cordova\www\resour
ces
[INF] merged 0 resources into C:\xampp\htdocs\QRSample\cordova\www\resources
[INF] merging 14 input resources into C:\xampp\htdocs\QRSample\cordova\www
[INF] merged 0 resources into C:\xampp\htdocs\QRSample\cordova\www
[INF] writing content to C:\xampp\htdocs\QRSample\sass\example\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\sass\example\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\sass\example\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\sass\example\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\sass\example\bootstrap.js
[INF] executing compass using system installed ruby runtime
identical ../css/app.css
[INF] Application available at http://localhost:1841
[INF] writing content to C:\xampp\htdocs\QRSample\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\bootstrap.js
[INF] appending content to C:\xampp\htdocs\QRSample\bootstrap.js
[INF] Appending content to C:\xampp\htdocs\QRSample\bootstrap.json
[INF] Copying page resources to C:\xampp\htdocs\QRSample\cordova\www
[INF] Writing content to C:\xampp\htdocs\QRSample\cordova\www\microloader.js
[INF] Appending content to C:\xampp\htdocs\QRSample\cordova\www\microloader.js
[INF] Building output markup to C:\xampp\htdocs\QRSample/cordova/www/index.html
[INF] Writing content to C:\xampp\htdocs\QRSample\cordova\www\index.html
[INF] [Cordova] Attempting Cordova Build for platforms "android"
[INF] [shellscript]
[INF] [shellscript] C:\xampp\htdocs\QRSample\cordova>cordova  build android
[INF] [shellscript] Discovered plugin "BarcodeScanner" in config.xml. Installing
 to the project
[INF] [shellscript] Running command: C:\xampp\htdocs\QRSample\cordova\platforms\
android\cordova\build.bat
[INF] [shellscript] [Error: Failed to run "java -version", make sure that you ha
ve a JDK installed.
[INF] [shellscript] You can get it from: http://www.oracle.com/technetwork/java/
javase/downloads.
[INF] [shellscript] Your JAVA_HOME is invalid: C:\Program Files\Java\jdk1.8.0_20
\
[INF] [shellscript] ]
[INF] [shellscript] Error: C:\xampp\htdocs\QRSample\cordova\platforms\android\co
rdova\build.bat: Command failed with exit code 2
[INF] [shellscript]     at ChildProcess.whenDone (C:\Users\cyclonmaster\AppData\
Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn
.js:131:23)
[INF] [shellscript]     at ChildProcess.emit (events.js:110:17)
[INF] [shellscript] ERROR building one of the platforms: Error: C:\xampp\htdocs\
QRSample\cordova\platforms\android\cordova\build.bat: Command failed with exit c
ode 2    at maybeClose (child_process.js:1015:16)
[INF] [shellscript] You may not have the required environment or OS to build thi
s project
[INF] [shellscript]
[INF] [shellscript]     at Process.ChildProcess._handle.onexit (child_process.js
:1087:5)
[ERR] The following error occurred while executing this line:
C:\xampp\htdocs\QRSample\.sencha\app\build-impl.xml:437: The following error occ
urred while executing this line:
C:\xampp\htdocs\QRSample\.sencha\app\packager-impl.xml:17: The following error o
ccurred while executing this line:
C:\xampp\htdocs\QRSample\.sencha\app\cordova-impl.xml:77: The following error oc
curred while executing this line:
jar:file:/C:/Users/cyclonmaster/bin/Sencha/Cmd/6.0.0.154/sencha.jar!/com/sencha/
ant/antlib.xml:647: shellscript returned: 1

C:\xampp\htdocs\QRSample>

**Comment by tnyeanderson** [comment]
You should run the cordova command for the cordova plugin. I can't help you with the other issue you are having. Try asking the author of the tutorial. Sorry about that.
