### ISSUE TITLE
App crashes when I try to re-scan

### ISSUE THREAD

**Issue by jffs** [phonegap/phonegap-plugin-barcodescanner#181]
Hi, I get this error sometimes when I want to start scanning again after the first detection. The app opens the camera but as soon as it displays the image onscreen, it crashes, and then it starts to scan again, crashes, and so on . If I press the home button to try and close it, the app keeps coming to the foreground. Eventually the device reboots itself.

Any solution?

**Comment by bau720123** [comment]
+1

**Comment by jffs** [comment]
i solved this issue changing the way i call the method "scan": instead using "ng-click" I used "on-touch"

**Comment by sarangan12** [comment]
This issue might be related to https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/205

**Comment by daserge** [comment]
@jffs, please reopen if this is still actual with the latest version and add some details like on which platform this occurs, device model and OS version.
