### ISSUE TITLE
Windows 10: scan() throws exception

### ISSUE THREAD

**Issue by lentyaishe** [phonegap/phonegap-plugin-barcodescanner#187]
Hi,

I'm using your plugin for scanning barcodes in a cordova application.

In Windows 8.1 it works like a charm but I had to upgrade my app to be executed in Windows 10 environment and your plugin stopped working. :(
I've upgraded to the latest version but still receive the following exception:

```
Exception is about to be caught by JavaScript library code at line 247, column 13 in ms-appx-web://.../www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js

0xc00d36b3 - JavaScript runtime error: The stream number provided was invalid.

PreviewState

WinRT information: PreviewState

If there is a handler for this exception, the program may be safely continued.
```

Can anything be done about it? Or what am I doing wrong?

UPDATE:
Could it be somehow related to this:
[Exception when rotating: The stream number provided was invalid](https://github.com/Redth/ZXing.Net.Mobile/issues/250)

Thanks in advance

**Comment by vkActDev** [comment]
I have same problem. Since three weeks I try with last plugin under Windows 10.

**Comment by newchiripa** [comment]
I'm having the same issue, got this error message from the error callback: **"WinRTError: The stream number provided was invalid"**. This is running the app in a **Windows 10 Surface 3 tablet**. However, tried in a different windows 10 tablet (**a Dell Venue 11**) and the barcodescanner works fine. Any clue?

Regards

**Comment by lentyaishe** [comment]
Well, at least mine is solved...
Just re-created the cordova project with the latest CLI (currently 6.1.1) and the issue is gone.. Succeeded scanning barcodes in portrait and in landscape.

Hope, it'll help you too..

**Comment by sarangan12** [comment]
This issue has been fixed with a recent commit. " The stream number provided was invalid" error does not happen anymore. There might be a different issue with scanning which is tracked by https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/188 . So, Closing this issue
