### ISSUE TITLE
Windows 10 crashes

### ISSUE THREAD

**Issue by geisi93** [phonegap/phonegap-plugin-barcodescanner#188]
Hi,

I've created a Cordova Project in Visual Studio 2015 and I installed the barcode scanner plugin. It works on Android and iOS, however, on Windows 10 the App crashes with following error message:

"Unhandled exception at line 2965, column 13 in ms-appx-web://com.test.app/www/WinJS/js/base.js
0x800a139e - JavaScript runtime error: NotFoundError"

Does anyone have any hints how to fix this error? Thanks in advance.

**Comment by AparnaChinya** [comment]
I am facing the same issue. Any pointers on this will be helpful.

**Comment by rolandoldengarm** [comment]
I get a different error on Windows 10 Desktop:
````
Exception is about to be caught by JavaScript library code at line 246, column 13 in ms-appx-web://com.test.app/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0xc00d36b3 - JavaScript runtime error: The stream number provided was invalid.
PreviewState
WinRT information: PreviewState
````

**Comment by yesiman** [comment]
Actually only solution i had is to replace in BarcodeScannerProxy.js this line : 
`capture.setEncodingPropertiesAsync(Windows.Media.Capture.MediaStreamType.VideoPreview, videoEncodingProperties, null);`
by : 
`if (!(window.device.platform.toUpperCase().indexOf("WINDOWS") > -1))
            {
                capture.setEncodingPropertiesAsync(Windows.Media.Capture.MediaStreamType.VideoPreview, videoEncodingProperties, null);
            }`

**Comment by sarangan12** [comment]
@geisi93  This issue has been fixed with a recent [commit](https://github.com/phonegap/phonegap-plugin-barcodescanner/commit/8e46fcb76d49c76f4598be195e489cd81fc29217) Could you please verify?

**Comment by yesiman** [comment]
Hi,
Well now no more js crash, the cam light goes on but nothing happen and no video appear on screen to scan the code.

**Comment by geisi93** [comment]
@sarangan12  no crash any longer. Thanks!

**Comment by daserge** [comment]
Please reopen if this still happens.

**Comment by yesiman** [comment]
Just test and all is ok thanks !
