### ISSUE TITLE
Support for PDF417

### ISSUE THREAD

**Issue by tnyeanderson** [phonegap/phonegap-plugin-barcodescanner#19]
I know you probably get asked this quite frequently, but is there any possibility of PDF417 support in iOS soon? If not, care to explain why? Maybe I could give it a shot and offer a pull request. Thanks!

**Comment by mattgrande** [comment]
Hey @tnyeanderson did you ever give this a shot?

**Comment by tnyeanderson** [comment]
Unfortunately I did not find the time. Fortunately, I did find a port to JS for ZXING PDF417 scanning. This is really perfect because I was planning to build my app with cordova, so now I just have to understand how to use the damn thing as the docs are non-existant. For the curious: https://github.com/PeculiarVentures/js-zxing-pdf417

**Comment by JoellyR** [comment]
hey @tnyeanderson did you ever find out a way to get the ZXING PDF417 port to work properly? By looking at the demo and such it looks like your just supposed to upload a file for it to decode.. Not use your camera to detect the barcode...

**Comment by guerson** [comment]
@tnyeanderson is js-zxing live stream recognition or we have to take a picture and than make de recognition.

**Comment by macdonst** [comment]
PDF_417 is supported in 6.0.6.
