### ISSUE TITLE
Scan QR Code very fast but result is that return empty string, problem with autofocus I guss

### ISSUE THREAD

**Issue by Petrik-a-dost** [phonegap/phonegap-plugin-barcodescanner#191]
Hello,
I have problem with scan qr code with autofocus I guss, becouse when I try scan qr code by barcode scanner so is too fast and it does't recognize content of qr code and return empty string. I think that even the camera not enough focus on qr code and barode scanner immediately scan fuzzy qr code and result is empty string.

Sometime the scanner try scanning qr code twice immediately again but anyway barcode scanner return empty string... 
I have samsung galaxy S4 mini with 8 Mpx. - android
id="phonegap-plugin-barcodescanner" version="4.1.0"

        $scope.scanBarcode = function () {
            $ionicPlatform.ready(function () {
                $cordovaBarcodeScanner.scan().then(function (imageData) {
                    if (imageData.cancelled) {
                        alert('Please scan again');
                    } else {
                        $state.go('app.tabsController.testDetail', { testDetailId: imageData.text });
                    }
                }, function (error) {
            });
         });
       }

Is it any way how to improve this code for better recognition of content of qr code? or set autofocus by handle click to display?

I am apologize for my english.

Thank You very much for your response.

Petrik-a-dost

**Comment by USSliberty** [comment]
I have exactly the same problem. I have a Nexus 5 with Android 5.1.1 and i use crosswalk.

**Comment by USSliberty** [comment]
03-30 17:56:25.077 16263-22484/it.infofactory.appudine D/DecodeHandler: Found barcode in 77 ms
03-30 17:56:25.095 16263-16263/it.infofactory.appudine D/CaptureActivityHandler: Got decode succeeded message
03-30 17:56:26.629 16263-16263/it.infofactory.appudine D/CaptureActivityHandler: Got return scan result message
03-30 17:56:28.035 16263-16263/it.infofactory.appudine I/PlatformSupportManager: Using implementation class com.google.zxing.client.android.camera.open.GingerbreadOpenCameraInterface of interface com.google.zxing.client.android.camera.open.OpenCameraInterface for SDK 9
03-30 17:56:28.036 16263-16263/it.infofactory.appudine I/GingerbreadOpenCamera: Opening camera #0
03-30 17:56:28.186 16263-16263/it.infofactory.appudine I/CameraConfiguration: Screen resolution: Point(1080, 1558)
03-30 17:56:28.186 16263-16263/it.infofactory.appudine I/CameraConfiguration: Supported preview sizes: 1920x1080 1600x1200 1280x960 1280x768 1280x720 1024x768 800x600 800x480 720x480 640x480 352x288 320x240 176x144 
03-30 17:56:28.186 16263-16263/it.infofactory.appudine I/CameraConfiguration: Found best approximate preview size: Point(1024, 768)
03-30 17:56:28.186 16263-16263/it.infofactory.appudine I/CameraConfiguration: Camera resolution: Point(1024, 768)
03-30 17:56:28.189 16263-16263/it.infofactory.appudine I/CameraConfiguration: Initial camera parameters: preview-size=1920x1080;video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size[...]
03-30 17:56:28.189 16263-16263/it.infofactory.appudine I/CameraConfiguration: Supported values: [off, auto, on, torch, red-eye]
03-30 17:56:28.189 16263-16263/it.infofactory.appudine I/CameraConfiguration: Settable value: off
03-30 17:56:28.189 16263-16263/it.infofactory.appudine I/CameraConfiguration: Supported values: [auto, macro, continuous-video, continuous-picture]
03-30 17:56:28.189 16263-16263/it.infofactory.appudine I/CameraConfiguration: Settable value: auto
03-30 17:56:28.215 16263-16263/it.infofactory.appudine I/PlatformSupportManager: Using implementation class com.google.zxing.client.android.common.executor.HoneycombAsyncTaskExecInterface of interface com.google.zxing.client.android.common.executor.AsyncTaskExecInterface for SDK 11
03-30 17:56:28.216 16263-16263/it.infofactory.appudine I/AutoFocusManager: Current focus mode 'auto'; use auto focus? true
03-30 17:56:29.373 16263-16263/it.infofactory.appudine D/CameraManager: Calculated framing rect: Rect(135, 439 - 945, 1119)
03-30 17:56:34.639 16263-22913/it.infofactory.appudine D/DecodeHandler: Found barcode in 33 ms
03-30 17:56:34.653 16263-16263/it.infofactory.appudine D/CaptureActivityHandler: Got decode succeeded message
03-30 17:56:36.194 16263-16263/it.infofactory.appudine D/CaptureActivityHandler: Got return scan result message
03-30 17:56:37.613 16263-16263/it.infofactory.appudine D/CordovaInterfaceImpl: Sending activity result to plugin
03-30 17:56:37.614 16263-16263/it.infofactory.appudine W/CordovaPlugin: Attempted to send a second callback for ID: BarcodeScanner252239265
                                                                        Result was: {"text":"http:\/\/www.perchenonfunzioni.it","format":"QR_CODE","cancelled":false}
**03-30 17:56:37.614 16263-16263/it.infofactory.appudine W/CordovaInterfaceImpl: Got an activity result, but no plugin was registered to receive it.**
03-30 17:56:37.661 16263-16263/it.infofactory.appudine W/art: Attempt to remove local handle scope entry from IRT, ignoring
03-30 17:56:37.725 16263-16263/it.infofactory.appudine E/chromium: [ERROR:layer_tree_host_impl.cc(2121)] Forcing zero-copy tile initialization as worker context is missing

**Comment by USSliberty** [comment]
@Petrik-a-dost i've finally found the reason why i get this behaviour. 
I'm using ionic and i've noticed that I recive a ghost click event that eventually calls the scan() function twice. So it creates **two activity** one on the top of the other, the first one works correctly and returns the corrected result and closes, the other one is still active so it seems that nothing happened.

Anyway is not a problem regarding the plugin, so i think is better to close this issue.

**Comment by Petrik-a-dost** [comment]
I find solution, I must replace on-touch instead of ng-click and its working, becouse when i use ng-click so sometimes the activity of scan start twice and scanner scan code twotimes imediately after first scan and in this case result was empty string.

**Comment by USSliberty** [comment]
Indeed, i used ng-click too an I had the same problem. Can you close this issue?
