### ISSUE TITLE
White screen after scan

### ISSUE THREAD

**Issue by front-stream** [phonegap/phonegap-plugin-barcodescanner#193]
I have a problem with barcode scanner on Android 5.0.2, cordova android 4.1.1. After click on back button I see white screen. When I click on home button and come back to app everything is ok. Is there workaround for this issue?

**Comment by sagrawal14** [comment]
I'm having the same issue on iPad *iOS10* with *Cordova 6.5.0* and *6.0.4* version of this library. I'm seeing a white screen after the scan completes. Although, scanning is working fine but the entire app gets hidden after that white screen.

**Comment by durasj** [comment]
I am seeing the same issue as @sagrawal14. As weird as it is, rotating the device afterward fixes the problem.

**Comment by sagrawal14** [comment]
I'm passing these options to the `scan` method:

```
{
    preferFrontCamera: true,
    showFlipCameraButton: true,
    orientation: 'landscape'
}
```

**Comment by jcesarmobile** [comment]
@sagrawal14 @durasj it's not the same issue, your is https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/402

**Comment by sagrawal14** [comment]
Wooohhh!! That was quick @jcesarmobile. I'll try out that immediately. Thanks a much!
