### ISSUE TITLE
Not working in LOLLIPOP and new device

### ISSUE THREAD

**Issue by edvenkat** [phonegap/phonegap-plugin-barcodescanner#194]
Hai friends 
I installed the barcode scanner plugin.it working on KITKAT version but not  LOLLIPOP  please tell if i did anything wrong................

**Comment by prasad8mhatre** [comment]
I think your issue might be:-
1. when you click on scan button, the scanner opens with error alert message.
Work around for that(hack): <platform> <preference name="android-targetSdkVersion" value="22"/></platform> in config.xml

**Comment by mike-eason** [comment]
> it working on KITKAT version but not LOLLIPOP 

What exactly isn't working? Can you be more specific? The more details you provide the more likely it'll be that we can identify what the issue is and whether or not it's a bug.

**Comment by AlDrag** [comment]
I think I am having the same issue as him?
With Ionic, my app doesn't seem to be requesting permissions for the Camera on Lollipop so it fails everytime. I am not sure if this is related to this plugin or bad implementation on my part.

**Comment by pramodkumard** [comment]
Its due to Permissions change in Android M.
Your Scanner needs camera and camera hasnt granted permissions to use and thus u getting error.
If this is the case, you need to upgrade your camera plugin to latest release.
Or for a quick fix just add this pref in config.xml
        <preference name="android-targetSdkVersion" value="22"/>
by which you are enforcing the app to behave as in Kitkat thought the device has Lollipop or whatever.

**Comment by AlDrag** [comment]
@prasad8mhatre 
My understanding is that the latest release does not have these permissions? Not when I tested anyway. It doesn't notify the user if they want to allow the app to use the Camera or not. I could be doing it wrong possibly?
Apologies, but your 'pref in config.xml' never appeared in your comment.

**Comment by pramodkumard** [comment]
`        <preference name="android-targetSdkVersion" value="22"/>
`

this code got stripped off in the above post.

**Comment by AlDrag** [comment]
But then you are leaving a market out for new devices :/ Oh well.
