### ISSUE TITLE
Incompability with the flashlight plugin

### ISSUE THREAD

**Issue by mfalk118** [phonegap/phonegap-plugin-barcodescanner#199]
I am trying to allow the user to turn on the flash, before scanning, by using this plugin: https://github.com/EddyVerbruggen/Flashlight-PhoneGap-Plugin

If i turn the flash on then the Android camera stops working. It has been working with older versions of phonegap, i am currenty using version 6.

I saw from another issue that i can use volume up/Down for flash which works, however i also use the app on iOs, and therefore i would like it to work the same way.

I am not sure if i can get any valuable information from the phone, but i get a lot of information in my output Windows (I use TACO). I have uploaded to files, one where the flash is on,
 and one where it was off

[Logs.zip](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/200836/Logs.zip)

Please help
br
Michael

**Comment by olton** [comment]
Same problem. It is possible as that to solve it or add an on, off and switching flash

**Comment by EddyVerbruggen** [comment]
In 6.0.4 you can pass in the option `showTorchButton : true` to show a torch button. 🔦
