### ISSUE TITLE
Scanning with vertical mode on Win 10 Mobile not working [2]

### ISSUE THREAD

**Issue by gapfonseca** [phonegap/phonegap-plugin-barcodescanner#202]
Tested on Nokia Lumia 730 Windows 10 Mobile, horizontal works ok, vertical doesn't work. Maybe it has to do with screen size since a guy around here said it worked for a Lumia 720 with Win 10 mobile.

Please check.

**Comment by rolandoldengarm** [comment]
Same issue on Lumia 925, Windows Mobile 10. Horizontal works fine, vertical does not. This is a showstopper for us.

**Comment by phongdaohp** [comment]
Are you solve this trouble?

**Comment by lentyaishe** [comment]
Guys, had similar problems in my environment. Couldn't scan at all on Win 10. Was using cordova.
Today I've re-created the cordova project with the latest CLI (6.1.1) and the problem is gone. Successfully performed scanning both in portrait and in landscape.

Hope, it'll help you too.
