### ISSUE TITLE
Windows multiple Scan

### ISSUE THREAD

**Issue by yesiman** [phonegap/phonegap-plugin-barcodescanner#205]
Hi,
On Windows 10 desktop I can use barcode scanner one time but on second scan click the scan load as a black screen with red bar but video seems to be launched lately and then barcode close by itself.
Thanks

**Comment by rosdi** [comment]
Happenning to me too..., scan works fine the first time, but on **second** scan onward it fails **most of the time (not all)**. in my case I am using it with Ionic 2.. here is a simplified code and the error I am receiving..

    import {BarcodeScanner} from 'ionic-native';

    public scan() {
        console.debug("Initiating scanning.");
        this.platform.ready().then(() => {
            console.debug("Platform ready, scanning...");
            BarcodeScanner.scan().then(
                (result) => this.scanSuccess(result),
                (error) => this.scanError(error));
        });
    }

    private scanSuccess(result): void {
        console.debug("Scan success: " + JSON.stringify(result));
    }

    private scanError(error): void {
        console.error("Scan failed: " + JSON.stringify(error));
    

And the error..

    Scan failed: {"asyncOpType":"Windows.Foundation.IAsyncOperation`1<Windows.Media.VideoFrame>","asyncOpSource":{},"asyncOpCausalityId":370}

**Comment by daserge** [comment]
This does not reproduce for me on 5.0.1 - could you please re-test, @yesiman?

**Comment by daserge** [comment]
Please reopen if this still occurs.
