### ISSUE TITLE
phonegap/cordova plugin never calls return success or error function

### ISSUE THREAD

**Issue by rocifier** [phonegap/phonegap-plugin-barcodescanner#214]
In phonegap I wrote a function, which I call when I press a link:

```
function scanBarcode(){
   cordova.plugins.barcodeScanner.scan(
	  function (result) {
		alert("scanned cancel: " + result.cancelled);
	    if (!result.cancelled) {
			alert("Scanned barcode: " + result.text);
			$("#current-code").val(result.text);
		}
	  }, 
	  function (error) {
		  alert("Scanning failed: " + error);
	  }
   );
}
```

On android 4.4.2 the scanner pops up, and I can scan a barcode, then control is returned to my application but none of the alerts ever pop up. I checked logcat and there is no error or warning messages, nothing. Using latest phonegap version and cordova plugin. I also tried using the current github version but it's the same.

**Comment by rocifier** [comment]
Hi any tips for how I might debug this? My client is waiting and I'm totally stumped :(

**Comment by sarangan12** [comment]
@rocifier In most cases, alert function is not available in cordova app. Use console.log or some other maniplulation like loading the results in a div. This will work.

**Comment by rocifier** [comment]
alert is working just fine. console.log has issues. If I place alert('scan'); before calling cordova.plugins.barcodeScanner.scan it pops up as a modal dialog. But after that I get none of the callback functions called, leading me to think the plugin is crashing silently behind the scenes.

**Comment by rocifier** [comment]
Oh my gosh I finally figured out what is happening on both devices I'm testing with. So get this:

1) I set up the state of my app
2) I scan the barcode (or take a photo)
2a) While the scanning screen is open, the OS is completely closing ("pausing") my app in the background presumable to save memory, even though I have a high powered device.
3) After scanning my app is re-launched ("resumed") but its state is not properly recovered - it has no idea we just took a photo, and the old callbacks are detached in memory so are never called.

The hints and possible solution for this are found at http://cordova.apache.org/docs/en/dev/guide/platforms/android/index.html#lifecycle-guide under "retrieving plugin callback results"

**Comment by rocifier** [comment]
Hmm okay so this isn't actually exactly what's happening...

If I enable the "Don't keep activities" setting in the General/Developer Options menu on my device, then I get the event.pendingResult as expected - the activity was actually destroyed. So this isn't working in the normal case where the activity is still alive in the background.

I'll keep you posted.

**Comment by rocifier** [comment]
Yeah it's definitely reloading my whole app when it resumes from taking a photo. My base index.js is being evaluated. That means my app.initialize(); is being called which re-binds all events including pause() and resume(). Then resume() is being called.

**Comment by rocifier** [comment]
Ok I'm convinced this isn't an issue with anything barcodescanner is or isn't doing, so I've made the question more general and moved it here http://stackoverflow.com/questions/37200948/why-is-onready-event-fired-when-my-cordova-phonegap-app-resumes-from-a-plugin-ac

You may close this issue and if anyone has any help or needs help on this issue head over to SO, cheers.

**Comment by jcesarmobile** [comment]
I saw that your problem was a form submitting, so closing this issue
