### ISSUE TITLE
Scanner not working in Android M due to new permissions model

### ISSUE THREAD

**Issue by pramodkumard** [phonegap/phonegap-plugin-barcodescanner#216]
If I jsut have Scaneer in my app and when Scanner requesting access to camera getting "Sorry, the Android Camera encountered a Problem. You may need to restart the device". Though I am using latest updated cordova-plugin-camera ,Im getting this error. If I use camera elsewhere in the app then by that camera will ask permission and now on wards scanner starts working. I think Scanner itself need to get permissions for camera and this plugin as well need to be updated as like other plugins to use cordova-plugin-compat.

**Comment by devcosta** [comment]
The error only happens on Android 6, version 5.1.0 android it worked

**Comment by fzanfolim** [comment]
Good morning , I had the same problem when you update the plugin from a touch :)

**Comment by rondymesquita** [comment]
Same problem here. Seems like plugin does not ask for permission before uses for camera. I think this is related to new android 6 permission styles, where permissions are asked before use and can be enabled/disabled anytime. The plugin [https://github.com/apache/cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera) is a good example. It asks for permission before uses it.

**Comment by rondymesquita** [comment]
[https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/139](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/139)
