### ISSUE TITLE
Custom Result Messages

### ISSUE THREAD

**Issue by riaz12s** [phonegap/phonegap-plugin-barcodescanner#219]
It would be awesome if users could to set custom result messages instead of the default messages like: "Found URL", "Found product"

**Comment by favors** [comment]
I met the same requirement and I install the plugin on https://github.com/wildabeast/BarcodeScanner, the original of this repo and change the file https://github.com/wildabeast/BarcodeScanner/blob/master/src/android/LibraryProject/src/com/google/zxing/client/android/CaptureActivity.java on method handleDecodeInternally to hide the text

**Comment by daserge** [comment]
@riaz12s, see #259

**Comment by EddyVerbruggen** [comment]
With 6.0.5 you can pass in `resultDisplayDuration: 0` to suppress the message on Android entirely. You can then show anything you want yourself as the scanner window will hide itself immediately.
