### ISSUE TITLE
How Can I customize the title and can I add a button below the barcode?

### ISSUE THREAD

**Issue by IYABAO** [phonegap/phonegap-plugin-barcodescanner#225]
The barcode page show a title what is not I want . I wanna customize, and how?
I want to put an button under the barcode so that users can save the barcode image to their phone.
Can you help me with this?

**Comment by riaz12s** [comment]
Hi Iyabao,

If I understand correctly, you want to change the title at the bottom of the screen when scanning a barcode ?

To do this you can set the **prompt** text:

`  cordova.plugins.barcodeScanner.scan(
  	function(result) {
  		alert("We got a barcode\n" +
  			"Result: " + result.text + "\n" +
  			"Format: " + result.format + "\n" +
  			"Cancelled: " + result.cancelled);
  	},
  	function(error) {
  		alert("Scanning failed: " + error);
  	}, {
  		"prompt": "Scan Item", // Change this to what you want it to be
  	}
  );`

**Comment by kodatech** [comment]
I have the same problem, I want to add a button to close the scanner window. Is that possible?

**Comment by jmloveyj** [comment]
It is not possible

**Comment by abcd-ca** [comment]
@jmloveyj I need to pursue adding a button as well. I assume you mean, it's not possible because there's no API to add a button. If I modify the source to add an API, I assume it is possible. Would you please verify?

**Comment by wmakdesi** [comment]
+1

**Comment by seematalanki** [comment]
prompt message is not working on windows platform. Can you please confirm, if any thing additional needs to be done.

**Comment by daserge** [comment]
@seematalanki, from the docs: `"prompt" : "Place a barcode inside the scan area", // supported on Android only`.
