### ISSUE TITLE
Camera crash in Android 6

### ISSUE THREAD

**Issue by cuiti** [phonegap/phonegap-plugin-barcodescanner#229]
This bug is still happening despite the latest merge.
 When I try to scan, there's an alert saying that the Android camera has a problem, and it's possible that you need to restart the device.
It's related to the new Android 6 (API 23) permissions. A workaround for now is setting the targetSdkVersion to "22" in AndroidManifest.xml.

This is the exception in logcat:
```
W/ServiceManager: Permission failure: android.permission.CAMERA from uid=10293 pid=1417
E/CameraService: Permission Denial: can't use the camera pid=1417, uid=10293
com.app-name W/CameraBase: An error occurred while connecting to camera: 0
com.app-name W/CaptureActivity: Unexpected error initializing camera java.lang.RuntimeException: Fail to connect to camera service
```

**Comment by roeycohen** [comment]
Hi culti, 

trying to change 23 to 22 in platforms/android/AndroidManifest.xml
causes this error:
Error: Failed to install apk to device: pkg: /data/local/tmp/android-debug.apk
Failure [INSTALL_FAILED_PERMISSION_MODEL_DOWNGRADE]

can you please explain better how you to by pass the problem?
10x :)

**Comment by cuiti** [comment]
For anyone having this error when changing the targetSdkVersion:
`Error: Failed to install apk to device: pkg: /data/local/tmp/android-debug.apk Failure [INSTALL_FAILED_PERMISSION_MODEL_DOWNGRADE]`
You need to uninstall the app from your device before running it with the modified target.

**Comment by Gp2mv3** [comment]
Beware that it will not be possible to downgrade if the app is published on the Play Store.

**Comment by econnolly** [comment]
There must be lots of people with this error and there is a pending pull request that looks like it will solve this properly. 

Any chance this could be reviewed and accepted if it works?
https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/210

**Comment by EddyVerbruggen** [comment]
@econnolly That code has already been included in the 5.0.0 release.

**Comment by EddyVerbruggen** [comment]
Just tested again on a Samsung Galaxy S6 running Android 6.x with target SDK 23: upon scanning it prompts me for permission and upon approval scanning starts.

Do you guys have these permissions in `AndroidManifest.xml`?

```xml
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
```

**Comment by pke** [comment]
>  That code has already been included in the 5.0.0 release.

Pity that 5.x is totally unusable because it does not detect QR codes properly and in a timely fashion anymore. (3.1.0 is the last version that works fast and reliable). I'll cherry-pick that into 3.1.0 and see if it helps to prevent this error from happening.

**Comment by jcesarmobile** [comment]
It doesn't crash anymore, closing the issue

**Comment by christianraj** [comment]
its getting crashed when the target SDK is 23

**Comment by jcesarmobile** [comment]
@christianraj can you create a new issue providing more information?
