### ISSUE TITLE
Scanning crashes on device.

### ISSUE THREAD

**Issue by nschubach** [phonegap/phonegap-plugin-barcodescanner#23]
During testing on my Nexus 5, I would scan a barcode, get a message stating it found something at the bottom of the scan screen then it crashes completely out.  I then tried it on other devices and it scanned.  Here are my current results:

Android 5.1.1 -- Nexus 5 Crashes on scan.
Android 5.1.1 -- Nexus 6 Works fine.
Android 5.0 -- MotoX 2014 (Second Gen) works.

**Comment by hoerresb** [comment]
+1 have the same issue on Android 5.0.1 - Samsung Galaxy s4. Issue https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/33 looks to be the same.

**Comment by EpoX44** [comment]
Yeah it's the same issue on Android 5.0 - Samsung Galaxy S5.

**Comment by surajpindoria** [comment]
I am unable to reproduce this using Android 5.1.1, is this still an issue for you? @nschubach

**Comment by nschubach** [comment]
Yes, 5.1.1 on my Nexus 5 still crashes.
My Nexus 10 works.

**Comment by sarangan12** [comment]
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it
