### ISSUE TITLE
How do you use the latest versions for Phonegap build

### ISSUE THREAD

**Issue by jonnywhite** [phonegap/phonegap-plugin-barcodescanner#231]
A dumb question but how do you use the latest versions for Phonegap build? If I add this to my config.xml 
`<gap:plugin name="com.phonegap.plugins.barcodescanner" version="5.0" />`
then phonegap build complains that the plugin isn't available. They also recommend [using the npm version](https://www.npmjs.com/package/cordova-plugin-barcodescanner) but it looks like this is quite out of date.

**Comment by jcesarmobile** [comment]
That isn't the phonegap plugin, to use the phonegap plugin (https://www.npmjs.com/package/phonegap-plugin-barcodescanner) you should put this in your config.xml

`<plugin name="phonegap-plugin-barcodescanner" version="5.0" />`
