### ISSUE TITLE
Scanning dense formats like Code 39 or 128 are nearly impossible

### ISSUE THREAD

**Issue by HenrySipp** [phonegap/phonegap-plugin-barcodescanner#232]
I've used this as the most basic possible implementation in my app that I could. I'm finding that when scanning specifically Code 39 barcodes the plugin takes up to 60 seconds in order to recognize the barcode. 

I'm experiencing this on both iOS and Android

**Comment by okonon** [comment]
We have same issue here...

**Comment by uniphonic** [comment]
I've seen the same issue, so we switched to a different Cordova plugin based on ZBar instead, which scans much faster:
https://github.com/tjwoon/csZBar

Only problem is that ZBar doesn't currently support 2D DataMatrix barcodes like the ZXing phonegap-plugin-barcodescanner does, and we need both!

**Comment by uniphonic** [comment]
@okonon @HenrySipp Have either of you tried disabling other barcode format types, to see if that speeds up scanning? I just noticed that there is a "formats" key, where you can pass in the different formats, where it defaults to all. I don't know if that will improve speed at all?

**Comment by pravinsa** [comment]
I have same problame with Code 39 Full Ascii type barcode.
Even some scaner in playstore dose not support this type.

**Comment by simonpapworth6742** [comment]
This is a problem with the more recent version - have just switched from version 2.0.0 (as I knew it in phonegapbuild) there is another thread on this issue as well

**Comment by simonpapworth6742** [comment]
Version 3.1.0 is still fast on iPod 5th Gen, 5.0.1 works ok (not super quick) on iPod 6th Gen

**Comment by Andalarian** [comment]
Do you still have that problem ? Because I'm having that issue and I'm not sure if it's my device or the plugin. I've tested it with a Samsung GalaxyTab S2.

**Comment by satnaruto** [comment]
This is a problem with the more recent version  <plugin name="phonegap-plugin-barcodescanner" spec="~6.0.6">

All worked in under 1 second before - now taking 15 seconds

**Comment by ymohammad** [comment]
I am also facing the same issue. Though it able to scan sometimes the CODE_39 barcode of 20 digits on Android 6+ versions. But it fails on Android 5.1. Maximum it can scan 14 digits barcode. I don't know what is the issue with Android 5.1. Do we have any other way to scan CODE_39 barcode of 20 digits?
