### ISSUE TITLE
Min Android SDK

### ISSUE THREAD

**Issue by AlDrag** [phonegap/phonegap-plugin-barcodescanner#233]
Do we need the min android SDK of 15 there?
Not that it's a huge issue, just that when I want to compile my non-crosswalk apk for android versions 19+, I need to remove this line.

Thanks.

**Comment by Delagen** [comment]
Yes. Don't modify default behavior. I cannot set minskd in all the ways with this plugin

**Comment by EddyVerbruggen** [comment]
Have you guys tried setting the minsdk in config.xml to override it? Not entirely sure that'll work but it usually does. If it doesn't help please comment back here and I'll smarten up the gradle script.

**Comment by Delagen** [comment]
config.xml does not correspond to my build system. But in this case I cannot modify this value through all other 3 methods

**Comment by AlDrag** [comment]
Yea setting minsdk in the config.xml does not work. Even manually setting the minsdk in AndroidManifest doesn't work either, so the plugin is definitely overriding it.

**Comment by nmaas87** [comment]
I got the same problem, because I need to compile for android 10 (2.3.3/2.3.7 Gingerbread Devices) - I know, very old but.. Can't help it.

It is very easy to do that. You just need to change:

config.xml
    <preference name="android-minSdkVersion" value="10" />
    <engine name="android" spec="~4.0.2" />

and in plattforms/Android/CordovaLib/AndroidManifest.xml
<uses-sdk android:minSdkVersion="10" />

HOWEVER, that does not work for this plugin, because of the fact that the aar plugin / packing type of the barcode scanner needs android4+ support, which is included here:

https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/src/android/barcodescanner.gradle

and as far as I know, does not work without that... And that is what is stopping you, I think...

**Comment by gustavocampos** [comment]
Gosh...... I've been struggling to build my non-crosswalk version for days and now I found out that this plugin is bringing min sdk down to 15+
I would stay on 4.x if the camera was not upside down on Nexus 5X

**Comment by cvaliere** [comment]
@EddyVerbruggen I can confirm that this plugin overrides any preference that we put in our config.xml, which seems to me as an obviously bad behaviour

can you remove the line, as suggested here? #275 

thanks a lot!

**Comment by EddyVerbruggen** [comment]
@cvaliere done!

**Comment by cvaliere** [comment]
@EddyVerbruggen thanks a lot
I looked at the commit, it's even better

**Comment by AlDrag** [comment]
@EddyVerbruggen I don't know why, but I think this is still not working.
Testing with Ionic. Even after 'Ionic State Reset' it still seems to override my config.xml
<preference name="android-minSdkVersion" value="19" />

**Comment by AlDrag** [comment]
@EddyVerbruggen Yea I think this still isn't working unfortunately. My AndroidManifest is still getting overwritten. Not sure if it's just my project though, can anyone else confirm? Thank you.

**Comment by cvaliere** [comment]
nope, I can confirm it works
(I have <preference name="android-minSdkVersion" value="16" /> in my config.xml, and it's not overriden)
maybe try to set up a minimal project?

**Comment by koga73** [comment]
I'm having this issue as well. Another plugin requires 16+ and this plugin is overwriting the minSdkVersion in the AndroidManifest.xml to 15. Build fails

**Comment by mafzst** [comment]
After  removing the Line in in config.xml you need to clear the build cache sometimes. 
For me (I'm using Ionic) the most simple methode is to remove and readd the Android platform

Hope It helps

**Comment by koga73** [comment]
@mafzst I removed the platforms and plugins directories, re-prepared the platform with the latest version of barcodescanner and it still drops my minSdkVersion from 16 to 15 during build. Since another plugin requires at least 16 the build fails.

The only way I was able to get around it was to modify the barcodescanner.gradle file and update it from 15 to 16. Definitely not a good solution though because if I ever wipe the platform it'll get lost.

**Comment by redon** [comment]
I have the same problem.
I need minSdkVersion 21 and in the AndroidManifest.xml I have
`    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="23" />
`
But when uploading the apk to the Play Store the version is downgraded to 15 :-(
Without the plugin the minSdkVersion in the Play Store is correct.

**Comment by andrey-andreev** [comment]
I have exactly the same problem like @koga73, I'm using ionic too and one of the plugins require minSdkVersion 16. Does some one have a solution ?

**Comment by Delagen** [comment]
I writed own cordova hook to remove this at build step

**Comment by redon** [comment]
this fork helped me
https://github.com/gustavocampos/phonegap-plugin-barcodescanner

Thanks

**Comment by kamilbrk** [comment]
Any news on this since few months ago? The override is still in place, ignoring  android:minSdkVersion setting in the project.

**Comment by danielehrhardt** [comment]
I have the same Problem with this Plugin and the PayPal Plugin. Is there a fix?

**Comment by jcesarmobile** [comment]
there are dozens of PayPal plugins, can you link the one you are using?

**Comment by Delagen** [comment]
use this hook https://gist.github.com/Delagen/c1264df9176666f25ee8d745f6a2cbc2 cause it https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/413 solve only one way of overriding minSDK
config.xml part
```xml
	<platform name="android">
		<hook type="before_compile" src="scripts/android/hook.js"/>
		<hook type="before_prepare" src="scripts/android/hook.js"/>
		<hook type="before_build" src="scripts/android/hook.js"/>
```

**Comment by jcesarmobile** [comment]
Yeah, I fogot to consider other plugins setting the minSDK.
I think this PR should cover it, can you test it?
https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/420

**Comment by Delagen** [comment]
@jcesarmobile  It only depends on `config.xml` preference.
But it could be set via
- gradle param with the way
```
1.  export ORG_GRADLE_PROJECT_cdvMinSdkVersion=20
2. -- --gradleArg=-PcdvMinSdkVersion=20
3.  cdvMinSdkVersion=20 in <your-project>/platforms/android/gradle.properties
4.  ext.cdvMinSdkVersion = 20 in <your-project>/build-extras.gradle
5. android-minSdkVersion in config.xml
```
