### ISSUE TITLE
Remove Result Prompt

### ISSUE THREAD

**Issue by drdpedroso** [phonegap/phonegap-plugin-barcodescanner#234]
Hey Guys, I don't want to show the result of the QRCode I'm reading. The prompt message is showed like "Simple text: foo"

Is there a way of taking this off without changing the plugin source?

**Comment by jcesarmobile** [comment]
On the success callback you have to do whatever you want with the result.text, you don't have to show it if you don't want, but the plugin code doesn't show it, just return the value

```
function (result) { 
           // Do whatever you want with result.text
}
```

**Comment by drdpedroso** [comment]
Really? Because the prompt is showing the result here. I'm doing something like this:

        $cordovaBarcodeScanner.scan(
            function (result) {
                var qrcodeReceived = result.text.split("|");
                 //dosomething
            },
            function (error) {
                  console.log("error")
            },
            {
                "preferFrontCamera" : false,
                "showFlipCameraButton" : false,
                "formats" : "QR_CODE, RSS_EXPANDED",
                "prompt": " ",    //if I remove this line, the prompt shows the result the same way
                "orientation" : "portrait"
            }
        );

**Comment by jcesarmobile** [comment]
I think I didn't understand you. Can you provide a screenshot of what you call "prompt"? 
This only happens on Android, right?

**Comment by daserge** [comment]
@drdpedroso, see #259. 
You will probably need to modify and rebuild underlying barcodescanner-lib-aar.

**Comment by drdpedroso** [comment]
Just changed the line 560 to 
     ` resultView.setVisibility(View.GONE);`

**Comment by daserge** [comment]
This one https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/eb9d15efa36e903100d7134c46759714f30b7d2e/barcodescanner/src/main/java/com/google/zxing/client/android/CaptureActivity.java#L560?

**Comment by jovi-Li** [comment]
change  line 560 did not work  
I delete line 653 worked:
// statusView.setText(getString(resultHandler.getDisplayTitle()) + " : " + rawResultString);

**Comment by drdpedroso** [comment]
Take a look at this fork: https://github.com/drdpedroso/BarcodeScanner
It has a white square for QR Code reading and the prompt is not showing.

**Comment by EddyVerbruggen** [comment]
Should be gone with 6.0.5 if you set `resultDisplayDuration: 0`.
