### ISSUE TITLE
Not working for iOS

### ISSUE THREAD

**Issue by oumayma-ltaief** [phonegap/phonegap-plugin-barcodescanner#236]
Hello,
I'm using your plugin for my cordova app.
It's working fine with android but when I tried to generate an iOS version with Xcode, the app build failed.
Any suggestions to fix that problem please?
Thanks.

**Comment by daserge** [comment]
@oumayma-ltaief could you please provide any error logs and describe your environment (iOS, OSX, XCode versions)?

**Comment by oumayma-ltaief** [comment]
The issue was solved after updating to version 4.0.1 of the plugin with ngCordova.
Thanks.
