### ISSUE TITLE
BarcodeScanner.java Error

### ISSUE THREAD

**Issue by KangJane** [phonegap/phonegap-plugin-barcodescanner#237]
Hello. I'm Jane. I will make a BarcodeScanner App but I have a problem.

After Installing BarcodeScanner plug, BarcodeScanner.java had Errors.

so.. I added com.google.zxing.client.android.captureacitivity.jar.

but I still have errors.

intentScan.putExtra(Intents.Scan.CAMERA_ID, obj.optBoolean(PREFER_FRONTCAMERA, false) ? 1 : 0);
                        intentScan.putExtra(Intents.Scan.SHOW_FLIP_CAMERA_BUTTON, obj.optBoolean(SHOW_FLIP_CAMERA_BUTTON, false));
                        if (obj.has(FORMATS)) {
                            intentScan.putExtra(Intents.Scan.FORMATS, obj.optString(FORMATS));
                        }
                        if (obj.has(PROMPT)) {
                            intentScan.putExtra(Intents.Scan.PROMPT_MESSAGE, obj.optString(PROMPT));
                        }
                        if (obj.has(ORIENTATION)) {
                            intentScan.putExtra(Intents.Scan.ORIENTATION_LOCK, obj.optString(ORIENTATION));
                        }
1. CAMERA_ID cannot be resolved or is not a field
2. ORIENTATION_LOCK cannot be resolved or is not a field.

Could you  reply my errors?

**Comment by daserge** [comment]
Hi @KangJane, could you please see if the solution in #224 helps?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by justinhenricks** [comment]
I am also getting this exact error in Android at the moment. Cordova version 6.4.0

**Comment by Gerben321** [comment]
Same here.
