### ISSUE TITLE
ios callbacks not called

### ISSUE THREAD

**Issue by roeycohen** [phonegap/phonegap-plugin-barcodescanner#238]
Trying the sample code on iPhone 6 shows the scanner but the success callback never returns.
the bug makes the library unusable :(

**Comment by davidecantini** [comment]
I'm experiencing the same issue on iPhone 6s iOS 9.3.2 (the same app works properly on Android).

**Comment by davidecantini** [comment]
After some experiments, I found out that the issue on iOS seems to be related to the "formats" parameter. In particular, while the following does not work:
`"formats" : "EAN_8, EAN_13, QR_CODE"  (not working)`
it works if "formats" is either omitted (i.e. default to all) or set to have the format of the code being scanned as the first in the list, i.e.
`"formats" : "EAN_13, EAN_8, QR_CODE" (working)`

Hopefully this helps to fix the issue. Thanks.

**Comment by EddyVerbruggen** [comment]
@davidecantini can you try `"formats" : "EAN_13,EAN_8,QR_CODE"` (no spaces)?

**Comment by davidecantini** [comment]
@EddyVerbruggen, it works without spaces, as follows:

"formats" : "EAN_8,EAN_13,QR_CODE" (working)

That confirms that the issue may be related to the "formats" parameter and, in particular, to its parsing.

**Comment by EddyVerbruggen** [comment]
Correct, the iOS implementation doensn't currently like spaces.

**Comment by roeycohen** [comment]
Hi,
playing with the formats doesn't work for me.
I've tried the samples above, without commas. tried to omit this parameter entirely but with no success.
:(

**Comment by daserge** [comment]
@roeycohen, are you using Ionic/Angular in your app? (might be related to #220?)
In a blank Cordova app it does not reproduce for me on iPad (iOS 8.1).

**Comment by EddyVerbruggen** [comment]
@roeycohen Just checking that where you say 'commas' you actually meant 'spaces'?

**Comment by diloreto** [comment]
Having the same issue here, regardless of whether I pass "formats" or not. I wish the options object was better documented for things like this. Is it required?

**Comment by jcesarmobile** [comment]
For those whose problem isn't the formats, can you try with console.log or the dialogs plugin instead of using a regular alert?

**Comment by jcesarmobile** [comment]
I can't reproduce the issue

Can you try latest version of the plugin and/or provide a sample where it fails?

**Comment by tranhieutt** [comment]
Today, I still can't scan QR code with iPhone 6 iOS 9.3.3

**Comment by teunsteenbekkers** [comment]
I'm having this issue as well.

Version 6.0.1 of the plugin, not using the options parameter(s).

Android works just fine, as do other apps with barcode scanning functionality.

This problem seems to happen mostly on iPhone 6 and iPad. Both with iOS 9.3.4 installed. Haven't been able to try out other devices myself.

**Comment by tranhieutt** [comment]
So, i decide to use :
[]https://github.com/TheLevelUp/ZXingObjC

to create plugin for cordova, it fast and can scan many bar code type/format.
