### ISSUE TITLE
iOS 9.3.2 Broke Scanner?

### ISSUE THREAD

**Issue by AlDrag** [phonegap/phonegap-plugin-barcodescanner#239]
I have some clients reporting The Scanner is no longer working on their phones. This seems to fall around the same time the iOS 9.3.2 update came out. Anyone else getting any issues on iOS 9.3.2 devices?

Thanks

**Comment by roeycohen** [comment]
same for me with iphone 6 with ios v8.4.

**Comment by AlDrag** [comment]
Nevermind. It works fine. Apologies. Feel free to remove.
