### ISSUE TITLE
Plugin fails to build in Cordova project

### ISSUE THREAD

**Issue by AndrePrins28** [phonegap/phonegap-plugin-barcodescanner#24]
Good day guys,

I have an issue where when I add the plugin to my project, the build fails, but when I remove it, it works just fine again.

The error result i get is the following:
    Warning: [aapt] warning: string 'menu_settings' has no default translation.
    Error: [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/BarcodeFormat;
       [dx]     at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
       [dx]     at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
       [dx]     at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
       [dx]     at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       [dx]     at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
       [dx]     at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
       [dx]     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
       [dx]     at com.android.dx.command.dexer.Main.run(Main.java:245)
       [dx]     at com.android.dx.command.dexer.Main.main(Main.java:214)
       [dx]     at com.android.dx.command.Main.main(Main.java:106)
       [dx]
    Error: /home/builder/BpcTooling/BuildScripts/node_build/node_modules/q/q.js:151
                throw e;
                      ^
[object Object]
    Error: 'Build failed with error code 8'

Any help would be appreciated!

Regards

**Comment by Hirbod** [comment]
+1

**Comment by surajpindoria** [comment]
Hi @AndrePrins28, I am unable to reproduce this. Is this still an issue for you?

**Comment by wundo** [comment]
I'm not @AndrePrins28, but yes, I'm still experiencing this very same issue

**Comment by AndrePrins28** [comment]
Hi guys

Sorry for never responding with the solution.

My issue was the following:
The plugin I included (a custom plugin in my case) was including a .java file already included in the project by another plugin (the java files are specified in the plugin.xml)

When I removed the duplicate .java file it worked.

**Comment by surajpindoria** [comment]
Are you seeing the same error as above @wundo?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by wundo** [comment]
Hi @surajpindoria no, I'm not experiencing it anymore thanks :)
