### ISSUE TITLE
Msi format for Android and iOS

### ISSUE THREAD

**Issue by dannywillems** [phonegap/phonegap-plugin-barcodescanner#241]
Coud you implement the Msi format for Android and iOS? It's only available on Windows for the moment.

**Comment by PhonegapDeveloper2017** [comment]
Is there any update on this? Is there any estimate on when this could be added?

**Comment by wildabeast** [comment]
I know this is old, just doing some gardening where I can.

This plugin is basically just a cordova plugin wrapper for the zxing barcode processing library. As such I wouldn't expect maintainers of this project to be adding support for additional barcodes. More likely something to take up with the zxing project maintainers -- and if it makes it in, this project could be updated with appropriate updated zxing libraries.

Closing, feel free to re-open if you disagree.
