### ISSUE TITLE
Configurations for Ionic

### ISSUE THREAD

**Issue by hamark** [phonegap/phonegap-plugin-barcodescanner#243]
Hi,
As you know barcodescanner is integrate in Ionic native. But without any configuration.

It seems that it would be possible to include configuration in Ionic native just by switching args in the scan method.

`BarcodeScanner.prototype.scan = function (successCallback, errorCallback, config) {..}`
with 
`BarcodeScanner.prototype.scan = function (config, successCallback, errorCallback) {..}`

Can you do something with this ?

**Comment by EddyVerbruggen** [comment]
@hamark If that's the case then to me it makes more sense to [report an issue in the Ionic Native repo](https://github.com/driftyco/ionic-native/issues) instead, don't you agree?

**Comment by hamark** [comment]
Thanks for your answer.

I'm obviously not an expert, but it seems to be a javascript limitation. When i look other cordova plugin integrate in ionic-native, options are always before success and failure function. 

for example if i try to change ionic-native with barcodescanner options
```ts
    @Cordova()
    static scan(options?:{
        preferFrontCamera?:boolean,
        showFlipCameraButton?:boolean,
        prompt?:string,
        formats?:string, 
        orientation?:string
    }):Promise<any> {
        return;
    }
```

i have the following error  : `BarcodeScanner.scan failure: success callback parameter must be a function`

If you still think it's an ionic-native problem, then i'll go open an issue in ionic-native

Thanks for your help.

**Comment by EddyVerbruggen** [comment]
Let's ask @kraffslol because he was the [original author of Ionic Native's barcodescanner bridge](https://github.com/driftyco/ionic-native/commit/c94fe23d2a561583ef633ff0179d458d45c1b535).

**Comment by kraffslol** [comment]
Is [this](https://github.com/driftyco/ionic-native/blob/c94fe23d2a561583ef633ff0179d458d45c1b535/src/plugins/barcodescanner.ts#L8-L15) of any help?

**Comment by hamark** [comment]
Same problem with this.
Is this work for you ?

**Comment by kraffslol** [comment]
Looking at [this](https://github.com/driftyco/ionic-native/commit/6688c4d91d38bd0407a570ac34882729f844554a#diff-226a9b93c8de035b9458de820a6ba14b)  commit it seems like they've modified it since I made it and removed the ability to add options. Sadly I'm far from experienced when it comes to TypeScript so I'm not of much help in this matter.

You could try forking the repo, and changing the line to 
```javascript
static scan(options: any): Promise<any>;
```
and then installing your version through npm.

**Comment by hamark** [comment]
Actualy i tried this before posting this issue here

**Comment by kraffslol** [comment]
Does this work?
```js
BarcodeScanner.scan({"preferFrontCamera" : true}).then((barcodeData) => {
    // Success! Barcode data is here
}, (err) => {
    // An error occurred
});
 ```

**Comment by hamark** [comment]
What i've tried : 
in `node_modules\ionic-native\dist\plugins\barcodescanner.d.ts`

```javascript
    static scan(options?: {
        preferFrontCamera?: boolean;
        showFlipCameraButton?: boolean;
        prompt?: string;
        formats?: string;
        orientation?: string;
    }): Promise<any>;
```

where i declare barcodescanner

```javascript
BarcodeScanner.scan({"preferFrontCamera" : true}).then((barcodeData) => {
            // ...
        }, (err) => {
            // ...          
        });
```
Error in my console when debugging on android phone :

`BarcodeScanner.scan failure: success callback parameter must be a function `

**Comment by kraffslol** [comment]
You can't modify .ts file directly like that since it has to compile down to .js. You will have to rebuild it whenever you change a .ts file. See [this](https://github.com/driftyco/ionic-native/blob/master/package.json#L40-L41)

**Comment by hamark** [comment]
Sure, i fallowed this [GUIDE](https://github.com/driftyco/ionic-native/blob/master/DEVELOPER.md)

**Comment by kraffslol** [comment]
Then I'm out of ideas :(. You should probably create an issue on the ionic-native, maybe they can help you out.

**Comment by hamark** [comment]
Thanks for your help anyway :+1:

**Comment by daserge** [comment]
Closing as it has been resolved on the ionic-native side.
