### ISSUE TITLE
Manual Entry Option

### ISSUE THREAD

**Issue by sbasi5576** [phonegap/phonegap-plugin-barcodescanner#245]
Is there a way to enter the barcode manually i.e. type it in?

**Comment by wcalderw** [comment]
You may do this in your app. 
We have a button that lets you scan a code associated with an edit box where it would be displayed.
If scanned fill in the edit box. If not let them type away.

**Comment by robinsonlam** [comment]
Hey @wcalderw, thanks for the answer.

Can you elaborate on your answer? I'm trying to have a button on the scan/camera page where you can click to open up an input box to input a manual code instead.

**Comment by wcalderw** [comment]
On the view where the Scan button is displayed have an edit box that
displays the scanned result. This editor box also supports typing in the
code if needed as well.

**Comment by robinsonlam** [comment]
Oh right, so instead of initializing the camera you pass the entry directly through? So there's no button on the actual camera screen itself?

**Comment by wcalderw** [comment]
You never call the barcode scanner because you let the user enter the
barcode value instead.
