### ISSUE TITLE
Cordova build - long time signing 

### ISSUE THREAD

**Issue by jacekhajduk** [phonegap/phonegap-plugin-barcodescanner#246]
Hello
I have some issue with new version plugin (5.0.0). 
When I use **cordova build android** - I must wait vary long to finish build (in v4.1.0 all work fine).
I use cordova 6.1.1. (Win 7)

Regards
Jacek

**Comment by guimapalmeira** [comment]
Hi,
I use cordova 6.1.1. (Win 7) too and have the some problem.
build android or run android take a long long time, after install the plugin.
The only workaround is downgrade to cordova 4.1.0?

**Comment by macdonst** [comment]
@jacekhajduk it's probably having to pull down a lot of libraries in order to build. You should raise this issue on cordova issue tracker.
