### ISSUE TITLE
Unable to take picture

### ISSUE THREAD

**Issue by JLNNN** [phonegap/phonegap-plugin-barcodescanner#247]
Hey,
the camera is being started, but I'm unable to hit the "take that picture damnit"-button. Why? Because it's not there 💃 

iOS is @ latest version, iPhone SE and iPhone 6s Plus tested. Barcodescanner version: 5.0.0.

Used plugins:
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-camera",
    "phonegap-plugin-barcodescanner"
  ]

Thanks in advance!

And by the way: 4.1.0 and 4.0.2 aren't working, too, the camera is just switching from back to front and back again.

![foto 02 06 16 15 50 16](https://cloud.githubusercontent.com/assets/1099235/15747500/4e8d8fbc-28db-11e6-91ae-1aeab6ddbe28.png)

**Comment by EddyVerbruggen** [comment]
The scanner is not supposed to be a picture taking thingy - it'll stop showing the UI when you hit cancel or a barcode is recognized.
