### ISSUE TITLE
Options - Front camera

### ISSUE THREAD

**Issue by bobalazek** [phonegap/phonegap-plugin-barcodescanner#25]
Is there any way, one could define which camera should be used to scan the (bar)code?

**Comment by MaicolBen** [comment]
+1

In iOS you can switch the camera side, but in Android you can't

**Comment by piqus** [comment]
It is camera and android specific quirk. Of course you can change which camera should be used via JS, and then also barcode scanner:

> cameraDirection property is used to set the camera direction(front/back). You have to add it in the options like this:
```
navigator.camera.getPicture(onPhotoDataSuccess, onFail, { quality: 50, cameraDirection:1, destinationType:        destinationType.DATA_URL}); } 
```
> "1" is used for front-facing camera and "2" is used for back-facing camera.
> via http://stackoverflow.com/questions/17021601/phonegap-cordova-front-facing-camera-by-default-in-android

**But, but...**

> "Any cameraDirection value results in a back-facing photo."
> via http://docs.phonegap.com/en/3.1.0/cordova_camera_camera.md.html#cameraOptions_android_quirks

**Comment by bobalazek** [comment]
You are talking about the camera plugin...

The barcodescanner plugin does not accept any options / config as I'm concerned, or does it? 
At least I can't find any documentation, that the .scan method would accept options.

**Comment by convey-mane** [comment]
As far as we are talking about the iOS side, take a look at #97 :wink:

**Comment by MaicolBen** [comment]
@convey-mane #97 adds Android front camera support? seems to me iOS improvements

**Comment by convey-mane** [comment]
@MaicolBen That's exactly why I wrote
> As far as we are talking about the iOS side

The original poster didn't mention any OS, so … just to be sure :wink:
But on iOS, you were right, switching cameras is already possible without my extensions – just added the right icon. Sorry for that!

**Comment by bobalazek** [comment]
Indeed, I was also more thinking about android. 

Otherwise, I wasn't talking about the camera plugin, but the barcode plugin (which doesn't accept any options; so the camera options are not really helpfull).

**Comment by MaicolBen** [comment]
@convey-mane :+1:

**Comment by mlemainque** [comment]
Did anybody find a way to use front camera ?

**Comment by inzi** [comment]
Is there a way to disable camera flipping in the barcode scanner plugin?

**Comment by EddyVerbruggen** [comment]
Note that in the latest ZXing library release a feature was added to specify the camera id. So once this is updated it's easy to pass it in to Android as well.

**Comment by dohoangn** [comment]
To Remove camera flipping in iOS, open CDVBarcodeScanner.mm.
 Remove everything associated with flipCamera in CDVBarcodeScanner.mm

**Comment by inzi** [comment]
Thank you! I ended up commenting it out and doing pretty much just that. 

I have yet to get a custom XIB to work - but for now that's working.
