### ISSUE TITLE
Error building Cordova app for Windows Phone (Universal)

### ISSUE THREAD

**Issue by aristt** [phonegap/phonegap-plugin-barcodescanner#258]
After installing phonegap-plugin-barcodescanner on a Ionic project I get an error when building for Windows Phone Universal with Visual Studio 2015.
I tried to remove the plugin and after that I can build the project without any problem.

Anybody experienced the same problem? Here's a log of the error (it says "file not found", but the .appx file does exist):

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(2519,5): error APPX1204: Failed to sign 'C:\Users\APIAZZA00\Documents\Visual Studio 2015\Projects\Ionic Blank App1\Ionic Blank App1\platforms\windows\AppPackages\CordovaApp.Windows10_0.0.1.0_x86_debug_Test\CordovaApp.Windows10_0.0.1.0_x86_debug.appx'. SignTool Error File not found: C:\Users\APIAZZA00\Documents\Visual Studio 2015\Projects\Ionic Blank App1\Ionic Blank App1\platforms\windows\AppPackages\CordovaApp.Windows10_0.0.1.0_x86_debug_Test\CordovaApp.Windows10_0.0.1.0_x86_debug.appx

Thank you

**Comment by daserge** [comment]
Hello @aristt, this is related to package signing, see http://stackoverflow.com/questions/15099859/signtool-error-while-packaging-windows-store-app for details.
