### ISSUE TITLE
Turning off found plain text 

### ISSUE THREAD

**Issue by midhunanew** [phonegap/phonegap-plugin-barcodescanner#259]
Is there any option to turnoff the text being displayed just after the scan like, `found plain text ...`. Even if it not available as an option for plugin, is there any way to comment out some part in source code and rebuild for Android?

Thank you,
Midhun

**Comment by daserge** [comment]
See https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/41a8f4d5997aee4b4c36228b5827710013007839/barcodescanner/src/main/res/values/strings.xml#L138 and https://github.com/EddyVerbruggen/barcodescanner-lib-aar

**Comment by EddyVerbruggen** [comment]
With 6.0.5 you can pass in `resultDisplayDuration: 0` to get this behavior on Android.
