### ISSUE TITLE
QR Code detection rate worse then v3.1.0

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-barcodescanner#264]
`v3.1.0` was very fast in detecting QR codes. The current master even with only QR code format specified rarely detects any code.
Has there something changed?

**Comment by EddyVerbruggen** [comment]
Can you compare the difference between 5.0.0 and 5.0.1 as well?

**Comment by pke** [comment]
It seems the camera is no longer auto-focusing correctly. Will try 5.0.1 in the next hour.

**Comment by daserge** [comment]
Is the issue on Windows?

**Comment by pke** [comment]
No, on iOS. The Windows implentation is not even worth testing. It needs to be redone using proper media filters. I have an experimental branch for that, a couple of months old.

**Comment by daserge** [comment]
It now works better at least on Windows 10.

**Comment by pke** [comment]
@daserge yes I just realized that. Please see my updated comment.

**Comment by daserge** [comment]
@pke - I agree and it would be great if you could share this alternative implementation.

**Comment by pke** [comment]
5.0.1 is terrible, sorry. Takes forever to focus and understand the QR-code.
3.1.0 was better but it has a terrible bug in how it handles options. The JS says options can be an object. But the iOS code treats the only parameter to `scan` as the `XiBOverlay`. Which of course crashes if you hand in an object as the 3rd argument to `scan`.

**Comment by EddyVerbruggen** [comment]
@pke do you see a difference between 5.0.0 and 5.0.0?

**Comment by pke** [comment]
if you mean between 5.0.1 and 5.0.0 I'd like to check the code differences first here but github seems to have lost that functionality

**Comment by EddyVerbruggen** [comment]
Lol, yeah (comment updated). The feature [is still there](https://github.com/phonegap/phonegap-plugin-barcodescanner/compare/5.0.0...5.0.1).

**Comment by simonpapworth6742** [comment]
Same problem here - sorry

**Comment by simonpapworth6742** [comment]
Ok, so I have done some more work on the iOS on iPod 5th Gen = very slow with version 5.01 & 5.0 & 4.10. On iPod 6th Gen it is much faster. The image keeps on moving and auto focus seems slow on the 5th Gen iPod.

Moved back to version 3.1.0 - and it is so fast - is this because of a new type of recognition, or a recent bar-code type being added?

**Comment by Z3roCoder** [comment]
Is thre any update on this? Two devices (Android 6.0 and 4.4.2) are terribly slow at detecting QR-Codes, the 4.4.2 one detected a code one time and then never again.

**Comment by pke** [comment]
I don't know. I suggest to use 3.1 for the time being. It has the fastest qrcode detection.

**Comment by Z3roCoder** [comment]
Is there not any drawback to it? I am going to need to target Android, iOS, and Windows Universal Apps (Windows10/WinPhones)

**Comment by pke** [comment]
Well the drawback is that the Windows implementation is shit. It uses no steady video stream but instead makes "photos" in intervals and tries to detect the QR code. On the other platforms it runs just fine

**Comment by vladimir-kotikov** [comment]
@pke, what are you saying isn't true, at least for Windows 10. The plugin has been reworked to use new APIs, available on Win10, so no "photos" anymore :)

**Comment by pke** [comment]
I was referring to the last really good working version, 3.1.0. With it qr codes are detected fast. But the Windows implementation in that version is shit. So not untrue at all.

**Comment by vladimir-kotikov** [comment]
Ah, sorry. That makes sense :)

**Comment by kashban** [comment]
Is this still an issue with 6.0.3?

**Comment by lfreneda** [comment]
Same problem here..

**Comment by kashban** [comment]
Latest version 6.0.3 works fine for me. The issue I had with a 4.x version on iOS originated from the bad camera resolution... it seemed to work only in VGA and as such the codes were not sharp but pixelated.

**Comment by lfreneda** [comment]
as @pke said, version 3.1.0 is reading qr codes very fast.. 
on lasted version (6.0.3) resolution is not helping D:

sad

**Comment by pke** [comment]
@lfreneda exactly. And so the recommendation still stands to pin 3.1.0 when you only want to scan QR codes - fast. If you need to detect EAN13 or others alongside QR code your users are in for some wait time :(

**Comment by lfreneda** [comment]
@pke any other issue/bug with v3.1.0?

**Comment by pke** [comment]
@lfreneda none. For Android 6.0 you have to make sure to ask for Camera permissions. I am using the [cordova Android permissions plugin](https://github.com/NeoLSN/cordova-plugin-android-permission) for that.

**Comment by jcesarmobile** [comment]
@pke also, on iOS, you have to set the camera usage description

**Comment by lfreneda** [comment]
@pke @jcesarmobile thank you both :)

**Comment by pke** [comment]
> @pke also, on iOS, you have to set the camera usage description

Correct for that I am using the [custom-config plugin](https://github.com/dpa99c/cordova-custom-config/)

**Comment by kashban** [comment]
@pke the cordova framework asks for camera permission if necessary. There is no need to program that yourself or use any third party plugins.

**Comment by jcesarmobile** [comment]
No, that is done by the plugin and was introduced recently. As they want to use a very old version of the plugin they will have to ask for the permission themselves.

**Comment by lfreneda** [comment]
@jcesarmobile CAMERA permissions? thanks
