### ISSUE TITLE
On Android 4.4.2 immediately return cancelled status, but camera not dissapeared

### ISSUE THREAD

**Issue by ZoRDoK** [phonegap/phonegap-plugin-barcodescanner#27]
Rarely return a scanned object. But if fall on start, not return anything even after success scan.

**Comment by surajpindoria** [comment]
Hi @ZoRDoK, are you still seeing this issue? I am unable to reproduce.

**Comment by Deminetix** [comment]
I believe this is related to https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/38

**Comment by sarangan12** [comment]
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it
