### ISSUE TITLE
iOS 10 requires Camera permission reason

### ISSUE THREAD

**Issue by EddyVerbruggen** [phonegap/phonegap-plugin-barcodescanner#270]
Your app will crash if you don't provide a 'usage description' for the Camera permission prompt.

I'll add an empty reason for now.

**Comment by pke** [comment]
Couldn't that use a `config.xml` preference instead of an empty string?

**Comment by EddyVerbruggen** [comment]
You can override it - this is just so your app doesn't crash if you don't.

**Comment by jcesarmobile** [comment]
Right now it's not possible to add that from config.xml, you'll have to use another plugin that writes to the info.plist

**Comment by pke** [comment]
@jcesarmobile I was under the impression plugins can read config preferences like this in `plugin.xml`:

```
<preference name="CAMERA_PERMISSION_REASON" />

<platform name="ios">
  <config-file target="*-Info.plist" parent="NSCameraUsageDescription">
    <string>$CAMERA_PERMISSION_REASON</string>
  </config-file>
</platform>
```

**Comment by jcesarmobile** [comment]
No, that is for reading variables passed on plugin install, but I think it's a good option to do it with a variable.
I've sent a PR to the contacts plugin following this approach because it has the same problem, you can take a look.
https://github.com/apache/cordova-plugin-contacts/pull/131

**Comment by jcesarmobile** [comment]
#271 was merged, but I'm not closing this yet as I think we should add a way to provide the UsageDescription instead of using an empty string

**Comment by pke** [comment]
Can't this be solved by using a plugin variable or better a preference?

**Comment by jcesarmobile** [comment]
Yes, it can be solved using a plugin variable, see the PR I linked contacts plugin.
But sadly no, a preference can't be used, I tried and didn't work

**Comment by jcesarmobile** [comment]
BTW, you can add the variable on the config.xml

This is what is added when you install the camera plugin with the variable and the --save param. I've tried to add that on a new empty project, just adding this lines on the config.xml and when I add iOS platform the plugin is added and the variable is passed.

```
<plugin name="cordova-plugin-camera" spec="https://github.com/apache/cordova-plugin-camera">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="your usage message" />
</plugin>
```

**Comment by macdonst** [comment]
@jcesarmobile can you take a look at my latest commit. I believe it resolves this issue but I want a second opinion. If it LGT you close this issue and maybe we can do a new plugin release.

**Comment by jcesarmobile** [comment]
Yes, it looks good, closing.

**Comment by michaljakubowski** [comment]
Is there a possibility to set different messages for each language?

**Comment by geoHeil** [comment]
I have set it up like:

```
<plugin name="cordova-plugin-camera" spec="~2.2.0">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="my message" />
        <variable name="NSPHOTOLIBRARYUSAGEDESCRIPTIONENTRY" value="my message" />
    </plugin>
```
In the config.xml

However, these values are not transferred to xcode / the info.plist file  when the ios platform is added.

**Comment by jcesarmobile** [comment]
that change was included in 2.3.0, so try changing to `spec="~2.3.0"`

**Comment by geoHeil** [comment]
Thanks. However, it still does not work.

jcesarmobile <notifications@github.com> schrieb am Fr., 30. Sep. 2016 um
11:21 Uhr:

**Comment by jcesarmobile** [comment]
Try removing platforms and plugins folders and adding ios platform again

Also, for photo library is `PHOTOLIBRARY_USAGE_DESCRIPTION`, not `NSPHOTOLIBRARYUSAGEDESCRIPTIONENTRY`

**Comment by pke** [comment]
>Also, for photo library is PHOTOLIBRARY_USAGE_DESCRIPTION, not NSPHOTOLIBRARYUSAGEDESCRIPTIONENTRY

That might be the reason. I already wondered what strange, non snake'ish, name `NSPHOTOLIBRARYUSAGEDESCRIPTIONENTRY` would be.

**Comment by pke** [comment]
How can this be localized? Can't we add a language specified to the `<string>` tag?

**Comment by jcesarmobile** [comment]
To localize you can read this answer, but it's for native projects, not Cordova ones http://stackoverflow.com/questions/25736700/how-to-localise-a-string-inside-the-ios-info-plist-file

**Comment by benface** [comment]
@geoHeil Were you able to make it work? I'm having this issue. I have this in my config.xml:

```
    <plugin name="cordova-plugin-media-capture" spec="~2.3.0">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="(app name) would like to access your camera to let you take a new profile picture." />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="(app name) would like to access your photo library to let you select a profile picture." />
    </plugin>
```

And I tried doing:
```
cordova platform remove ios
cordova platform add ios
cordova build
```

But this is what ends up in my Info.plist:
```
    <key>NSCameraUsageDescription</key>
    <string/>
    <key>NSMicrophoneUsageDescription</key>
    <string/>
    <key>NSPhotoLibraryUsageDescription</key>
    <string/>
```

**Comment by benface** [comment]
Nevermind, I got this all wrong. I'm using a different plugin, `cordova-plugin-media-capture`. I actually removed it (as well as that snippet from my config.xml file) and re-added it with

```
cordova plugin add cordova-plugin-media-capture --variable CAMERA_USAGE_DESCRIPTION="(app name) would like to access your camera to let you take a new profile picture." --variable PHOTOLIBRARY_USAGE_DESCRIPTION="(app name) would like to access your photo library to let you select a profile picture."
```

And it worked.

**Comment by jcesarmobile** [comment]
Just for your information, the "(app name) would like to access your camera" will be displayed by the system, don't repeat it again, you just have to add the reason why you want to access it.

**Comment by geoHeil** [comment]
Indeed I got it to work after figuring out some caching issues.
jcesarmobile <notifications@github.com> schrieb am Di. 11. Okt. 2016 um
00:02:

**Comment by wmalevski** [comment]
Hello is there a solution for Build Phonegap? I tried:

`  <plugin spec="https://github.com/phonegap/phonegap-plugin-barcodescanner.git#6.0.5" source="git">
    <param name="CAMERA_USAGE_DESCRIPTION" value="Some text here." />
    <param name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="Some text here." />
  </plugin>`

Also I have tried:

`
  <config-file platform="ios" parent="NSCameraUsageDescription">
    <string>Some text here.</string>
  </config-file>
`

But still downloading and opening the IPA, I don't find any text, just empty strings.

**Comment by vendicto** [comment]
@wmalevski  I have the same trouble. Does you resolve it ?

**Comment by wmalevski** [comment]
hey @vendicto 

I have found a solution myself, using:
```
  <gap:config-file platform="ios" parent="NSPhotoLibraryUsageDescription" overwrite="true">
    <string>We are using the Photo Library for something..</string>
  </gap:config-file>
```

This is specific for Build Phonegap.

good luck!

**Comment by vendicto** [comment]
@wmalevski, Thanks for answer but...
I tried your solution, added to the config in different places also added here: <platform name="ios">, but it still doesn't work, at the end I have plist file without "Privacy - Photo Library Usage Description"
You can see my question here http://stackoverflow.com/questions/41680639/nsphotolibraryusagedescription-doesnt-working-on-phonegap

**Comment by jcesarmobile** [comment]
@vendicto the answer @wmalevski gave you is for building with phonegap build, config-file tag doesn't work on Cordova projects. 
You have the values in the info.plist, so if they are removed when you archive, maybe you have found a bug, it they are there, the shouldn't disappear. Try creating the app with the Cordova CLI `cordova build ios --device --release` (you have to create and configure a build.json file first with your cert and provisioning profile information)


BTW, you don't have to add the "AppName would like to access xx", that will be displayed by the system, so it will appear twice, just add the reason why your app needs the camera.

**Comment by vendicto** [comment]
@jcesarmobile @wmalevski  Thanks dudes.
@jcesarmobile I'll try to do like you said.
P.S I removed AppName from description, it was the old screen )

**Comment by Lestt** [comment]
Hi guys,

I tried the last vesion (6.0.5) and i still have this error concerning the PHOTOLIBRARY_USAGE_DESCRIPTION. I've removed the plugin, deleted the ios platform, added the plugin with this commande:
 `cordova plugin add phonegap-plugin-barcodescanner --variable CAMERA_USAGE_DESCRIPTION="My usage here" --variable PHOTOLIBRARY_USAGE_DESCRIPTION="My usage here"`
I had to add the right manually in xcode.
Moreover, i looked into the plugin.xml file in the plugins directory (it's an ionic project so in my case _plugins/phonegap-plugin-barcodescanner/plugin.xml_), and there is no mention about _PHOTOLIBRARY_USAGE_DESCRIPTION_ variable:
```
    <preference name="CAMERA_USAGE_DESCRIPTION" default=" "/>
    <config-file target="*-Info.plist" parent="NSCameraUsageDescription">
      <string>$CAMERA_USAGE_DESCRIPTION</string>
    </config-file>
```
Maybe that could help.

**Comment by jcesarmobile** [comment]
@Lestt this plugin doesn't have the PHOTOLIBRARY_USAGE_DESCRIPTION, does it need it?

**Comment by Lestt** [comment]
@jcesarmobile I tried to upload my app to the store and i got this 2 error message from apple store:
```
Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
```
For this first one, i forgot to add the variable parameter on the command line when i added the plugin. As **phonegap-plugin-barcodescanner** is the one plugin that manipulate camera (and photo ?) in my porject, i suppose i had to add this right too ? I have no more informations from the store about this error.  Let me know if i can help you more about it.
I am a noob with ios environnement so i don't know how i can help you.

**Comment by jcesarmobile** [comment]
It's strange because if you don't have the NSPhotoLibraryUsageDescription and you try to access the Photo Library it will crash, will take a look.
Maybe the encode function is writing/reading in/from the library and nobody noticed that it crash.

**Comment by jcesarmobile** [comment]
Found the problem, I've created a new issue about it https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/406

**Comment by jcesarmobile** [comment]
@Lestt I was wrong, there is no problem with the plugin, see my last comment on #406

You might have another plugin which is adding the NSPhotoLibraryUsageDescription

**Comment by vadimkrutovlv** [comment]
Guys this solution worked for me. Just add following lines to your project projectName-info.plist file.
If you are using xcode, right click and open file a source code. 

    <key>NSCameraUsageDescription</key>
    <string>Description</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Description</string>

**Comment by Lestt** [comment]
@jcesarmobile Ok, sry pointing a non issue and waste your time :/

**Comment by jcesarmobile** [comment]
@Lestt no problem

**Comment by Poliuk** [comment]
This solved my problem 

`config.xml`

```
    <plugin name="cordova-plugin-camera"              source="npm" >
      <variable name="CAMERA_USAGE_DESCRIPTION" value="Allow the app to use your camera" />
      <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="Allow the app to access your photos" />
    </plugin>
    <plugin name="cordova-plugin-media-capture"       source="npm"  >
      <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="Allow the app to access your photos" />
    </plugin>
```

I guess this hardcoded strings will be a problem in the future when it comes to support multiple languages in the App. Any advice?

**Comment by springcode** [comment]
I solved it by adding the tags as suggested by @Poliuk and then removing and re-adding the plugin.

**Comment by ekambarrao** [comment]
Hi all, I have Visual Studio 2017 and used Cordova 7.0 and ios 8.3.1 and Mac 10.X. I am able to successfully build the solution and getting the ipa and plist. Now I am held up at publishing to store. It is giving error as
**Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.**
and I have gone through all the link available and does all mentioned in several posts found it be not resolving the issue. Any suggestion? Note: I know that this not remotebuild issue to add here in this 'thread' but could not find a better place to mention about this than here. 

Can somebody throw some light on this?

**Comment by springcode** [comment]
Hi see the comments above regarding the config.xml in the root of your cordova build.

**Comment by ekambarrao** [comment]
@springcode I have used all those options. in *-info.plist inside Platform/ios/project folder, I can see all the values but it is failing at store validation.

**Comment by springcode** [comment]
Its in the cordova config.xml in the root of your project not in the platform.  You can also click on the plist in Xcode but this will get overwritten with each cordova build

**Comment by jcesarmobile** [comment]
@ekambarrao you don't have to change the info.plist, you have to add the variables in the config.xml or provide such variables from VS2017 (if possible)

```
<plugin name="phonegap-plugin-barcodescanner" spec="~6.0.5">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes" />
</plugin>
```

**Comment by ekambarrao** [comment]
@springcode 
@jcesarmobile

I understand. In that same Config.xml,  I have added all of such tags inside config and they are reflecting in *-info.plist but still getting the same error.

**Comment by DanielNo** [comment]
@Poliuk Your workaround worked for me thanks! Been struggling with this bug for a while

**Comment by joelnewcomer** [comment]
I tried everything and the only solution for me was to uninstall and re-install the cordova-plugin-camera plugin.

**Comment by furkankatman** [comment]
I spent a night on this and pulled my hair but at the end the solution for me  was to add plugin with those params . with these params info plist changed in xcode and successfully uploaded app to test. cordova plugin add cordova-plugin-camera --variable CAMERA_USAGE_DESCRIPTION="your usage message" --variable PHOTOLIBRARY_USAGE_DESCRIPTION="your usage message"

**Comment by raghav-khunger** [comment]
For me the "ionic cordova build ios --release" was removing the values present inside PHOTOLIBRARY_USAGE_DESCRIPTION and CAMERA_USAGE_DESCRIPTION properties in this code:
 
`    <plugin name="cordova-plugin-camera"              source="npm" >
      <variable name="CAMERA_USAGE_DESCRIPTION" value="Allow the app to use your camera" />
      <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="Allow the app to access your photos" />
    </plugin>
`

I changed that to

`        <config-file parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
            <string>Allow the app to access your photos</string>
        </config-file>
        <config-file parent="NSCameraUsageDescription" platform="ios" target="*-Info.plist">
            <string>Allow the app to use your camera</string>
        </config-file>`

and added that code inside of  `<platform name="ios">` tag. 

After rebuilding the Ionic code it is no longer trimming the values present inside PHOTOLIBRARY_USAGE_DESCRIPTION.

**Comment by raghav-khunger** [comment]
I have provided another solution which you can opt while installing plugin.
https://stackoverflow.com/a/47736017/148657

**Comment by jcesarmobile** [comment]
@raghav-khunger That answer is not good anymore, latest versions of cordova core plugins no longer use variables for the usage descriptions, you have to use `edit-config` tag

**Comment by vousys** [comment]
First, this works for me with Cli-7.1.0 after apple reject me the ipa.

1) In your code, if you use for ex. cordova-plugin-barcodescanner and cordova-plugin-camera and cordova-plugin-ios-camera-permissions all the variables CAMERA_USAGE_DESCRIPTION, PHOTOLIBRARY_USAGE_DESCRIPTION should have the same string inside. If one of them is different apple rejects your ipa, because phonegap use the default variable .

ej:
```

<plugin name="cordova-plugin-ios-camera-permissions" >
     <variable name="CAMERA_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
     <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
</plugin><!-- spec="1.0.3" !-->

<plugin name="cordova-plugin-camera" > 
     <variable name="CAMERA_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
     <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
<gap:plugin name="cordova-plugin-image-picker" source="npm" />
<gap:plugin name="cordova-plugin-base64-joewsh" source="npm" />   <!-- convertir a base64 los files !-->


<!-- barcode la v.0.7.2 tiene problemas, ojo !-->
<gap:plugin name="cordova-plugin-barcodescanner"   source="npm" spec="0.7.0" >

     <variable name="CAMERA_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
</gap:plugin>
```
2) add this code (remember to use the same string in the variables, as I mention before):

```
<platform name="ios">

     <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge" overwrite="true">
          <stringYOUR-PERMISSION-REQUEST</string>
     </edit-config>
     <edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge" overwrite="true" >
          <string>YOUR-PERMISSION-REQUEST</string>
     </edit-config>
     <edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge" overwrite="true">
          <string>YOUR-PERMISSION-REQUEST</string>
     </edit-config>
</platform>
```
