### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by donnygunawan93** [phonegap/phonegap-plugin-barcodescanner#273]
![untitled](https://cloud.githubusercontent.com/assets/10414213/16414964/028581a8-3d65-11e6-961e-b47032ac013c.png)

i use sdk 23
after add plugins i got this error, why? how to fix?

**Comment by daserge** [comment]
@donnygunawan93, can you look if #224 helps?

**Comment by donnygunawan93** [comment]
thx
