### ISSUE TITLE
Unable to add plugin

### ISSUE THREAD

**Issue by ayajshaikh** [phonegap/phonegap-plugin-barcodescanner#274]
I am trying to add the plugin using following commands but getting error.

`phonegap plugin add phonegap-plugin-barcodescanner`
`Error: Cannot find plugin.xml for plugin 'phonegap-plugin-barcodescanner'. Please try adding it again.`

**Comment by jcesarmobile** [comment]
I have just tested and worked fine.

Can you provide your phonegap version?
