### ISSUE TITLE
[Android] Barcodescanner sets minSdkVersion to 15

### ISSUE THREAD

**Issue by Nilos** [phonegap/phonegap-plugin-barcodescanner#275]
This would be fine if my minSdkVersion would be lower than 15 which I guess is the case for most projects, but I want to build a version of my app with minSdkVersion 21 which is impossible due to this behaviour of the barcodescanner plugin.
The problem stops if I remove this line: https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/src/android/barcodescanner.gradle#L1

**Comment by gustavocampos** [comment]
Same here.

And here https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/233

**Comment by gustavocampos** [comment]
I cloned this repo and removed the min sdk build instruction, if you want to use it on phonegap build:

<gap:plugin spec="https://github.com/gustavocampos/phonegap-plugin-barcodescanner" source="git" />

**Comment by Nilos** [comment]
Ah thanks! Do not understand why they do not fix this though! :(

**Comment by ben-8409** [comment]
I am affected by this as well and i took me hours to find out what was happening until i manually removed and re-added all plugins to find out. 

I looked at @gustavocampos work and tried to improve by online setting the ext.cdvMinSdkVersion if not yet set or smaller then the current minSdkVersion for this plugin. For me, this fixes the issues.

**Comment by gustavocampos** [comment]
@ben-8409 does it works with Adobe PhoneGap Build?  If yes, can you explain how to change it online?

**Comment by ben-8409** [comment]
@gustavocampos I tried with cordova. How can you tell me the minimal steps to test in phonegap?

**Comment by gustavocampos** [comment]
@ben-8409 the problem with PhoneGap Build is that you cannot change much during the build process, any changes you made for manifest are lost if some plugin overrides it, the build is done online on Adobe servers. 

You'd have to create a project there https://build.phonegap.com/ and do some changes in your config.xml, don't bother doing it I was just curious about how you built the package.

**Comment by ben-8409** [comment]
This is how I tried to verify in phonegap:

1. Install Phonegap CLI (npm install phonegap-cli
2. Create a demo app with phonegap create
3. Add and build android.
4. Verify minSdkVersion on the package using aapk. Result 14.
5. Add the plugin and rebuilt the package.
6. Verify minSdkVersion on the package using aapk. Result 15.

However, it seems settings in config.xml are still ignored. So this is only a half fix.

**Comment by ZoRDoK** [comment]
Some bug on 6.0.4 version

**Comment by ZoRDoK** [comment]
It check cdvMinSdkVersion (gradle param) not a  minSdkVersion set in AndroidManifest.xml

**Comment by basvdijk** [comment]
Are there any updates on if this issue will be resolved / merged? Due this hard coded 15 my Cordova app has a minSdk of 15 while our app only works from 21. This value is overridden when the barcode plugin is used.
