### ISSUE TITLE
App crash in android 5.1.1

### ISSUE THREAD

**Issue by jaassoon** [phonegap/phonegap-plugin-barcodescanner#276]
Error message like that: Android camera has encountered an error, and the APP will be close.

When you start scan,the app will ask you whether allow the device to access camera or not.
If you select no, then the app crash.

manifest file have setting these:
uses-permission android:name="android.permission.CAMERA"
uses-permission android:name="android.permission.FLASHLIGHT" 
uses-feature android:name="android.hardware.camera" android:required="false" 

test device:
huawei SCL-AL00 ,
OS:EMUI 3.1 ,
android version: 5.1.1 API 22

**Comment by fmiboy** [comment]
yes, i confirm this. I had this recently am now using 5.0.0, but I get "Sorry, the Android camera encountered a problem. You may need to restart the device" message for target 23+ API.
Not sure what to do yet, tried various combinations, still unable to solve issue without setting target to 22.

**Comment by daserge** [comment]
This does not reproduce for me neither on Galaxy Grand Prime 5.1.1 nor on Galaxy S4 5.0.1.
Could you please share your `config.xml` and the output of `cordova platforms` and `cordova plugins`?

**Comment by fmiboy** [comment]
I had following, cordova platform add android@5.1.1
and plugin barcodescanner 5.0.0 and after build with min target 23.
I have installed it on Android 6.0.1 and for me app would close without any messages.

**Comment by jaassoon** [comment]
src code at : https://github.com/jaassoon/hello.git  
branch : hello-barcode
attachment is the error log file.
[barcode-scaner-error.txt](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/347989/barcode-scaner-error.txt)

**Comment by daserge** [comment]
@jaassoon, the sample worked fine for me on Android 5.0.1.
I'm going to update SDK tools and retry.

**Comment by daserge** [comment]
Updated SDK, retried on Android 5.0.1 (nothing changed); tried on Android 6 emulator also - works well, `Deny` button does not cause crash, `Allow` opens video preview on successive permission question, recognition works.

**Comment by jaassoon** [comment]
attach files are some screenshots about this issue.

![screenshot_2016-07-06-23-20-59](https://cloud.githubusercontent.com/assets/15890333/16705015/e301601a-45b9-11e6-98e3-12093d49900a.png)
![screenshot_2016-07-06-23-24-45](https://cloud.githubusercontent.com/assets/15890333/16705038/25491d46-45ba-11e6-8f94-456a85871754.png)
![screenshot_2016-07-06-23-25-53](https://cloud.githubusercontent.com/assets/15890333/16705039/25498a92-45ba-11e6-864f-356a0001f224.png)
![screenshot_2016-07-06-23-28-20](https://cloud.githubusercontent.com/assets/15890333/16705040/254aae4a-45ba-11e6-8d55-cfcf86087eb9.png)
