### ISSUE TITLE
Really hard to scan barcode from older phones.

### ISSUE THREAD

**Issue by christiangoudreau** [phonegap/phonegap-plugin-barcodescanner#279]
It's really hard to scan barcode from older phone. Could we scan from a picture instead?

**Comment by asdrubalivan** [comment]
Scanning from a picture is not supported according to the documentation. I'm having the same problem with a Samsung Galaxy GT

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
