### ISSUE TITLE
Native scanner

### ISSUE THREAD

**Issue by pufanalexandru** [phonegap/phonegap-plugin-barcodescanner#280]
I have a PE900S device, which does not have a camera, only a native scanner. 
http://img.china.alibaba.com/img/ibank/2015/845/428/2487824548_99755371.jpg

Is there any method to use this to scan barcodes?

**Comment by jcesarmobile** [comment]
This plugin is to use the phone camera to scan the barcodes, you should check if the device vendor offers some kind of SDK to use the barcode, or maybe it's even ready to just fill the data on some form field where you have the focus. 
But that is out of the scope of this plugin, so I'm closing the issue
