### ISSUE TITLE
IOS freeze cam

### ISSUE THREAD

**Issue by vgiacchina** [phonegap/phonegap-plugin-barcodescanner#281]
I used this plug-in without any problem with ionic . I recently updated cordova - ios and ionic to the latest versions . 
Since I've done the update, the qrcode scanning is no longer working.  
9 times out of 10 when I start scanning, the video streaming remain stuck like a screengrab.
This happens only with iOS, can you tell me how to solve this problem ?

Unfortunately I don't have an iPhone, I received the feedback from users who are using my app

thanks

**Comment by sirius2013** [comment]
I got similar issue. :(

**Comment by vgiacchina** [comment]
6.0.0 works, but i have problem in lollipop, now I study why.

**Comment by devotebest** [comment]
this issue is fixed really?

**Comment by jcesarmobile** [comment]
The person who opened the issue said that it works on 6.0.0 and I couldn't reproduce the issue, so I assume it's fixed.
