### ISSUE TITLE
Surface 3 - focusstate <Not allowed>

### ISSUE THREAD

**Issue by Ponsen** [phonegap/phonegap-plugin-barcodescanner#288]
Running the Plugin on a Surface 3 (not Pro) crashes with the following error:

<img width="368" alt="screen1" src="https://cloud.githubusercontent.com/assets/6484343/16954461/3c105dc2-4dd1-11e6-85d0-496b5d3abef5.PNG">
<img width="537" alt="screen2" src="https://cloud.githubusercontent.com/assets/6484343/16954459/3c0ec80e-4dd1-11e6-9584-9ba882a95aec.PNG">
<img width="388" alt="screen3" src="https://cloud.githubusercontent.com/assets/6484343/16954460/3c0f369a-4dd1-11e6-862d-9664f475fb8b.PNG">

I can see a working preview when I put a breakpoint in line 346 . Continuing results in an app crash.

Commenting the lines 346-348 solves the problem on this device.

**Comment by vladimir-kotikov** [comment]
@Ponsen, unfortunately i don't have a Surface 3 at hand to reproduce the problem and verify the fix, so it'd be great if you could check #318 and let me know if it works for you. Thanks.

**Comment by Ponsen** [comment]
Yes, it's working now like a charm.
Thank you!
