### ISSUE TITLE
stable v2.0.1 works better than current stable v3.0.0 

### ISSUE THREAD

**Issue by liangzhenghui** [phonegap/phonegap-plugin-barcodescanner#29]
my ios sdk is 8.4 and cordova 5.1.1.  
i write two demo
demo1 with v2.0.1 and demo2 with v3.0.3

and i found demo1 is quickly than demo2 with a QR Code image(small and has an url on it)
i test many times,and get the result on my app.hope you to solve it.

**Comment by caipirginka** [comment]
Same for me on iPad Air 2 with a very old plugin version (com.phonegap.plugins.barcodescanner 0.6.0 "BarcodeScanner") all QR Codes were always recognized at first glance.
Now with a very new plugin version (phonegap-plugin-barcodescanner 3.1.2 "BarcodeScanner") it always take a good while and several tries from different point of views, before it reads them.

**Comment by aaronksaunders** [comment]
I am getting various results from scanning the same barcode, also it is starting to scan immediately before I event line it up over the barcode... does the older version address some of this issues?

**Comment by liangzhenghui** [comment]
@aaronksaunders  i did not find such a situation on 2.0.1 version,you can have a try.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
