### ISSUE TITLE
Do not work on Android 6.0.1

### ISSUE THREAD

**Issue by oxydron** [phonegap/phonegap-plugin-barcodescanner#291]
Followed this tutorial here: https://www.youtube.com/watch?v=4EbXrugC3q0
Compiled for android 5.1.1.

```
> cordova platform                                                             
Installed platforms:
    android 5.1.1
```

The error message says (translated from portuguese) _"Sorry, the Android camera found a problem. It may restart the device."_

**Comment by prober996** [comment]
I am getting the same error message using 6.0.1 on a Galaxy Tab A, installed platform android 5.1.1:  "Sorry, the Android camera encountered a problem. You may need to restart the device".  Restarting the device does not cure the problem.  The plugin does work with the same app build on a Samsung tablet running 4.4.

**Comment by prober996** [comment]
Just found a work-around from post #139, which worked for me:

> A potential workaround is to change your target sdk version to 22 (Lollipop) instead of 23 (Marshmallow).
> In platforms/android/AndroidManifest.xml change to:
> 
> <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />
> In platforms/android/prodject.properties change to:
> 
> target=android-22
> I had the same problems as above. Updated cordova to 6, Cordova Android to 5.1 and nothing worked. Then I dowgraded my sdk and that fixed it. Building to Android 5 and Android 6 devices with the old sdk works fine.

**Comment by jcesarmobile** [comment]
which plugin version do you have installed?

type `cordova plugin ls` and paste here the results

**Comment by oxydron** [comment]
> cordova plugin ls
    cordova-plugin-compat 1.0.0 "Compat"
    cordova-sqlite-storage 1.4.6 "Cordova sqlite storage plugin"
    phonegap-plugin-barcodescanner 6.0.1 "BarcodeScanner"

**Comment by jcesarmobile** [comment]
Did you allow your app to use the camera permission?

**Comment by sbasi5576** [comment]
@jcesarmobile  The barcode scanner automatically doesn't ask for the permissions to use the camera on Android 6.1   Instead you have to take a picture with the the app to opt in.

**Comment by Anuj-786** [comment]
hey @sbasi5576 the Android 6.1 app do not ask about permissions. But permission is required you have to write the code for permission otherwise camera will not work.

**Comment by Anuj-786** [comment]
@sbasi5576 use this code to resole the problem:
`barcodescanner.hasCameraPermission().then(
    function(granted) {
      // if this is 'false' you probably want to call 'requestCameraPermission' now
      console.log("Has Camera Permission? " + result);
    }
);

// if no permission was granted previously this wil open a user consent screen
barcodescanner.requestCameraPermission().then(
    function() {
      console.log("Camera permission requested");
    }
);`

**Comment by camilonos77** [comment]
I have this issue. Sorry my english I am spanish speaker. I run the  app with ionic I and the next plugins config:

developer@developer:~/app/geo_tags$ sudo cordova platform
Installed platforms:
  android 5.0.0


developer@developer:~/app/geo_tags$ sudo cordova plugin ls
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova.plugins.diagnostic 3.2.2 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.2 "BarcodeScanner"


But when the plugin read the QR code the App reload to init page config. I test on the device Moto G turbo 3 and Nexus 7 2013  same with android 6 version. Also in the debug with chrome inspect I dont received any error when the app reload the debug is closed and I dont show any message or error.

**Comment by jcesarmobile** [comment]
@camilonos77 that looks like a memory problem, very common on low memory devices when launching an intent. But I test on a moto G 2014 and moto G 2015 and don't have such problem

**Comment by camilonos77** [comment]
I receive the same error at me galaxy Nexus 7 2013 version.

**Comment by amrayoub** [comment]
@prober996 it works perfectly , thank you so much

**Comment by ahsan154** [comment]
Any proper resolution the above problem? 

I am facing the same issue

**Comment by deepakrout** [comment]
I am having same issue. But, in my case it says plugin not installed. I am using ionic 3 project, same plugin works fine in iOS. When I am trying to install the plugin manually getting this error:

`Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.3.0
Skipping 'phonegap-plugin-barcodescanner' for android
Saved plugin info for "phonegap-plugin-barcodescanner" to config.xml
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes`

Any idea?

**Comment by jcesarmobile** [comment]
@deepakrout it's not the same issue.
Your problem is you are using a cordova-android version not compatible with latest version of the plugin.
You can update the cordova-android version or downgrade the plugin version
