### ISSUE TITLE
Android menu crash

### ISSUE THREAD

**Issue by IgorVanian** [phonegap/phonegap-plugin-barcodescanner#294]
So, there was this issue before this repo became official:

https://github.com/wildabeast/BarcodeScanner/issues/11

And it was fixed then (menu items removed from android).
However, the crash still happens in this version (supposed to be fixed?).
Is there a way to remove this menu or will it be fixed in the near future?

**Comment by brainwind-software** [comment]
I am having the same problem, will there be some fix ?
Some possibitlity to remove the menu ?
