### ISSUE TITLE
How to save the result into a variable from Barcodescanner?

### ISSUE THREAD

**Issue by detectivemerry** [phonegap/phonegap-plugin-barcodescanner#296]
Hi, I am new to phonegap and have just successfully installed the Barcode scanner plugin and made it work. However, I am having problems of saving the result of the scan into a variable in Javascript. I have followed lots of answers on StackOverflow on how to, but cant seem to get it working. I am aware I have to either use Callback or AJAX to retrieve result but I am having trouble on both. For callbacks, I can't come up with correct structure and here is what I have ended up with following [this:](http://stackoverflow.com/questions/6847697/how-to-return-value-from-an-asynchronous-callback-function) 

> function scanLater(barcode, fn){
> 						
> 						   cordova.plugins.barcodeScanner.scan(
> 								   fn(result);					
> 							);
> 					}
> 					
> 						scanLater("barcode", function(result){
> 							alert(result);
> 						}

For AJAX, I have jQuery and I tried following [this](http://stackoverflow.com/questions/18066858/barcode-scanner-phonegap-plugin-cant-save-results-into-global-variable-or-sav)

I am stuck at making the AJAX call because i have no idea what to fill under 'url'. I have always directed the url to my php files which made sense but have no idea what the url should be here. I have tried using the path to index.html ( which is where the scanner is at) but it didnt work.

Help on either methods will greatly appreciated!

**Comment by jcesarmobile** [comment]
No, ajax doesn't make any sense in your case, the question you link wanted to send the scanned result to the server, so he was advised to use ajax to do so. In your case you don't want to send it to the server (or you didn't told us that). Ajax is for sending or receiving information to/from the server, and the scan result doesn't come from the server.

I think you just have to change your code to:

`cordova.plugins.barcodeScanner.scan(fn);`

or

```
cordova.plugins.barcodeScanner.scan(function(result) {
    fn(result);
});
```

I have not tested, but I think it should work.

In any case I'm closing the issue as this is not a problem with the plugin itself
