### ISSUE TITLE
PhoneGap Build error

### ISSUE THREAD

**Issue by circleride** [phonegap/phonegap-plugin-barcodescanner#298]
In  Latest PhoneGap Build version: 
https://build.phonegap.com/current-support

PhoneGap (iOS / Android / Windows)
cli-6.3.0 (4.2.0 / 5.2.1 / 4.4.1)

`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "phonegap-plugin-barcodescanner" via npm Installing "phonegap-plugin-barcodescanner" at "6.0.1" for windows Error during processing of action! Attempting to revert... Failed to install 'phonegap-plugin-barcodescanner':Error: Uh oh! ENOENT: no such file or directory, open 'C:\cygwin\home\Administrator\gimlet\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj' at Error (native) at Object.fs.openSync (fs.js:549:18) at Object.fs.readFileSync (fs.js:397:15) at Object.module.exports.parseElementtreeSync (C:\cygwin\tmp\gimlet\2184880\project\cordova\node_modules\cordova-common\src\util\xml-helpers.js:118:27) at Object.jsprojManager.addProjectReference (C:\cygwin\tmp\gimlet\2184880\project\cordova\lib\JsprojManager.js:187:44) at handlers.framework.install (C:\cygwin\tmp\gimlet\2184880\project\cordova\lib\PluginHandler.js:92:25) at Object.ActionStack.process (C:\cygwin\tmp\gimlet\2184880\project\cordova\node_modules\cordova-common\src\ActionStack.js:56:25) at PluginManager.doOperation (C:\cygwin\tmp\gimlet\2184880\project\cordova\node_modules\cordova-common\src\PluginManager.js:117:20) at PluginManager.addPlugin (C:\cygwin\tmp\gimlet\2184880\project\cordova\node_modules\cordova-common\src\PluginManager.js:147:17) at Api.addPlugin (C:\cygwin\tmp\gimlet\2184880\project\cordova\Api.js:191:10) Uh oh! ENOENT: no such file or directory, open 'C:\cygwin\home\Administrator\gimlet\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj' -`

Can you help me? :/ :(

**Comment by liamcooper** [comment]
I'm also having this problem, so would be interested in how to sort it. Can provide config.xml if required.

**Comment by darkdante83** [comment]
Same problem

Build Date: 2016-08-11 14:09:28 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Installing "org.apache.cordova.device" at "0.3.0" for windows
Fetching plugin "cordova-plugin-inappbrowser@1.4.0" via npm
Installing "cordova-plugin-inappbrowser" at "1.4.0" for windows
Fetching plugin "cordova-plugin-network-information@1.2.1" via npm
Installing "cordova-plugin-network-information" at "1.2.1" for windows
Fetching plugin "cordova-plugin-splashscreen@3.2.2" via npm
Installing "cordova-plugin-splashscreen" at "3.2.2" for windows
Fetching plugin "cordova-plugin-statusbar@2.1.3" via npm
Installing "cordova-plugin-statusbar" at "2.1.3" for windows
Fetching plugin "cordova-plugin-whitelist@1.2.2" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for windows
Fetching plugin "cordova-plugin-dialogs@1.2.1" via npm
Installing "cordova-plugin-dialogs" at "1.2.1" for windows
"plugman.cmd install --platform windows --project /cygwin/tmp/gimlet/1352253/project --plugin phonegap-plugin-barcodescanner@6.0.1": Fetching plugin "phonegap-plugin-barcodescanner@6.0.1" via npm
Installing "phonegap-plugin-barcodescanner" at "6.0.1" for windows
Error during processing of action! Attempting to revert...
Failed to install 'phonegap-plugin-barcodescanner':Error: Uh oh!
ENOENT: no such file or directory, open 'C:\cygwin\home\Administrator\gimlet\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.module.exports.parseElementtreeSync (C:\cygwin\tmp\gimlet\1352253\project\cordova\node_modules\cordova-common\src\util\xml-helpers.js:118:27)
    at Object.jsprojManager.addProjectReference (C:\cygwin\tmp\gimlet\1352253\project\cordova\lib\JsprojManager.js:187:44)
    at handlers.framework.install (C:\cygwin\tmp\gimlet\1352253\project\cordova\lib\PluginHandler.js:92:25)
    at Object.ActionStack.process (C:\cygwin\tmp\gimlet\1352253\project\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\cygwin\tmp\gimlet\1352253\project\cordova\node_modules\cordova-common\src\PluginManager.js:117:20)
    at PluginManager.addPlugin (C:\cygwin\tmp\gimlet\1352253\project\cordova\node_modules\cordova-common\src\PluginManager.js:147:17)
    at Api.addPlugin (C:\cygwin\tmp\gimlet\1352253\project\cordova\Api.js:191:10)
Uh oh!
ENOENT: no such file or directory, open 'C:\cygwin\home\Administrator\gimlet\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj'

**Comment by darkdante83** [comment]
I did some testing. Everything is working fine with cli-6.1.0 and lower. So cli-6.2.0 and cli-6.3.0 are not working  with  the plugin. It does not matter what plugin version you are using, all versions are not working on these phonegap versions.

**Comment by narrowfail** [comment]
Same error over here!

**Comment by riddler2kone** [comment]
same here :(

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
