### ISSUE TITLE
Troubles with IOS

### ISSUE THREAD

**Issue by wodka** [phonegap/phonegap-plugin-barcodescanner#30]
Hi, for me on IOS the scanner does not open every time (camera window freezes)

-> if it freezes than I can switch between front and back camera to "unfreeze" the window. Problem with this is that the success function is no longer called.
Luckily there is already a fix for that: https://github.com/wildabeast/BarcodeScanner/issues/282 (working)

but this is only a workaround - any idea how to fix this?
(there is also a small thread here: https://github.com/wildabeast/BarcodeScanner/issues/284)

**Comment by wodka** [comment]
By now I have a solution:

one file needs to be modified:
AppDelegate.m
```(objectivec)
    // replace line 88 "self.window.rootViewController = self.viewController;"
    UINavigationController *aNavigationController = [[UINavigationController alloc]                                                  initWithRootViewController:self.viewController];
    self.window.rootViewController = aNavigationController;
```
(source: http://stackoverflow.com/questions/12350437/getting-current-uiviewcontroller-in-phonegap)

-> change will be that the right view is taken :)

you should also apply fix https://github.com/wildabeast/BarcodeScanner/issues/282

**Comment by halfpt** [comment]
Has there been any progress on this issue? I am encountering it too. I tried the changes to AppDelegate, but it adds an extra header menu into my app (I am using Ionic). 

Any pointers would be greatly appreciated.

**Comment by wodka** [comment]
@halfpt can you try the change from the pull request? I finally found the reason for the behavior (at least for me) - I was calling the scan from a button and there it fired the event twice.

Somehow when it is executed twice the window reference is lost

**Comment by halfpt** [comment]
Thanks a lot for getting back so quickly - I just applied the PR and it seems to have cleared the issue. Now I think back, my UI button seemed to click/flicker twice during the intermittent instances of the freeze. I'll report back if I encounter another freeze, but thanks again for the heads-up.

**Comment by Evanion** [comment]
I discussed this on the Ionic IRC yesterday, and It seems like iOS registers the click twice, and tries to fire up 2 instances. I got [a workaround](https://gist.github.com/AlexSwensen/725ae0b32873612d2db4) from a helpful guy on IRC, but this fix seems to solve the issue @ native level, and I know we all like to avoid js bloat :)

**Comment by pdsullivan** [comment]
I had this happening as well, realized it was caused by the scanner being called more than once. Hope this helps someone. Preventing that from happening fixed the issue. 👍

**Comment by pdsullivan** [comment]
hmm...


![image](https://cloud.githubusercontent.com/assets/2042218/16138195/06d4a262-33f0-11e6-9041-45d9755549ab.png)
