### ISSUE TITLE
Scanner problems on devices with high resolution

### ISSUE THREAD

**Issue by Z3roCoder** [phonegap/phonegap-plugin-barcodescanner#300]
Hello! I experience a frustrating problem right now.
I own a Samsung Galaxy S7 Smartphone and am trying to use the scanner with it, but have two problems with it.
The first one beeing the actual "Scan-Window" beeing terribly small, so its very hard to actually get the QR-Code into the window at all.
The second problem is that the moment I go into portrait mode, the whole image looks weird distorted.

Screenshot:
Problem 1: [http://imgur.com/cMZaCS7](url)
Problen 2: [http://imgur.com/ikjHchO](url) 

Does anyone have an idea how I would go about to resolve those things?

**Comment by Hypher** [comment]
Your screenshots are 404, did you solve your problem?
