### ISSUE TITLE
Error callback not called on first error with version 6.0.1

### ISSUE THREAD

**Issue by Bouzmine** [phonegap/phonegap-plugin-barcodescanner#301]
As stated in title, the error callback isn't called on first `scan` call (when there's an error). It was working with 5.0.1.

**Comment by daserge** [comment]
@Bouzmine, thanks for reporting.
Could you please add details on what platforms are affected and a minimum sample to reproduce it?

**Comment by Bouzmine** [comment]
@daserge Platform is iOS. I simply called `scan` with no options except the success and error callback. I disabled the permission for the camera for my app and that's why I expect an error to be triggered. It triggers this error the second time.

**Comment by jcesarmobile** [comment]
Is there an easy way of making the plugin fail?

**Comment by jcesarmobile** [comment]
I've sent a PR that call error callback if the app doesn't have permission to use the camera

https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/302

But it's strange that it worked on v5 as it has never checked the permission

**Comment by Bouzmine** [comment]
I think it worked in v5 because it called the error callback when an error occurred (this behavior might have changed between the two versions)
