### ISSUE TITLE
Encode not working on Android

### ISSUE THREAD

**Issue by phoxoey** [phonegap/phonegap-plugin-barcodescanner#305]
I build for iOS and test and encoding a QR Code works fine and I can see the tmp jpeg image in the file system. But when tested on Android (version 5.0.2) I get no build errors, no errors when it runs the encode function but no image in the file system and it never runs either the success function or the error function.

**Comment by phoxoey** [comment]
I just updated the plugin version to 6.0.1 from 5.0.0 and now iOS has the same problem, no image.

**Comment by uaza** [comment]
I have the same issue with plugin version 6.0.1 on Android 5.0.2 and 6.x, iOS works fine. Have you already found a solution?

**Comment by phoxoey** [comment]
Couldn't find a solution to making it work on Android. My app interacts with a NodeJs server so I found a NodeJs module called "node-qr-image". It produces an SVG object and returns. Then I construct the SVG image with simple HTML. So long story short, I'm creating the image on the server instead of the phone.

**Comment by uaza** [comment]
Ok, thanks for the information!

**Comment by d3orn** [comment]
I am having the same problem. It looks like Zxing is not loaded/used correctly. Everything works with iOS

**Comment by sivense** [comment]
I hame same problem, logcat say:
THREAD WARNING: exec() call to BarcodeScanner.encode blocked the main thread for 36ms. Plugin should use CordovaInterface.getThreadPool().

**Comment by Mayankjain96** [comment]
@wildabeast  Please correct this issue in android

**Comment by Mayankjain96** [comment]
@phoxoey  Did you guys found any solution for this, encode is not working in android

**Comment by Mayankjain96** [comment]
@daserge Did you guys found any solution for this, encode is not working in android

**Comment by phoxoey** [comment]
@Mayankjain96 I never got it to work on Andriod. The solution that worked for me was to find a way to produce an SVG image, on the server, and send to the mobile app. If your mobile app doesn't interact with a server then your options are limited for sure.

**Comment by Mayankjain96** [comment]
@phoxoey  I am doing the same. Thanks

**Comment by alsorokin** [comment]
@EddyVerbruggen @macdonst 
Hey guys, can you please shed some light on the expected behavior of `encode()` function on Android?
Right now `encode()` on iOS returns an object with a path to an image file with the generated QR code.
On Android I'm getting some another activity opened, which displays the QR code, the text encoded and a "share" button (which is not working, by the way, giving "SD card not available" error). No callbacks called, even after returning to the app.

So is that expected or should it behave like iOS implementation, generating a file and providing a path to it?

**Comment by alsorokin** [comment]
@phoxoey are you getting another activity opened or just nothing at all?

**Comment by EddyVerbruggen** [comment]
Hey @alsorokin AFAIK encode on Android has indeed always worked like that (which sucks in my opinion). I've had the need for encoding myself once and simply called some online API which worked way easier.

**Comment by alsorokin** [comment]
@EddyVerbruggen thanks for clarifying! I was trying to look into this issue but couldn't reproduce it - I always get the code displayed. So if I understand the reporter correctly, it's specific to Android 5.0.2 and there are no code being displayed.
Unfortunately I don't have any 5.0.2 devices, and I couldn't reproduce it on Android 5.0.1 or 4.4.
