### ISSUE TITLE
app crash on ios 9.3 when plug in start

### ISSUE THREAD

**Issue by EminDemiri** [phonegap/phonegap-plugin-barcodescanner#309]
Hello to all.

I just finished an application created with indel XDK.
the application is launched but when I go to start the plugin for scanning the barcode the app is closed.
The first time the system was launched asked permission for the room after which it is closed without giving errors.

What can I do to fix?

IntelXDK version: 3491
Cordova version: 5.4.1

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
