### ISSUE TITLE
Trouble scanning CODE_128 format barcode for VIN

### ISSUE THREAD

**Issue by shawnlehner** [phonegap/phonegap-plugin-barcodescanner#311]
Problem:
Scanner is not recognizing CODE 128 format barcode. I have uploaded an example image that I am attempting to scan.

Description:
I am working on a VIN (Vehicle Identification Number) scanning application and I am having trouble scanning CODE 128 barcodes. I think this could be due to the high density nature of the barcode itself, but I was hoping someone could provide some input on this.

![vin_plate-u12397](https://cloud.githubusercontent.com/assets/5307103/17978074/448d672a-6aa9-11e6-97af-f7ed7fde0e45.png)

**Comment by tylermakin** [comment]
It looks like the image you provided has a resolution too low to read. If you are looking to scan the VIN on an actual vehicle instead of an image like the one above, keep in mind that reflective metal plates and curved glass can make scanning difficult.

**Comment by shawnlehner** [comment]
I tested multiple libraries with this same image and others worked fine on the same device and camera so I don't think it is entirely the image.

**Comment by tylermakin** [comment]
Is it possible that this is not Code 128 format? I generated a few Code 128 barcodes and none of them match the above image, but they all match each other. I overlaid the barcode I generated on your barcode and they do not match.

![overlay](https://cloud.githubusercontent.com/assets/11431414/23488432/6d43b84a-fea1-11e6-86b2-64ea6528f11d.png)

**Comment by chadupton** [comment]
VINs are Code 39, not Code 128.
