### ISSUE TITLE
build failing on android when using this plugin with crosswalk

### ISSUE THREAD

**Issue by sombriks** [phonegap/phonegap-plugin-barcodescanner#319]
After several hours removing and re-adding  plugins and platforms, i've narrowed my problema to those specific (yet not unusual) plugins combination:

> $ cordova plugin list
> cordova-plugin-compat 1.0.0 "Compat"
> cordova-plugin-crosswalk-webview 2.0.0 "Crosswalk WebView Engine"
> cordova-plugin-whitelist 1.2.2 "Whitelist"
> phonegap-plugin-barcodescanner 6.0.1 "BarcodeScanner"

every time i try to build it for android, i get this error:

> Error: /home/sombriks/git/solys-portaria/platforms/android/gradlew: Command failed with exit code 1 Error output:
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> /home/sombriks/git/solys-portaria/platforms/android/AndroidManifest.xml:31:5-74 Error:
> 	uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [org.xwalk:xwalk_core_library:20.50.533.12] /home/sombriks/git/solys-portaria/platforms/android/build/intermediates/exploded-aar/org.xwalk/xwalk_core_library/20.50.533.12/AndroidManifest.xml
> 	Suggestion: use tools:overrideLibrary="org.xwalk.core" to force usage
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':processArmv7DebugManifest'.
> > Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [org.xwalk:xwalk_core_library:20.50.533.12] /home/sombriks/git/solys-portaria/platforms/android/build/intermediates/exploded-aar/org.xwalk/xwalk_core_library/20.50.533.12/AndroidManifest.xml
>   	Suggestion: use tools:overrideLibrary="org.xwalk.core" to force usage
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

The saddest part is that error message is misleading. The generated AndroidManifest.xml project have minSdkVersion set to 16, yet this plugin combination argues that it is 15. there is a 16 there.

If i either remove cordova-plugin-crosswalk-webview or phonegap-plugin-barcodescanner the build works normally.

how can it be solved?

**Comment by sombriks** [comment]
narrowedi it to **barcodescanner.gradle**, in the following line:

> ext.cdvMinSdkVersion = 15

looking at HEAD revision i undersand that it might be solved already.

i'll test master and confirm there.

**Comment by sombriks** [comment]
Hello,

i can now confirm that head version restored the builds containing crosswalk plugin.

i'm using #master for now, however a release would be vastly appreciated.

**Comment by Fayozjon** [comment]
How you solved this? I got some issues with this too

**Comment by sombriks** [comment]
Hi @Fayozjon 

i updated this plugin to the master revision.

at the moment the latest stable version already have it fixed too.

This problem is very specific to barcodescanner+crosswalk.
