### ISSUE TITLE
Release-Build problems on Windows 10

### ISSUE THREAD

**Issue by JToto** [phonegap/phonegap-plugin-barcodescanner#321]
Hello,

I am trying to get this plugin working on an Ionic App on Windows 10. I am therefore using Visual Studio.
Steps I have done:
- Installed phonegap-plugin-barcodescanner via config.xml editor in Visual Studio
- Selected "Debug", "Windows-ARM" and run it on "Device" (Lumia 550)

--> Works perfectly. Can scan QR-Codes without any problems.
- Selected "Release", "Windows-ARM" and run it on "Device"

--> Unspecific Build Errors, see Screenshots

![error1](https://cloud.githubusercontent.com/assets/12485720/18204495/66f170ac-711d-11e6-978a-3fe0672275ee.PNG)

I am able to build and run the app with the plugin deinstalled (I tried it multiple times).

What am I doing wrong?

Greetings from germany.

JToto

**Comment by daserge** [comment]
Hello @JToto is this still an issue?
Which version of cordova-windows platform has the issue if so?

**Comment by daserge** [comment]
The issue might be related to [CB-9524/UseDotNetNativeToolchain](https://github.com/apache/cordova-windows/commit/bb33dfb7d906ecbb77a698393967ae5bace82d80) but it is fixed since cordova-windows@4.1.0.

**Comment by daserge** [comment]
Forgot to say that it works properly in Microsoft Visual Studio Community 2015 Version 14.0.25431.01 Update 3 & Visual Studio Tools for Apache Cordova Update 10.
