### ISSUE TITLE
Windows 10 ZXing is undefined

### ISSUE THREAD

**Issue by sebastianor** [phonegap/phonegap-plugin-barcodescanner#322]
I'm trying run scanner in my Lumia550 with Windows 10. When the scanner is running i get output error 

> /www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
> 0x800a1391 - JavaScript runtime error: 'ZXing' is undefined

I'm trying remove plugin and add it,   but it not helps. My Cordova version is 6.3.1. Thanks for help.

**Comment by daserge** [comment]
@sebastianor are you specifying an architecture?
It is required on Windows 10 and the plugin should currently alert you in Visual Studio TACO or in Cordova CLI.
