### ISSUE TITLE
phonegap-plugin-barcodescanner in npm is version 4.1.0?

### ISSUE THREAD

**Issue by chrstr** [phonegap/phonegap-plugin-barcodescanner#325]
### Expected Behaviour

Doing something like:

cordova plugin add phonegap-plugin-barcodescanner

would pull in the latest version (6.0.2)

### Actual Behaviour

Pulls in version 4.1.0

#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by LintonDevEasy** [comment]
These plugins are so frustrating...

**Comment by jcesarmobile** [comment]
I've just tried and got 6.0.2, maybe you have something cached
