### ISSUE TITLE
Issue with using scanner the first time (after allowing permission)

### ISSUE THREAD

**Issue by dkaskoun** [phonegap/phonegap-plugin-barcodescanner#327]
So, I'm having some issues with the scanner the first time it runs on a device and asks for access to the camera.

Basically what happens, I launch the app, and I click on my test button to bring up the scanner. It runs the scan function, and then ios prompts me to allow access to the camera. I tell it yes. After allowing it, however, the scanner never actually comes up (and actually, the white background that pops up behind the prompt goes away). Any time I try to use the scanner after this, I'm blocked because it's already running, and it never ran any callback functions.

If I restart the app completely and click the button, the scanner works fine. It only has a problem the first time I try to scan something.

Another bit of weirdness to add to the equation: if I hit the Allow button fast enough, it all works, like something is continuing to run in the background but doesn't wait to see if the user gives camera access.

I'm hoping that I'm just being stupid and I'm simply setting something up wrong, or something along those lines. I've encountered this on 2 devices, both running some form of 9.3 I believe. Plugin version is 6.0.2

**Comment by lukasT** [comment]
Have you tried using the diagnostic-plugin to ask for the permission before actually opening the scanner? That way you would be able to react to the answer of the user "authorized" or "denied" accordingly. https://github.com/dpa99c/cordova-diagnostic-plugin.  Not quite sure but I guess thats how it worked for me.
