### ISSUE TITLE
Scan not responding until double tapping iOS home button

### ISSUE THREAD

**Issue by thelucre** [phonegap/phonegap-plugin-barcodescanner#328]
### Expected Behaviour
On iOS, when firing `cordova.plugins.barcodeScanner.scan`, the phone should request camera access (the first time) and when confirmed, display the scanning screen. 

### Actual Behaviour
My app does nothing. Only when double tapping the home button (to view the open apps summary screen) does the access dialog and/or scanning screen show up. Then scanning works normally. When re-requesting `cordova.plugins.barcodeScanner.scan`, the same action is needed to complete the scan. The scanning feature works fine when serving to an iPhone device. The issue occurs after a Phonegap Build is installed on device.

#### Platform and Version 
Bug seen on 
iPhone5s - iOS 10.0.1 
iPad iOS - 9.3.5

#### Cordova CLI version and cordova platform version
6.3.0

Installed platforms:
  android 5.1.1
  browser 4.1.0
  ios 4.1.1

#### Plugin version
6.0.2

**Comment by kafenio** [comment]
+1

**Comment by kafenio** [comment]
Same behaviour here.

Platform and Version
iphone 6 plus, ios 10.0.1,
cordova 6.3.1
plugin version 6.0.2, 6.0.1, 6.0.0

**Comment by thelucre** [comment]
It may be Phonegap Build related, because I'm seeing the same behavior with the `geolocation` plugin. I have an open issue on SO: http://stackoverflow.com/questions/39588073/phonegap-plugin-callbacks-dont-fire-in-ios-build

Possibly related to the plugin build config for iOS?

**Comment by thelucre** [comment]
@kafenio This solved my problem: https://github.com/driftyco/ionic-cli/issues/259#issuecomment-139238385

Related to the `whitelist` plugin
