### ISSUE TITLE
App closes after scanning a Barcode

### ISSUE THREAD

**Issue by EpoX44** [phonegap/phonegap-plugin-barcodescanner#33]
Hi,

i got the problem that the scanner correctly detectes the barcode but closes the app without any error messages on Android. I scan Barcodes with a length of 4 characters and want to navigate to the productdetails of the scanned productno. 

I use cordova and Ionic for the programming.

This is my Code snippet:

     $scope.scanBarcode = function(){
        cordova.plugins.barcodeScanner.scan(
            function ( resultCode ){
                var productno = resultCode.text;
                Product.get( productno ).then(
                    function onSuccess( result ){
                        if(result.rows.length == 0){
                            $scope.popup = $ionicPopup.alert({
                                title: 'Fehler',
                                template: 'Artikel konnte nicht gefunden werden.'
                            });
                            return;
                        }
                        $state.go('app.product.detail', {productId: productno})
                    }, function onError(){

                    }
                );
        }, function( error ){
            console.log("Fehler aufgetreten -> " + error);
        });
    };

Thanks in advance

**Comment by docherty** [comment]
@EpoX44 I have this issue too. I'm using the plugin with Ionic and what I've noticed is that after the plugin scans the barcode correctly, is cancelled etc. it creates **2** "go back" commands. I used the Cordova "Toast" plugin ( nl.x-services.plugins.toast ) to present the user with some feedback. When I did this, the barcode plugin only seems to initiate **1** "go back" command.

It depends on your app but if you're scanning a barcode only 1 screen "deep" within your app then the **2** "go back" commands will exit the app.

I hope that helps.

**Comment by EpoX44** [comment]
Thanks for the reply, but that seemed not to be the problem. In an older version of my app the plugin worked fine.

So I fixed the problem by removing the android platform and adding it again. I have no idea what the problem was, but somehow this worked.

**Comment by sumitsoman** [comment]
Could you help with this similar issue?

[https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/432](432)
