### ISSUE TITLE
How to change the appearance of this plug-in using css?

### ISSUE THREAD

**Issue by grinmax** [phonegap/phonegap-plugin-barcodescanner#332]
I want to change the appearance of this plug-in.
How can i do this?

**Comment by jlowe234** [comment]
Do you mean you just want to change the color of the reticle image (green box)? 

That's hardcoded in the plugin, so if you wanted to make this configurable, someone would need to implement methods to configure those colors.

**Comment by maduperera** [comment]
What about changing the size of the screen to show the below page contents as the title bar. Can that also be done. Please advice.

**Comment by grinmax** [comment]
@jlowe234 @maduperera 
i need do this https://yadi.sk/d/Js7sck9MvqhJS
this can be done?

**Comment by jlowe234** [comment]
It doesn't appear to be an easy way to customize the plugin in the way that you're describing.  You would need to fork and rewrite some of the view controller code for the plugin in order to do what you're describing.

**Comment by grinmax** [comment]
@jlowe234 Thanks for the answer

**Comment by cnryb** [comment]
UI is not very beautiful.
We need a more beautiful UI

**Comment by carol-braileanu** [comment]
+1

**Comment by tiagosamaha** [comment]
@jlowe234 Can you specify the view controller base file?

**Comment by macdonst** [comment]
#11 & #35
