### ISSUE TITLE
build failing on android when crosswalk plugin is added after barcode scanner plugin

### ISSUE THREAD

**Issue by mlaponder** [phonegap/phonegap-plugin-barcodescanner#337]
### Expected Behaviour

When adding the crosswalk plugin and the barcode scanner plugin it should't make a difference in which order they are added to the project.
### Actual Behaviour

When we first add the barcode scanner plugin, and then the crosswalk plugin the compile step fails with the following error:

```
:processArmv7DebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [org.xwalk:xwalk_core_library:21.51.546.6] C:\Users\mla\dev\crosswalk-problem\platforms\android\build\intermediates\exploded-aar\org.xwalk\xwalk_core_library\21.51.546.6\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="org.xwalk.core" to force usage

```

However when adding crosswalk first and then the barcode scanner plugin the build succeeds. Issue seems related to https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/319 and https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/275.
#### Steps to Reproduce

`$ cordova create crosswalk-problem`
`$ cd crosswalk-problem`
`$ cordova platform add android`
`$ cordova plugin add phonegap-plugin-barcodescanner`
`$ cordova plugin add cordova-plugin-crosswalk-webview`
`$ cordova compile`
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

android@5.2.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Not relevant, problem occurs in the compile step
#### Cordova CLI version and cordova platform version

cordova-version: 6.3.1
platform: android@5.2.2
#### Plugin version

phonegap-plugin-barcodescanner 6.0.2 "BarcodeScanner
#### Sample Code that illustrates the problem

See reproduction step.
#### Logs taken while reproducing problem

No additional logs

**Comment by mfzagal** [comment]
same problem

Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library ....

phonegap-plugin-barcodescanner 6.0.2 "BarcodeScanner"

**Comment by nicolasFernandez** [comment]
I'm having the same problem... 

did anyone find a solution?

**Comment by AlDrag** [comment]
@nicolasFernandez remove the minsdkversion 15 from the barcode scanner plugin and it will work.

**Comment by macdonst** [comment]
Won't fix as crosswalk is no longer supported.
