### ISSUE TITLE
Scanning failed: Class not found

### ISSUE THREAD

**Issue by julie78990** [phonegap/phonegap-plugin-barcodescanner#34]
Hi !
I have a problem with the barcode scanner plugin on Android. It works perfectly when I build the app with the CLI but not when I'm using PGB which is strange (or not?). When I press scan I have the alert presents in the title.
Thanks in advance

**Comment by surajpindoria** [comment]
Hi @julie78990, are you still seeing this issue?

**Comment by julie78990** [comment]
Hi @surajpindoria, yes still the same

**Comment by sarangan12** [comment]
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it
