### ISSUE TITLE
Issues scanning ITF barcode on iOS

### ISSUE THREAD

**Issue by reymarx** [phonegap/phonegap-plugin-barcodescanner#341]
Scanning the ITF barcode found at http://www.scandit.com/products/barcode-scanner/symbologies/itf-2-of-5/ works correctly on android, but the plugin doesn't seems to be able to read the barcode in iOS

I'm using version 5.0 of the plugin and tried on both iPhone and iPads

Edit: Using the latest version (6.0.2.) exhibits the same behavior

**Comment by tocrea** [comment]
Hi. Thanks wildabeast team for your barcodescanner plugin.
I'm waiting for your answer, because i've got same issue, event trying using formats option : "formats" : "EAN_13,ITF". Works fine with phonegap app 1.7.2. on Android but can't scan ITF on ios10 (but EAN13 is OK).
Don't have signing key for yet to try online with phonegapbuild.

**Comment by reymarx** [comment]
@wildabeast do you have any insights on what could be happening here? thanks in advance

**Comment by tocrea** [comment]
Hi. Back to give news. I get today my Apple Development ID et signing key for phone gap build and all work perfectly with barcodescanner plugin, including ITF barcode on iOS (testing on iphone)!

**Comment by lucascdsilva** [comment]
I'm having the same problem,  have found a solution? read ITF in ios,  i test in Ipad ios 9.3.2 with barcodescanner 6.0.3

**Comment by tocrea** [comment]
@lucascdsilva the plugin seems don't work for ITF barcode when testing with phone gap mobil app.
But with apple signing key you can test with build.phonegap.com and ITF is working.

**Comment by lucascdsilva** [comment]
Sorry, I do not understand. what's the difference?

**Comment by lucascdsilva** [comment]
I found that my problem is related to the issue #354 ,  ITF with Barcode type - INTERLEAVED 2 of 5

**Comment by cescd6** [comment]
I have the same problem, I explained my situation in #354 

@reymarx  @tocrea were you able to solve the problem?

**Comment by tocrea** [comment]
For me the issue was only when testing with phonegapapp. After signing the app from apple dev. I was able to test the app with phonegap build ( and apple testflight, it's same thing) and all works fine, no more trouble with ITF!

**Comment by lucascdsilva** [comment]
@tocrea I believe it is the type of coding of the bar code "ITF - INTERLEAVED 2 of 5"

**Comment by lucascdsilva** [comment]
try read that code bar with IOS, i want only android
![whatsapp image 2016-11-16 at 16 07 05](https://cloud.githubusercontent.com/assets/4581253/20363816/1d9ab910-ac17-11e6-9ea8-d624bb765fb9.png)

**Comment by cescd6** [comment]
Thanks all, 

But @tocrea I have this problem after signing the app with an Apple's Development Provisioning and testing it with my ipad.

**Comment by imarem** [comment]
I have the same problem after signing the app with an Apple's Development Provisioning.

**Comment by jcesarmobile** [comment]
It's fixed in master
