### ISSUE TITLE
build failing on android

### ISSUE THREAD

**Issue by redon** [phonegap/phonegap-plugin-barcodescanner#345]
### Actual Behaviour
when adding the plugin to the build, the build fails with error

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    A problem occurred configuring root project 'android'.
    > Could not resolve all dependencies for configuration ':_debugCompile'.
       > Could not find any matches for com.android.support:support-v4:+ as no versions of com.android.support:support-v4 are available.
         Searched in the following locations:
             https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
             https://repo1.maven.org/maven2/com/android/support/support-v4/
             https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
             https://jcenter.bintray.com/com/android/support/support-v4/
             file:/private/tmp/xy/xxyy/platforms/android/libs/
         Required by:
             :android:unspecified

the build is completed correctly with no problems, when the plugin is not added
it also worked with the plugin added a month ago
the plugin is the only one I am adding

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android@5.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Not relevant, problem occurs in the compile step

#### Cordova CLI version and cordova platform version
    cordova --version: 6.3.1
    cordova platforms: android@5.1.1

#### Plugin version
    cordova plugin version | grep phonegap-plugin-barcodescanner: 6.0.3

#### Logs taken while reproducing problem
No additional logs

**Comment by pmn4** [comment]
any luck @redon? I'm having the same issue with very similar cordova/plugin versions

**Comment by pmn4** [comment]
to get around this, I removed this line from my <project>-barcodescanner.gradle file:
``` javascript
-    compile 'com.android.support:support-v4:+'
```

_(no idea whether that will impact the behavior of the plugin)_

**Comment by redon** [comment]
that
[http://stackoverflow.com/questions/33185086/failed-to-resolve-com-android-supportsupport-v423-0-0](url)
helped me
I think especially «Had to add "Android Support Repository" from SDK Manager.»

So the problem is not with the barcodescanner-plugin itself but with the installed SDKs
I therefore close this issue
