### ISSUE TITLE
Android 6 close app when the code is scaned

### ISSUE THREAD

**Issue by camilonos77** [phonegap/phonegap-plugin-barcodescanner#348]
#### Cordova CLI version and cordova platform version

```
cordova --version
cordova platforms
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-barcodescanner
```

**Comment by camilonos77** [comment]
I have this issue. Sorry my english I am spanish speaker. I run the app with ionic I and the next plugins config:

developer@developer:~/app/geo_tags$ sudo cordova platform
Installed platforms:
android 5.0.0

developer@developer:~/app/geo_tags$ sudo cordova plugin ls
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova.plugins.diagnostic 3.2.2 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.2 "BarcodeScanner"

But when the plugin read the QR code the App reload to init page config. I test on the device Moto G turbo 3 and Nexus 7 2013 same with android 6 version. Also in the debug with chrome inspect I dont received any error when the app reload the debug is closed and I dont show any message or error.

**Comment by niroussel** [comment]
Same problem here. However, the crash occures only with the whitelist plugin! I need both :/

**Comment by russosalv** [comment]
I have the same problem also me , looks that after scan android run an new activity and app reboot.

**Comment by shaggy8871** [comment]
For anyone else having the same issue, the `prompt` option is mandatory for Android.

**Comment by gregor-srdic** [comment]
Omg, thanks, I was certain I have a problem with google libraries versions conflicting between different plugins, and I spent several hours trying to fix it ⭕️ 
this simple option did the trick!
