### ISSUE TITLE
Camera overlay

### ISSUE THREAD

**Issue by thomas-tran** [phonegap/phonegap-plugin-barcodescanner#35]
Hi,

I am just wondering whether this plug in can have the overlay layer on the camera. In my use case, I need to provide the custom text and a custom button when the camera open. How can I do it with this plug in.

Thanks
THomas

**Comment by jaredgreener** [comment]
+1

**Comment by rwagnon** [comment]
+1

**Comment by mrgcohen** [comment]
+1

**Comment by lasseron** [comment]
+1

**Comment by gaetansenn** [comment]
+1

**Comment by nicks258** [comment]
+1

**Comment by caroguerrero** [comment]
+1

**Comment by jcesarmobile** [comment]
Duplicate of #11
