### ISSUE TITLE
Barcodescanner creates hidden history on android

### ISSUE THREAD

**Issue by AAUBSS** [phonegap/phonegap-plugin-barcodescanner#350]
Hi,

I'm concerned that this barcodescanner creates a sqLite history database of all qrcodes previously scanned without mentioning it and without the option to disable this behaviour.

The history is saved in \com\google\zxing\client\android\history

Is there a possibility to disable this history creation?

**Comment by daserge** [comment]
Hi @AAUBSS , try [rebuilding the barcodescanner-lib-aar](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/228#issuecomment-254534990) using [preferences_history=false](https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/dd7685fef0c21aac827493e1aa01e1337912f642/barcodescanner/src/main/res/xml/preferences.xml#L67).

**Comment by daserge** [comment]
@AAUBSS did this help?
The issue can be closed if so I believe.

**Comment by AAUBSS** [comment]
Hi, sorry for missing your answer. If understand correctly, i would have to manually rebuild the lib and change it with the one that is located in in the barcodescanner plugin directory? Is there a  way to configure the history behavior instead? Is there even a reason to use a lib with enabled history for this plugin, why not disabling it by default?

**Comment by daserge** [comment]
> i would have to manually rebuild the lib and change it with the one that is located in in the barcodescanner plugin directory?

Right.

> Is there a way to configure the history behavior instead? 

Not through config.xml/plugin.xml as we are including aar which is already compiled.

> Is there even a reason to use a lib with enabled history for this plugin, why not disabling it by default?

I'm not sure - but probably because [it is enabled in ZXing library by default](https://github.com/zxing/zxing/blob/47459f4bd7ce6b883321a298df26eb5e279f4a32/android/res/xml/preferences.xml#L68).

**Comment by renanbandeira** [comment]
Hi, I think the change I made can solve the problem: https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/505

**Comment by macdonst** [comment]
@renanbandeira thanks, I've merged in your fix.

**Comment by AAUBSS** [comment]
@renanbandeira Thank you for solving this!
