### ISSUE TITLE
Barcode scanner plugin is not working in android 6+ ionic!!!!

### ISSUE THREAD

**Issue by Smohanapriya** [phonegap/phonegap-plugin-barcodescanner#353]
I am developing my ionic app using ngCordova.  I have installed camera plugin by using,
               `   cordova plugin add org.apache.cordova.camera`
Then, I have installed barcode scanner plugin by using,

`cordova plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner.git`
While running my ionic app it's asking for camera permission. I have allowed the permission also. so, I can able to capture the image.

But, by opening the barcode scanner,

```
    $cordovaBarcodeScanner.scan().then(function(imageData) {
        alert(imageData.text);
        alert("Barcode Format -> " + imageData.format);
        alert("Cancelled -> " + imageData.cancelled);
    }, function(error) {
        alert("An error happened -> " + error);
    });
```
I can able to opening scanner. I am not able to get the result. scanner is not scanning the barcode..

The same plugin is working for me for android 5+ versions.

Anyone help will be Appreciated!!!!

**Comment by daserge** [comment]
@Smohanapriya this does not reproduce for me (Acer Liquid Zest Android 6.0).
Does it work if you use Cordova API?
```javascript
cordova.plugins.barcodeScanner.scan(
            function (result) {
                navigator.notification.alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
            },
            function (error) {
                navigator.notification.alert("Scanning failed: " + error);
            },
            {
                "preferFrontCamera": true, // iOS and Android
                "showFlipCameraButton": true, // iOS and Android
                "prompt": "Place a barcode inside the scan area", // supported on Android only
                "formats": "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
                "orientation": "landscape" // Android only (portrait|landscape), default unset so it rotates with the device
            }
        );
```

**Comment by IvanDreamer** [comment]
The same happened with me on Android 6.0.0.1 OnePlus One. I did only once a result, but the rest of the time does not.
