### ISSUE TITLE
Close Button for AngularJS App

### ISSUE THREAD

**Issue by 1cm** [phonegap/phonegap-plugin-barcodescanner#355]
is it possible to add close button when the plug-in is in scan mode?

i am asking you this because in angularjs app when you press back button in order to cancel scanning, the app is going back in window.history.

**Comment by daserge** [comment]
@1cm you could try to subscribe to [backbutton event](http://cordova.apache.org/docs/en/dev/cordova/events/events.html#backbutton) in the app code and check if you are scanning at the moment.

**Comment by 1cm** [comment]
Thanks dude.

**Comment by vikas0vanvi** [comment]
and how to check if its scanning at the moment ??

**Comment by jcesarmobile** [comment]
you can create a boolean flag "isScanning", set it to true when you call scan and set it to false on the success/error callback

**Comment by vikas0vanvi** [comment]
thanks , solved !!

**Comment by vikas0vanvi** [comment]
For Lazy People

Factory -

`app.factory('backButtonOverride', function ($rootScope, $ionicPlatform) {
    var results = {};
    function _setup($scope, customBackFunction) {
        var oldSoftBack = $rootScope.$ionicGoBack;
        $rootScope.$ionicGoBack = function () {
            customBackFunction();
        };
        var deregisterSoftBack = function () {
            $rootScope.$ionicGoBack = oldSoftBack;
        };
        var deregisterHardBack = $ionicPlatform.registerBackButtonAction(
            customBackFunction, 101
        );
        $scope.$on('$destroy', function () {
            deregisterHardBack();
            deregisterSoftBack();
        });
    }
    results.setup = _setup;
    return results;
});`

Controller - 

`      var isScanning = false;
        backButtonOverride.setup($scope, function () {          
            if (isScanning == false)
            {
                $ionicHistory.goBack();
            }
            isScanning = false            
        });
 $scope.ScanBarcode = function () {
            cordova.plugins.barcodeScanner.scan(
                 function (result) {
                     isScanning = false;                 
                     if (result.cancelled) {                         
                         isScanning = true;
                     }
                 },
                 function (error) {
                     isScanning = false;
                     alert("Scanning failed: " + error);
                 },
                 {
                     preferFrontCamera: false,
                     showFlipCameraButton: false,  
                     showTorchButton: true,  
                     torchOn: false, 
                     prompt: "Place a barcode inside the scan area",  
                     resultDisplayDuration: 500,  
                     formats: "QR_CODE,DATA_MATRIX",
                     orientation: "landscape",
                     disableAnimations: true 
                 }
              );
        }
`
