### ISSUE TITLE
Example code on Win10 crashes app with hot-swappable camera hardware unplugged

### ISSUE THREAD

**Issue by robert-crowell-gdit** [phonegap/phonegap-plugin-barcodescanner#361]
### Expected Behaviour
If camera hardware is not installed, was expecting a clean error that could be caught by the calling application to display a user-friendly warning message to plug in hot-swappable camera hardware.

### Actual Behaviour
Barcode scanner uses Promise mechanism, yet throws an exception that can't be caught with javascript try/catch block surrounding example code (also error function section in example code never executes).  

Was expecting a clean error that could be caught by the calling application to display a user friendly warning message to plug in the hot-swappable camera hardware, instead receive application crash on Win 10.

60    if (!cameras || cameras.length === 0) {
61               throw new Error("No cameras found");
62           }

Attempted to catch the exception "No camera found' by wrapping try/catch around example code, yet that does not work. Not sure how to modify example code to cleanly catch this exception for user-friendly message.

### Reproduce Scenario (including but not limited to)
(see Steps to Reproduce)

#### Steps to Reproduce
On Win10, unplug webcam, run example code on project's main page..   recieve application crash with background debug message "No cameras found", that cannot be caught since Javascript Promise is used in barcode scanner plugin.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Win 10

#### Cordova CLI version and cordova platform version
    cordova --version
= 6.4.0
    cordova platforms
=
Installed platforms:
  android 6.0.0
  browser 4.1.0
  windows 4.4.3

#### Plugin version
    cordova plugin version | grep phonegap-plugin-barcodescanner
= phonegap-plugin-barcodescanner 6.0.3 "BarcodeScanner"

#### Sample Code that illustrates the problem
1. Tried Example code referenced on main project page.
2.  Then tried Example code on main page wrapped in try/catch block to cleanly catch the 'No cameras found' exception.

Like so:

try
{
cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      },
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          "preferFrontCamera" : true, // iOS and Android
          "showFlipCameraButton" : true, // iOS and Android
          "prompt" : "Place a barcode inside the scan area", // supported on Android only
          "formats" : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          "orientation" : "landscape" // Android only (portrait|landscape), default unset so it rotates with the device
      }
   );
} catch (err) {
         console.log("Exception handler!, No camera!.. do user dialog message here");
         alert("No camera found!  Please plugin the web cam and retry.");
}

#### Logs taken while reproducing problem

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/2.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception was thrown at line 62, column 13 in ms-appx://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a139e - JavaScript runtime error: No cameras found
Exception was thrown at line 538, column 13 in ms-appx://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pause'
The program '[3384] WWAHost.exe' has exited with code 3 (0x3).

**Comment by daserge** [comment]
@robert-crowell-gdit, while we are investigating the issue you should be able to handle the exception in [`WinJS.Application.onerror`](https://msdn.microsoft.com/en-us/library/windows/apps/hh974768.aspx) in the application code.

**Comment by daserge** [comment]
@robert-crowell-gdit could you try [this branch](https://github.com/daserge/phonegap-plugin-barcodescanner/tree/promise-done)?

**Comment by robert-crowell-gdit** [comment]
Nearly identical results..    I can't catch the exception, and when your ".pause" is called my program dies.

log:
'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception is about to be caught by JavaScript library code at line 57, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a139e - JavaScript runtime error: No cameras found
Exception is about to be caught by JavaScript library code at line 417, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pause'

The program '4052] WWAHost.exe' has exited with code 3 (0x3).

**Comment by daserge** [comment]
@robert-crowell-gdit , taking the line numbers into account I can assume you have taken the master branch of my fork.
Could you please retry with `git clone -b promise-done https://github.com/daserge/phonegap-plugin-barcodescanner`?

**Comment by ronsononline** [comment]
Hello guys,
tried it with the master branch, tried it with the promise-done branch and got always the same like robert, i cant catch the failure with try/catch if the camera doesnt exists. It brings up an error message like "Something went wrong with the Android Camera.." and after that message if u click it away it jumps back and in the result object, cancelled is true

**Comment by daserge** [comment]
@ronsononline this issue is about Windows platform - please create a separate one for Android with details.

**Comment by robert-crowell-gdit** [comment]
1. Yes, you were correct. I had the wrong version. I am new to all of this and did not know about your special git command.

a. cordova plugin ls
          phonegap-plugin-barcodescanner 5.0.0 "BarcodeScanner"

b. cordova plugin remove phonegap-plugin-barcodescanner

c. git clone -b promise-done https://github.com/daserge/phonegap-plugin-barcodescanner

(this made a new folder in my project, but didn't add it, so I added it manually like the next command)

d. cordova plugin add [app path]\phonegap-plugin-barcodescanner

e. cordova plugin ls
        phonegap-plugin-barcodescanner 6.0.3 "BarcodeScanner"

f. cordova build


2. However, I STILL get the same result, only with different line numbers as you pointed out previously and the app STILL crashes.   Your exception is not bubbling up to the calling code at all.  Perhaps a different method should be added to the framework like:     .canScan()   that checks hardware avaliablility, and .scan()  for the actual scanning.  Lumping them together doesn't seem to be working out so well.

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception is about to be caught by JavaScript library code at line 62, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a139e - JavaScript runtime error: No cameras found
Exception is about to be caught by JavaScript library code at line 538, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pause'

The program '[5648] WWAHost.exe' has exited with code 3 (0x3).

**Comment by robert-crowell-gdit** [comment]
Is there a way I could call "findCamera()" directly myself, before I call .scan() ?

**Comment by daserge** [comment]
@robert-crowell-gdit thanks for the update!
Could you please re-try the branch with the fix?

**Comment by robert-crowell-gdit** [comment]
YOU GOT IT!!   That did it!    Here's the end result.


'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception is about to be caught by JavaScript library code at line 62, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a139e - JavaScript runtime error: No cameras found
Exception was thrown at line 553, column 21 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a139e - JavaScript runtime error: NotFoundError


And I got the output message from the error section and it worked awesome!

console-via-logger.js (173,15)
NotFoundError
console-via-logger.js (173,15)
   {
      [functions]: ,
      __proto__: { },
      ABORT_ERR: 20,
      code: 8,
      DATA_CLONE_ERR: 25,
      DOMSTRING_SIZE_ERR: 2,
      HIERARCHY_REQUEST_ERR: 3,
      INDEX_SIZE_ERR: 1,
      INUSE_ATTRIBUTE_ERR: 10,
      INVALID_ACCESS_ERR: 15,
      INVALID_CHARACTER_ERR: 5,
      INVALID_MODIFICATION_ERR: 13,
      INVALID_NODE_TYPE_ERR: 24,
      INVALID_STATE_ERR: 11,
      message: "NotFoundError",
      name: "NotFoundError",
      NAMESPACE_ERR: 14,
      NETWORK_ERR: 19,
      NO_DATA_ALLOWED_ERR: 6,
      NO_MODIFICATION_ALLOWED_ERR: 7,
      NOT_FOUND_ERR: 8,
      NOT_SUPPORTED_ERR: 9,
      PARSE_ERR: 81,
      QUOTA_EXCEEDED_ERR: 22,
      SECURITY_ERR: 18,
      SERIALIZE_ERR: 82,
      SYNTAX_ERR: 12,
      TIMEOUT_ERR: 23,
      TYPE_MISMATCH_ERR: 17,
      URL_MISMATCH_ERR: 21,
      VALIDATION_ERR: 16,
      WRONG_DOCUMENT_ERR: 4
   }

GDITLOG :  barcode scanning error!! {"originatedFromHandler":true,"asyncOpType":"Windows.Foundation.IAsyncOperation`1<Windows.Devices.Enumeration.DeviceInformationCollection>","asyncOpSource":{},"asyncOpCausalityId":124}
console-via-logger.js (173,15)

**Comment by daserge** [comment]
Great, thanks @robert-crowell-gdit !
Will merge it soon then.

**Comment by robert-crowell-gdit** [comment]
Thank you!  Great job, Sir!

**Comment by robert-crowell-gdit** [comment]
I can make a seperate submission for my next error, but it's using this branch we have already discussed..

git clone -b promise-done https://github.com/daserge/phonegap-plugin-barcodescanner

in Win10, I'm getting a "Class not registered" error when trying to use the webcamera, can you tell me what it means?

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception was thrown at line 444, column 17 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x80040154 - JavaScript runtime error: Class not registered
Exception was thrown at line 553, column 21 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a139e - JavaScript runtime error: NotFoundError

It looks like it's referencing this section:

function startPreview() {
            return findCamera()
            .then(function (id) {
                var captureSettings = new Windows.Media.Capture.MediaCaptureInitializationSettings();

How can I be missing "Windows.Media.Capture.MediaCaptureInitializationSettings" on Windows 10?  

Any advice?

**Comment by daserge** [comment]
@robert-crowell-gdit which version of cordova-windows are you using? (What is the output of `cordova platforms`?)
Can you try using master version? (`cordova platform rm windows && cordova platform add https://github.com/apache/cordova-windows`)
Which device is failing (and which architecture is it)?
What is your Visual Studio version?

**Comment by daserge** [comment]
Could you please also create a separate issue for it?

**Comment by robert-crowell-gdit** [comment]
Will create a seperate issue.. and will go back to the master version for this issue. Thank you.

**Comment by daserge** [comment]
@robert-crowell-gdit also make sure you are specifying an Architecture when you build for Windows 10 - i.e. x86 or x64 for desktop or ARM for phone.

**Comment by robert-crowell-gdit** [comment]
I have specified the Architecture..  will include on the new issue.
