### ISSUE TITLE
Phone Gap Build Android Compile Error 

### ISSUE THREAD

**Issue by Hallidayo** [phonegap/phonegap-plugin-barcodescanner#362]
Hi,

When im submiting my app to the PhoneGap Build I am unable to compile for Android (Windows & iPhone are fine). Looking at the error log I am seeing the following:

compile:
    [javac] Compiling 10 source files to /project/bin/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /project/src/com/phonegap/plugins/barcodescanner/BarcodeScanner.java:26: error: package com.google.zxing.client.android does not exist
    [javac] import com.google.zxing.client.android.Intents;
    [javac]                                       ^
    [javac] /project/src/com/phonegap/plugins/barcodescanner/BarcodeScanner.java:173: error: package Intents does not exist
    [javac]                         intentScan.putExtra(Intents.Scan.CAMERA_ID, obj.optBoolean(PREFER_FRONTCAMERA, false) ? 1 : 0);
    [javac]                                                    ^
    [javac] /project/src/com/phonegap/plugins/barcodescanner/BarcodeScanner.java:174: error: package Intents does not exist
    [javac]                         intentScan.putExtra(Intents.Scan.SHOW_FLIP_CAMERA_BUTTON, obj.optBoolean(SHOW_FLIP_CAMERA_BUTTON, false));
    [javac]                                                    ^
    [javac] /project/src/com/phonegap/plugins/barcodescanner/BarcodeScanner.java:176: error: package Intents does not exist
    [javac]                             intentScan.putExtra(Intents.Scan.FORMATS, obj.optString(FORMATS));
    [javac]                                                        ^
    [javac] /project/src/com/phonegap/plugins/barcodescanner/BarcodeScanner.java:179: error: package Intents does not exist
    [javac]                             intentScan.putExtra(Intents.Scan.PROMPT_MESSAGE, obj.optString(PROMPT));
    [javac]                                                        ^
    [javac] /project/src/com/phonegap/plugins/barcodescanner/BarcodeScanner.java:182: error: package Intents does not exist
    [javac]                             intentScan.putExtra(Intents.Scan.ORIENTATION_LOCK, obj.optString(ORIENTATION));
    [javac]                                                        ^
    [javac] 6 errors
    [javac] 3 warnings

Does anyone know how I can this fixed?

Im using Phoneghap build 3.5.0 and Android Build Tool is set to Gradle.

Thanks

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
