### ISSUE TITLE
UPC_A codes now scans with extra 0 at the start

### ISSUE THREAD

**Issue by jrobichaud** [phonegap/phonegap-plugin-barcodescanner#364]
### Expected Behaviour
UPC_A should return 12 digits

### Actual Behaviour
UPC_A returns 13 digits

### Reproduce Scenario (including but not limited to)
Scan [this code](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/586763/codedb42a5efb3392c5acb9892435df49371.pdf)

#### Steps to Reproduce
1. Scan bar code with commit: https://github.com/phonegap/phonegap-plugin-barcodescanner/commit/68e7c05dd1a008deca8e4fc8a47b3c0169bcc01e
2. Scan bar code with commit: https://github.com/phonegap/phonegap-plugin-barcodescanner/commit/df54d51c029b3a35640ed32ae50325421c48db94

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Any iOS
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Any iOS

#### Cordova CLI version and cordova platform version

    cordova --version: 6.4.0
    cordova platforms:
     ios 4.2.1

#### Plugin version

It was introduced by this pull request: https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/338

**Comment by pbergner** [comment]
@macdonst was this issue resolved?

**Comment by macdonst** [comment]
@pbergner nope, not yet. I was able to reproduce it but did not get the chance to fix it.

**Comment by pbergner** [comment]
@macdonst oops, my fault i thought it was closed. I guess its still early (not really). I just ran into this issue as well.

**Comment by macdonst** [comment]
@pbergner yeah, I'm trying to give this plugin some more love as time allows.

**Comment by macdonst** [comment]
@pbergner @jrobichaud  please install the latest from master and confirm it fixes your issue and I'll release a new version of the barcode scanner plugin once I hear back.

**Comment by jrobichaud** [comment]
@pbergner can you please do it? I am not set up to test this.

**Comment by pbergner** [comment]
@macdonst fixed for me! very similar to the workaround I had just put in place. Thanks!

**Comment by macdonst** [comment]
@pbergner yeah, I put it in the JS side for now and will retest when I update the ZXing library. I will publish 6.0.8 today or tomorrow.
