### ISSUE TITLE
android,The image is distorted in the scan area

### ISSUE THREAD

**Issue by xgzl87** [phonegap/phonegap-plugin-barcodescanner#365]
android,The image is distorted in the scan area

**Comment by daserge** [comment]
@xgzl87 please add some details - which is device' Android version, what version of the plugin are you using?
Also please post the code you are using for scanning (especially call options).

**Comment by frateaubets** [comment]
Hi @xgzl87 @daserge did you solve this issue?
Actually I'm working on a simple app (ionic-angularjs-cordova). The reader works fine but the viewer is distorted.
Testing on Android 6.0 (Huawei P8 Lite (EMUI 4.0))
Tested through the ionicview w

That's the function.

$scope.llegirCodi = function () {
	$cordovaBarcodeScanner.scan()
		.then(function(codi){
		console.log(codi + 'read');    
	},
	function(err){
		console.log(err + 'error');
	})
}

System info:
Cordova CLI: 5.2.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Windows 7
Node: v0.12.7

Thanks!

**Comment by daserge** [comment]
@frateaubets not yet, but I would [look here](https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/master/barcodescanner/src/main/res/layout-ldpi/capture.xml#L45).

**Comment by xgzl87** [comment]
@frateaubets not yet！

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
