### ISSUE TITLE
How can I change the scan window ?

### ISSUE THREAD

**Issue by rafaelescrich** [phonegap/phonegap-plugin-barcodescanner#369]
This is my funtion that calls the scan method:

              $scope.scan = function() {
			$ionicPlatform.ready(function () {
				$cordovaBarcodeScanner.scan()
					.then(function(barcodeData) {
        		$scope.setBarcode(barcodeData.text);
      		}, function(error) {
        		console.error("Error reading barcode", error);
      		},
      		{
          	"preferFrontCamera" : false, // default false
          	"showFlipCameraButton" : false, // default false
          	"prompt" : "Posicione o código de barra da área de leitura",
          	"orientation" : "landscape"
        	}
      	);
	  	});
 		};

But this options are been overriding and I can't find the place that I set the windows size of the scan area.

**Comment by rafaelescrich** [comment]
Yes, thank you for pointing out.

**Comment by daserge** [comment]
OK, thanks! I will close this one then.
