### ISSUE TITLE
tmpqrcode.jpeg does not get updated

### ISSUE THREAD

**Issue by RaulGarafulic** [phonegap/phonegap-plugin-barcodescanner#372]
**Expected Behaviour**
Using the `encode` function with dynamic data, I expect it to update the image where QRCode is.

### Actual Behaviour
When I encode a string, works perfectly, but when I try to insert another text, the image holds still.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
I'm developing in Ionic 2, Phonegap 6.3.3

#### Cordova CLI version and cordova platform version

    cordova --version 6.3.1
    cordova platforms  android 5.2.2
                                     ios 4.2.1

#### Sample Code that illustrates the problem
passing a string with success:

```
ionViewDidEnter () {
  this.someText = this.navParams.get ('text');
  this.encodeSomeText (this.someText);
}

encodeSomeText (someText) {
  this._zone.run (() => {
    let barcode = BarcodeScanner;
    barcode.encode (barcode.Encode.TEXT_TYPE, someText)
    .then (success => {
      this.imageUrl = success.file
      console.log (success.file); 
  // Here I get a path, which I can't find: 
  // /private/var/mobile/Containers/Data/Application/CE83F727-F920-4C0F-8D41-EFA20A86C39F/tmp/tmpqrcode.jpeg
    }), (error) => {
      alert ('err: ' + error);
    }
  }); 
}

```
The problem here is that, when I try to re-call a function with another value of someText, the tmpqrcode.jpeg does not update on my view and I get the first QR code I got, but it never changes again. I get the encodeSomeText function with success and I get the same path as the first one. 

I thought it would be possible that the image was the one that wasn't updating, but I test that wrong. It is that the tmpqrcode.jpeg is not getting updated in that path.

Please, if you could guide me through a solution for this, would mean the world to me.

Thanks a lot.

By the way, I'm using an iPhone 5s with iOS 10.1. I didn't try this on an Android, I hope it works there.

**Comment by RaulGarafulic** [comment]
Please, someone answer this. It's killing me! I can't make it work! 😫😫😫

**Comment by alsorokin** [comment]
hey @RaulGarafulic can you check if my fix for your issue is working? You can find it here:
https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/386
https://github.com/alsorokin/phonegap-plugin-barcodescanner/tree/ios-encode-update

**Comment by vladimir-kotikov** [comment]
The fix has landed into master branch, closing this.
