### ISSUE TITLE
Plugin not found, or is not a CDVPlugin

### ISSUE THREAD

**Issue by Bazzaccosrl** [phonegap/phonegap-plugin-barcodescanner#376]
Hi,
  when I try to use the plugin on iOS, it return this error: "ERROR: Plugin 'BarcodeScannerPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.".
I've try to reinstall the plugin, but it gives always the same error.

On Android it works perfectly.

Cordova version: 6.4.0
iOS platform's version: 4.3.0
Plugin version: 6.0.3

Thanks

**Comment by jcesarmobile** [comment]
that happens when the plugin is not installed correctly. 
Try removing and re-adding the plugin and if it doesn't work try removing and re-adding cordova-ios platform
Closing because it's not really a problem with the plugin, it's a problem on Cordova itself

**Comment by Bazzaccosrl** [comment]
Nope, I've changed <feature name="BarcodeScanner"> to <feature name="BarcodeScannerPlugin"> in config.xml, and it works... (Plugin install bug?)

**Comment by jcesarmobile** [comment]
No, `BarcodeScannerPlugin` is not used anywhere in the code. 
Can you check your barcodescanner.js file and see if cordova.exec is calling BarcodeScanner or BarcodeScannerPlugin?
https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/www/barcodescanner.js#L118

**Comment by Bazzaccosrl** [comment]
It calls BarcodeScanner...

**Comment by jcesarmobile** [comment]
Then your fix makes no sense, what the feature tag does is to map the javascript call to the native class, if you javascript is calling `BarcodeScanner` but your feature tag has `BarcodeScannerPlugin` then is when you should get a 

> "ERROR: Plugin 'BarcodeScanner' not found, or is not a CDVPlugin.

That's what I get if I change `BarcodeScanner` to `BarcodeScannerPlugin` in the config.xml

Can you search for `BarcodeScannerPlugin` in your project?

**Comment by Bazzaccosrl** [comment]
Wait, wait. My mistake. BarcodeScannerPlugin has nothing to do... I thought it was what, but simply the system doesn't see it anymore and it use another plugin that I use on Android (Honeywell Barcode Scanner). I've removed this and changed BarcodeScannerPlugin to BarcodeScanner (It doesn't work otherwise, obviously) and it works perfectly.

Sorry for making you waste time, really :(
