### ISSUE TITLE
$cordovaBarcodeScanner camera not show when view by iOS 10+

### ISSUE THREAD

**Issue by tungcntt619** [phonegap/phonegap-plugin-barcodescanner#377]
when i click the scan button, nothing will happen, i sleep the ipad, and turn on again, then the camera will appear.

**Comment by samscudder** [comment]
Have the same problem, on an iPhone 5s with 10.1.1. The scanner windows doesn't show up until I click the home key and click on the app icon again. If I tap the scan button twice, I get a "Scan is already in progress" popup, even though the scan windows isn't showing.

**Comment by xavierfernandes** [comment]
his is due to the new content security introduced in iOS 10 to prevent XSS.

[https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/382#issuecomment-271886739](url)

**Comment by jcesarmobile** [comment]
Duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/382

**Comment by amoizesmailacn** [comment]
Hi, do we have solution for this?

**Comment by jcesarmobile** [comment]
@amoizesmailacn yes, you have to add `gap:` to your CSP

**Comment by amoizesmailacn** [comment]
@jcesarmobile  Do u have a steps on how to do it?

**Comment by jcesarmobile** [comment]
@amoizesmailacn look for your `Content-Security-Policy` meta tag in your `index.html` and add `gap:` in the `default-src`.

**Comment by amoizesmailacn** [comment]
@jcesarmobile Oh the first tap of the scan button, nothing happen and when I tap again the button the error message is "Scanning failed: Scan is already in progress"
