### ISSUE TITLE
Scan not returning to application

### ISSUE THREAD

**Issue by noobiwan** [phonegap/phonegap-plugin-barcodescanner#38]
Sometimes when scanning a barcode, it doesn't go back.  After the bip, the capture screen remains open and I have to scan the barcode again so it will finally go back to my application. It then returns {"text: "", "format": "", "cancelled": true} 

Any idea of why this is happening? Any suggestions on how to debug this?

Android 5.0.2 on HTC One

**Comment by TruyenNV** [comment]
CordovaInterfaceImpl: Got an activity result, but no plugin was registered to receive it.

**Comment by fromvega** [comment]
Any clue why? Suggestions to solve it?

**Comment by gfr** [comment]
Same here on Android 4.2.2

**Comment by robertfoobar** [comment]
Same here. Android 5.0.1 HTC One M8.

**Comment by Deminetix** [comment]
We're seeing this on all Samsung devices in general. Happens more often than not so plugin is currently unusable.

**Comment by adexerivera** [comment]
Hi everybody,

I've the same problem, any solution?

**Comment by voidmachine** [comment]
I also face this Issue with the latest version (4.1.0), cordova 5.4.1 and ionic 1.7.10 and ngcordova

**Comment by voidmachine** [comment]
I figured out that this was an issue with the Ionic/AngularJS-Layer. The trick is to use ```on-touch``` instead of ```ng-click``` for the button action.

    <button on-touch="click()">
       Scan Barcode
    </button>

See http://stackoverflow.com/questions/32336683/cordova-barcode-scanner-opens-twice-in-android.

**Comment by Tazaf** [comment]
@deckerj : That completely did the trick !
Many thanks !

**Comment by koga73** [comment]
@deckerj Yes that seems to solve the problem!

**Comment by sarangan12** [comment]
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it

**Comment by zhang037830** [comment]
@deckerj  Thanks for sharing
                 Has been resolved

**Comment by daniefvh** [comment]
I'm getting this on ionic 2 atm. Only when dismissing the barcode scanner with the back button. Am I missing a trick?

**Comment by zhang037830** [comment]
I use it for ionic. You can try using the touch.

**Comment by MUmer1124** [comment]
Hi, I'm facing this issue only works well if I close scanner view with back button otherwise it show blank overlay. I missing any trick? Thanks
