### ISSUE TITLE
Using IOS 10.1, barcode scanner not showing

### ISSUE THREAD

**Issue by fargobee** [phonegap/phonegap-plugin-barcodescanner#380]
Using IOS 10.1, barcode scanner not showing and produce this issue :

/Users/macbookpro/Documents/myapp/platforms/ios/myapp/Plugins/phonegap-plugin-barcodescanner/CDVBarcodeScanner.mm:265:17: Method definition for 'captureOutput:didOutputSampleBuffer:fromConnection:' not found

**Comment by jlowe234** [comment]
What version of the plugin are you using?

**Comment by andersborgabiro** [comment]
In my case the app crashes when trying to scan a code on iOS. Possibly the same error. I haven't checked yet. Works fine on Android.

**Comment by jcesarmobile** [comment]
No answer after 3 months, closing

**Comment by irperera** [comment]
any update on this
