### ISSUE TITLE
Flipping orientation on Android crashes app

### ISSUE THREAD

**Issue by alexbuijs** [phonegap/phonegap-plugin-barcodescanner#383]
### Expected Behaviour
Flipping the orientation of the device rotates the scan preview window

### Actual Behaviour
Flipping the orientation crashes the app

#### Steps to Reproduce
Invoke scan window and rotate the device

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.4

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motorola XT1039

#### Cordova CLI version and cordova platform version
cordova 6.4.0
cordova-android 6.1.0

#### Plugin version
phonegap-plugin-barcodescanner 6.0.4

#### Logs taken while reproducing problem
```
W/dalvikvm( 4242): threadid=39: thread exiting with uncaught exception (group=0x4167bd40)
E/AndroidRuntime( 4242): FATAL EXCEPTION: Thread-5660
E/AndroidRuntime( 4242): Process: app.id, PID: 4242
E/AndroidRuntime( 4242): java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
E/AndroidRuntime( 4242): 	at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:50)
E/AndroidRuntime( 4242): 	at com.google.zxing.client.android.camera.CameraManager.buildLuminanceSource(CameraManager.java:372)
E/AndroidRuntime( 4242): 	at com.google.zxing.client.android.DecodeHandler.decode(DecodeHandler.java:92)
E/AndroidRuntime( 4242): 	at com.google.zxing.client.android.DecodeHandler.handleMessage(DecodeHandler.java:60)
E/AndroidRuntime( 4242): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4242): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4242): 	at com.google.zxing.client.android.DecodeThread.run(DecodeThread.java:110)
W/ActivityManager( 1020):   Force finishing activity app.id/com.google.zxing.client.android.CaptureActivity
```

**Comment by kozuch** [comment]
I have the same problem. Running on Samsung S5 (Android 5.0), cordova-android 5.1.1, cordova-cli 6.1.1. Plugin version: phonegap-plugin-barcodescanner 6.0.4 "BarcodeScanner".

Here is my log:

`
E/AndroidRuntime: FATAL EXCEPTION: Thread-192023
                                                                      Process: cz.csdevelopment.nDemo, PID: 6322
                                                                      java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
                                                                          at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:50)
                                                                          at com.google.zxing.client.android.camera.CameraManager.buildLuminanceSource(CameraManager.java:372)
                                                                          at com.google.zxing.client.android.DecodeHandler.decode(DecodeHandler.java:92)
                                                                          at com.google.zxing.client.android.DecodeHandler.handleMessage(DecodeHandler.java:60)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at com.google.zxing.client.android.DecodeThread.run(DecodeThread.java:110)
`

**Comment by EddyVerbruggen** [comment]
Could you please update the plugin from github (which gives you 6.0.5-dev currently) and see if the crash still occurs?

**Comment by clearride** [comment]
got the same on samsung Crop rectangle does not fit within image data. at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:50) at

**Comment by clearride** [comment]
{
          "showFlipCameraButton" : true, // iOS and Android
          "showTorchButton" : true,
	     "orientation" : "portrait",
	    "prompt" : "FOCUS CAMERA ON PRODUCT BARCODE"
        }

pass this to scan until a fix is available & also to customize the scanner screen a bit with options

**Comment by EddyVerbruggen** [comment]
@clearride please see my previous comment - on which version did you see this?

**Comment by clearride** [comment]
@EddyVerbruggen I am not able to get 6..0.5-dev  , my current plugin ver is 6.0.4, but I'm not held up here as my need is for a portrait view mode only.

**Comment by EddyVerbruggen** [comment]
@clearride I get that this isn't your problem, but it would help everybody if anyone could test the changes made for this issue in 6.0.5-dev. It's just a matter of specifying `https://github.com/phonegap/phonegap-plugin-barcodescanner` as the plugin source instead of the npm package name.

**Comment by clearride** [comment]
@EddyVerbruggen got it, looks like it works on my setup & test with samsung galary(android 4.1.1) & Xiomi (android 6)

**Comment by EddyVerbruggen** [comment]
@clearride That's great, thanks for the test! That reassures me we can push this to npm soon 👍

**Comment by EddyVerbruggen** [comment]
6.0.5 is on npm.
