### ISSUE TITLE
Always on camera

### ISSUE THREAD

**Issue by stanzahk** [phonegap/phonegap-plugin-barcodescanner#384]
Hi,
is it possible to have the camera always on when scanning barcodes, and in the callback make some http request for example?

The camera gets released every time a barcode is scanned (in my code).

`var config = {
              "preferFrontCamera" : false,
              "showFlipCameraButton" : false,
              "prompt" : "Place a barcode inside the scan area",
              "orientation" : "landscape"
            };
            cordova.plugins.barcodeScanner.scan(mySuccess,myError,config);
`

Versions:
cordova version: 6.4.0
cordova platforms: android 6.0.0
phonegap-plugin-barcodescanner 6.0.4 "BarcodeScanner"

Thanks

Daniele

**Comment by carol-braileanu** [comment]
This has been requested already: #122

**Comment by jcesarmobile** [comment]
Closing as duplicate
