### ISSUE TITLE
Flashlight default value

### ISSUE THREAD

**Issue by aiuliansoft** [phonegap/phonegap-plugin-barcodescanner#385]
### Expected Behaviour
In case you have hundreds of bar-codes to scan, it's a little bit time consuming to turn the flash on each time. A configuration option like: "TorchModeOn": true, would be great.
### Actual Behaviour
I've noticed that in the version 6.0.4 was added "showTorchButton": true, feature that is perfect, but sometimes not sufficient.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4+
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
-
#### Cordova CLI version and cordova platform version
6.1.1

#### Plugin version
6.0.5-dev

**Comment by EddyVerbruggen** [comment]
With 6.0.5 you can now pass in `torchOn: true` to get this behavior on Android.

**Comment by aiuliansoft** [comment]
It works great!! Thanks!
