### ISSUE TITLE
Switch camera and torch button

### ISSUE THREAD

**Issue by JeremyKeusters** [phonegap/phonegap-plugin-barcodescanner#387]
Hello everyone,

I'm using this plugin in an Ionic project (it's great, thanks!) but I have an issue. When I try to show the 'switch camera' and 'torch' button, it doesn't work. I have included some code of my controller where I specified these options.

### Expected Behaviour
See a button for switching camera and for the flashlight

### Actual Behaviour
There's no button for switching the camera and for the flashlight

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10

#### Cordova CLI version and cordova platform version

cordova --version: 
   6.2.0
cordova platforms: 
   android 5.1.1
   ios 4.1.1

#### Plugin version

cordova plugin version | grep phonegap-plugin-barcodescanner:
   phonegap-plugin-barcodescanner 6.0.5-dev "BarcodeScanner"

#### Sample Code that illustrates the problem

```
    $scope.scanBarcode = function() {
        $cordovaBarcodeScanner.scan().then(function(imageData) {
            
            $scope.scanned = imageData.text;
            console.log("Barcode Format -> " + imageData.format);
            console.log("Cancelled -> " + imageData.cancelled);
        }, function(error) {
            console.log("An error happened -> " + error);
        },
        {
          "showFlipCameraButton" : true, // iOS and Android
          "showTorchButton" : true // iOS and Android
        });
    };
```

![img_1146](https://cloud.githubusercontent.com/assets/4648081/21195892/fda77398-c235-11e6-97de-0b556930e168.PNG)

**Comment by EddyVerbruggen** [comment]
Looks like you're passing the options to the Promise result rather than the plugin.. look carefully at the empty `scan()` call.

**Comment by JeremyKeusters** [comment]
@EddyVerbruggen Thank you for your answer! Indeed a silly error on my side.. Works like a charm now! :)
