### ISSUE TITLE
Embedded view instead of pop-up

### ISSUE THREAD

**Issue by JeremyKeusters** [phonegap/phonegap-plugin-barcodescanner#388]
Hello all,

I have a little question. Currently, the scanner opens as a pop-up that takes some time to load. However, I would actually like to 'embed' the scanner into an HTML page so that it doesn't 'pops-out'.

Is this possible? I saw an issue about this from +- a year ago but I'm not sure if it's still not possible.

Thanks in advance!

-Jérémy

**Comment by jcesarmobile** [comment]
It's not possible with this plugin
There is another issue open about it, so I'm closing yours as duplicate
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/223
