### ISSUE TITLE
Windows 10 (Surface Pro 3) Throws "WinRTError: Access Denied" when trying to scan()

### ISSUE THREAD

**Issue by joshstrange** [phonegap/phonegap-plugin-barcodescanner#389]
### Expected Behaviour
Camera comes up and you can scan barcode
### Actual Behaviour
Error is thrown "WinRTError: Access Denied"
### Reproduce Scenario (including but not limited to)
Call ````scan()````
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows 10 (Surface Pro 3)
#### Cordova CLI version and cordova platform version

    cordova --version
````
6.4.0
````

    cordova platforms
````
Installed platforms:
  android 6.0.0
  ios 4.3.1
  windows 4.4.3
````
#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner
````
phonegap-plugin-barcodescanner 6.0.4 "BarcodeScanner"
````

#### Logs taken while reproducing problem
````
Exception was thrown at line 565, column 21 in ms-appx-web://XXXXX.XXXXXX.XXXXX/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a139e - JavaScript runtime error: NotFoundError
````

**Comment by daserge** [comment]
@joshstrange could you check if it reproduces with `6.0.5` (latest published)?

**Comment by joshstrange** [comment]
@daserge I will try that soon but I was able to get it working but putting the following in my config.xml:


````
 <config-file target="package.appxmanifest" parent="/Package/Capabilities">
      <DeviceCapability Name="webcam"/>
    </config-file>
````

It's odd because that's the same thing in your plugin.xml and should have gotten picked up. I'm going to close this since I just got it working but I will update soon.

**Comment by daserge** [comment]
Ah, thanks, 
then it's https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/360 - fixed in cordova-windows platform master but not released yet.
