### ISSUE TITLE
Have iOS ignore 3rd .scan argument, debug why options scan_width, scan_height aren't used in Android.

### ISSUE THREAD

**Issue by cepm-nate** [phonegap/phonegap-plugin-barcodescanner#39]
For iOS, I don't include the 3rd argument as it makes the iOS app crash. :-(

On Android, the call looks like this:
```
cordova.plugins.barcodeScanner.scan( 
	function(a){console.log(a)}, 
	function(a){console.warn(a)}, 
	{
		SCAN_HEIGHT	: 200, 
		SCAN_WIDTH	: 1200		// If this is over the device width, it is lowered automaically.
	}
);
```
This did work a few months ago, but I haven't been testing the scanning function each day, so do not know exactly when it switched back to the default size.

I dropped a breakpoint in cordova.js line 943, and the config arguments are getting sent to the plugin.

I've tried using plugin-barcodescanner versions 3.1.2, 3.1.1, 3.1.0, 3.0.1, but they all seem to ignore the options. The scanning window stays the same default size.

I've scanned through the pieces of code in the plugin that refer to the arguments being passed, and the only area that seems to be affecting this is in https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/4

Pull request #4 is all about screen rotation on android (very useful). Perhaps there is a conflict?

Anyone else run into this?

I'm not that familiar with the coding in src/android/LibraryProject/src/com/google/zxing/client/android/camera/CameraManager.java, but it looks like the .java file is expecting requestedFramingRectWidth / Height to be set somehow, or the setManualFramingRect() function to be called (looks like circular programming to me). Would someone mind looking into this and seeing if this function is called when SCAN_HEIGHT and SCAN_WIDTH are supplied?

**Comment by sarangan12** [comment]
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it

**Comment by zhoffice** [comment]
This problem still exist in version 6.0.7
