### ISSUE TITLE
Front facing camera won't read barcodes

### ISSUE THREAD

**Issue by abouttimeruss** [phonegap/phonegap-plugin-barcodescanner#391]
### Expected Behaviour
In front facing mode, it should read barcodes just the same as rear facing

### Actual Behaviour
It won't read them at all. It shows the camera just fine, but won't read the barcode no matter how close/far you move the barcode to the camera.

### Reproduce Scenario (including but not limited to)
Read a barcode in front camera mode.

#### Steps to Reproduce
Launch app with latest plugin; scan a barcode. Rear facing mode works great. Flip to front facing and it won't scan at all. Camera shows up and looks good and looks like it should work. But it won't read the same barcode that worked in rear camera mode.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.0.2
Android 6.x+

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 6+
Samsung, Nexus tablets

#### Cordova CLI version and cordova platform version
6.3.1
    cordova --version 
    cordova platforms

#### Plugin version
phonegap-plugin-barcodescanner 6.0.4 "BarcodeScanner"
    cordova plugin version | grep phonegap-plugin-barcodescanner

#### Sample Code that illustrates the problem
Sample code should be sufficient. Same code used within ionic framework app.

#### Logs taken while reproducing problem
No errors. Just won't read in front mode.

**Comment by Richard1974** [comment]
I can confirm this.

Is this happening because the front camera is mirrored?

**Comment by Richard1974** [comment]
Upon further testing, I have found that it does work after all.  It's just a little finicky, perhaps because of my Doogie brand Android phone.

Also, the front camera on my old iPhone 4 works fine, though it works better further away from the camera.

**Comment by pegros** [comment]
I have the same issue both on my iPhone 6 and my old iPad 2.
In both cases, the front camera is activated but no scan triggered (neither success nor failure handlers are called), even when trying many distances between camera and code.
From what I read elsewhere, it seems to be linked to front camera lacking auto-focus.
When using the same App with the rear camera, I do scan Aztek or PDF417 codes perfectly.
Any possible solution to this issue ?

**Comment by Abhishek134** [comment]
I'm also facing the same,
Can anyone able to solve it ?

**Comment by pegros** [comment]
From what I saw, I think the reason must be that there is a mirror effect when taking a photo with the front facing camera. Just try taking a picture of yourself with a written sign in the background and you will see it clearly. If the codes / decoding is sensitive to this transformation, it must fail.

**Comment by Abhishek134** [comment]
i'm able to scan from front camera but it takes too much time to scan.

**Comment by pegros** [comment]
I shall check again, but scanning PDF417 or Aztek codes did not on my iPhone.

**Comment by Abhishek134** [comment]
I'm scanning the qrcode for my ionic app.
