### ISSUE TITLE
Camera cannot focus due to wrong aspect ratio since plugin 6.0.5

### ISSUE THREAD

**Issue by Style117** [phonegap/phonegap-plugin-barcodescanner#392]
### Expected Behaviour
This Screenshot shows the Plugin on the same smartphone in version 4.1.0. Scanning of barcodes and QR-codes works fine.

![plugin_4_1_0](https://cloud.githubusercontent.com/assets/24733072/21454155/4dffdc86-c916-11e6-819b-df9d145fba60.png)

### Actual Behaviour
This Screenshot shows the Plugin in version 6.0.5. It looks like the plugin calculates the wrong screen resolution. The camera does not focus and the aspect ratio is wrong (drawn-out). It is impossible to scan Barcodes like this. QR-Codes are scanned very fast.

![plugin_6_0_5](https://cloud.githubusercontent.com/assets/24733072/21454157/54c3f606-c916-11e6-93ee-ce1ae6cba0f2.png)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy Grand Prime (SM-G531F)

#### Cordova CLI version and cordova platform version
 6.4.0

#### Plugin version
 phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner"

**Comment by gczudowski** [comment]
I see the same issue on the same device (Samsung grand prime). Plugin v6.0.4. The phone keeps trying to focus, but the image is blurred all the time when you put the barcode inside the square. It works fine when you increase the distance between the barcode and the phone.
The grand prime is not the only phone with the issue.

Any idea what might be the cause of it?

**Comment by gczudowski** [comment]
A way out of this situation would be to remove the grey area and only show the red line so that the users don't think they need to put the phone very close for the app to scan the code properly.

Could we have the option in the config to disable the greyed out area?

**Comment by jstoup111** [comment]
Any status on this?

**Comment by wcalderw** [comment]
We are seeing the same problem on different phone depending on the quality of the camera. 
However if we use the xing bar code scanner (i'm assuming that the plugin also uses the xing library) on the same phone with the same bar code it scans fine. So our conclusion is that this is a problem with the barcode plugin and not the hardware/phone.
https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en

**Comment by briebug** [comment]
I am seeing the same issue using my Samsung Galaxy Tab 4 with Cordova CLI 6.4.0 and phonegap-plugin-barcodescanner 6.0.5.  The plugin is unable to focus and scan any barcodes.  I've attempted multiple different lighting scenarios as well as distance from the barcode.

I have downloaded ZXing Test and Barcode Scanner from the Play Store and both work fine.  I am able to consistently scan barcodes.

I downgraded phonegap-plugin-barcodescanner to 6.0.2 and I am now able to scan barcodes again.  It looks like there were several big changes to the android source that could impact the performance.

For now, I am using `ionic plugin add phonegap-plugin-barcodescanner@6.0.2` as a workaround.  I deleted my platforms directory, add the plugin and then add my platforms:

```
rm -fr platforms
ionic plugin add phonegap-plugin-barcodescanner@6.0.2
ionic platform add android
ionic platform add ios

ionic run android --device
```

**Comment by Style117** [comment]
I do not see any difference on the Samsung Grand Prime with plugin version 6.0.2.

**Comment by gczudowski** [comment]
@Style117  I agree. the problem is present on 6.0.2 as well. Anyone found a fix that could be applied?

**Comment by sebmaniac** [comment]
I am also having this issue (latest Cordova on Android). I tried several different versions, no luck. This is an absolute blocker!

**Comment by briebug** [comment]
At risk of sounding dumb, did you remove both platforms and plugins?  

```
ionic platform rm ios
ionic platform rm android
rm -fr platforms
rm -fr plugins
ionic plugin add phonegap-plugin-barcodescanner@6.0.2 --save

ionic prepare
```

We have tested this on multiple devices and found it to work.  The key was removing platforms and plugins so that ionic could update everything properly.

**Comment by sebmaniac** [comment]
I am not using ionic, just plain cordova. But I'll give it a try.

**Comment by briebug** [comment]
@sebmaniac - it shouldn't matter if you are using just cordova... Ionic is just a wrapper around cordova.  Just replace ionic with cordova in the example I gave and it should work.

**Comment by sebmaniac** [comment]
I just tried it, no luck. It is not working with 6.0.2., even after removing the entire plugins and platform.

**Comment by sebmaniac** [comment]
Any news on this? Are the developers addressing this issue?

**Comment by EddyVerbruggen** [comment]
FYI this developer doesn't have a device that replicates the issue. My Nexus 6P and Samsung PRO8 behave just fine (correct aspect ratio's). Perhaps someone else with a 'problematic' device can take a look?

**Comment by javierlopeza** [comment]
Any news on this? I'm having the same issue.

**Comment by gczudowski** [comment]
Hi everybody. I'm trying to work on this issue. I need some help on reproducing this issue. any movies or screenshots presenting the issue would be helpful.
@Style117 how do you know it is connected with wrong aspect ratio?

**Comment by Style117** [comment]
@gczudowski  I dont know if its connected to the wrong aspect ratio. But if you compare the two screenshots its all squeezed together.

**Comment by douglasevaristo** [comment]
any news? i have the same problem :(

**Comment by biswas123** [comment]
Any news?

**Comment by ming-k** [comment]
Here's a video of the aspect ratio problem on Samsung Galaxy Mega 5.8 (GT-I9152) trying to scan a QR Code.

[barcode.m4v.zip](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/849458/barcode.m4v.zip)

**Comment by wcalderw** [comment]
[BarCodeSF550.avi.zip](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/853871/BarCodeSF550.avi.zip)

Here's a video of the barcode failing. You'll notice that the 3rd and 4th time it scans the wrong number.

**Comment by gczudowski** [comment]
I was able to solve this issue successfully, it seems. The aar library needed some fine-tuning. Do you guys know where the current .aar library source code is located? I'd like to submit a pull request with the new lib, but is https://github.com/EddyVerbruggen/barcodescanner-lib-aar the current `barcodescanner-release-2.1.2.aar`?

**Comment by EddyVerbruggen** [comment]
Hey guys (especially those of you that experienced this issue),

Can you please give the latest version from GitHub's master branch a spin? It includes the changes @gczudowski made today. Like I said before I can't test them, I was only able to check for regression issues on my devices.

**Comment by Style117** [comment]
Hi, the error is fixed on my Grand Prime.

I tested it with:
cordova CLI: 6.4.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7 

@gczudowski thanks for the update. 👍

**Comment by ming-k** [comment]
The fix is confirmed on Samsung Galaxy Mega 5.8 (GT-I9152), thank you @gczudowski :thumbsup:

**Comment by MUmer1124** [comment]
Hi Guys. Any update is this issue is fixed?
I facing same issue using phonegap-plugin-barcodescanner@6.0.8.
I also downgrade version 6.0.2 & 6.0.5 but no luck.

**Comment by wcalderw** [comment]
Was fixed several months ago. I know we verified the fix here.

**Comment by MUmer1124** [comment]
Thanks for your reply on time.

I deduce this issue was generated when I change my height & width of scanning area. But otherwise your lib is works cool.

Can you give me a suggestion how can I change the size of scanning area.

public synchronized Rect getFramingRect() {
        if (framingRect == null) {
            if (camera == null) {
                return null;
            }
            Point screenResolution = configManager.getScreenResolution();
            if (screenResolution == null) {
                // Called early, before init even finished
                return null;
            }

            int width = screenResolution.x;
            int height = screenResolution.y;

            int rotation = context.getApplicationContext().getResources().getConfiguration().orientation;
            if (rotation == Configuration.ORIENTATION_PORTRAIT) {
                width = (int) getDeviceWidth(width, 90); // 90%
                height = (int) getDeviceHeight(height, 40); // 40%
            }
            else {
                width = (int) getDeviceWidth(width, 70); // 70%
                height = (int) getDeviceHeight(height, 50); // 50%
            }

            int leftOffset = (screenResolution.x - width) / 2;
            int topOffset = (screenResolution.y - height) / 2;
            framingRect = new Rect(leftOffset, topOffset, leftOffset + width, topOffset + height);
        }
        return framingRect;
    }

The above code I change on your lib code then preview is generated fine. But scanner scanning speed is going too slow but its read correctly Code-39 format but not read QRCodes smoothly. 
Thanks in advance.
