### ISSUE TITLE
Using Torch on iOS Device without Flashlight crashes the app

### ISSUE THREAD

**Issue by AlDrag** [phonegap/phonegap-plugin-barcodescanner#393]
Using the torch button on iOS devices without a flashlight crashes the app. Maybe should just hide the torch button if the device doesn't have a flashlight?

**Comment by EddyVerbruggen** [comment]
Oh wow, which device? In the meanwhile you may want to use the Flashlight plugin to check for availability..

**Comment by AlDrag** [comment]
@EddyVerbruggen Apologies for the late reply. Hope you had a good Christmas!

This iPad Device is a iPad Mini 4 running iOS 10.1
It doesn't have a flash light :) Don't think any iPads do.

**Comment by EddyVerbruggen** [comment]
Hah, my iPad Pro (9,7") _does_ have a flashlight but I'm sure older models / Minis lack it.

I've just pushed a change to GitHub - can you please use the plugin from here (master branch) to verify the flashlight icon is gone for your iPad Mini?

**Comment by AlDrag** [comment]
@EddyVerbruggen Yep that fixed it. All working. Can probably close the issue now. Thank you.

**Comment by EddyVerbruggen** [comment]
Thanks for confirming that!
