### ISSUE TITLE
Scanner not working on jelly bean, it works fine on versions starting from kitkat

### ISSUE THREAD

**Issue by junryl** [phonegap/phonegap-plugin-barcodescanner#394]
### Expected Behaviour
The scanner should read the barcode on jelly bean devices

### Actual Behaviour
The scanner is on progress trying to read the barcode but it does not return the barcode nor show an error.

#### Steps to Reproduce
I have a button that executes the code from sample code.
When the button is tapped, it opens the camera ang tries to read the barcode.
But it can't read the barcode nor return an error.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android 4.1.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version

    cordova --version : 6.4.0
    cordova platforms : android

#### Plugin version

   latest plugin version

#### Sample Code that illustrates the problem
cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      },
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          preferFrontCamera : true, // iOS and Android
          showFlipCameraButton : true, // iOS and Android
          showTorchButton : true, // iOS and Android
          torchOn: true, // Android, launch with the torch switched on (if available)
          prompt : "Place a barcode inside the scan area", // Android
          resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
          formats : "", // default: all but PDF_417 and RSS_EXPANDED
          orientation : "portrait", // Android only (portrait|landscape), default unset so it rotates with the device
          disableAnimations : true // iOS
      }
   );

**Comment by macdonst** [comment]
We are no longer supporting JB.
