### ISSUE TITLE
How to hide in the scan as shown

### ISSUE THREAD

**Issue by xgzl87** [phonegap/phonegap-plugin-barcodescanner#399]
![qq 20170110133957](https://cloud.githubusercontent.com/assets/12945325/21795066/936c2932-d73a-11e6-8784-7efb6900c2cc.png)

**Comment by EddyVerbruggen** [comment]
Look for `resultDisplayDuration` in the readme.

**Comment by xgzl87** [comment]
oh  thanks!!!
