### ISSUE TITLE
Cannot control android back button while QRCode scanner open

### ISSUE THREAD

**Issue by cyclonmaster** [phonegap/phonegap-plugin-barcodescanner#400]
Android 5.0
Xiaomi redmi Note 3

Cordova CLI version 6.4.0
Plugin version 6.0.4

How to control back button in this plugin?
I want it to produce as failed or function(error) so that I can execute certain function if user press back button on Android. Right now, while qrcode scanner is open, when user press back button. It did not do anything. Just close QRCode scanner and go back to previous page.

Any hint? Thank you

**Comment by vikas0vanvi** [comment]
[355](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/355)
