### ISSUE TITLE
error while ionic run iOS

### ISSUE THREAD

**Issue by bhandaribhumin** [phonegap/phonegap-plugin-barcodescanner#401]
> ionic-app-scripts build

[00:02:21]  ionic-app-scripts 1.0.0 
[00:02:21]  build dev started ... 
[00:02:21]  clean started ... 
[00:02:21]  clean finished in 6 ms 
[00:02:21]  copy started ... 
[00:02:21]  transpile started ... 
[00:02:25]  typescript: src/pages/home/home.ts, line: 19 
            Property 'scan' does not exist on type 'BarcodeScanner'. 

      L18:    scanBTN() {
      L19:       this.barcodeScanner.scan().then((barcodeData) => {
      L20:  // Success! Barcode data is here

[00:02:25]  transpile failed 
[00:02:25]  ionic-app-script task: "build" 
[00:02:25]  Error: Error 

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

Apples-MacBook-Pro-4:BarcodeProject BhuminB$ ionic plugin update
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner"

**CODE:**
home.ts file

i

> mport { Component } from '@angular/core';
> import { BarcodeScanner } from 'ionic-native';
> @Component({
>   selector: 'page-home',
>   templateUrl: 'home.html'
> })
> export class HomePage {
>     constructor(public barcodeScanner:BarcodeScanner) {
>     };
>  
>    scanBTN() {
>       this.barcodeScanner.scan().then((barcodeData) => {
>  // Success! Barcode data is here
>  alert('barcodeData > '+JSON.stringify(barcodeData));
> }, (err) => {
>     // An error occurred
>      alert('barcodeData err >'+JSON.stringify(err));
> });
>     };
> 
> }
>

**Comment by macdonst** [comment]
@bhandaribhumin this is an Ionic issue. You should be asking them why the build fails.
