### ISSUE TITLE
phonegap/phonegap-plugin-barcodescanner

### ISSUE THREAD

**Issue by Teenashrivastava** [phonegap/phonegap-plugin-barcodescanner#405]
/**
 * Created by TShrivastava on 1/22/2017.
 */
Ext.define('BarcodeExampel.view.main.Scanner', {
    extend: 'Ext.Container',
    xtype:'Scanner',

    /*
    Uncomment to give this component an xtype
    xtype: 'scanner',
    */

    requires: [
        'Ext.Button',
        'Ext.Img',
        'Ext.layout.VBox'
    ],
    config: {
        layout: {
            type:"vbox",
            pack:"center",
            align:"center"
        },
        items: [
            {
                xtype: "image",
                src: "http://placehold.it/200x200",
                width: 200,
                height: 200
            },
            {
                xtype: "button",
                text: "Photo",
                handler: function() {

                    cordova.plugins.barcodeScanner.scan(
                        function (result) {
                            alert("We got a barcode\n" +
                                "Result: " + result.text + "\n" +
                                "Format: " + result.format + "\n" +
                                "Cancelled: " + result.cancelled);
                        },
                        function (error) {
                            alert("Scanning failed: " + error);
                        },
                        {
                            preferFrontCamera : true, // iOS and Android
                            showFlipCameraButton : true, // iOS and Android
                            showTorchButton : true, // iOS and Android
                            torchOn: true, // Android, launch with the torch switched on (if available)
                            prompt : "Place a barcode inside the scan area", // Android
                            resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
                            formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
                            orientation : "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
                            disableAnimations : true // iOS
                        }
                    );

                }
            }
        ]
    }
});

----------[-----------------Error : Igot on local host ------------------------------------------------------------------------------

I got the error on localhost,When we tap the button of scan the product .
Uncaught ReferenceError: cordova is not defined
at constructor.handler [as _handler] (Scanner.js?_dc=1485243742253:37)
at Object.callback (ext-modern-all-debug.js?_dc=1485243742253:5676)
at constructor.doTap (ext-modern-all-debug.js?_dc=1485243742253:82881)
at ext-modern-all-debug.js?_dc=1485243742253:13127
at constructor.fire (ext-modern-all-debug.js?_dc=1485243742253:12957)
at constructor.doFireEvent (ext-modern-all-debug.js?_dc=1485243742253:13640)
at constructor.doFireEvent (ext-modern-all-debug.js?_dc=1485243742253:28158)
at constructor.prototype.doFireEvent (ext-modern-all-debug.js?_dc=1485243742253:34461)
at constructor.fireEventArgs (ext-modern-all-debug.js?_dc=1485243742253:13546)
at constructor.fireEventArgs (ext-modern-all-debug.js?_dc=1485243742253:4728

**Comment by fappels** [comment]
Did you include cordova.js in your app.json of your ext project. 
You should post on the sencha community forum, there are a lot of Ext + cordova users on it.
Github is reporting bugs and asking new features, not for asking community support.

**Comment by Teenashrivastava** [comment]
Yes i included .
