### ISSUE TITLE
Writing to the photo album requires NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-plugin-barcodescanner#406]
dumpImage method https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/src/ios/CDVBarcodeScanner.mm#L750 is writing in the photo library, so Apple detects it and wants the app to add NSPhotoLibraryUsageDescription to tell the user why does it writes on the photo library.

But, that method is for debugging only.

Should we remove dumpImage? or should we add the NSPhotoLibraryUsageDescription?

**Comment by macdonst** [comment]
@jcesarmobile can we put the code inside a debug preprocessor?

```
#ifdef DEBUG
    // debug only code
#else
```

The call to `dumpImage` is commented out anyway so it must be used infrequently.

**Comment by jcesarmobile** [comment]
I think Apple is scanning the code and when it sees AssetsLibrary it tells the user that it needs the NSPhotoLibraryUsageDescription.
I can do a test later uploading an app with the debug code

**Comment by jcesarmobile** [comment]
False alarm, I've created a new Cordova app, added just phonegap-plugin-barcodescanner and on first submit I got 

> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

That's because I didn't add an usage description for the camera. After adding it, the app was uploaded and processed correctly
