### ISSUE TITLE
Impossible to scan on Windows Phone 8.1 (Universal). No autofocus.

### ISSUE THREAD

**Issue by iandonov** [phonegap/phonegap-plugin-barcodescanner#41]
Using Lumia 830 and Samsung Ativ S I get the same result.

Code for activating Auto focus or Continuous focus is not working.
BarcodeScannerProxy.js (lines 69 - 78)

If however I put a button that triggers autofocus with the same code - autofocus is activated:
controller.focusControl.focusAsync();

**Comment by carocad** [comment]
I am having the same issue on the Nokia Lumia 735. I checked and it only happens if the compilation target is Windows Phone (Universal). For Windows Phone 8 everything works as expected.

@iandonov could you please tell me exactly which code did you use to enable the autofocus? I can't figure out how to trigger the autofocus without copying most of the module code.

**Comment by iandonov** [comment]
This is moved out of startPreview() in a new function (with a small modification to startPreview):
---
        function setFocus() {
            var controller = capture.videoDeviceController;

            if (controller.focusControl && controller.focusControl.supported) {
                if (controller.focusControl.configure) {
                    var focusConfig = new Windows.Media.Devices.FocusSettings();
                    focusConfig.autoFocusRange = Windows.Media.Devices.AutoFocusRange.macro;

                    var supportContinuousFocus = controller.focusControl.supportedFocusModes.indexOf(Windows.Media.Devices.FocusMode.continuous).returnValue;
                    var supportAutoFocus = controller.focusControl.supportedFocusModes.indexOf(Windows.Media.Devices.FocusMode.auto).returnValue;

                    if (supportContinuousFocus) {
                        focusConfig.mode = Windows.Media.Devices.FocusMode.continuous;
                    } else if (supportAutoFocus) {
                        focusConfig.mode = Windows.Media.Devices.FocusMode.auto;
                    }

                    controller.focusControl.configure(focusConfig);
                    controller.focusControl.focusAsync();
                }
            }
        }
---- 
create a button and bind to this function or just invoke like this (with a timeout !?):
        try {
            createPreview();
            startPreview();
            setTimeout(function () {
                setFocusMode();
                startBarcodeSearch(maxResProps.width, maxResProps.height);
            }, 1000);

        } catch (ex) {
            fail(ex);
        }
-----
However it is so unreliable that I ended up using WP8 target and not this code but the native dll.
It is a pity nobody can fix this as WP8 is getting old and probably will not be supported soon.

**Comment by carocad** [comment]
Hey @iandonov,
Thanks for the info on the timeout :)

After doing lots of different test and trying to figure out exactly what was going wrong. I found out that only one line is the cause of the problem in BarcodeScannerProxy.js.
```
controller.focusControl.focusAsync();
```
I wrapped that spefic line with the timeout and it worked. According to my tests, any other line can be outside of the timeout without interfiring with the continous focus. Also the focus mode is only changed once the focusAsync() method finishes i.e. .done(// callback). Before that the focusmode stayed in auto (value 0).

It is not clear to me at all why is this happening, but at least now I can focus properly.

I hope it helps ;)

**Comment by dominikfeininger** [comment]
+1

Hi, having the same problem on a Lumia 930. @carocad fixed the issue, unfortunately this works just once. After the barcode scanner is closed and open again the auto focus issue still occurs.

**Comment by carocad** [comment]
Hey @dominikfeininger can you describe exactly what you mean by "After the barcode scanner is closed and open again", do you mean that you cancelled the scan and reopened later or that you sucessfully scanned something and wanted to scan something else afterwards? also, are you calling the scan function through a button or any other mean?

This actually doesnt happen to me on the Lumia 735. I can scan very well several barcodes on a row without any problem with the "patch" that I used.

Maybe you should increase the timeout?
