### ISSUE TITLE
Error "No cameras found" on Windows 10 - Visual Studio.

### ISSUE THREAD

**Issue by newchiripa** [phonegap/phonegap-plugin-barcodescanner#410]
### Expected Behaviour
App to trigger scanner.

### Actual Behaviour
cordova.plugins.barcodeScanner.scan() fails, triggering the error function.

#### Steps to Reproduce
Visual Studio 2015 -> New Project -> Apache Cordova Apps

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
target Windows 10

#### Cordova CLI version and cordova platform version

    cordova --version 6.3.0

#### Plugin version
    phonegap-plugin-barcodescanner 6.0.5

Hello,
I've an issue using the plugin in windows 10 devices (Desktop AND tablets)
Everytime I trigger cordova.plugins.barcodeScanner.scan() it fails going into the error function with error "No Cameras found".

I've created a clean project to test from the default template for Apache Cordova Apps.
Added the plugin to the project and in the DeviceReady function added this code and ran in debug mode.

        debugger;
        cordova.plugins.barcodeScanner.scan(
              function (result) {
                  console.log("We got a barcode\n" +
                        "Result: " + result.text + "\n" +
                        "Format: " + result.format + "\n" +
                        "Cancelled: " + result.cancelled);
              },
              function (error) {
                  console.log("Scanning failed: " + error);
              });

the program logs "Error: No Cameras found" on the console.
I've tested this in a Windows 10 machine through Visual Studio Debugger, and tried in 2 different Windows 10 tablets (after compiling and installing) and I'm having the same issue.
I have made certain I've got Windows Media Player and the Media Features Pack installed.

Any idea what could be causing this issue?
![image](https://cloud.githubusercontent.com/assets/18033426/22655733/f6c2d8f6-ec88-11e6-92ba-3f4ee5ea6481.png)

**Comment by daserge** [comment]
@newchiripa have you tried using master version of Windows platform? `cordova platform rm windows && cordova platform add https://github.com/apache/cordova-windows`

**Comment by newchiripa** [comment]
Hello,
I managed to "Solve" the issue:
Had to DOWNGRADE the Cordova version from 6.3.0 to 6.0.0 Any other version (6.1.0 upwards) would make the barcodescanner to not find any cameras on windows 10 devices.
