### ISSUE TITLE
IOS 10: barcode can't be identified, keep scanning without result.

### ISSUE THREAD

**Issue by netsesame2** [phonegap/phonegap-plugin-barcodescanner#412]
A recently project, using Ionic2+Angular2+photogap-plugin-barcodescanner 6.0.4. 

Testing on my iPhone5s+IOS10.2, plugin window can be open, barcode image is prefectly located in the scaner box,  but no way to get the result.

There are some similar issues here:
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/173
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/333

There are anyway to fix?

**Comment by EddyVerbruggen** [comment]
Please share the barcode (and type) you're trying to scan.

**Comment by netsesame2** [comment]
Barcode for QR.

It's very strange. Just now I scan my barcode in my office's desktop PC, it is successful.
However, yesterday evening, on my notebook screen, the same barcode, always fail.

The main difference is the screen and light around. I'll test it this night, and give the feedback here.

**Comment by netsesame2** [comment]
Just a while I test again to scan the QR on my Notebook screen, the result is still failed.
So I try to change the backlight of the screen to a higher value, this time it is successful.

To be compared, I scan the same QR with my old version App binding with this plugin of V2.1,  no second to get the result, very fast.

So, it is time to check out what's wrong.
