### ISSUE TITLE
NSCameraUsageDescription for PhoneGap Build

### ISSUE THREAD

**Issue by andersborgabiro** [phonegap/phonegap-plugin-barcodescanner#417]
### Expected Behaviour

Successful publishing of app via iTunes Connect

### Actual Behaviour

iTunes Connect complains about missing NSCameraUsageDescription when building with PhoneGap Build, and there's no mention of a workaround for PhoneGap Build. Changing info.plist is not an option and a config-file setting (via cordova-custom-config) doesn't work.

### Reproduce Scenario (including but not limited to)

Simply not providing any NSCameraUsageDescription

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 10

#### Cordova CLI version and cordova platform version

cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3) (iOS / Android / Windows)

#### Plugin version

6.0.5 (as I don't state it)

**Comment by jcesarmobile** [comment]
http://stackoverflow.com/questions/41525725/phonegap-missing-plist-key/41692078#41692078

**Comment by jcesarmobile** [comment]
Will add that to the documentation
