### ISSUE TITLE
iOS :: Statusbar and Barcode scanner problem :: After start the scanner statusbar overlays webview

### ISSUE THREAD

**Issue by davixz** [phonegap/phonegap-plugin-barcodescanner#423]
Iphone 6, iOS 10.1, cordova ios 4.3.1, cordova 6.5.0, phonegap-plugin-barcodescanner@6.0.5 (latest)

I have in my config.xml
<preference name="StatusBarOverlaysWebView" value="false" />
And this works ok, but as soon as i start the barcode scanner, when i leave the scanner (scaning something or not) the statusbar is overlaying the webview

I also have android motog 1 with cordova-android-6.1.2 and the problem does not occur there

Screenshot of statusbar overlaying webview after the scanner start
http://imgur.com/a/5HsIz

**Comment by jcesarmobile** [comment]
It's a bug on the statusbar plugin, it's fixed on master, you can install it from github url or wait until it's released probably on Monday

**Comment by jcesarmobile** [comment]
statusbar plugin has been released, you can now install 2.2.2 version
