### ISSUE TITLE
Barcode scanner stops reading QR codes after reading 81 times

### ISSUE THREAD

**Issue by andrewtang1** [phonegap/phonegap-plugin-barcodescanner#425]
### Expected Behaviour
My app requires reading multiple QR codes. I expected the plugin to not post any limit on the number of times it can read bar/QR codes.

### Actual Behaviour
After calling the plugin to successfully read 81 times, the plugin would not read any more codes. On the 82nd time, when placing the QR code in the middle of the green square with the camera perfectly focus (just like the previous 81 times), the scanner just would not pick up the code any more. No beep, and it does not come out of the camera mode until I press Cancel. This behavior is very consistent and is reproducible.

### Reproduce Scenario (including but not limited to)
Please see sample code below.

#### Steps to Reproduce
Please see sample code below

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.2.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPod 6

#### Cordova CLI version and cordova platform version

    cordova --version  cli-6.5.0
    cordova platforms  (4.3.1 / 6.1.2 / 4.4.3)

    Built with phonegap: cli-6.5.0 (iOS 4.3.1, Android 6.1.2, Windows 4.4.3)

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

     6.0.5

#### Sample Code that illustrates the problem
// It is supposed to continuously scan until I press cancel.
// It works for the first 81 scans, but on the 82nd scan, it would not read any more
// and stuck in the camera mode.
// When I do cancel out of the camera mode, and later call barcodeScanner.scan
// to scan again, it would exhibit the same behavior (unable to read bar/QR codes).
// In order to "reset" the situation, I'd need to terminate my app, and
// relaunch my app. Doing this would let me scan 81 more times before it
// gets stuck again.
cordova.plugins.barcodeScanner.scan(
function(result)
{
	if (!result.cancelled)
	{
		// A QR Code was scanned, add it to the list.
		//_this.showDebug("Barcode type is: " + result.format + ", text=" + result.text);
		_this.addDeviceToList(result.text, $appPageDiv);

		// Scan again
		$scanButtonDiv.find("#scanMultipleButton").trigger("click");
	}
},
function(error) {
	_this.showDebug("Scanning failed: " + error);
},
{
	"preferFrontCamera" : false,
	"showFlipCameraButton" : true,
	"prompt" : "Place a barcode inside the scan area",
});

**Comment by aldehitdeveloper** [comment]
81 is too much my app 4 times after close 
how can we solve this issue i dont know

**Comment by douglasevaristo** [comment]
I need to read 2 diferent code bar in the same time. Did you know how to do this? Because, if i do like you, the problem is: ta app read the fist one, any time.

**Comment by arruix** [comment]
I have the same issue, after 70 scans is not reading more https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/370

**Comment by lasseron** [comment]
I have the same issue, scan stops returning code value after about 50 successful scans #370

**Comment by andrewtang1** [comment]
Good news I suppose! I just upgraded my iPod from iOS 10.2.1 to iOS 10.3.1 (which just came out a week ago), and the problem appears to getting better (although has not completely gone away). For my device, which used to stop scanning after 81 times, and restarting the app is the only option to recover, now with iOS 10.3.1, after 81 times, the camera now shows a black screen (as if you are taking a picture in pitch black). But after pressing "Cancel" at the bottom, and invoking the scan function again, it would scan normally for another 81 times.

Although the problem has not completely gone away, the behavior now a bit better than before. At least I don't have to restart the entire app.

**Comment by macdonst** [comment]
#370
