### ISSUE TITLE
iphone barcode format not working

### ISSUE THREAD

**Issue by ojores** [phonegap/phonegap-plugin-barcodescanner#426]
I have this problem on iPhone, but not Android.

I've changed the format of barcodeScanner.scan() to only read QR_CODE, but it correctly reads an EAN_13 code.
And I have a second scanner that is set to read EAN_13 only, but it also reads the QR_CODE.

Is it possible that they are added the same instance of barcodeScanner ?
If so, how could I separate them ?
If not, what else could it be ?

**Comment by aldehitdeveloper** [comment]
i have a question.this plugin is working on ios10. Did you try ?

**Comment by stevesum** [comment]
Yes. I use it on iOS 10 devices.

2017-03-11 22:30 GMT+01:00 aldehitdeveloper <notifications@github.com>:

**Comment by aldehitdeveloper** [comment]
i use it but if i scan 4 times , my app give crash, did you build it or use emilator or ionic view ?

**Comment by stevesum** [comment]
I'll check this 4 times test tomorrow in the office. We use real phones and
simple cordova together with sencha view, not ionic framework.

2017-03-12 11:05 GMT+01:00 aldehitdeveloper <notifications@github.com>:

**Comment by aldehitdeveloper** [comment]
okey thaks my friend

**Comment by stevesum** [comment]
I tested with our applications on an iPhone 6 (iOS10) and worked without
any problem. I scanned over 20 barcodes (EAN13).
May the bug connected a barcode type?

2017-03-12 19:58 GMT+01:00 aldehitdeveloper <notifications@github.com>:

**Comment by ojores** [comment]
I'm scanning EAN13 barcodes and QR_Codes nothing else
I'm using iOS8.3 and 10.1, same results on both

**Comment by aldehitdeveloper** [comment]
maybe problem source is ionicview , i didnt see log, therefor i dont say anything

**Comment by ojores** [comment]
Ok, so i've tried different formats on an iPad 2 (iOS10.2.1,14D27)
From what I can tell, you can't choose formats for the scanner on iOS, all formats are accepted no matter what you put.

So... bug ?

**Comment by wildabeast** [comment]
Just tried out some different versions... the formats parameter works as expected in 6.0.2, but has no effect in 6.0.3. I'm thinking commit f81c88ced9f48c40f3082f3d55ade944574cd898 might be the culprit.

**Comment by irperera** [comment]
I'm having this same issue

**Comment by jmevangelist** [comment]
@wildabeast I tried using version 6.0.2 but I can still scan any barcode type. Any update on this?
