### ISSUE TITLE
Capture multiple barcodes from the same scan

### ISSUE THREAD

**Issue by douglasevaristo** [phonegap/phonegap-plugin-barcodescanner#427]
### Expected Behaviour
capture multiple barcodes from the same scan.
### Actual Behaviour
i try to repeat the read, but its not good idea.

**Comment by jcesarmobile** [comment]
It's a duplicate, there is an issue for continuous recognition

**Comment by douglasevaristo** [comment]
@jcesarmobile its not a continuous recognition. Its identify multiple codebar at same time! i'm wrong?

**Comment by jcesarmobile** [comment]
Feel free to reopen then, but we just use zxing and they don't support that, maybe start asking them to support it
