### ISSUE TITLE
iOS scan never returns

### ISSUE THREAD

**Issue by jhuggart** [phonegap/phonegap-plugin-barcodescanner#43]
When I try to scan a barcode on iOS (8.1.3) the camera comes up. But it never recognizes the barcode. Same barcode works fine on Android devices. Any ideas?

**Comment by jhuggart** [comment]
So what I've found is that some really small barcodes will not scan on ios and some take a really long time to focus. Other than that, the plugin seems to be working fine.

**Comment by fromvega** [comment]
On my Android phone sometimes it also takes long to focus.

**Comment by Delagen** [comment]
Image hang and never updates at start of scanning
