### ISSUE TITLE
Android unable to load page after QR Code scanning

### ISSUE THREAD

**Issue by sumitsoman** [phonegap/phonegap-plugin-barcodescanner#432]
I am unable to get back to the Cordova App html page after scanning the QR code.

    cordova.plugins.barcodeScanner.scan(
     function (result) {

         myXMLString = result.text;

         if (result != null){

         document.location.href = "MyPage.html";

         }

     },
     function (error) {
         alert("Scanning failed: " + error);
      }
    );

However, when I run the app on the device, the scan completes and I get the message

    Application Error

    net::ERR_FILE_NOT_FOUND (file:///android_asset/www/MyPage.html

How do I fix this? It works on Windows and iOS Platforms.

**Comment by EddyVerbruggen** [comment]
Does navigating to that file work without scanning? If not, check that the casing is correct. If it does, perhaps wrap navigation in a little timeout.

**Comment by sumitsoman** [comment]
In other places in my code, I am able to successfully navigate to pages using 
    document.location.href = "MyPage.html";

The error is only when the QR code scanning returns. I am also able to display the result in an alert dialog. How can I wrap navigation in a timeout?

**Comment by gmarm** [comment]
@sumitsoman have you solved this somehow?

**Comment by gmarm** [comment]
I'm having the same issue on only _some_ devices on Android using Ionic.

Could someone assist me or point to the right direction?
