### ISSUE TITLE
iOS 7 crash

### ISSUE THREAD

**Issue by Ernestoschiavo** [phonegap/phonegap-plugin-barcodescanner#434]
### Expected Behaviour
Normal behaviour

### Actual Behaviour
App crash

#### Steps to Reproduce
Simply try it on iPhone 4 (or any device with iOS 7)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 7.1.2

#### Cordova CLI version and cordova platform version

    cordova 6.5.0
    cordova iOS 4.3.1

#### Plugin version

    6.0.6

#### Logs taken while reproducing problem
The problem is related to "setUpCaptureSession" method. Exactly, the app crashes at line 526:
[output setMetadataObjectTypes:@[AVMetadataObjectTypeQRCode, ....]];

**Comment by jcesarmobile** [comment]
AVMetadata​Object​Type​Data​Matrix​Code is iOS 8+ and probably other types too (didn't check all)

BTW, cordova iOS 4.3.1 is iOS 8+ too, did you modify the Xcode project to run the app on iOS 7?

**Comment by Ernestoschiavo** [comment]
Not really, I use xCode 7.1 in order to build on iOS7. I didn't really know platform 4.3.1 is for iOS8+, I didn't find any reference to this in [official page](https://cordova.apache.org/announcements/2016/12/02/ios-release.html). Do you know where can I find this type of info? Also in this plugin page there is an ambiguos "iOS support". Thanks you

**Comment by jcesarmobile** [comment]
It was changed on 4.0.0 https://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html

So, you didn't have to manually change the deployment target on the Xcode project to make it work on iOS 7?

**Comment by Ernestoschiavo** [comment]
Well, that's actually possibile. I did it some months ago. Do you know any valid reason in order to not do that?

**Comment by jcesarmobile** [comment]
If you remove and re add the platform the deployment target will be restored to iOS 8, so you have to remember to re set it to iOS 7.
Other than that, there is no problem. When we remove support for an old iOS version it usually just mean that we no longer test on it, so it might or might not work, but in case it doesn't work, it won't be fixed. (Talking about cordova-ios, not sure about this plugin policy)

**Comment by macdonst** [comment]
Not supporting iOS 7 for this plugin.
