### ISSUE TITLE
DOMException on Windows 10 Phone

### ISSUE THREAD

**Issue by edwardgaoyb** [phonegap/phonegap-plugin-barcodescanner#435]
### Expected Behaviour
Barcode scanning window is displayed on Windows 10 Phone.

### Actual Behaviour
Nothing happened. There is a DOMException in JS console in Visual Studio

### Reproduce Scenario (including but not limited to)
Invoking barcode scanner api , nothing happened in UI, and an exception was caught in Visual Studio

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows 10, version 1607, build 10.0.14393.953                                                            

#### Cordova CLI version and cordova platform version

    phonegap --version

6.4.6

    cordova platforms

windows 4.4.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

6.0.6

#### Sample Code that illustrates the problem
(function() {
    window.addEventListener('message', function(e) {
    	if (e.data.slice(0, 'barcodescanner-'.length) == 'barcodescanner-') {
    		startBarCodeScanner();
    	}
    }, false);
    
    function startBarCodeScanner() {
    	
    	cordova.plugins.barcodeScanner.scan(
    			function (result) {
    				var iframe = document.getElementById('app');
    				if (iframe) {
    			    	iframe.contentWindow.postMessage("barcodescanned-" + result.text, "*");
    				}
    			}, 
    			function (error) {
    				alert("Scanning failed: " + error);
    			}
    	);
    	
	};

})();

#### Logs taken while reproducing problem

NotFoundError
BarcodeScannerProxy.js (568,21)
   {
      [functions]: ,
      __proto__: { },
      ABORT_ERR: 20,
      code: 8,
      DATA_CLONE_ERR: 25,
      DOMSTRING_SIZE_ERR: 2,
      HIERARCHY_REQUEST_ERR: 3,
      INDEX_SIZE_ERR: 1,
      INUSE_ATTRIBUTE_ERR: 10,
      INVALID_ACCESS_ERR: 15,
      INVALID_CHARACTER_ERR: 5,
      INVALID_MODIFICATION_ERR: 13,
      INVALID_NODE_TYPE_ERR: 24,
      INVALID_STATE_ERR: 11,
      message: "NotFoundError",
      name: "NotFoundError",
      NAMESPACE_ERR: 14,
      NETWORK_ERR: 19,
      NO_DATA_ALLOWED_ERR: 6,
      NO_MODIFICATION_ALLOWED_ERR: 7,
      NOT_FOUND_ERR: 8,
      NOT_SUPPORTED_ERR: 9,
      PARSE_ERR: 81,
      QUOTA_EXCEEDED_ERR: 22,
      SECURITY_ERR: 18,
      SERIALIZE_ERR: 82,
      SYNTAX_ERR: 12,
      TIMEOUT_ERR: 23,
      TYPE_MISMATCH_ERR: 17,
      URL_MISMATCH_ERR: 21,
      VALIDATION_ERR: 16,
      WRONG_DOCUMENT_ERR: 4
   }

**Comment by daserge** [comment]
@edwardgaoyb have you tried updating to cordova-windows@latest?
`cordova platform add windows@latest`

**Comment by edwardgaoyb** [comment]
@daserge Thank you. That helps. It is weird that I got cordova-windows 4.4.3 without the "@latest" qualifier. I thought that the latest version should be used by default. 
The previous error is gone, but I got a new JavaScript exception. 

---
Exception is about to be caught by JavaScript library code at line 137, column 5 in ms-appx-web://myoshsafetysoftware.myoshsafetysoftware/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js

0x800a1391 - JavaScript runtime error: 'ZXing' is undefined

If there is a handler for this exception, the program may be safely continued.
---

Could you please advise why the ZXing object is missing?

**Comment by daserge** [comment]
@edwardgaoyb ensure that you are 1) specifying an architecture (ARM for a phone device) and that you are 2) invoking the plugin after deviceready has been fired.
Like this:
```javascript
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },
    onDeviceReady: function() {
        cordova.plugins.barcodeScanner.scan(...)
    ... 
    }
```

**Comment by daserge** [comment]
@edwardgaoyb did it help?

**Comment by edwardgaoyb** [comment]
@daserge Sorry for the latest response. Got some urgent tasks and my Windows development machine collapsed.   :-(    I'm struggling to rebuild it. Will post the result once I got my app up and running again.

**Comment by edwardgaoyb** [comment]
@daserge It turned out that I was using 'AnyCPU' when debuggin the app on my phone with VStudio. The exception has gone, but I can only see a green window with a horizontal red line in the middle of it. There is not any exception/error/warning in the VStudio JavaScript console. Any advice on what I missed?
Thank you!

**Comment by daserge** [comment]
Green screen means that the camera driver has crashed - try rebooting your device.

**Comment by edwardgaoyb** [comment]
@daserge Cool! I restarted my phone and the barcode scanner is working now. Thank you so much!

**Comment by daserge** [comment]
No problem :)

**Comment by maximumver** [comment]
After some recent update this thing happens on WIN 10 DESKTOP.
On windows 10 mobile everything is ok, on PC previously worked too, now i'm getting this same exception..

And also in addition to this DOM exception barcodescanner returns this error, without opening camera:

`{"asyncOpType":"Windows.Foundation.IAsyncAction","asyncOpCausalityId":241,"__zone_symbol__currentTask":null}
`
asyncOpCausalityId":241 -> this number changes everytime.

I'm using Ionic framework, everything is up to date, latest versions.
But the most interesting thing that i had this app made in January & barcodescanner worked on win 10 PC at the time, now this OLD app gives me this exception.
So i believe this is some recent win 10 update on desktop.

I've decided to update this app, updated, nothing changed -> same exception as in OLD app.
cordova-windows 5
ionic 3.4.2
