### ISSUE TITLE
Always returning cancelled on android cordova 5.1.1 on Android

### ISSUE THREAD

**Issue by albertrosa** [phonegap/phonegap-plugin-barcodescanner#44]
Upon scanning notice of "Found Plain Text" appears after scanning however when processing the success function the response object returns with:  { text: "", format:"" cancelled: true }.

After modifying the plugin with logs to see if the scan result was being return post the scan activity however the log was triggered on failure before the scanner intent is completed.

**Comment by albertrosa** [comment]
I've confirmed with multiple android SDK build from SDK version 16  to 22.

**Comment by clock157** [comment]
+1

**Comment by gfr** [comment]
Same here on Android 4.2.2

**Comment by albertrosa** [comment]
I went back to look into this and noticed this warning:

```PluginManager﹕ THREAD WARNING: exec() call to BarcodeScanner.scan blocked the main thread for 51ms. Plugin should use CordovaInterface.getThreadPool().```

Not sure if this would mean anything as it calls the new activity to take over the MainUIThread

**Comment by clock157** [comment]
I have resolved. 
update the last version.
git clone https://github.com/phonegap/phonegap-plugin-barcodescanner
cordova plugin add $THAT_DIR

**Comment by albertrosa** [comment]
I have attempted the latest from master as mention by @clock157 still experiencing the same issue.

**Comment by ibrahimyu** [comment]
Same here. The plugin scanned and found the code twice, then return cancelled: true.

**Comment by albertrosa** [comment]
Everyone I have dug into this fully. The plugin does not introduce this issue. I have been able to replicate the issue with other plugins calling ```this.cordova.startActivityForResult()```

After many attempts I have realized the issue was within the settings for the cordova build.  (config.xml)

if you have this in your settings ```<preference name="AndroidLaunchMode" value="singleInstance" />``` it will always return cancelled and start the activity.. what you would want to do is either remove the settings or set the value to "singleTop" ```<preference name="AndroidLaunchMode" value="singleTop" />```

Sorry this took so long to resolve.

**Comment by bikasahoo** [comment]
I faced the same problem; but later discovered it was bad quality picture being captured by the camera itself. Hope this may help anyone.

**Comment by tinkywinky92** [comment]
is it a bad quality picture really? on first try i've got cancelled true, but the second time i've got success, did anyone solved it?

**Comment by gianx89** [comment]
I have the same issue. I didn't have <preference name="AndroidLaunchMode" value="singleInstance" /> in my config. Adding <preference name="AndroidLaunchMode" value="singleTop" /> will not solve the issue. Android 4.2.2

**Comment by mcmemam** [comment]
Solved [here](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/38). Also, you can  wrap your code inside settimeout function.
