### ISSUE TITLE
Error converting bytecode to dex

### ISSUE THREAD

**Issue by hrobar** [phonegap/phonegap-plugin-barcodescanner#440]
in ionic 2

ionic run android --device
......

#### Cordova CLI version and cordova platform version

    cordova --version
`6.5.0`

Installed platforms:
```
  android 6.1.2
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.4.0
  wp8 ~3.8.2 (deprecated)
```

#### Plugin version
cordova-hot-code-push-plugin 1.5.2 "Hot Code Push Plugin"
cordova-plugin-android-support-v4 21.0.1 "Android Support v4"
cordova-plugin-app-update 1.3.9 "AppUpdate"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"

#### Logs taken while reproducing problem
```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

:transformClassesWithDexForDebug FAILED

BUILD FAILED

Total time: 1 mins 38.382 secs

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\androidapp\aaaa\platforms\android\src\org\apache\cordova\splashscreen\SplashScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by beatgrabe** [comment]
Same for me with:

```
cordova 6.4.0
android 5.2.2
```

There is a related [SO Question](http://stackoverflow.com/questions/20989317/multiple-dex-files-define-landroid-support-v4-accessibilityservice-accessibility), but I was not able to try out mentioned solutions, yet.

**Comment by macdonst** [comment]
@hrobar you shouldn't need to include `cordova-plugin-android-support-v4` as this plugin pulls in support-v4 from gradle.

**Comment by lasseron** [comment]
I'm having the same problem:

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/apache/cordova/BuildHelper;

Whe I remove phonegap-plugin-barcodescanner plugin, building APK works fine.. but of course I need the plugin. My versions are as follows, hope somebody can give me a hint:

cordova 7.0.1
android 6.3.0

cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-swift-support 3.1.1 "SwiftSupport"
cordova-plugin-whitelist 1.3.2 "Whitelist"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanne

**Comment by lasseron** [comment]
I managed to figure it out. The problem seems to be that barcodescanner requires cordova-plugin-compat which is deprecated in android@6.3.0. 

When you update the Android platform they ask you to:
"This release contains the integration of cordova-plugin-compat, so please remove that plugin from projects once you update to this version of cordova-android."

Once you try this, cordova claims
"Error: The plugin 'cordova-plugin-compat' is required by (phonegap-plugin-barcodescanner), skipping uninstallation. (try --force if trying to update)"

If you then force remove the plugin, building APK in Android Studio works fine. 

The only thing is that "cordova prepare" still cries out for the plugin "Error: Cannot find plugin.xml for plugin "cordova-plugin-compat". Please try adding it again."
