### ISSUE TITLE
UPC-A does not work

### ISSUE THREAD

**Issue by irperera** [phonegap/phonegap-plugin-barcodescanner#441]
### Expected Behaviour
UPC-A is suppose to scan the barcode nothing happens

### Actual Behaviour
only EAN-13 is scanning. iphone 7

#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by macdonst** [comment]
@irperera can you post UPC-A barcode so I can test?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
