### ISSUE TITLE
Unfortunately <appname> has stopped in android 5.0

### ISSUE THREAD

**Issue by Bala893** [phonegap/phonegap-plugin-barcodescanner#442]
#### Cordova CLI version and cordova platform version

    cordova -- 6.5 version
    

I am using the phonegap-plugIn-barcodescanner for my ionic project. I created a very simple app which is working perfectly on  Android 4.3, Android 4.4 and Android 6.0. I have also tried to upload the Project to a Android Android 5.0. but there it is not working.
Everytime I try to scan a barcode by calling the plugIn my application throws an error which says "Unfortunately app has stopped".
![screenshot_20170403-175016](https://cloud.githubusercontent.com/assets/22056977/24650697/939b9d34-1948-11e7-8abf-747f7a07d34d.png)

**Comment by macdonst** [comment]
@Bala893 the stack trace of the crash would be super helpful.

**Comment by Bala893** [comment]
Thanks macdonst.
I don't know how to do stack trace?
Can you please explain.

**Comment by macdonst** [comment]
@Bala893 use `adb logcat` to capture logs from the device https://developer.android.com/studio/command-line/logcat.html

**Comment by Bala893** [comment]
Thanks 👍 @macdonst

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
