### ISSUE TITLE
QR_CODE barcodescanner

### ISSUE THREAD

**Issue by jrahma** [phonegap/phonegap-plugin-barcodescanner#445]
Hi,
 
I am trying to use this pluging:
 
[https://www.npmjs.com/package/cordova-plugin-barcodescanner](https://www.npmjs.com/package/cordova-plugin-barcodescanner)
 
The barcode scan frame is set for normal bar code but I want to make it square for QR_CODE because my app will only need to read QR_CODE
 
How can I do this please?
 
Thanks.
[Jassim](https://www.softnames.com)

**Comment by tylermakin** [comment]
You are looking for the `cordova-barcodescanner-plugin` repo, not this repo. On the NPM page you linked to it has a link to the [repo you are looking for](https://github.com/hypery2k/cordova-barcodescanner-plugin).

**Comment by lfreneda** [comment]
@tylermakin what is the difference between `phonegap/phonegap-plugin-barcodescanner` and `cordova-barcodescanner-plugin` you mentioned above?

**Comment by tylermakin** [comment]
I am not sure, I just wanted to point out that the npm package @jrahma linked to is for that repo, not this one. This repo and that one are both forks of [wildabeast/BarcodeScanner](https://github.com/wildabeast/BarcodeScanner) and it does not look like there is a big difference between the two.

**Comment by lfreneda** [comment]
@tylermakin Thanks :+1:
