### ISSUE TITLE
screen stays black after second call to cordova.plugins.barcodeScanner.scan on Samsung SM-G357FZ

### ISSUE THREAD

**Issue by yeti68** [phonegap/phonegap-plugin-barcodescanner#45]
when I call the function cordova.plugins.barcodeScanner.scan for the second time the screen stays (mostly) black. It does scan qr-codes though. This issue only happens on a Samsung Phone (Model: SM-G357FZ, Android 4.4.4), works fine on other devices. Since my customer wants to use this phone I'm stuck right now

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
