### ISSUE TITLE
Android: Class not found. 

### ISSUE THREAD

**Issue by kopihao** [phonegap/phonegap-plugin-barcodescanner#456]
### Expected Behaviour
Able to launch barcode scanner

### Actual Behaviour
Error returned : class not found 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4 above , building using Android Studio

#### Cordova CLI version and cordova platform version
MFP (7.1) cordova project  

#### Sample Code that illustrates the problem

   ###Inside CordovaUtil class

    '''declare var cordova: any;
    public static scanBarcode() {
        return new Promise((resolve, reject) => {
            cordova.plugins.barcodeScanner.scan(
                (result: any) => resolve(result),
                (err: any) => reject(err),
                {
                    preferFrontCamera: false, // iOS and Android
                    showFlipCameraButton: true, // iOS and Android
                    showTorchButton: true, // iOS and Android
                    torchOn: true, // Android, launch with the torch switched on (if available)
                    prompt: "Place a barcode inside the scan area", // Android
                    resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
                    formats: "QR_CODE,PDF_417,CODE_128", // default: all but PDF_417 and RSS_EXPANDED
                    orientation: "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
                    disableAnimations: true, // iOS
                    disableSuccessBeep: false // iOS
                }
            );
        }); 
    }

   ###Inside Angular Component

   '''openQR() {
        if (!this.isFavouritePayment) {
            CordovaUtil.scanBarcode().then(
                (response: any) => { this.processQRResult(response) },
                (err: any) => { this.showDialog1Btn(444, 'Invalid barcode, please try again', 'OK') }
            )
        }
    }

#### Logs taken while reproducing problem
class not found

**Comment by jcesarmobile** [comment]
which class?

**Comment by kopihao** [comment]
the console log just write : class not found

**Comment by victorsosa** [comment]
I had the same issue; the error don't said which class is

**Comment by victorsosa** [comment]
I just try doing;
```
cordova platform rm android
cordova platform add android
```
and this the issue

**Comment by macdonst** [comment]
@kopihao can you get the logs from `adb logcat`?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
