### ISSUE TITLE
BarcodeScanner not working on Android

### ISSUE THREAD

**Issue by mimilum83** [phonegap/phonegap-plugin-barcodescanner#457]
Expected Behaviour

This plugin works as expected on Apple devices. This does not work on Android devices

Actual Behaviour

The camera comes up but it doesn't focus and return any scanned barcodes

Reproduce Scenario (including but not limited to)

LG Leon and Samsung Note 3

Steps to Reproduce

Install the plugin and run in Android Studio

Platform and Version (eg. Android 5.0 or iOS 9.2.1)

$ cordova plugin list
com.phonegap.plugins.barcodescanner 6.0.5 "BarcodeScanner"
cordova-custom-config 3.1.4 "cordova-custom-config"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-whitelist 1.3.2 "Whitelist"
$ cordova platform
Installed platforms:
android 6.2.1
ios 4.3.1
Available platforms:
amazon-fireos ~3.6.3 (deprecated)
blackberry10 ~3.8.0
browser ~4.1.0
firefoxos ~3.6.3
osx ~4.0.1
webos ~3.7.0
$ cordova --version
6.5.0

I've also put this in my config.xml and it doesn't seem to help

**Comment by victorsosa** [comment]
Having similar issue on android 4.4.4
