### ISSUE TITLE
iOS : inverted DATA_MATRIX

### ISSUE THREAD

**Issue by PawelPiasecki** [phonegap/phonegap-plugin-barcodescanner#459]
### Expected Behaviour
Scan DATA_MATRIX code with inverted colors (white on black background)
### Actual Behaviour
Scan only black on white background
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10

Hello Guys,

Can anyone help me with this problem ? Because I use method mentioned in another Issue for inverted QR codes and unfortunetly, it doesnt work for Data matrix code type.

All best

**Comment by macdonst** [comment]
@PawelPiasecki I can reproduce this but I will have to dig in and see if white on black data matrix is supported by library used by this plugin.

**Comment by macdonst** [comment]
#411

**Comment by Vane101** [comment]
Hi,any update regarding this issue? I see that issue #411 points to issue #459 and issue #459 points to #411. Its a loop with no solution.  Really need help with reading  inverted DATA_MATRIX on iOS
