### ISSUE TITLE
Error when using plugin in vs 2015

### ISSUE THREAD

**Issue by radud** [phonegap/phonegap-plugin-barcodescanner#46]
Hi, 

I am trying to add this plugin in Visual Studio 2015 (cordova app) and I get this error: 
"Visual Studio was unable to parse plugin.xml. Please ensure plugin.xml exists and contain no errors." 

I can add the older version from: https://github.com/wildabeast/BarcodeScanner.git and this is parsed ok. 

Please advise, 
Radu

**Comment by jianyi0115** [comment]
I met the same issue, I due to the plugin.xml format error. you can download all file and add 
 xmlns:rim="http://www.blackberry.com/ns/widgets" to the the root <plugin . and add plugin for the folder in vs.

**Comment by nlsdg** [comment]
This has been fixed in PR #52 in August of 2015.

**Comment by jcesarmobile** [comment]
Thanks @nlsdg, closing the issue
