### ISSUE TITLE
iOS GS1 is not recognize

### ISSUE THREAD

**Issue by amoizesmailacn** [phonegap/phonegap-plugin-barcodescanner#460]
Does this plugin supports GS1 data bar? 

So far what's working in GS1 Databar is the is GS1-128.

To test this barcodes just go to this [barcode generator](http://barcode.tec-it.com/en/RSS14?data=0123456789012).

Thanks,
Moiz

**Comment by macdonst** [comment]
@amoizesmailacn no, it is not supported.
