### ISSUE TITLE
List of Barcodeformats to decode is not fault tolerant

### ISSUE THREAD

**Issue by ArneAlex** [phonegap/phonegap-plugin-barcodescanner#462]
Using this configuration for the barcode - scanner should allow one to scan
QR - Codes and PDF - 417 - Codes.

            {
                "preferFrontCamera" : false, // iOS and Android
                "showFlipCameraButton" : false, // iOS and Android
                "showTorchButton" : false, // iOS and Android
                "disableAnimations" : true, // iOS
                "resultDisplayDuration": 0, 
                "orientation" : 'landscape',
                "formats" : "QR_CODE, PDF_417", // default: all but PDF_417 and RSS_EXPANDED
            }

The plugin does not recognize the formats set, because of the space between QR_CODE and PDF_417.
Without notice to the user it reverts to default and is then unable to scan PDF_417.

This does only happen on Android devices as far as I can tell.

It should throw an error to inform the user of this wrong input for "formats". Otherwise one
could not tell, why there is no PDF_417 detection enabled, if both QR_CODE and PDF_417 are set.

Omitting the space leads to a perfectly normal behavior, like in this example:

            {
                "preferFrontCamera" : false, // iOS and Android
                "showFlipCameraButton" : false, // iOS and Android
                "showTorchButton" : false, // iOS and Android
                "disableAnimations" : true, // iOS
                "resultDisplayDuration": 0, 
                "orientation" : 'landscape',
                "formats" : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
            }

**Comment by macdonst** [comment]
#238
