### ISSUE TITLE
Error: Failed to fetch plugin QRCode” via registry.

### ISSUE THREAD

**Issue by lfreneda** [phonegap/phonegap-plugin-barcodescanner#463]
#### Steps to Reproduce

```cordova plugin add phonegap-plugin-barcodescanner --variable CAMERA_USAGE_DESCRIPTION=“Ler QRCode”```

#### Cordova CLI version and cordova platform version

    cordova --version: 6.2.0
    cordova platforms: Installed platforms: ios 4.1.1

#### Logs taken while reproducing problem

```
cordova plugin add phonegap-plugin-barcodescanner --variable CAMERA_USAGE_DESCRIPTION=“Ler QRCode”
Fetching plugin "phonegap-plugin-barcodescanner@3" via npm
Installing "phonegap-plugin-barcodescanner" for ios
Fetching plugin "QRCode”" via npm
npm ERR! addLocal Could not install /Users/macosx/lfreneda/work/orc/QRCode”
Error: Failed to fetch plugin QRCode” via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: ENOENT: no such file or directory, open '/Users/macosx/lfreneda/work/orc/QRCode”'
```

**Comment by lfreneda** [comment]
Forget about it D:

**Comment by adyz** [comment]
How did you fix this?

**Comment by jcesarmobile** [comment]
@adyz `phonegap-plugin-barcodescanner` was being installed correctly, but then another plugin called `QRCode` was failing to intall. It was probably a mistake in his `config.xml`

**Comment by lfreneda** [comment]
@adyz @jcesarmobile the problem is on the command line when I copied/pasted HAHAH `“` is not a valid character.
