### ISSUE TITLE
BarcodeScanner plugin on ios does not dismiss the scan screen after user does not allow the permission

### ISSUE THREAD

**Issue by jonathanli2** [phonegap/phonegap-plugin-barcodescanner#464]
### Expected Behaviour
On iOS cordova app, when user clicks "Do not allow" button on permission dialog, the scan screen should be closed and the cordova callback method should be called.

### Actual Behaviour
When user clicks "Do not allow" button, the scan screen is still opened, and user has to click cancel button to dismiss the scan screen, although user already decides to cancel the scan operation when user does not give the permission to use camera 
 
### Reproduce Scenario (including but not limited to)
Create a ios cordova app to use scan function as below

function myFunction(){
  cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      },
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          preferFrontCamera : true, // iOS and Android
          showFlipCameraButton : true, // iOS and Android
          showTorchButton : true, // iOS and Android
          formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          disableAnimations : true, // iOS
          disableSuccessBeep: false // iOS
      }
   );
}

And then call the method after the app installed on ios device. 

#### Steps to Reproduce
When first time running the ios app, when calling the scan method, it will pop up a dialog to ask user permission to use camera. Click "Do not allow" button to refuse the permission request. The scan operation should be cancelled.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 10.3.1
#### Cordova CLI version and cordova platform version

    cordova --version 
6.5.0
    cordova platforms
Cordova-ios 
4.3.1
#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner
6.0.6 "BarcodeScanner"

#### Sample Code that illustrates the problem

in index.html
        <br><br><br><button onclick="myFunction()">Click me</button>

in index.js
function myFunction(){
  cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      },
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          preferFrontCamera : true, // iOS and Android
          showFlipCameraButton : true, // iOS and Android
          showTorchButton : true, // iOS and Android
          formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          disableAnimations : true, // iOS
          disableSuccessBeep: false // iOS
      }
   );
}

**Comment by macdonst** [comment]
@jonathanli2 the cordova camera plugin doesn't dismiss the camera layer either so I'm going to move this to won't fix.
