### ISSUE TITLE
android 4.4 always success callback 

### ISSUE THREAD

**Issue by mikoSTAR** [phonegap/phonegap-plugin-barcodescanner#466]
### Expected Behaviour
After opening camera the success callback should be fired after we successfully scan QR code

### Actual Behaviour
After opening camera the success callback is always fired with data result as:
`Object {cancelled: true, text: "", format: ""} `

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version
cordova 6.5.0

#### Plugin version
6.0.6

#### Implementation Sample
```
     this.$window.cordova.plugins.barcodeScanner.scan((result) => {
        console.log(result)
        deferred.resolve(result);
     }, (err) => deferred.reject(err));
```

`Object {cancelled: true, text: "", format: ""} `

**Comment by victorsosa** [comment]
having a similar issue on android 4.4.4

**Comment by JoeChester** [comment]
+1

**Comment by telember** [comment]
I found solution for my ionic app 
[https://stackoverflow.com/a/42374060/3920648](https://stackoverflow.com/a/42374060/3920648)

**Comment by macdonst** [comment]
@mikoSTAR what is the start mode of your app?
