### ISSUE TITLE
README.md fix

### ISSUE THREAD

**Issue by shtaif** [phonegap/phonegap-plugin-barcodescanner#471]
Thanks for this amazing tool.
A little fix for the docs:

> The plugin creates the object cordova/plugin/BarcodeScanner with the method scan(success, fail).

Should be corrected to (changes in bold):

> The plugin creates the object cordova/**plugins**/**barcodeScanner** with the method scan(success, fail).

**Comment by jcesarmobile** [comment]
In fact, it should be `cordova.plugins.barcodeScanner`, with dots.
Can you send a Pull Request with the fix?

**Comment by shtaif** [comment]
Yes, that will my first Pull Request ever.
