### ISSUE TITLE
small barcode product are not scanning 

### ISSUE THREAD

**Issue by Bala893** [phonegap/phonegap-plugin-barcodescanner#477]
ionic v1
### Expected Behaviour
Need to scan all type of barcode

### Actual Behaviour
It only scan the medium size barcode 

When i am trying to scan the smaller size barcode like stapler box which one is similar to my product.i does not happen the out of focus in the phone camera
Please help :(

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
In both iPhone and Android

    cordova --version 6.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

#### Sample Code that illustrates the problem
 $cordovaBarcodeScanner.scan().then(function(Data) {
alert("We got a barcode\n" +
                   "Result: " + Data.text + "\n" +
                   "Format: " + Data.format + "\n" +
                   "Cancelled: " + Data.cancelled);

            console.log("Barcode Format -> " + Data.format);
            console.log("Cancelled -> " + Data.cancelled);
})

![img_1001](https://cloud.githubusercontent.com/assets/22056977/26683682/4536d73e-4702-11e7-9823-3e575d17fbc7.JPG)
![img_1002](https://cloud.githubusercontent.com/assets/22056977/26683685/49e9c390-4702-11e7-904f-08e5318ec12c.JPG)

**Comment by andersborgabiro** [comment]
If the camera can't auto-focus, that's the problem, not this plugin. Hold the phone further away.

The photos are too low-res/fuzzy to be possible to scan.

**Comment by sonicwong** [comment]
Agree with andersborgabiro.
I tested with your barcode sample, it can scan correctly(fast).
Please test your app on other device.

**Comment by macdonst** [comment]
I could scan those barcodes on my devices. I think you need a better quality camera.
