### ISSUE TITLE
PDF417 does not work on iOS

### ISSUE THREAD

**Issue by voodoodrul** [phonegap/phonegap-plugin-barcodescanner#478]
### Expected Behaviour
PDF417 barcodes should be decoded 

### Actual Behaviour
PDF417 barcodes are never detected by the scanner in iOS. Works properly on Android 

### Reproduce Scenario (including but not limited to)
Any attempt to call 
```
this.barcodeScanner.scan({formats : "PDF417"})
```

#### Steps to Reproduce
See sample code

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Plugin version 6.0.6
iOS 10.3.2
Android 7.1.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nexus 5X

#### Cordova CLI version and cordova platform version
cordova --version
7.0.1

Installed platforms:
  android 6.2.3
  ios 4.4.0

#### Plugin version

    phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"

#### Sample Code that illustrates the problem
```
this.barcodeScanner.scan({formats : "PDF417"}).then((barcodeData) => {
      // Success! Barcode data is here
    }, (err) => {
      // An error occurred
      console.error(err);
    });
```

#### Logs taken while reproducing problem
Nothing useful is logged to the ionic console when this happens

**Comment by macdonst** [comment]
Might be related to #489

**Comment by macdonst** [comment]
@voodoodrul can you try:

```
this.barcodeScanner.scan({formats : "PDF_417"}).then((barcodeData) => {
      // Success! Barcode data is here
    }, (err) => {
      // An error occurred
      console.error(err);
    });
```

**Comment by voodoodrul** [comment]
@macdonst I should have mentioned, but I did try a few variations of the type string. I tried "PDF417", "PDF_417", lowercase versions, and even adding a few other types before or after. I'll test again on the latest code.

**Comment by macdonst** [comment]
@voodoodrul I'm using this image as a test barcode:

https://en.wikipedia.org/wiki/PDF417#/media/File:Better_Sample_PDF417.png

Using the current version of the barcode scanner it works properly. One thing about the current version on iOS is that is pretty much ignores `formats` which is something PR #431 should fix.

**Comment by jeanpi-gomez** [comment]
@macdonst, This is the image example that you asked me for in PR #509 
![screen shot 2017-07-25 at 9 36 13 am](https://user-images.githubusercontent.com/19995934/28577631-e55f9874-711c-11e7-9e8e-1c54794d4e43.png)
It works correctly on Android but not in iOS.

Thanks

**Comment by jasj** [comment]
I have same problem works on Android perfect but on IOS only works with  normal text, this is an example of a backpart of costa rican card  ID,  on android we can read it perfect but in iOS something happen, with my id just read 12 chars with my partner card ID we only read 1.  


this is an image example [
![cedulashort](https://user-images.githubusercontent.com/5565617/28850889-55bf604e-76dc-11e7-83ea-21d77591e127.png)
](url)

**Comment by jasj** [comment]
cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + binaryAgent(result.text) + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
				
				console.log(binaryAgent(result.text))
      },
      function (error) {
          
      },
      {
          preferFrontCamera : false, // iOS and Android
          showFlipCameraButton : true, // iOS and Android
          showTorchButton : true, // iOS and Android
          torchOn: true, // Android, launch with the torch switched on (if available)
          saveHistory: false ,// Android, save scan history (default false)
          prompt : "Ubique la parte detraz de la cédula", // Android
          resultDisplayDuration: 3500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
          formats : "PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          orientation : "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
 
      }
   );

**Comment by jasj** [comment]
Is binary or text? ios version is giving problems with binary pdf417 codes due the encode, for example the next seq is read from a binary pdf using the android version of the plugin, but in apple code between 128 and 196 are taken  as control signals
19_0_53_152_55_63_167_32_149_156_114_180_66_157_79_141_79_116_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_96_75_246_69_75_210_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_127_181_74_131_32_155_73_98_119_75_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_222_35_153_233_6_208_54_225_53_237_48_21_3_52_148_48_59_147_18_160_209_51_224_3_208_49_233_2_2_48_103_241_255_143_19_149_44_171_183_156_140_162_149_71_171_118_152_117_42_60_157_252_108_236_84_85_157_56_163_106_173_95_64_77_119_54_119_153_249_147_202_65_167_114_163_67_143_65_162_187_166_113_47_156_186_52_176_10_124_98_64_152_64_182_115_171_191_129_144_29_156_219_7_73_33_187_78_165_108_255_45_16_186_106_221_187_12_80_149_37_236_95_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_50_32_160_119_94_108_146_32_95_188_97_139_83_146_166_152_186_159_83_10_120_129_229_144_229_67_97_103_111_81_66_171_82_64_66_112_198_107_139_229_143_207_86_92_120_81_115_98_69_163_187_162_156_57_121_176_205_160_4_118_79_116_179_99_85_125_163_188_157_172_193_133_96_18_91_208_129_86_69_100_127_50_112_188_126_29_251_20_84_243_37_239_93_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_160_0_15_147_18_160_209_51_224_3_208_0_223_0_39_48_4_

**Comment by jasj** [comment]
#519 also i had this problem

**Comment by voodoodrul** [comment]
@jasj There should be control chars in the rawText. I encode to base64 before transporting it in order to preserve these since they are critical for decoding AAMVA. AAMVA allows each issuer of a license to specify their own delimiter control char, so anything is fair game there.

**Comment by jasj** [comment]
@voodoodrul  i didnt get any trouble with iOS using raw text.  and base64 have the only normal chars, so it will work perfectly
