### ISSUE TITLE
Barcode scanner plugin is not scan qr code in android

### ISSUE THREAD

**Issue by arkomr** [phonegap/phonegap-plugin-barcodescanner#479]
I can able to opening scanner. I am not able to get the result. scanner is not scanning the qr barcode..

Anyone help will be Appreciated!!!!

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 4 & 6

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung

#### Cordova CLI version and cordova platform version

    cordova --version 7.0.1
    cordova platforms

#### Plugin version

    4,5,6

**Comment by macdonst** [comment]
@arkomr I can't reproduce this, do you have a sample QR Code we can use for testing?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by MUmer1124** [comment]
Scanner not reading QRCode on android, I use this version phonegap-plugin-barcodescanner@6.0.8.
