### ISSUE TITLE
plugin.xml still on 3.1.2 for 4.0.0 version

### ISSUE THREAD

**Issue by derwaldgeist** [phonegap/phonegap-plugin-barcodescanner#48]
I tried to download the plugin for a Meteor application which checks the version string in plugin.xml. As far as I can tell, plugin.xml still reports "3.1.2" for version "4.0.0", which lets the version check fail.

**Comment by stevengill** [comment]
You are correct. Just published 4.0.1 to fix that.

**Comment by derwaldgeist** [comment]
Great, thanks!
