### ISSUE TITLE
IOS app goes full screen after opening the barcode scanner

### ISSUE THREAD

**Issue by tokidoki11** [phonegap/phonegap-plugin-barcodescanner#481]
### Expected Behaviour
[IONIC v 2.2.2]On IOS when you open qr scanner, after scan the application goes full screen
I have set in config xml
<preference name="StatusBarOverlaysWebView" value="false" /> 

### Actual Behaviour
Application should not go full screen

### Reproduce Scenario (including but not limited to)
Scanning / canceling QR Code scanning

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
IOS 10.3.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 5s
#### Cordova CLI version and cordova platform version

    cordova --version = 6.5.0
    cordova platforms = 
Installed platforms:
  android 6.1.2
  ios 4.3.1

#### Plugin version
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"

**Comment by jcesarmobile** [comment]
What do you mean by "app goes full screen"?

**Comment by tokidoki11** [comment]
@jcesarmobile I mean the application is overlapping the status bar.

**Comment by jcesarmobile** [comment]
That is a bug on the statusbar plugin that was fixed long time ago, make sure you are using latest version
