### ISSUE TITLE
Options set don't affect the plugin

### ISSUE THREAD

**Issue by Alb93** [phonegap/phonegap-plugin-barcodescanner#482]
Expected Behaviour:
The barcode scanner adapts itself depending on options passed to the scan() method.

Actual Behaviour
No options (that are set) affect the barcode scanner

Sample Code that illustrates the problem

`import { BarcodeScanner, BarcodeScannerOptions } from '@ionic-native/barcode-scanner';this.barcodeScanner.scan( {
          preferFrontCamera : true, // iOS and Android
          showFlipCameraButton : true, // iOS and Android
          showTorchButton : true, // iOS and Android
          torchOn: true, // Android, launch with the torch switched on (if available)
          prompt : "Place a barcode inside the scan area", // Android
          resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
          formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          orientation : "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
          disableAnimations : true, // iOS
          disableSuccessBeep: false // iOS
      }).then(...`

Platform and Version
Android 7.0

(Android) What device vendor (e.g. Samsung, HTC, Sony...)
One Plus 3

Cordova CLI version and cordova platform version

    cordova --version: 7.0.1
    cordova platforms: Installed platforms: android 6.2.3 browser 4.1.0

Plugin version

    phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"
    cordova-plugin-barcodescanner 0.7.0 "BarcodeScanner"

**Comment by Alb93** [comment]
Solved by updating the entire project, unistalling and reinstalling the plugin.

**Comment by Kumar-Ankit** [comment]
Hi there, 

I tried by uninstall and install plugin again and agian. but still preferFrontCamera : true  is not working. It still opening back camera. 

Here are specifications. 

plugin version -  7.1.2
cordova version -  7.1.0

Here is code I am using. Please suggest what I am doing wrong. 

		   $cordovaBarcodeScanner.scan(
      function (result) {
         // alert("We got a barcode\n" +
//                "Result: " + result.text + "\n" +
//                "Format: " + result.format + "\n" +
//                "Cancelled: " + result.cancelled);

			callback(result.text);
                return false;
      },
      function (error) {
           callback(fail);
                return false;
      },
      {
          preferFrontCamera : true, // iOS and Android
          showFlipCameraButton : true, // iOS and Android
          showTorchButton : false, // iOS and Android
          torchOn: false, // Android, launch with the torch switched on (if available)
       
          prompt : "Place a barcode inside the scan area", // Android
          resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
         
          orientation : "portrait", // Android only (portrait|landscape), default unset so it rotates with the device
         
          disableSuccessBeep: false // iOS and Android
      }
   );

**Comment by jcesarmobile** [comment]
Please, don't comment on closed issues, if something is not working now, report a new issue.
