### ISSUE TITLE
Generate appxupload file using phonegap build

### ISSUE THREAD

**Issue by ramyam001** [phonegap/phonegap-plugin-barcodescanner#485]
Am currently using phonegap build to generate iOS and Android build(ARM).
Wanted to generate a windows build - .APPXUPLOAD file for windows store.
However in the phonegap site, I only see the option to generate a .APPX file.
How do I generate a .APPXUPLOAD file for the store and the the APPXBUNDLE file with dependencies/ .ps file to install on desktop ?

Phonegap cli used : 6.4.0

thanks

**Comment by jcesarmobile** [comment]
This repo is for barcode plugin, for Phonegap build issues you should report them on https://github.com/phonegap/build/issues.
But this doesn't really looks like an issue, it's more like a question, so you should probably ask on Phonegap forums.
https://forums.adobe.com/community/phonegap/build
