### ISSUE TITLE
Plugin has stopped working on iOS

### ISSUE THREAD

**Issue by Slugsie** [phonegap/phonegap-plugin-barcodescanner#488]
We have a Cordova app that is running on both Android and iOS, and includes a barcode scanning capability. It's worked fine until last week when the iOS version stopped scanning, the Android version still works fine. The app is developed on a Windows 7 machine in Visual Studio 15, then sent over the network to a Macbook running OSX El Capitan v10.11.6/XCode 8.1. The Barcode scanner plugin is v6.0.6.

We have tried uninstalling and reinstalling the plugin several times, with no luck. Unfortunately we're all Windows guys here and know very little about doing things on a Mac which is making our lives just that little bit harder. 

Can anyone offer any pointers or guidance?

**Comment by jcesarmobile** [comment]
Do you have a Content-Security-Policy meta tag in your index.html?

**Comment by Slugsie** [comment]
Yes:
`<meta http-equiv="Content-Security-Policy" content="default-src * gap://ready file:;default-src * 'unsafe-eval'; style-src 'self' 'unsafe-inline'; script-src * 'self' 'unsafe-inline' 'unsafe-eval'" />`

**Comment by Slugsie** [comment]
We ended up upgrading the Mac to 10.12 Sierra, and XCode to 8.3. This seems to have fixed things, at least for now. However as our MacBook is just about to go end-of-life and won't be supported by future upgrades that option may not help in future.
