### ISSUE TITLE
iOS: Cancel button not working

### ISSUE THREAD

**Issue by derwaldgeist** [phonegap/phonegap-plugin-barcodescanner#49]
On iOS, there is a cancel button showing up. Yet, it does not have any function, it won't react on my taps. What am I doing wrong?

**Comment by skudryk** [comment]
I have this issue too, "fail" handler is not called by plugin.

**Comment by hpelance** [comment]
I have same issue in iOS9. Camera and Cancel button is not working. Not able to return back on app screen. 'Fail' handler is not called by plugin. 'Success' is working.  Please help me out.

**Comment by vianneyniji** [comment]
+1

**Comment by cagedagain** [comment]
Also suffering from this on iOS9. It appears that no actions are being fired for the items within the toolbar.
