### ISSUE TITLE
Is it possible to keep scanning more than 1 item?

### ISSUE THREAD

**Issue by GiancarloGomez** [phonegap/phonegap-plugin-barcodescanner#492]
Just a question, but wanted to know if it is possible to continue scanning items that you can process in the background?

For instance, if we want to use it as a scanner to add items to a cart, we would like to not have the view closed until the user makes the request.

**Comment by jcesarmobile** [comment]
It's not possible at the moment

This is a duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/122
