### ISSUE TITLE
WebContentsDelegate::CheckMediaAccessPermission: Not supported on andriod

### ISSUE THREAD

**Issue by RaiserWeb** [phonegap/phonegap-plugin-barcodescanner#495]
White screen appearing on android device (Galaxy s7) on scan init

Console error:
I/chromium: [INFO:CONSOLE(11)] "URL.createObjectURL(stream) is deprecated! Use elem.srcObject = stream instead!", source: file:///android_asset/www/js/vendor.js (11)

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
