### ISSUE TITLE
Plugin not working...

### ISSUE THREAD

**Issue by Jamal2001** [phonegap/phonegap-plugin-barcodescanner#496]
I did this plugin as described in readme.md, i followed everything, i added gradle to config.xml and permission to internet, camera and files.. it works fine on phonegap Developer App.. but whenever I compile it online on www.build.phonegap.com into an apk... when i click the button it does nothing... Please help me

**Comment by jcesarmobile** [comment]
Did you add the plugin to your config.xml?

**Comment by Jamal2001** [comment]
Yes i did

**Comment by Jamal2001** [comment]
oh no i double checked config.xml and its not there but its folder is in plugins folder...

What should i add to config.xml on phonegap build to add the plugin???

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.

**Comment by jcesarmobile** [comment]
@Jamal2001 you should add this to your config.xml

`<plugin name="phonegap-plugin-barcodescanner" spec="~6.0.8" />`

**Comment by Jamal2001** [comment]
@jcesarmobile thanks but i already solved it... the problem was that i had 2 scanner plugins. This and a qr code scanner so it duplicated the camera preference for android
