### ISSUE TITLE
Subscribe button 

### ISSUE THREAD

**Issue by paulkavs** [phonegap/phonegap-plugin-barcodescanner#497]
Currently the subscribe button does nothing when you select it.

**Comment by jcesarmobile** [comment]
which button?

**Comment by paulkavs** [comment]
I am trying to subscribe to an open defect to get notified when something new  has been posted. 
When you click on the Subscribe button, nothing happens: 

![image](https://user-images.githubusercontent.com/5006519/27860533-f5ca1c82-6174-11e7-87b4-431680550e65.png)

On a github page that has Subscribe setup you will see the following when the button is pressed:

![subscribe](https://user-images.githubusercontent.com/5006519/27860512-e3e1fa62-6174-11e7-8733-0b7d66822184.PNG)

**Comment by macdonst** [comment]
@paulkavs that's not a problem with the plugin. You should take that up with github. Perhaps some browser extension you have installed prevents it from working.
