### ISSUE TITLE
App wont build or compile

### ISSUE THREAD

**Issue by Jamal2001** [phonegap/phonegap-plugin-barcodescanner#498]
I installed the plugin on config.xml with this: 
    <plugin name="phonegap-plugin-barcodescanner" source="npm"/>
but when i went to build.phonegap.com to compile it i get an error on android here is all the log:

Build Date: 2017-07-05 10:46:34 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.2" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-battery-status@~1.1.1" via npm
Installing "cordova-plugin-battery-status" at "1.1.2" for android
Fetching plugin "cordova-plugin-camera@~2.1.1" via npm
Installing "cordova-plugin-camera" at "2.1.1" for android
Fetching plugin "cordova-plugin-media-capture@~1.2.0" via npm
Installing "cordova-plugin-media-capture" at "1.2.0" for android
Fetching plugin "cordova-plugin-file" via npm
Installing "cordova-plugin-file" at "4.3.3" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" at "1.1.0" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Fetching plugin "cordova-plugin-console@~1.0.2" via npm
Installing "cordova-plugin-console" at "1.0.7" for android
Fetching plugin "phonegap-plugin-barcodescanner" via npm
Installing "phonegap-plugin-barcodescanner" at "6.0.6" for android
Dependent plugin "cordova-plugin-compat" already installed on android.
Subproject Path: CordovaLib
Fetching plugin "cordova-plugin-contacts@~2.0.1" via npm
Installing "cordova-plugin-contacts" at "2.0.1" for android
Fetching plugin "cordova-plugin-device@~1.1.1" via npm
Installing "cordova-plugin-device" at "1.1.6" for android
Fetching plugin "cordova-plugin-device-motion@~1.2.0" via npm
Installing "cordova-plugin-device-motion" at "1.2.5" for android
Fetching plugin "cordova-plugin-device-orientation@~1.0.2" via npm
Installing "cordova-plugin-device-orientation" at "1.0.7" for android
Fetching plugin "cordova-plugin-dialogs@~1.2.0" via npm
Installing "cordova-plugin-dialogs" at "1.2.1" for android
Plugin "cordova-plugin-file" already installed on android. Making it top-level.
Fetching plugin "cordova-plugin-file-transfer@~1.5.0" via npm
Installing "cordova-plugin-file-transfer" at "1.5.1" for android
Dependent plugin "cordova-plugin-file" already installed on android.
Fetching plugin "cordova-plugin-geolocation@~2.1.0" via npm
Installing "cordova-plugin-geolocation" at "2.1.0" for android
Fetching plugin "cordova-plugin-globalization@~1.0.3" via npm
Installing "cordova-plugin-globalization" at "1.0.7" for android
Fetching plugin "cordova-plugin-inappbrowser@~1.3.0" via npm
Installing "cordova-plugin-inappbrowser" at "1.3.0" for android
Fetching plugin "cordova-plugin-media@~2.2.0" via npm
Installing "cordova-plugin-media" at "2.2.0" for android
Dependent plugin "cordova-plugin-file" already installed on android.
Fetching plugin "cordova-plugin-network-information@~1.2.0" via npm
Installing "cordova-plugin-network-information" at "1.2.1" for android
Fetching plugin "cordova-plugin-splashscreen@~3.2.1" via npm
Installing "cordova-plugin-splashscreen" at "3.2.2" for android
Fetching plugin "cordova-plugin-statusbar@~2.1.2" via npm
Installing "cordova-plugin-statusbar" at "2.1.3" for android
Fetching plugin "cordova-plugin-vibration@~2.1.0" via npm
Installing "cordova-plugin-vibration" at "2.1.5" for android
Plugin with alternate id cordova-plugin-statusbar is already fetched, so installing it instead of org.apache.cordova.statusbar
Plugin "cordova-plugin-statusbar" already installed on android.
Fetching plugin "cordova-plugin-qrscanner" via npm
Installing "cordova-plugin-qrscanner" at "2.5.0" for android
Dependent plugin "cordova-plugin-compat" already installed on android.
Subproject Path: CordovaLib
Plugin with alternate id cordova-plugin-network-information is already fetched, so installing it instead of org.apache.cordova.network-information
Plugin "cordova-plugin-network-information" already installed on android.
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareBarcodescannerLibrary
:prepareComAndroidSupportAppcompatV72310Library
:prepareComAndroidSupportSupportCompat2600Alpha1Library
:prepareComAndroidSupportSupportCoreUi2600Alpha1Library
:prepareComAndroidSupportSupportCoreUtils2600Alpha1Library
:prepareComAndroidSupportSupportFragment2600Alpha1Library
:prepareComAndroidSupportSupportMediaCompat2600Alpha1Library
:prepareComAndroidSupportSupportV42600Alpha1Library
:prepareComJourneyappsZxingAndroidEmbedded330Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest/project/AndroidManifest.xml:31:5-90 Error:
	Element uses-permission#android.permission.CAMERA at AndroidManifest.xml:31:5-90 duplicated with element declared at AndroidManifest.xml:20:5-65
/project/AndroidManifest.xml:32:5-85 Error:
	Element uses-feature#android.hardware.camera at AndroidManifest.xml:32:5-85 duplicated with element declared at AndroidManifest.xml:22:5-84
/project/AndroidManifest.xml Error:
	Validation failed, exiting

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processDebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.742 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/AndroidManifest.xml:31:5-90 Error:
	Element uses-permission#android.permission.CAMERA at AndroidManifest.xml:31:5-90 duplicated with element declared at AndroidManifest.xml:20:5-65
/project/AndroidManifest.xml:32:5-85 Error:
	Element uses-feature#android.hardware.camera at AndroidManifest.xml:32:5-85 duplicated with element declared at AndroidManifest.xml:22:5-84
/project/AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by Jamal2001** [comment]
Anyone help?!

**Comment by stevesum** [comment]
I guess this is because you use BarcodeScanner and QRScanner plugin together. Both try to add camera permissions into the AndroidManifest.xml what cause the android.permission.CAMERA and android.hardware.camera is duplicated. 

The best if you use only one camera plugin, or you have to modify the plugin.xml one of them to remove this uses-feature and uses-permission.

As I see the merging of the plugin xml files have some problem in the cordova itself.

**Comment by Jamal2001** [comment]
Oh so in order to fix it i must remove the qr scanner plugin and remove one of these:

1) android.hardware.camera
2) android.permission.CAMERA

Is this right?

**Comment by stevesum** [comment]
remove both of them from the platform/android/android.json
and add the qr scanner plugin again.

But the best (if the qr scanner plugin already in your plugins folder) just
open the plugin.xml from there, and remove this two lines from that:
<uses-permission android:name="android.permission.CAMERA"
android:required="false" />
<uses-feature android:name="android.hardware.camera"
android:required="false" />

After that any time you build the platform will work.

2017-07-10 8:37 GMT+02:00 Jamal2001 <notifications@github.com>:

**Comment by Jamal2001** [comment]
I dont want the qr scanner plugin so can i remove it all?

**Comment by stevesum** [comment]
of course that is a solution too. If you don't need that, just remove and
the problem will solved.

2017-07-10 8:48 GMT+02:00 Jamal2001 <notifications@github.com>:

**Comment by Jamal2001** [comment]
Ok i will try it and if it works that will be a HUGE THANKS ❤️

**Comment by Jamal2001** [comment]
Thanks alot man you are my hero ❤️ It finally worked 🌹

**Comment by cristianizzo** [comment]
I have the same issue and after removed the 2 line of code 

`
<uses-permission android:name="android.permission.CAMERA" android:required="false" />
<uses-feature android:name="android.hardware.camera" android:required="false" />
`

I get this error

`error: cannot find symbol
                        intentScan.putExtra(Intents.Scan.SHOW_FLIP_CAMERA_BUTTON, obj.optBoolean(SHOW_FLIP_CAMERA_BUTTON, false));
`
