### ISSUE TITLE
Unable to get the scanned data in Raw bytes format using phonegap-plugin-barcodescanner

### ISSUE THREAD

**Issue by sridharlsn31** [phonegap/phonegap-plugin-barcodescanner#499]
HI guys,

   I had integrated this plugin in my application as described in the readme.md file, i have followed all the steps. Also am able to scan the QR code's or Barcode's successfully both from Android and iOS as well. In the successful scanned scenario am able to get(see) the Result, which contains the Result Text , Format and cancelled status. 
Here instead of the Result Text i need the Raw bytes of the QR code or Barcode. Could you please any one help me on this issue.

Thank you in advance !!! 

Best Regards,
Sridhar Etikala

**Comment by macdonst** [comment]
@sridharlsn31 sorry this plugin does not support the returning of the raw bytes of the scan result.

**Comment by sridharlsn31** [comment]
Thank you responding Macdonst. Could you please suggest any solution to achieve this.

Thank you in advance !!!

Best Regards,
Sridhar Etikala
