### ISSUE TITLE
Changes in .java files don't apply

### ISSUE THREAD

**Issue by binoculars88** [phonegap/phonegap-plugin-barcodescanner#50]
I want to change the Barcode scanner plugin for Cordova a bit, so forked it and changed something rather simple for testing purposes.

On line 87 of URIResultHandler.java, I changed the result_uri to result_text . This way, when I would scan a URL, the information would say I scanned plain text.

Then, I added this plugin to my Ionic project, using cordova plugin add https://github.com/binoculars88/phonegap-plugin-barcodescanner .

Browsing to the files in my text editors does show my edits. But... when I run the application on my device, it keeps saying "URL Found".

It's like my changes don't apply... Anyone knows what to do?
I've tried removing android platform and reinstalling the plugin, but that didn't work.

Update:
I've tried changing the text itself in the strings.xml file, just for testing.
I've noticed that this indeed needs a remove and re-add of the platform. After that, the text is changed.

So changes in strings.xml do apply, but the original problem remains: changes in a .java file don't seem to apply.

The ultimate goal of this testing, is to make the duration time after a code is scanned (and the result text is shown) smaller. In CaptureActivity.java, I've changed DEFAULT_INTENT_RESULT_DURATION_MS = 1500L to DEFAULT_INTENT_RESULT_DURATION_MS = 15L , but the duration time stays the same, even after removing and re-adding android platform.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
