### ISSUE TITLE
Slow scan?

### ISSUE THREAD

**Issue by kenedzel** [phonegap/phonegap-plugin-barcodescanner#500]
Im trying to use this library in Ionic 2 Framework, but whenever I am trying to scan a barcode or a QR code, it takes too much time before it reads its data.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by coolbeatz71** [comment]
Hello @macdonst i am facing the same problem with the phonegap-plugin-barcodescanner in android it is too slow, its taking about 2 minutes for scanning a qr code. but in window phone its so quick

**Comment by IvanDreamer** [comment]
Same issue.
