### ISSUE TITLE
phonegap barcode scanner not working.

### ISSUE THREAD

**Issue by jo-hk** [phonegap/phonegap-plugin-barcodescanner#502]
i'm new to phonegap. wanna make an app scanning barcode with my cell phone's camera. failed to do so. please help. thanks.

have added plugin in phonegap:
<plugin name="phonegap-plugin-barcodescanner" />
<preference name="android-build-tool" value="gradle" />

on phonegap build seems ok:
Plugin	Source	Version	Installed	Latest	Platforms
cordova-plugin-inappbrowser   	npm	~1.7.1	1.7.1	n/a	android,ios,winphone
phonegap-plugin-barcodescanner   	npm	*	6.0.7	n/a	android,ios,winphone

my code index.html belows:
<!DOCTYPE html>
<html>
<head>
<script>
cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      },
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          preferFrontCamera : true, 
          showFlipCameraButton : true,
          showTorchButton : true, 
          torchOn: true, 
          prompt : "Place a barcode inside the scan area", 
          resultDisplayDuration: 500, 
          formats : "QR_CODE,PDF_417", 
          orientation : "landscape", 
          disableAnimations : true, 
          disableSuccessBeep: false 
      }
   );</script>
</head>
<body>
<button click="scan()">Click me</button>
</body>
</html>

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
