### ISSUE TITLE
AllowBackup is set to true.

### ISSUE THREAD

**Issue by GeFurtuoso** [phonegap/phonegap-plugin-barcodescanner#503]
When trying to set the allowBackup to false in the ionic config.xml, it is conflicting with what is coming by default in the plugin. Any solution to this case?

Error: Attribute application@allowBackup value=(false) from AndroidManifest.xml :5:18-45 is also present at [:barcodescanner:] AndroidManifest.xml:12:9-35 value=(true).

**Comment by macdonst** [comment]
@GeFurtuoso what version of the plugin are you using? The allowBackup value was removed.
