### ISSUE TITLE
Can not open project in Visual Studio 2017

### ISSUE THREAD

**Issue by JanMisker** [phonegap/phonegap-plugin-barcodescanner#504]
I am adding windows support to an existing Cordova app with this barcodescanner plugin.
In Visual Studio 2015 everything works fine, I can open the app, compile, debug & run on emulator and device.

But when I opened that same project on Visual Studio 2017, I get this error:

`..\..\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=BC8A1FFA-BEE3-4634-8014-F334798102B3
`
(the link goes nowhere).

cordova-windows 5.0.0
phonegap-plugin-barcodescanner 6.0.5

**Comment by kumboleijo** [comment]
I'm facing the same issue

**Comment by nlsdg** [comment]
Don't think it's supported. See https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects

Windows Store/Phone apps: Projects for Windows Store 8.1 and 8.0, and Windows Phone 8.1 and 8.0 are not supported in Visual Studio 2017. To maintain these apps, continue to use Visual Studio 2015. To maintain Windows Phone 7.x projects, use Visual Studio 2012.

**Comment by sherburne** [comment]
I'm already using the plugin for iOS and Android, and it works great. I'd like to use this plugin for a Windows 10 app built with VS2017. I can't use VS2015 because other plugins have moved away from that. Are there plans to migrate this to VS 2017?

**Comment by macdonst** [comment]
No plans as far as I know but PR's are always welcome.
