### ISSUE TITLE
Application crashes when using plugin with Windows 10

### ISSUE THREAD

**Issue by hoffmanjon** [phonegap/phonegap-plugin-barcodescanner#506]
I am trying to use this plugin but my test apps crash when trying to use it with a Windows 10 app.  Here is what I am doing

I created a new ionic 2 application and added the plugin using:
    _ionic plugin add phonegap-plugin-barcodescanner_
I then adding the following code to use the plugin

```
  scan() {
    this.message = "here"
    cordova.plugins.barcodeScanner.scan(
      function (result) {
          this.message = "We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled; 
      },
      function (error) {
        this.message = error
      
      },
     {
          preferFrontCamera : true, // iOS and Android
          showFlipCameraButton : true, // iOS and Android
          showTorchButton : true, // iOS and Android
          torchOn: true, // Android, launch with the torch switched on (if available)
          prompt : "Place a barcode inside the scan area", // Android
          resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
          formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          orientation : "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
          disableAnimations : true, // iOS
          disableSuccessBeep: false // iOS
      }
   ); 
  }
```

When I press the button to call the scan method the whole application crashes.  I did some debugging, which was basically just commenting out code until it stopped crashing to figure out what was causing the crash and it appears that the issue is in line 461:

`return capture.initializeAsync(captureSettings);`

In the documentation for the MediaCapture class (https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture#Windows_Media_Capture_MediaCapture_InitializeAsync) it does say that the initializeAsync() initializer should be called from the main UI thread.  

I believe this is an issue with the plugin since I am using the example code right from the README.  I do see that the options are for iOS and Android so I also tried setting the options to null but that did not change anything.  I also made sure that the Windows Media Play (Movies & TV) and the Media Feature Pack were both installed.  I run the test app like this:

ionic run windows --archs=x64

I did test this code on my development machine and on two separate Windows 10 tablets.  On my development machine I am running Windows 10 Enterprise version 1607 OS build 14393.1480.  On my tablets I am running Windows 10 Pro version 1703 OS Build 15063.483

Here is the information about my ionic environment:

```
cordova CLI: 6.5.0
Ionic Framework Version: 3.5.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.0.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.1
Xcode version: Not installed
```

Thanks,

**Comment by Fuchur84** [comment]
This may be the same as what I have experienced. It is just happening for the latest production build.
I get this debug notice: The program "[13216] WWAHost.exe" has been closed with the code -1073741819 (0xc0000005) 'Access violation'.

(translated from German: "Das Programm "[13216] WWAHost.exe" wurde mit Code -1073741819 (0xc0000005) 'Access violation' beendet.)

Any idea what is going on there? I do not get any other information about the crash.
It worked before (still runs on for instance build 14393.1066 (still have a smartphone on that build and it works there) and I am quite sure it runs on 15063.540 (it still ran a two weeks ago)) but very likely after the last update to Build 15063.608 it seems to be a problem.

Best regards and thank you very much for looking into it in advance :).
Fuchur
