### ISSUE TITLE
How do I bypass the Alert "Cancelled" Button?

### ISSUE THREAD

**Issue by giemiranda** [phonegap/phonegap-plugin-barcodescanner#507]
### Expected Behaviour
What I want to do is, I want to changed the alert message when the "Cancelled" button is tapped. Different Alert message from Scanned and Another Alert for cancelled.

### Actual Behaviour
Same alert message pops up when cancelled is tapped. Minus the barcode type and code.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 5s and iPad 4th Gen

**Comment by jcesarmobile** [comment]
In the success callback check `result.cancelled` and do whatever you want if it's true, or another thing if it's false
