### ISSUE TITLE
Is there any way to disable the beep in android??

### ISSUE THREAD

**Issue by EloiRodriguezGaxas** [phonegap/phonegap-plugin-barcodescanner#508]
I've been searching for the beep sound without any success. 

Has anyone gotten rid of the sound?

Thanks!!

**Comment by macdonst** [comment]
@EloiRodriguezGaxas it's possible to do but sending in a PR would be the quickest way to get this resolved. In the BarcodeScanner.java class you'd need to do pretty much the same this as this PR:

https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/505/files

Where you use `Intents.Scan.BEEP_ON_SCAN` to turn the beep on or off.
