### ISSUE TITLE
PDF_417 format not being read on iOS

### ISSUE THREAD

**Issue by jeanpi-gomez** [phonegap/phonegap-plugin-barcodescanner#509]
#### Issue
I'm using this plugin to read the barcode on US drivers' licenses and extract some information, for android it worked like a charm, the problem is when you try to use it on iOS, it doesn't read the barcode, seems like it doesn't recognize the format. According to PR-431 (https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/431) this problem was resolved, still it doesn't work on iOS.

#### Platform and Version
iOS 10.3.1
Android 6.2.3

#### Cordova CLI version and cordova platform version

    cordova --version 7.0.1
    cordova platforms android 6.2.3 && ios 4.4.0

#### Plugin version

    cordova plugin version 6.0.8

#### Sample Code that illustrates the problem

    cordova.plugins.barcodeScanner.scan(
        scanSuccess,
        scanError,
        {
          formats: 'PDF_417,CODE_128'
        }
      );
    }

    function scanSuccess (result) {
        console.log(result.format, result.text);
    }

**Comment by jamesyangf** [comment]
According to the documentation, I don't think they support PDF_417 format on iOS yet. We could ask them if they plan to support it soon.

**Comment by macdonst** [comment]
Please comment on #478 and give me an example image.

**Comment by lsaballo** [comment]
Despite the documentation , PDF_417 works fine on ios for me , but never did the same on android, I've tried with some phonegap-plugin-barcodescanner plugins's version like 6.0.6 and 7.1.0 , didn't works for me on android.

**Comment by lsaballo** [comment]
So frustrating, I can't find some post that really fix it.
