### ISSUE TITLE
Generated .gradle file invalid, parseInt takes wrong argument

### ISSUE THREAD

**Issue by zaubara** [phonegap/phonegap-plugin-barcodescanner#512]
### Expected Behaviour
Gradle build should work.

### Actual Behaviour
Crash in:
platforms/android/phonegap-plugin-barcodescanner/appname-barcodescanner.gradle' line: 3
Works when concatenating what looks like to be an array now;
`if (cdvMinSdkVersion == null || Integer.parseInt('' + cdvMinSdkVersion) < minSdk ) {`
seems to work.

#### Steps to Reproduce
Remove android platform and re-add it completely.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
OnePlus

#### Cordova CLI version and cordova platform version

7.0.1

Installed platforms:
  android 6.2.3
  ios 4.4.0
Available platforms: 
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  osx ~4.0.1
  webos ~3.7.0

#### Plugin version

phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"

#### Logs taken while reproducing problem

FAILURE: Build failed with an exception.

* Where:
Script '/Users/<>/Documents/_git/<>/platforms/android/phonegap-plugin-barcodescanner/<>-barcodescanner.gradle' line: 3

* What went wrong:
A problem occurred evaluating script.
> No signature of method: static java.lang.Integer.parseInt() is applicable for argument types: (java.lang.Integer) values: [16]
  Possible solutions: parseInt(java.lang.String), parseInt(java.lang.String, int), print(java.lang.Object), print(java.io.PrintWriter)

**Comment by majid701** [comment]
Same issue! Anyone who fixed it?

**Comment by cyberbobjr** [comment]
same issue too :(

**Comment by runelk** [comment]
The empty string concatenation trick makes the app compile, but it might just be a quickfix to a problem further up the chain somewhere. For my Ionic app the file to be edited is in platforms/android/phonegap-plugin-barcodescanner/starter-barcodescanner.gradle

**Comment by jemc771** [comment]
Hi, I fixed that error modifying the code in 'phonegap-plugin-barcodescanner-master\src\android\barcodescanner.gradle' 

if (cdvMinSdkVersion == null || Integer.parseInt(cdvMinSdkVersion) < minSdk ) {
    ext.cdvMinSdkVersion = minSdk;
}

for this:

if (cdvMinSdkVersion == null) {
    ext.cdvMinSdkVersion = minSdk;
}
else{
	int num = cdvMinSdkVersion as Integer 
	if(num < minSdk ){
		ext.cdvMinSdkVersion = minSdk;	
	}
}

**Comment by macdonst** [comment]
@zaubara thanks, I just pushed a fix.
