### ISSUE TITLE
com.android.support Version Error

### ISSUE THREAD

**Issue by thetoad01** [phonegap/phonegap-plugin-barcodescanner#515]
When trying to use the barcodescanner with another plugin I was not able to build the cordova app.

After working through many errors it appears to come down to the fact that this (barcodescanner) pugin is using “com.android.support:support-v4:26.0.0-alpha1” (alpha version) which is interfering with another plugin using “com.android.support:appcompat-v7:25.3.1” (production version)

So, when the project is trying to merge all the settings from the all the plugins, due to inconsistency of the versions, errors occur.

Is it possible to get a new version of the plugin with the latest version of  “com.android.support:appcompat-v7:25.3.1”?

**Comment by macdonst** [comment]
See #480

**Comment by thetoad01** [comment]
Thanks for the link.  I ended up going into the file myapp/platforms/android/phonegap-plugin-barcodescanner/myapp-barcodescanner.gradle and changing the dependency to:
    compile 'com.android.support:appcompat-v7:+'

This appears to work.
