### ISSUE TITLE
BarcodeScanner.java  report errors

### ISSUE THREAD

**Issue by KitchenLiang** [phonegap/phonegap-plugin-barcodescanner#521]
![qq 20170803115202](https://user-images.githubusercontent.com/7965306/28905231-348d3db2-7842-11e7-9e6e-ec959a3378ed.png)

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
