### ISSUE TITLE
"the SD card is not accessible." issue for encoding (Ionic)

### ISSUE THREAD

**Issue by isWalter** [phonegap/phonegap-plugin-barcodescanner#527]
### Expected Behaviour

The encoded barcode can be saved to my device.

### Actual Behaviour

It shows "the SD card is not accessible". And there seems no options to set saving location as local storage?

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Sony (without sd card)

#### Plugin version

    cordova plugin phonegap-plugin-barcodescanner  v6.0.7

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/.github/ISSUE_TEMPLATE.md
