### ISSUE TITLE
Won't scan any Code 128 or Med-High density Code 39 codes on ios

### ISSUE THREAD

**Issue by jhuggart** [phonegap/phonegap-plugin-barcodescanner#53]
I've tested on several ios 8 devices and out of the six barcodes seen [here](http://www.barcodehq.com/images/BARCODES/barcodechart.gif), the only one that I can get to scan is the low density code 39. They scan just fine on android. 

I've compared the code in zxing/Code39Reader.cpp to the corresponding Code39 section in zxing-all-in-one.cpp and the important bits seem to be the same. Has anyone else experienced this?

**Comment by olimortimer** [comment]
Both low density barcodes work on our iPad Mini, however none of the barcodes work on our iPod Touch - it seems like the iPod Touch can't differentiate between the lines

**Comment by olimortimer** [comment]
@jhuggart I've done some digging, and found a fix - hopefully the fix works for your issue too:

https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/65#issuecomment-135750331

**Comment by jhuggart** [comment]
@olimortimer unfortunately, that did not do the trick. At least with an iPhone 6 Plus, I can still only scan low density code 39 barcodes.

**Comment by rakeshrockb** [comment]
Hi @jhuggart .  I'm in same boat as you. I'm unable to scan code 128 barcodes. Did you overcome this issue or have any recommendations for workarounds?. @olimortimer

**Comment by jhuggart** [comment]
@rakeshrockb I'm still experiencing this issue. I haven't had time to figure out a workaround. For the time being, we're just not allowing barcode scanning in our iOS App.

**Comment by olimortimer** [comment]
@rakeshrockb what Apple device are you using?  The fix I commited worked for me on an iPod Touch and iPhone 5S, which had issues before, but @jhuggart is still having problems with it on iPhone 6 Plus.

**Comment by rakeshrockb** [comment]
Thanks @jhuggart @olimortimer  I'm using IPhone 6 . What I noticed is it is working with Code 128 barcodes, but if it has more numbers, then my scanner is not recognizing. 

In barcodescanner.js file, I see this.format is initialized with some constants. Can I change the default value of "code_128": 16 to  "code_128": 32 ?. I'm not sure what it is doing, but my feeling is it only scans up to 16 digits. Thoughts?. Thanks so much again.

**Comment by rakeshrockb** [comment]
@olimortimer nm, changing this to 32 didn't work. I'll try this in android and will let you know.

**Comment by rakeshrockb** [comment]
@olimortimer  Finally working for me :). I had to change AVCaptureSessionPresetMedium to AVCaptureSessionPresetHigh CDVBarcodeScanner.mm file. 
@jhuggart  For some reason this is not automatically updating in ios folder after issuing  "cordova prepare" command. So make sure this is updated in right place and give it a try. Thank you both !.

**Comment by olimortimer** [comment]
@rakeshrockb that's the fix I posted further up the page :)

https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/65#issuecomment-135750331

**Comment by sunilhari9** [comment]
Barcode scanner is not working for both IOS and Android, if I am trying to scanner bar code generated with code 128.
I am generating barcode using following string "**10000019, BR 1234**"
