### ISSUE TITLE
The type or namespace name 'Windows' could not be found

### ISSUE THREAD

**Issue by PremkumarAgrawal** [phonegap/phonegap-plugin-barcodescanner#531]
`Reader.cs(17,11): error CS0246: The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]

Reader.cs(18,11): error CS0246: The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(19,11): error CS0246: The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(20,11): error CS0246: The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(21,11): error CS0246: The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(23,11): error CS0246: The type or namespace name 'ZXing' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(72,26): error CS0246: The type or namespace name 'MediaCapture' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(91,16): error CS0246: The type or namespace name 'IAsyncOperation<>' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(91,32): error CS0246: The type or namespace name 'Result' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(112,28): error CS0246: The type or namespace name 'Result' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(136,28): error CS0246: The type or namespace name 'Result' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(35,17): error CS0246: The type or namespace name 'BarcodeReader' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(45,17): error CS0246: The type or namespace name 'MediaCapture' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(50,17): error CS0246: The type or namespace name 'ImageEncodingProperties' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]
Reader.cs(60,17): error CS0246: The type or namespace name 'InMemoryRandomAccessStream' could not be found (are you missing a using directive or an assembly reference?) [F:\A_LHS_Projects\DynamicApp\DA_Code\AA\DynamicApp_V3\plugins\phonegap-plugin-barcodescanner\src\windows\lib\WinRTBarcodeReader.csproj]

Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1`

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/.github/ISSUE_TEMPLATE.md
