### ISSUE TITLE
Scan options are being ignored

### ISSUE THREAD

**Issue by mr-unicoder** [phonegap/phonegap-plugin-barcodescanner#534]
### Expected Behaviour
When passing options object with custom prompt message as the third parameter to scan method, I expect to see this message when scanning

### Actual Behaviour
Default message appears and my message is ignored

### Reproduce Scenario (including but not limited to)
Run the sample code below and check the prompt message

#### Platform and Version
Android 7

#### (Android) What device vendor
LG G5 SE

#### Cordova CLI version and cordova platform version
Cordova 6.3.1
Platform android 7

#### Plugin version
0.7.1

#### Sample Code that illustrates the problem

        cordova.plugins.barcodeScanner.scan(
            function (result) {
                }
                alert("We got a barcode\n" +
                    "Result: " + result.text + "\n" +
                    "Format: " + result.format + "\n" +
                    "Cancelled: " + result.cancelled);
            },
            function (error) {
                alert("Scanning failed: " + error);
            },
            {
                preferFrontCamera: false, // iOS and Android
                showFlipCameraButton: true, // iOS and Android
                showTorchButton: true, // iOS and Android
                torchOn: false, // Android, launch with the torch switched on (if available)
                prompt: "Custom Prompt Message", // Android
                resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
                formats: "QR_CODE",
                disableAnimations: true, // iOS
                disableSuccessBeep: false // iOS and Android
            }
        );

**Comment by mr-unicoder** [comment]
Any help please ?

**Comment by jcesarmobile** [comment]
Are you really using 0.7.1 version of the plugin? that's from 2013, that features weren't available by then

**Comment by mr-unicoder** [comment]
This is really weird !!
Visual studio installed version 0.7.1 I don't know why, I reinstalled the plugin and now version 6.0.8 is installed and it's working fine,
sorry for the inconvenience.
