### ISSUE TITLE
Unable to translate "Cancel" button on iOS

### ISSUE THREAD

**Issue by bedinsky** [phonegap/phonegap-plugin-barcodescanner#536]
### Expected Behaviour

I woud like to translate text "Cancel" displayed on button to cancel scan on iOS with the same language of the device

### Actual Behaviour

I did not found the way to translate such button

I've a look in CDVBarcodeScanner.mm code and I did not see any particular text associated to cancel button

`    id cancelButton = [[[UIBarButtonItem alloc]
                       initWithBarButtonSystemItem:UIBarButtonSystemItemCancel
                       target:(id)self
                       action:@selector(cancelButtonPressed:)
                       ] autorelease];
`

### Reproduce Scenario (including but not limited to)

Common plugin usage

#### Steps to Reproduce

use the plugin
scan valid code on a device with iOS having Italian language
English text displayed "Cancel"

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS platform, all versions affected

#### Cordova CLI version and cordova platform version

    cordova --version

     6.4.0

    cordova platforms

    Installed platforms:
      android 6.1.0
      ios 4.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

    phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"

#### Sample Code that illustrates the problem

basic example is OK

#### Logs taken while reproducing problem

no logs

**Comment by jcesarmobile** [comment]
This is not a plugin problem but a project problem, you have to configure your project to support Italian.
The cancel button is a system button and will only be translated if your project support that language.
You have to write this on the info.plist to support more languages:

      ```
<key>CFBundleLocalizations</key>
      <array>
          <string>it</string>
          <string>otherlanguagecode</string>
      </array>
```

You can try to add it with edit-config tag on config.xml or with a plugin

**Comment by bedinsky** [comment]
Thank you for quick answer !
I have found out that [edit-config doesn't work with plist files ](https://issues.apache.org/jira/browse/CB-12070), I'll try a plugin

**Comment by jcesarmobile** [comment]
I think that issue is out of date, it's working fine for me on Cordova CLI 6.5.0 and Cordova CLI 7.0.1
