### ISSUE TITLE
Minimum required android and ios versions

### ISSUE THREAD

**Issue by bharatmohan1994** [phonegap/phonegap-plugin-barcodescanner#538]
I have an app using the plugin cordova-plugin-BarcodeScanner version 6.0.8 of the plugin, and cordova 7.0.0.

I've tested the application in android (SDK 23) and ios (10.0).It works fine.
I am targeting to deploy the same in all android api's greater than 14 and ios 4.x and above.
I couldn't find any specifications regarding the same in any of the documentations.
I've to make sure the app works fine in all the target devices before deployment.Could someone help me with this.

Thanks.

**Comment by macdonst** [comment]
@bharatmohan1994 Apache Cordova itself supports Android 4.4 and up as well as iOS 9.0 and up.
