### ISSUE TITLE
Resize camera window

### ISSUE THREAD

**Issue by seaBass3** [phonegap/phonegap-plugin-barcodescanner#539]
Can the camera window be resized with this plugin or can html be superimposed onto the the camera?  My app will have a lists at the bottom the users will be checking items off by scanning barcodes.  So I would like to have the top half of the window the camera window and below it the lists of items they need to scan.

**Comment by Simerjit-developer** [comment]
Are you able to fix the camera size?

**Comment by macdonst** [comment]
@seaBass3  it's not possible right now. We are doing some work on the media streams API and hope to be able to support it in the future.

**Comment by nicks258** [comment]
@Simerjit-developer are u able to solve this??
