### ISSUE TITLE
hint-text and beep config

### ISSUE THREAD

**Issue by EuAndreh** [phonegap/phonegap-plugin-barcodescanner#54]
There should be an option to disable the "beep" that sounds when a barcode is scanned as well as the option to remove the "Place your barcode inside the viewfinder rectangle to scan it" text.

Taken from the [old repo](https://github.com/wildabeast/BarcodeScanner/issues/127).

The ngCordova [documentation](http://ngcordova.com/docs/plugins/barcodeScanner/) links to the old repo. Should I open an issue in ngCordova repo to fix the link?

**Comment by jamesla** [comment]
+1 would be great to be able to disable the beep

**Comment by someidiot** [comment]
+1 the beep makes this completely unusable for me

**Comment by jamesla** [comment]
+1

**Comment by cookieguru** [comment]
I was able to overwrite the beep sound with a silent ogg file of my own (effectively silencing it but not eliminating the audio playback) using a build hook:

```js
#!/usr/bin/env node

var fs = require('fs');

var rootdir = process.argv[2];

if(rootdir) {
	var filename = 'beep.ogg';
	if(fs.existsSync(filename)) {
		fs.rename(filename, 'platforms/android/res/raw/' + filename, function(e) {
			console.warn(e);
		});
	} else {
		console.warn(filename + ' does not exist');
	}
}
```
In config.xml:
```xml
<platform name="android">
	<hook type="before_compile" src="overwrite_beep.js" />
</platform>
```

**Comment by oodavid** [comment]
Beep disabling would be useful

**Comment by olimortimer** [comment]
+1

**Comment by roeycohen** [comment]
it is possible to set the hint-text to nothing:
```
cordova.plugins.barcodeScanner.scan(
      function (result) {}, 
      function (error) {},
      {
          "prompt" : "" // supported on Android only
      }
   );
```

**Comment by Slanman3755** [comment]
+1

**Comment by pom421** [comment]
I don't want to keep the beep too... What a pity that it is not customizable in the plugin...

However, following the @cookieguru 's idea, with Ionic 2, I have done : 

- create a silence.ogg (with Audacity, generate Silence, export in .ogg)
- ionic hoooks add, if you have not the hooks structure with after_prepare
- create a new file in hooks/after_prepare/030_overwrite_beep_scanner.js
```js
#!/usr/bin/env node

var fs = require('fs');

var rootdir = process.argv[2];

if (rootdir) {
    var filename = 'silence.ogg';
    var dirPart = __dirname + '/resources/';
    if(fs.existsSync(dirPart + filename)) {
        fs.createReadStream(dirPart + filename).pipe(fs.createWriteStream('platforms/android/res/raw/beep.ogg'));
    } else {
        console.warn(dirPart + filename + ' does not exist');
    }
}
```
- chmod 755 030_overwrite_beep_scanner.js
- copy silence.ogg in hooks/after_prepare/resources/

Hope it helps!

**Comment by yoann54** [comment]
For those who uses meteor I finaly found how to do that by just putting a new beep.ogg (silent of course) in a special top folder that meteor provide.

So first u have to create a folder named cordova-build-override, then inside create a platforms/android/res/raw folder and place ur new beep.ogg inside.

this url gave me the idea : https://documentation.onesignal.com/docs/customize-notification-sounds
