### ISSUE TITLE
Lacking NSCameraUsageDescription

### ISSUE THREAD

**Issue by andersborgabiro** [phonegap/phonegap-plugin-barcodescanner#540]
### Expected Behaviour

Approval from Apple.

### Actual Behaviour

Apple warns: "Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data. "

### Reproduce Scenario (including but not limited to)

Following the instructions in this documentation. Always fails.

I can find NSCameraUsageDescription in the Info.plist in the IPA, but it has no effect.

#### Steps to Reproduce

-"-

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

n/a

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

n/a

#### Cordova CLI version and cordova platform version

PhoneGap Build cli-7.0.1

#### Plugin version

6.0.8

#### Sample Code that illustrates the problem

        <config-file platform="ios" parent="NSCameraUsageDescription" overwrite="true">
            <string>The app needs access to the camera, to be able to read barcodes.</string>
        </config-file>

I also include this to be on the safe side:

    <plugin name="cordova-custom-config" />

#### Logs taken while reproducing problem

n/a

**Comment by jcesarmobile** [comment]
phonegap build has deprecated config-file tag, you can use edit-config now
we should update the docs

**Comment by andersborgabiro** [comment]
That explains it, yet odd that the IPA contains a setting.

If you update I'll verify right away (I need to get an app update out the door today :) ).

**Comment by wildabeast** [comment]
Note that the correct way to set this on PhoneGap Build is as follows;
```
<plugin name="phonegap-plugin-barcodescanner">
  <param name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes." />
</plugin>
```
I've updated the [docs](https://github.com/phonegap/phonegap-plugin-barcodescanner#phonegap-build-usage) to reflect this.

**Comment by andersborgabiro** [comment]
Yup. Noted and implemented :).
