### ISSUE TITLE
Disable flashlight at volume-buttons

### ISSUE THREAD

**Issue by christoph-schindler** [phonegap/phonegap-plugin-barcodescanner#546]
Is there an option like "DisableVolumeTorch" or something like this, to remove the flashlight-feature? I want the users to adjust the volume of the beep and not the light on / off.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by christoph-schindler** [comment]
### Expected Behaviour
The user wants to change the volume during the scan to hear the beep sound better

### Actual Behaviour
Volume buttons do not change the volume during scanning, but control the flash light

#### Steps to Reproduce 
Start scan and use volume up/down buttons

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android all Versions

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
All Android devices

#### Cordova CLI version and cordova platform version
All verions

#### Plugin version

    phonegap-plugin-barcodescanner 6.0.8

#### Sample Code that illustrates the problem
there is no option "disableVolumeTorch: true" to disable the flashlight-function for volume buttons
