### ISSUE TITLE
VIN barcodes problem

### ISSUE THREAD

**Issue by fttx** [phonegap/phonegap-plugin-barcodescanner#547]
Hi, i've got a feedback from a user using my app:

> Was trying out your app and server program. Was hoping to use it as a way to scan vehicle VIN barcodes and have it input into our program for vehicle repairs. Issue I have come up with is scanning chrysler VIN barcodes the program inputs the character I at the beginning of the VIN. Other barcode scanners correctly input the VIN without the I. Example to try yourself 
> ![image](https://user-images.githubusercontent.com/5663423/30600972-0d408770-9d61-11e7-9d31-0be62af782c5.png)
> So far this specific issue seems to be chrysler only VINs. 
> Any fix for this? Its the only thing preventing me from getting what I need from you otherwise great program. Thanks.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
