### ISSUE TITLE
Is it possible to add "barcode approved" text and label ontop of scan view

### ISSUE THREAD

**Issue by Mattporter0** [phonegap/phonegap-plugin-barcodescanner#548]
Is it possible to add a 2 second "barcode approved/declined" Notification over the top of the scan view. Keeping the scan view open ready for next barcode to be scanned

**Comment by jcesarmobile** [comment]
Not right now, there are an issue open about adding continuous scanning

**Comment by nicks258** [comment]
Did anyone find a solution for this?
