### ISSUE TITLE
Cordova barcode scanner does not scan pdf_417 format on us driving license..

### ISSUE THREAD

**Issue by rattangaurav** [phonegap/phonegap-plugin-barcodescanner#549]
My plugin version is 6.0.8 and cordova version is 7.0.1
The cordova barcode scanner does not work with pdf_417 code on us driving license even if i have mention the format in code.i am using this code.

this.options = {
			 "formats": "PDF_417,PDF417, QR_CODE, DATA_MATRIX, UPC_E, UPC_A, EAN_8, EAN_13, CODE_128, CODE_39, CODE_93, CODABAR, ITF"
		 };  
		 
				  this.barcodeScanner.scan(this.options).then((barcodeData) => {
			 // Success! Barcode data is here
			     alert(JSON.stringify(barcodeData));
			}, (err) => {
				// An error occurred//000032693375NCA6UL01
				alert(err);
			});  

it is not scanning pdf417 ..
can anyone help me with this issue?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
