### ISSUE TITLE
VIN barcodes problem

### ISSUE THREAD

**Issue by fttx** [phonegap/phonegap-plugin-barcodescanner#550]
### Expected Behaviour
The scanned text should be this: JHLRD77874C026456

### Actual Behaviour
The scanned text is this: IJHLRD77874C026456
(It adds the I character )

### Reproduce Scenario (including but not limited to)
It happens with Chrysler VIN barcodes like this:
![image](https://user-images.githubusercontent.com/5663423/30922082-64edb4fa-a3a8-11e7-873e-3fbcdce8ea3a.png)

#### Steps to Reproduce
Scan the barcode above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
I've tried on Android 7

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG

#### Cordova CLI version and cordova platform version
    cordova --version: 6.5.0
    cordova platforms: android 6.2.3

#### Plugin version
    phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"

#### Sample Code that illustrates the problem
    The same as the README.md full example

#### Logs taken while reproducing problem
    n/d

**Comment by blogui91** [comment]
Same problem here +1

**Comment by wildabeast** [comment]
I don't think this is a bug. VIN barcodes are actually just CODE_39 barcodes, and I'm pretty sure that the barcode you provided above does include the "I" character, as do all CODE_39-encoded VIN barcodes. For example load your image up into [this online barcode image reader](http://www.onlinebarcodereader.com/) -- it will include the "I" in the output. Some processors will probably "know" that this is a VIN barcode and remove the I -- but this reader doesn't explicitly support VIN barcodes and so reads it as a CODE_39 and returns the "I".

Closing -- feel free to open if you disagree :beers:

**Comment by AdrianBinDC** [comment]
Here's a RegEx string that will strip out the problematic "I" and give you what you need:

`[A-HJ-NPR-Z0-9]{17}`
