### ISSUE TITLE
Scanner returns empty string <android><bug>

### ISSUE THREAD

**Issue by julioaze** [phonegap/phonegap-plugin-barcodescanner#553]
### Expected Behaviour
Read an QR Code in tablet Android 4.1.0.
works fine smathphone Android 5.0 +

### Actual Behaviour
returns an empty string
does not request camera permission as in android 5 or higher

### Reproduce Scenario (including but not limited to)
Objective: Read a qrcode

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.1.0 (SDK 16)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy Tab 2 10.1" 

#### Cordova CLI version and cordova platform version
Cordova: 7.0.1
Cordova Platforms: Android 6.2.3

#### Plugin version
Plugin Version: 6.0.8

#### Sample Code that illustrates the problem
 ```
async scann(){
    this.options = {
        prompt : "Scann",
        formats : "QR_CODE",
        orientation : "portrait",
        preferFrontCamera : false,
        showFlipCameraButton : false
    }

    await this.barcodeScanner.scan(this.options).then((barcodeData) => {        
        this.scanData = barcodeData.text;
        console.log('QR Code: ' + this.scanData);
        this.storage.set('qrcode', this.scannData);
    }, (err) => {
        this.presentAlert('Scann Error.');
    });             
}
```

#### Logs taken while reproducing problem
console log returns empty

**It would be nice to have a list of compatible versions with the plugin**

**Comment by macdonst** [comment]
Sorry, we are not supporting Android 4.1.

**Comment by julioaze** [comment]
Hi macdonst.
What is the minimum supported version?
