### ISSUE TITLE
What is the minimum supported version?

### ISSUE THREAD

**Issue by julioaze** [phonegap/phonegap-plugin-barcodescanner#554]
Hello, I opened a issue on version 4.1 of Android, but unfortunately, the plugin does not support this version. What is the minimum Android version supported by the plugin?
Regards

**Comment by jcesarmobile** [comment]
@macdonst barcodescanner.gradle has default min version set to 15. 
plugin.xml and package.json don't have any cordova-android version restriction other than cordova > 3.0

We should document the min android version, configure the engines in plugin.xml and package.json and probably remove the gradle code and it creates more problems that it solves

**Comment by julioaze** [comment]
Thanks!
