### ISSUE TITLE
Customizing the BarcodeScanner

### ISSUE THREAD

**Issue by partII** [phonegap/phonegap-plugin-barcodescanner#555]
Is there any way to customize the scanner? I have been looking around for an answer, but can't find anything. I really want to make it more functional with buttons and additional text.

Like this:
[Dribbble](https://dribbble.com/shots/3583103-QR-Warehouse-scanner-Concept)

**Comment by wildabeast** [comment]
I don't think that kind of customization is exposed in terms of simple configuration. You'd have to dive into the nitty gritty native code and do this yourself.
