### ISSUE TITLE
Windows Mobile - Ionic - Preview stuck behind application

### ISSUE THREAD

**Issue by paulmorrishill** [phonegap/phonegap-plugin-barcodescanner#56]
When using the windows 8.1 version of the plugin while using the Ionic framework, the canvas element that the preview is rendered to is behind the content. 

The solution is to set a ```z-index``` on the canvas and the control elements so that it is in front of the content.

**Comment by vladimir-kotikov** [comment]
The issue was fixed in #62 and merged into master
