### ISSUE TITLE
Android Custom Scanner Apps

### ISSUE THREAD

**Issue by hasyeum001** [phonegap/phonegap-plugin-barcodescanner#563]
Yesterday , I made an android apps for QR or Bar code scanning using ZXing library. It works well on android 6.0 but not in another versions under 6.0. After using my scanner apps the user must restart their phone so they can use their camera on another apps.

Can someone help me? I really appreciate your help. (Sorry for my english)

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by nicks258** [comment]
Did any one find a solution for this?
