### ISSUE TITLE
Phone Gap Build not including as a plugin

### ISSUE THREAD

**Issue by BradKemp** [phonegap/phonegap-plugin-barcodescanner#573]
### Expected Behaviour
I have the below in my config.xml which I am expecting to include the plugin when phonegap builds my app. 
```
<plugin name="phonegap-plugin-barcodescanner">
  <param name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes." />
</plugin>
```

### Actual Behaviour
When I unpack the APK after building in phonegap build I do not see the  "assets\www\plugins\phonegap-plugin-barcodescanner" folder. There is a folder for each of the plugins except for this one. 

### Reproduce Scenario (including but not limited to)
Been trying since yesterday tried just including <plugin name="phonegap-plugin-barcodescanner" />
Have tried a couple android phones and  they do not scan or ask for permissions to scan (because the plugin is not there) 

#### Steps to Reproduce
1. Include the plugin with the above code in the config.xml and build an app on phonegap build. 
2. unpack the APK and see if the plugin was included. 
3. Try to scan with the app. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Current Phone gap

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Tried on one plus and another android phone (but plugin not in apk)
 
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version
None specified. 
    cordova plugin version | grep phonegap-plugin-barcodescanner

#### Sample Code that illustrates the problem
```
<plugin name="phonegap-plugin-barcodescanner">
  <param name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes." />
</plugin>
```

**Comment by jcesarmobile** [comment]
Do you have any phonegap version set in your config.xml?

**Comment by BradKemp** [comment]
No, I did not and turns out that was the issue. Thank you. 
<plugin name="phonegap-plugin-barcodescanner" version="6.0.5">
  <param name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes." />
</plugin>
