### ISSUE TITLE
After 60 scan, Bar code scan working stop

### ISSUE THREAD

**Issue by deepikajainvoloansys** [phonegap/phonegap-plugin-barcodescanner#575]
When i start scan bar code it is working perfectly, but when i scan 60 bar code after it stop working.
after that i have to kill app and restart app again.

**Comment by lucasverra** [comment]
provide more info please @deepikajainvoloansys

**Comment by jcesarmobile** [comment]
Closing as duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/370
