### ISSUE TITLE
On some android devices front camera is too dark to scan

### ISSUE THREAD

**Issue by GilbertLiddell** [phonegap/phonegap-plugin-barcodescanner#576]
### Expected Behaviour
We are wanting to scan QR codes using the front camera of an android tablet & have been conducting device testing using our cordova tablet app which was previously deployed on iPads, using the phonegap-plugin-barcodescanner plugin. 

### Actual Behaviour
On some android devices when the scanner opens the picture is too dark to scan QR codes, whereas on other android devices it is possible to scan the QR codes successfully in low light conditions

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Kodak Tablet 7

#### Cordova CLI version and cordova platform version

    cordova --6.1.1

#### Plugin version
6.0.8

#### Sample Code that illustrates the problem
Initialising with front camera active

**Comment by macdonst** [comment]
@GilbertLiddell have you considered add the `showTorchButton: true` option so the user can turn on the flash if things are too dark?

**Comment by jcesarmobile** [comment]
@macdonst he is talking about front camera, that one usually doesn't have flash.

I don't think we can do something to improve this issue, some devices have better cameras and can scan on worse conditions, and probably screen brightness might also be affecting the recognition

**Comment by macdonst** [comment]
@jcesarmobile ooof, oh yeah, speed reading too many issues today. There is nothing we can do about this issue. That device has a 2MP front camera which is not very good.
