### ISSUE TITLE
7.0.0 not loading at all. Android 8.0.0

### ISSUE THREAD

**Issue by Fever905** [phonegap/phonegap-plugin-barcodescanner#578]
Issue on Android 8.0.0 on Nexus 6P.  I have not tested on other phones yet.

Built with Phone Gap Build 7.0.1
PhoneGap (iOS / Android / Windows):
cli-7.0.1 (4.4.0 / 6.2.3 / 5.0.0)

Couple issues going on.  Everything was fine until Nov 1st, but I'm not certain what has changed.

Using 7.0.0 nothing happens at all, just doesn't load.  (What is the best way to debug this? Developer mode on the phone?)

~~Using 6.0.8 everything works up until the scan is complete and decoded, then the app gets reset.  I tried this in my full version app as well as the bare bones "Hello World" app.  Any advice?  Should I go back to a prior version?~~

6.0.8 is working perfect, so not sure on 7.0.0

**Comment by HellHound90** [comment]
Same here.
Using phonegap application developer it's working but after the release version builded with phonegap build it doesn't work on android devices.

**Comment by Fever905** [comment]
I switched to this one and everything is working both iOS 10 ad Android 8.0.0

Under the iOS platform in my config,xml i call it sed this for iOS..

```
<plugin spec="https://github.com/Telerik-Verified-Plugins/BarcodeScanner.git" source="git" >
<param name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes." />
</plugin>
```

**Comment by macdonst** [comment]
@Fever905 the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
