### ISSUE TITLE
PDF417 scanner not working fine in Android

### ISSUE THREAD

**Issue by Rindegastos** [phonegap/phonegap-plugin-barcodescanner#579]
### Expected Behaviour
The scanning of a PDF417 code in a document should work as good as in an iOS device.

### Actual Behaviour
In android the majority of times the scanner just does not recognize the PDF417 code. We tried in a lot of android devices like Samsung J3, Samsung S8 Huawei P9 all with Android 6 and up.

#### Steps to Reproduce
I am attaching two pdf417 codes that are scanned instantly in an ios device and are not scanned or recognized in any android device.
![pdf417 2](https://user-images.githubusercontent.com/29754848/33188371-216d60ca-d078-11e7-9d6e-f67998f1fb93.png)
![pdf417 1](https://user-images.githubusercontent.com/29754848/33188372-2197ff10-d078-11e7-8748-f0d81802a6bb.png)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6 and up.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung, Huawei

#### Cordova CLI version and cordova platform version

    cordova v7.1.0
    cordova platforms: android and ios

#### Plugin version

    cordova plugin version 7.0.0 and tested in 6.0.8 version too.

**Comment by macdonst** [comment]
@Rindegastos can you add your comment to #532
