### ISSUE TITLE
pdf 417 on android doesn't work

### ISSUE THREAD

**Issue by boomgetchopped** [phonegap/phonegap-plugin-barcodescanner#58]
pdf 417 does not scan on android.  The barcode is not recognized at all.

**Comment by boomgetchopped** [comment]
I looked into this some more.  I believe the issue is the underlying library (zxing) has pdf 417 disabled by default.  You have to specify the format when initiating the scan.  So is there a way to specify formats via the plugin?

**Comment by multilexus** [comment]
Yes, there is!

I got it to work on Android with PDF417 by adding the following code as 3rd line in my plugin's BarcodeScanner.java file inside scan function:

intentScan.putExtra("SCAN_FORMATS","CODE_39,CODE_93,CODE_128,DATA_MATRIX,ITF,CODABAR,EAN_13,EAN_8,UPC_A,QR_CODE,PDF_417");

After that i had to recompile the android platform code. Easy way to do it is to remove platform, then add platform and rebuild.

Cheers,
Alex $

**Comment by andreszs** [comment]
OR simply add
```
{
			SCAN_FORMATS: 'PDF_417'
}
```

as the third parameter of the cordova.plugins.barcodeScanner.scan() function.
