### ISSUE TITLE
How to exit the barscanner screen

### ISSUE THREAD

**Issue by nitishxp** [phonegap/phonegap-plugin-barcodescanner#580]
i am not able to exit the barcode scanner . I have to scan the qrcode then only it is exiting.

**Comment by giemiranda** [comment]
+1 on this question.

**Comment by alejandro-heredia-coderoad-com** [comment]
It'd be really useful to have a method to exit camera.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md
