### ISSUE TITLE
After Granting Access to camera, barcode scanner doesn't open.

### ISSUE THREAD

**Issue by giemiranda** [phonegap/phonegap-plugin-barcodescanner#581]
### Expected Behaviour
- 1st time to open the application
- When I click my button to "Scan"
- Grant Access pop up appears to grant access to Camera
- It should continue to scanner (open camera to scan)

### Actual Behaviour
- After granting access
- It doesn't continue to scanner (open camera to scan). It just stays on my page
- When I clicked again my "Scan" button, there's an alert that pops stating "Scanning Failed: scanner is still open etc....."
- I need to restart my application for me to use it like normal.

#### Steps to Reproduce
- normal function of scanning.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
- iOS 10, iOS 11

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
-Apple

#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by macdonst** [comment]
Please give a detailed reproduction scenario in #490
