### ISSUE TITLE
iPhone X - The cancel button is hidden behind the home indicator

### ISSUE THREAD

**Issue by woutderooms** [phonegap/phonegap-plugin-barcodescanner#583]
### Expected Behaviour

The cancel button should be easily reachable

### Actual Behaviour

The cancel button is hiding behind the home indicator

### Reproduce Scenario (including but not limited to)

Any iPhone X (in both orientations)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 11.2

**Comment by macdonst** [comment]
If anyone has an iPhone X I could use some help with this one.
