### ISSUE TITLE
Button for cancelling the barcode scan and closing the camera

### ISSUE THREAD

**Issue by alejandro-heredia-coderoad-com** [phonegap/phonegap-plugin-barcodescanner#584]
### Expected Behaviour

It's necessary to have a cancel button on-screen apart from the hardware back button to close the camera.

### Actual Behaviour

On Android, when the plugin opens the camera and you press the hardware back button, the event propagates, causing Ionic apps to trigger the back button on the view as well, causing unexpected view exits.

#### Steps to Reproduce

1. Start an Ionic2 app
2. Install the plugin
3. Call the scan method
4. Press the back button

#### Cordova CLI version and cordova platform version

    cordova --6.5
    cordova platforms android 6.2.1

#### Plugin version

Latest

**Comment by jcesarmobile** [comment]
For the back button problem
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/355

Not closing as a duplicate in case somebody wants to add the back button functionality

**Comment by macdonst** [comment]
@alejandro-heredia-coderoad-com you could set a boolean flag to let the app know you've entered the barcode scanner UI then check the value in your backbutton event handler.

**Comment by lulzzz** [comment]
I also have this problem.
The app just quits. Does not pause. It quits.

**Comment by jpike88** [comment]
@macdonst Seems to be a lot of inactivity here. Can someone make me a contributor so I can get these things sorted for everyone?

**Comment by jcesarmobile** [comment]
Anybody can contribute by sending PRs, you don't need to be a contributor to do that. After a few contributions macdonst will probably make you contributor.

**Comment by macdonst** [comment]
@jpike88 like @jcesarmobile said, sends some PR's first then we can worry about contributor status.

**Comment by 27garg** [comment]
Can anyone tell me how to add back button on a camera, rather than hardware have on it?
