### ISSUE TITLE
cordova.plugins undefined with phonegap-plugin-barcodescanner 7.0.0 but works with 6.0.5 using build.phonegap.com

### ISSUE THREAD

**Issue by mspiceland** [phonegap/phonegap-plugin-barcodescanner#586]
I'm a phonegap novice.  I happened to make the first app without specifying a version such that the latest version of phonegap-plugin-barcode scanner would be used.  At the time, it worked.  After rebuilding for the first time in a while, it stopped working.  Through debugging, reverting to the previous version seems to have resolved it for me.  I don't know if the documentation is outdated and I should be using a different function or if something changed that makes it no longer work on build.phonegap.com as before.

### Expected Behaviour
cordova.plugins.barcodeScanner and therefore cordova.plugins.barcodeScanner.scan() can be used.

### Actual Behaviour
cordova.plugins is undefined.

When I rebuilt the app, barcode scanning no longer worked and cordova.plugins was undefined.  Through trial and error, I realized that when I reverted back to the last release of 6.0.5 it worked again.

#### Steps to Reproduce
Build using build.phonegap.com.
In the deviceready event callback, verify that cordova.plugins is undefined.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0.0

#### Cordova CLI version and cordova platform version

    build.phonegap.com appears to use cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)

#### Plugin version

    phonegap-plugin-barcodescanner 7.0.0

**Comment by jrmihalick** [comment]
@mspiceland I thought that I had the same problem, but it turned out that I had a syntax error in the javascript interface file for another plugin that I was developing.  This was preventing all of my plugins that were binding themselves into _cordova.plugins_ from successfully doing so, including the barcode scanner plugin's _barcodeScanner_ value.

**Comment by andreszs** [comment]
I'm having the exact same problem with a blank Apache Cordova project created with Visual Studio 2015.
An app without any plugins whatsoever will raise the error 
> Uncaught TypeError: Cannot read property 'barcodeScanner' of undefined
whenever this plugin is invoked.

Returning to plugin version 6.x until this is fixed.

**Comment by jcesarmobile** [comment]
The version 7.x.x of this plugin requires cordova-android 6.3.0 or greater. Phonegap build didn't provide that version until a few days ago. You have to configure your app to use the CLI 7.1.0, then the plugin should work.

Closing as it isn't really a plugin problem, but a phonegap build problem. If you still have problems with the plugin and phonegap build, then report it on phonegap build forums or the issue tracker

**Comment by rkeene** [comment]
Thanks for the information -- it would be better if this issue manifested itself at compile-time rather than runtime, if it has particular compile-time dependencies.
