### ISSUE TITLE
Updating ZXing Library

### ISSUE THREAD

**Issue by boomgetchopped** [phonegap/phonegap-plugin-barcodescanner#59]
Would anyone be able to outline steps for updating the underlying ZXing library?

I believe many of the issues people are experiencing with this plugin are due to the zxing library
not being up to date.

I've used zxing outside of cordova framework and it works phenomonally.

**Comment by timwindsor** [comment]
Updating the library used by BlackBerry's implementation is on my list to do. We're going to have to find the most recent version with a C++ port, build it for BB10, and package it with the plugin's other native libraries. I can't speak for the other platforms.

**Comment by bhack** [comment]
@timwindsor I think the best you can have in c++ is at https://github.com/glassechidna/zxing-cpp/issues/29. It is not so much but it is something.

**Comment by r4ts0n** [comment]
I am looking the same for Android too. I am wondering if copying https://github.com/zxing/zxing/tree/master/android to https://github.com/phonegap/phonegap-plugin-barcodescanner/tree/master/src/android/LibraryProject would work.

**Comment by alexbuijs** [comment]
@ratson Unfortunately, the original 4.3.1 zxing source code has been changed quite a bit. See: https://github.com/phonegap/phonegap-plugin-barcodescanner/commits/master/src/android/LibraryProject

Updating to the most recent zxing involves reapplying all the changes (perhaps easiest by making a diff from https://github.com/zxing/zxing/tree/38b3fe1280943d3849f73675d4205f85f98f3698/android with https://github.com/phonegap/phonegap-plugin-barcodescanner/tree/master/src/android/LibraryProject)...

**Comment by ratson** [comment]
@EddyVerbruggen Is this solved by https://github.com/EddyVerbruggen/barcodescanner-lib-aar?

**Comment by EddyVerbruggen** [comment]
@ratson yes it does
