### ISSUE TITLE
Cordova 8.0.0 Android not supported

### ISSUE THREAD

**Issue by brainfoolong** [phonegap/phonegap-plugin-barcodescanner#590]
Without this plugin my application work fine, i can build it and run it without problems.
After installing this plugin the build process is broken.
When i remove the plugin from my app than all work again.
I have tried to remove all platform and plugin files and started from scratch, nothing have worked.

Installation log

    cordova plugin add phonegap-plugin-barcodescanner --variable CAMERA_USAGE_DESCRIPTION="To scan codes"
    Installing "phonegap-plugin-barcodescanner" for android
    Android Studio project detected
    Subproject Path: CordovaLib
    Subproject Path: app
    Installing "phonegap-plugin-barcodescanner" for browser
    Adding phonegap-plugin-barcodescanner to package.json
    Saved plugin info for "phonegap-plugin-barcodescanner" to config.xml

Plugin version

    phonegap-plugin-barcodescanner 7.0.0 "BarcodeScanner"

Cordova Version

    8.0.0

Platform versions

    Installed platforms:
      android 7.0.0
      browser 5.0.3
    Available platforms:
      ios ~4.5.4
      osx ~4.0.1
      windows ~5.0.0
      www ^3.12.0

Error in build

    FAILURE: Build failed with an exception.

    * Where:
    Script 'D:\www\desktopfiletransfer\platforms\android\CordovaLib\cordova.gradle' line: 168

    * What went wrong:
    A problem occurred evaluating script.
    > D:\www\desktopfiletransfer\platforms\android\app\res\xml\config.xml (File not found)

I have tried to create that file manually, than i got this.
Note that i have no "res" folder by default, it has not been created, even on a before successfull build without that plugin.

    * What went wrong:
    Could not resolve all files for configuration ':app:debugCompileClasspath'.
    > Could not find :barcodescanner:.
      Searched in the following locations:
          file:/D:/PortableApps/android-sdk-windows/extras/m2repository//barcodescanner//barcodescanner-.pom
          file:/D:/PortableApps/android-sdk-windows/extras/m2repository//barcodescanner//barcodescanner-.aar
          file:/D:/PortableApps/android-sdk-windows/extras/google/m2repository//barcodescanner//barcodescanner-.pom
          file:/D:/PortableApps/android-sdk-windows/extras/google/m2repository//barcodescanner//barcodescanner-.aar
          file:/D:/PortableApps/android-sdk-windows/extras/android/m2repository//barcodescanner//barcodescanner-.pom
          file:/D:/PortableApps/android-sdk-windows/extras/android/m2repository//barcodescanner//barcodescanner-.aar
          https://jcenter.bintray.com//barcodescanner//barcodescanner-.pom
          https://jcenter.bintray.com//barcodescanner//barcodescanner-.aar
          https://maven.google.com//barcodescanner//barcodescanner-.pom
          https://maven.google.com//barcodescanner//barcodescanner-.aar
          https://repo1.maven.org/maven2//barcodescanner//barcodescanner-.pom
          https://repo1.maven.org/maven2//barcodescanner//barcodescanner-.aar
          file:/D:/www/desktopfiletransfer/platforms/android/app/libs/barcodescanner-.aar
          file:/D:/www/desktopfiletransfer/platforms/android/app/libs/barcodescanner.aar
      Required by:
          project :app

**Comment by jcesarmobile** [comment]
This is really a cordova-android bug that has been already fixed. See [CB-13721](https://issues.apache.org/jira/browse/CB-13721)
Also, current master version is not affected by this, the lines that might cause the issue were removed some time ago, but still not released @macdonst can you do a patch release for it?

Anyway, the plugin will not work with cordova-android 8.0.0 because of some other bugs, see https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/589

**Comment by macdonst** [comment]
@jcesarmobile do you mean we need a patch release for cordova-android?

**Comment by jcesarmobile** [comment]
No, for the plugin, last one is from ~2 months ago and I removed the gradle code ~1 month ago. A new release of the plugin will not contain #590, but will still be affected by #589.

I think  #589 is a cordova-android problem, or a mix of problems between the plugin and in cordova-android, we will need to investigate.

**Comment by macdonst** [comment]
@jcesarmobile pushed a 7.0.1
