### ISSUE TITLE
Fail to compile with Error CDVBarcodeScanner.mm normal armv7 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler

### ISSUE THREAD

**Issue by rahulshirphule** [phonegap/phonegap-plugin-barcodescanner#594]
CDVBarcodeScanner.mm file keep failing on Bamboo server but it works on my local machine.

Below is the Xcode build script 

	xcodebuild -scheme ${SEL_TARGET_ENV} clean archive -archivePath build/RESTClient 

And I also set the compiler flag as "Objective-C++" in compile sources of build target 

You help would be really appreciated.
Thanks

**Comment by jcesarmobile** [comment]
Sorry, you should contact them?
