### ISSUE TITLE
Phonegap build failed for android 

### ISSUE THREAD

**Issue by ipehimanshu** [phonegap/phonegap-plugin-barcodescanner#595]
we are using phonegap build site to create build 

Here is our config 

`<preference name="phonegap-version" value="cli-7.0.1" />`

and we use below plugins 

`<plugin name="cordova-plugin-facebook4" spec="^1.9.1" source="npm">
        <variable name="APP_ID" value="xxxxxxxxxxxxxx" />
        <variable name="APP_NAME" value="xxxxxxxxxx" />
    </plugin>`

	`<plugin name="cordova-android-support-gradle-release" spec="0.0.2" source="npm">
        <variable name="ANDROID_SUPPORT_VERSION" value="25.+" />
    </plugin>`

	`<plugin name="phonegap-plugin-barcodescanner" spec="6.0.8" source="npm">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes." />
    </plugin>`

	`<plugin spec="https://github.com/NazarKozak/cordova-plugin-multidex.git" source="git" />`

We get this type error 

from phonegap build url 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class

So any one please help me to resolve this issue ?

**Comment by rudzuan2008** [comment]
same issue using cordova cli 8

**Comment by caroguerrero** [comment]
This solution worked for me #592

**Comment by macdonst** [comment]
@ipehimanshu the Facebook SDK also includes ZXing. Can you upgrade to 7.0.2 and see if the problem persists for you?

**Comment by ipehimanshu** [comment]
ok i try and it works now 

Thanks
