### ISSUE TITLE
Product serial number barcode not scanning

### ISSUE THREAD

**Issue by Ramakrishnatp** [phonegap/phonegap-plugin-barcodescanner#599]
![untitled](https://user-images.githubusercontent.com/34594130/35041255-2132e4d8-fbaa-11e7-8839-66075c1e51ee.png)
Not able to scan attached  product serial number

**Comment by jcesarmobile** [comment]
Closing the issue, you have to follow the template.
Also, you should tell which kind of barcode is that, is one of the supported?

**Comment by Ramakrishnatp** [comment]
Its Code -128 format 
i am able to scan sample code 128 format barcodes, but i don't know why not able to scan serial number what i have attached above.

please share some inputs.
