### ISSUE TITLE
iOS error NSInvalidArgumentException

### ISSUE THREAD

**Issue by isaacwebfix** [phonegap/phonegap-plugin-barcodescanner#60]
When running my phonegap app on the device (iPhone 5 running iOS 8), via Xcode 7 beta, I get the following error (logged to Xcode) and no other feedback. The camera doesn't initialise at all.

The app is using version 4.0.1 of the plugin and Phonegap CLI 5.2.0.
Android works fine.

    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '[__NSDictionaryM length]: unrecognized selector sent to instance 0x16ec2c20'

**Comment by hilkeheremans** [comment]
Having the exact same issue, with an iPhone 6 Plus running Xcode 7 beta and iOS 9.

**Comment by dandrayan** [comment]
I can reproduce the same issue with plugin 4.0.2 on Cordova 5.1.1 and 5.2.0 on both an iPhone 5 (iOS 8.4.1) and iPod 5th generation (iOS 8.3). The funny thing is I can take the exact same code and configuration from my main app for launching the camera and put it in its own project unmodified and it will work fine. Perhaps my app has grown large enough that memory pressure is causing issues with loading the plugin?

**Comment by hilkeheremans** [comment]
@dandrayan By configuration, do you also mean you are using the exact same plugins in the test project?

**Comment by dandrayan** [comment]
@hilkeheremans Correct, same plugins and versions.

**Comment by CraigSnowden** [comment]
Getting this problem, can't work it out. Currently trying to add iOS support to an existing Android application

**Comment by Nertil** [comment]
I have the same problem. Did someone solve it?

**Comment by hilkeheremans** [comment]
try `http://plugins.telerik.com/cordova/plugin/barcodescanner` instead, should work.

**Comment by Nertil** [comment]
thanks @hilkeheremans, it works!!!

**Comment by mglmgl** [comment]
i found out, that the app crashes on iOS when i call the .scan()-Function with 3 parameters.
This works:
`barcodeScanner.scan(function (successCallback) {}, function (errorCallback) {});`
While this results in a crash:
`barcodeScanner.scan(function (successCallback) {}, function (errorCallback) {},{ ...options... });`

On Windows Phone and Android i don't have any issues with the options-parameter.

**Comment by EddyVerbruggen** [comment]
@mglmgl With 5.0.0 that should be ok. Alternatively, can you try like this?

```js
barcodeScanner.scan(
  function (successCallback) {},
  function (errorCallback) {},
  [{foo: "bar"}] // pass as an array
);
```

Please post a stacktrace / error in case that's still failing for you.
