### ISSUE TITLE
QRcode scanning is too slow on lenovo yoga tab 3

### ISSUE THREAD

**Issue by utpaul** [phonegap/phonegap-plugin-barcodescanner#602]
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by utpaul** [comment]
For ionic v1 its work very slow

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Anmol-Tuple** [comment]
@macdonst Hi ,
I am finding that this plugin library is too slow to read QR Code as compare to ZBar.
Please look into the issue
