### ISSUE TITLE
how can I trigger an function using barcode scanner

### ISSUE THREAD

**Issue by yuvanesh10** [phonegap/phonegap-plugin-barcodescanner#603]
I would like to trigger the function (in any front end) by scanning the barcode.
Instead of using a button to start the function

### BARCODE FILE

    import Quagga from 'quagga';
    barcode = '';
    configQuagga = {
     inputStream: {
      name: 'Live',
      type: 'LiveStream',
      target: '#inputBarcode',
       constraints: {
        width: { min: 640 },
        height: { min: 480 },
        aspectRatio: { min: 1, max: 100 },
        facingMode: 'environment', // or user
        },
       singleChannel: false // true: only the red color-channel is read
       },
       locator: {
      patchSize: 'medium',
      halfSample: true
       },
       locate: true,
       numOfWorkers: 4,
      decoder: {
       readers: ['code_128_reader']
       }
      };
     constructor(private http: Http, private ref: ChangeDetectorRef) {}
     ngOnInit() {
     console.log('Barcode: initialization');
      }
     testChangeValues() {
    this.barcode = 'Code-barres bidon : 0123456789';
     }

     startScanner() {
      this.barcode = '';
     this.ref.detectChanges();
     Quagga.onProcessed((result) => this.onProcessed(result));
     Quagga.onDetected((result) => this.logCode(result));
     Quagga.init(this.configQuagga, (err) => {
      if (err) {
        return console.log(err);
      }
      Quagga.start();
      console.log('Barcode: initialization finished. Ready to start');
      });
      }

     private onProcessed(result: any) {
     const drawingCtx = Quagga.canvas.ctx.overlay;
     const drawingCanvas = Quagga.canvas.dom.overlay;

     if (result) {
      if (result.boxes) {
        drawingCtx.clearRect(0, 0, parseInt(drawingCanvas.getAttribute('width'), 10), 
        parseInt(drawingCanvas.getAttribute('height'), 10));
        result.boxes.filter(function (box) {
          return box !== result.box;
        }).forEach(function (box) {
          Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, { color: 'green', lineWidth: 2 });
        });
      }
      if (result.box) {
        Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, { color: '#00F', lineWidth: 2 });
      }
      if (result.codeResult && result.codeResult.code) {
        Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, { color: 'red', lineWidth: 3 });
      }
      }
      }
     private logCode(result) {
      const code = result.codeResult.code;
      if (this.barcode !== code) {
      this.barcode = 'Code-barres EAN : ' + code;
      this.ref.detectChanges();
      console.log(this.barcode);
      Quagga.stop();
      }
     }
     }

#### Platform and Version
QUAGGA JS 8 (0.12.1) 
angular 4 framework

**Comment by jcesarmobile** [comment]
Unclear what you asking.
And you have to follow the template.

closing
