### ISSUE TITLE
The camera opens but it does not read the barcode iOS

### ISSUE THREAD

**Issue by Studio27AB** [phonegap/phonegap-plugin-barcodescanner#607]
### Expected Behaviour
The camera opens and barcode is read just as it does in Android and Windows

### Actual Behaviour
The camera opens and everything looks as it should but nothing happens on iOS

### Reproduce Scenario (including but not limited to)
I use phonegap build

#### Steps to Reproduce
I have added this to config.xml

```
<plugin name="phonegap-plugin-barcodescanner" />
<edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
    <string>To scan barcodes</string>
</edit-config>
```

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3.5
#### Cordova CLI version and cordova platform version
cli-8.0.0
cordova 4.5.4

#### Plugin version

7.0.2

#### Sample Code that illustrates the problem

    cordova.plugins.barcodeScanner.scan(
        function (result) {
            console.log(result.text);
        },
        function (error) {
            alert("Scanning failed: " + error);
        },
        {
            preferFrontCamera: false, // iOS and Android
            showFlipCameraButton: false, // iOS and Android
            showTorchButton: true, // iOS and Android
            torchOn: true, // Android, launch with the torch switched on (if available)
            saveHistory: true, // Android, save scan history (default false)
            prompt: "Place a barcode inside the scan area", // Android
            resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
            formats: "all", // default: all but PDF_417 and RSS_EXPANDED
            orientation: "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
            disableAnimations: true, // iOS
            disableSuccessBeep: false // iOS and Android
        }
    );

**Comment by papattes** [comment]
Hi, I had exactly the same problem under the same conditions.
In my config.xml, replace : 

<plugin name="phonegap-plugin-barcodescanner" />
<edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
    <string>To scan barcodes</string>
</edit-config>

By

<plugin name = "phonegap-plugin-barcodescanner" spec = "^ 7.0.2">
     <param name = "CAMERA_USAGE_DESCRIPTION" value = "To scan barecode" />
</ Plugin>

At the launch of the plugin, there is the request for access to the camera without the message "To scan barecode" but it still works for me

**Comment by studiostart** [comment]
In my case, IOS works without problem and it reads the barcode in a fraction of second. The only problem I've found is on the camera focus. In my iPhone it works well, instead in my iPad the camera doesn't focus well the barcode and for this reason the reading doesn't work.

**Comment by jcesarmobile** [comment]
don't use "all" as formats, either provide a list of supported formats or don't provide anything, but all is not a valid format
