### ISSUE TITLE
Problem build android

### ISSUE THREAD

**Issue by cardonazio** [phonegap/phonegap-plugin-barcodescanner#608]
good afternoon people, fine. I'm having trouble enabling permissions for the barcode plugin.

<plugin name = "phonegap-plugin-barcodescanner" />

In the desktop phonegap he is running normally, he asked for permission when I accessed the link that called him. But when I ran the app to get into the store, it did not make a mistake.

But do not access the plugin, someone has already had this problem. can you tell me what permission I have to add in config.xml

Thank you guys!!!

**Comment by macdonst** [comment]
@cardonazio Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/.github/ISSUE_TEMPLATE.md
