### ISSUE TITLE
The possibility to choose front camera or back camera, landscape or portrait mode

### ISSUE THREAD

**Issue by bottasergio** [phonegap/phonegap-plugin-barcodescanner#61]
It would be a great contribution to this plugin to add the possibility to choose front camera or back camera and landscape or portrait mode.

For example... https://github.com/tjwoon/csZBar  supports front or back camera... but it is not possible to use with PhoneGap Build.

**Comment by convey-mane** [comment]
As far as we are talking about the iOS side, take a look at #97 :wink:

**Comment by andreszs** [comment]
Any news on forcing the correct orientation and override the device's orientation (in Android)? This is critical for scanning codes with smaller screen devices.

**Comment by diego-vieira** [comment]
It seems that Windows got this working
