### ISSUE TITLE
MSI barcode scanner for Android

### ISSUE THREAD

**Issue by ramanbalaji** [phonegap/phonegap-plugin-barcodescanner#612]
### Expected Behaviour
Phonegap-plugin-barcodescanner should scan MSI-Plessey barcode in Android devices

### Actual Behaviour
Phonegap-plugin-barcodescanner is not scanning MSI-Plessey barcode in Android devices

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Android Acer Iconia 10

#### Cordova CLI version and cordova platform version
    cordova --version - 8.0.0
    cordova platforms - Android

#### Plugin version
    cordova plugin version | grep phonegap-plugin-barcodescanner - 7.0.0

**Comment by viba9** [comment]
Hello,
I would like to know if you have an idea on how to develop the function msi for android and ios?
