### ISSUE TITLE
#585: Regarding fixed iPhoneX safe area problem [Question] 

### ISSUE THREAD

**Issue by JoshuaRa** [phonegap/phonegap-plugin-barcodescanner#619]
Hi,

I'm wondering when you will release the fix(#585) to release branch.
I need to use that one but this fix is not included in latest release version.
Please let me know when you will release this fix and I hope it's released ASAP!

Thank you.

**Comment by jcesarmobile** [comment]
There is no date, but will be soon probably.
If you can't wait, you can install from the github url
