### ISSUE TITLE
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0

### ISSUE THREAD

**Issue by bankjirapan** [phonegap/phonegap-plugin-barcodescanner#628]
When click button scan application stop end show error : Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by jcesarmobile** [comment]
Closing because it doesn't follow the issue template and doesn't provide any information about platforms/plugin version.
Feel free to reopen if you provide all the required information
