### ISSUE TITLE
ios 11.2 do not request again permissions

### ISSUE THREAD

**Issue by speedfl** [phonegap/phonegap-plugin-barcodescanner#629]
### Expected Behaviour
If user request to use this feature permission should be requested again (even if disallowed earlier)

### Actual Behaviour
Crash with message meaning permissions not granted

#### Steps to Reproduce
Create a simple app with this plugin (ie: ionic app)
Launch it on ios 11.2 (reproduced on 6s, 6s+, 7 and X)
Launch plugin
Give permission
Close app
Go to settings
Change app permission for camera
Reopen app
Launch plugin

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 11.2
Plugin 6.0.8

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : ios 4.5.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v6.11.2
    npm        : 5.3.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

#### Plugin version

6.0.8

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

N/A

**Comment by jcesarmobile** [comment]
This is not possible, on iOS you can only ask once.

But keeping it open as it shouldn't crash if the permission was not granted

**Comment by jcesarmobile** [comment]
Anyway, I think this was fixed. Can you try with latest version (7.1.0)?

**Comment by speedfl** [comment]
Ok It is not crashing anymore. I just get error about permission.

Why ios is so complicated compared to android 🗡
