### ISSUE TITLE
BarcodeScanner and QRScanner Conflict android manifest

### ISSUE THREAD

**Issue by cristianizzo** [phonegap/phonegap-plugin-barcodescanner#630]
Reference issue: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/498

I have the same issue using both QRscanner and barcodescanner and after removed the 2 line of code:

`<uses-permission android:name="android.permission.CAMERA" android:required="false" /> <uses-feature android:name="android.hardware.camera" android:required="false" />`

I get this error

`error: cannot find symbol intentScan.putExtra(Intents.Scan.SHOW_FLIP_CAMERA_BUTTON, obj.optBoolean(SHOW_FLIP_CAMERA_BUTTON, false));`

**Comment by jcesarmobile** [comment]
There is a conflict between both plugins as they both import zxing in different ways
