### ISSUE TITLE
Xcode Version 8.2.1 (8C1002) with patch for iOS 11.2 (15C5097c)

### ISSUE THREAD

**Issue by uest555** [phonegap/phonegap-plugin-barcodescanner#631]
can not build anymore for iOS, no problem with Android

phonegap-plugin-barcodescanner version 7.1.0

More infos
![schermata 2018-03-23 alle 17 33 46](https://user-images.githubusercontent.com/16060607/37846001-896c1ec0-2ecc-11e8-9b82-b9dde6f9fc6d.png)

  Cordova CLI: 8.0.0
	Ionic CLI Version: 3.20.0
	Ionic App Lib Version: 2.2.1
	ios-deploy version: 1.9.1
	ios-sim version: 5.0.4
	OS: Mac OS X El Capitan
	Node Version: v9.3.0
	Npm Version: v5.7.1
	Xcode version: Xcode 8.2.1 Build version 8C1002
	Android SDK Tools: 26.1.1
	Ionic Framework Version: ionic1 1.3.3

	Installed platforms:
		android 7.0.0
		ios 4.5.4

**Comment by jcesarmobile** [comment]
Ah, yeah, we should have wrapped that code in `#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000`.

It's an easy fix, but starting 1st of April, Apple will require Xcode 9 for app updates and new submissions, so we won't fix this for just one week.

**Comment by uest555** [comment]
Thanks man, I’ll do it on my own
