### ISSUE TITLE
Plugin localization issue

### ISSUE THREAD

**Issue by mitchn82** [phonegap/phonegap-plugin-barcodescanner#634]
Hi all,
I'm using Ionic 3 for scanning a barcode in my app. When I start the barcode scanning on iOS, the plugin interface seems to be in asiatic language. Where can I set the current language or even how can I localize the interface? 

### Actual Behaviour
![screen shot 2018-03-22 at 14 29 03](https://user-images.githubusercontent.com/35527319/37906918-e65b1bf2-3103-11e8-95d7-d0a3f9f1b045.png)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 5
#### Cordova CLI version and cordova platform version
ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v9.7.1
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

#### Plugin version

cordova plugin version | grep phonegap-plugin-barcodescanner

phonegap-plugin-barcodescanner 7.1.0 "BarcodeScanner"

**Comment by jcesarmobile** [comment]
The Cancel button is just a System Cancel button, so it will be displayed in a language based in `CFBundleDevelopmentRegion` and `CFBundleLocalizations` entries of your info.plist

You can set the `CFBundleDevelopmentRegion` with the `defaultlocale` attribute of widget inside config.xml

You can set `CFBundleLocalizations` by using edit-config tag
