### ISSUE TITLE
Cordova build fails due to "com.android.support:support-v4" version

### ISSUE THREAD

**Issue by prudnikovdbison** [phonegap/phonegap-plugin-barcodescanner#639]
Cordova build fails with exception:
`:processDebugResourcesERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex`

This can be fixed in "barcodescanner.gradle" by upgrading 
`com.android.support:support-v4:+`
to a higher version like 27.0.1 or downgrading to 23.+. (tested versions)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android, v6.3.0+

#### Cordova CLI version and cordova platform version
    cordova --version => 6.5.0

#### Plugin version
    cordova plugin version | grep phonegap-plugin-barcodescanner => ^6.0.6

**Comment by jcesarmobile** [comment]
Current version (7.1.0) uses 27+ as default and it's configurable with a preference in the config.xml https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/plugin.xml#L44
