### ISSUE TITLE
Can't install plugin via Visual Studio

### ISSUE THREAD

**Issue by sgo13** [phonegap/phonegap-plugin-barcodescanner#64]
When I try to import this plugin directly from Visual Studio 2015 RC I get this error message:

Visual Studio was unable to parse plugin.xml. Please ensure plugin exist and contains no errors.

Do you have any idea ?

Thank you.

**Comment by nlsdg** [comment]
This is the same as issue #52 and #46. Fix for that hasn't been released yet.
See the related pull request with issue 52 on how to fix it by hand.
BTW VS 2015 is RTM now.

**Comment by sgo13** [comment]
Thank you for your help

**Comment by tyroneallen281** [comment]
Hey has this fix been made public

**Comment by nemo3000** [comment]
I have same problem but the string show in other issue is already present.

**Comment by macdonst** [comment]
Fix was merged
