### ISSUE TITLE
Could not get unknown property 'ANDROID_SUPPORT_V4_VERSION'

### ISSUE THREAD

**Issue by Vesper14** [phonegap/phonegap-plugin-barcodescanner#645]
### Expected Behaviour
I expect Ionic project to build for Android after adding phonegap-plugin-barcodescanner to it.

### Actual Behaviour
```
FAILURE: Build failed with an exception.
* Where:
Build file 'C:\Users\*\source\repos\epm-qrbk-mobile-2018\platforms\android\app\build.gradle' line: 262
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'ANDROID_SUPPORT_V4_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Changing plugin variable
```
<plugin name="phonegap-plugin-barcodescanner" spec="^7.0.4">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
</plugin>
```
doesn't make any difference. Just like changing default value in plugin.xml.
The problem can be fixed by adding variable explicitly to build in /platforms/android/build.gradle to 
```
allprojects {
     project.ext {
          ANDROID_SUPPORT_V4_VERSION="26.0.0-alpha1"
```
Would like to know is there any other resolution of this problem.

#### Steps to Reproduce
```
cordova plugin add phonegap-plugin-barcodescanner
cordova build android
```

#### Platform and Version
```
@ionic/cli-utils  : 1.19.1
ionic (Ionic CLI) : 3.19.1
global packages:
    cordova (Cordova CLI) : 7.0.0
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 10

```
#### Plugin version
phonegap-plugin-barcodescanner: v7.0.4

**Comment by jcesarmobile** [comment]
can you try removing and adding android platform?

**Comment by Vesper14** [comment]
@jcesarmobile 
Tried - the problem remains the same

**Comment by Vesper14** [comment]
@jcesarmobile Ok, I did as you proposed. So now my Android version is 6.2.3 and build succeeds!
But when I try to invoke it, I get 

> "plugin_not_installed"

 error message

**Comment by jcesarmobile** [comment]
The problem is the variables for fameworks was introduced in cordova 7.1.0, but we allow to install 7.0.4 version of the plugin on previous versions where it doesn't work.

So what we can do is to release a new 7.0.x version without the variable.

As a workaround, you can update cordova to 7.1.0. If that's not possible, then you can downgrade the plugin to 7.0.0, 7.0.1 or 7.0.2

**Comment by Vesper14** [comment]
@jcesarmobile First, I tried downgrading the plugin to all those versions you specified and that didn't help. Whatever updating to cordova 8.0.0 has really helped. Thanks!

**Comment by jcesarmobile** [comment]
If you see your config.xml, you have this `<plugin name="phonegap-plugin-barcodescanner" spec="^7.0.4">`.
The `^` means latest minor, so when you tried to downgrade, as you still had the `^`, it will always get latest minor (7.1.1 at the moment), not the version you wanted.

**Comment by Vesper14** [comment]
@jcesarmobile I see.. Can you please tell me are there any cases when ScanResult.cancelled sets to true automatically? It seems that physical back button doesn't set it.

**Comment by BassamHabash** [comment]
I have the same issue, there is any solution for the problem ?

**Comment by BassamHabash** [comment]
@jcesarmobile  
Thanks you, I have solved the problem using 👍 

ionic cordova add phonegap-plugin-barcodescanner@latest --variable ANDROID_SUPPORT_V4_VERSION="27.1.1"

**Comment by hector-oviedo-dev** [comment]
Issue still happens

**Comment by davidquon** [comment]
I'm trying to back port the changes in https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/621 on top of `6.0.8`.  My changes are located https://github.com/davidquon/phonegap-plugin-barcodescanner/tree/support-preference-v6.  I'm still seeing the issue as described above.  Any suggestions of what may be wrong?

I brought in these changes like this:
```
$ ionic cordova plugin add https://github.com/davidquon/phonegap-plugin-barcodescanner.git#support-preference-v6
```

Here is my Cordova version:
```
$ cordova --version
7.1.0
```

**Comment by davidquon** [comment]
Never mind.  Fixed my problem above by removing and adding the Android platform which installed `<engine name="android" spec="~6.3.0" />`.  My bad jumping the 🔫.  😞
```
$ ionic cordova platform remove android
$ ionic cordova platform add android
```
