### ISSUE TITLE
Android: exit app when cancelled

### ISSUE THREAD

**Issue by Story5** [phonegap/phonegap-plugin-barcodescanner#647]
### Expected Behaviour
    Return previous page when cancelled
### Actual Behaviour
    Exit app when cancelled
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
    Android 8.0.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
    OnePlus 3
#### Cordova CLI version and cordova platform version
    cordova 8.0.0
#### Plugin version
    7.1.0

**Comment by MatthiasBusch** [comment]
I can confirm the same wrong behaviour on an OnePlus 5t

**Comment by jcesarmobile** [comment]
Are you using Ionic?

**Comment by MatthiasBusch** [comment]
No, I am using phonegap

**Comment by jcesarmobile** [comment]
And any framework for the UI?

**Comment by MatthiasBusch** [comment]
Yes, framework 7 actually, but i will test it soon with a blank app as well and provide feedback

**Comment by MatthiasBusch** [comment]
Alright, it worked without the framework. After that I found out that they released a fix yesterday for it. So at least from my side this issue is resolved. Thanks!

**Comment by jcesarmobile** [comment]
Yeah, that's what I thought, I asked about Ionic because I've seen the same problem there, but at it seems to be related to certain frameworks and not to Cordova/Phonegap I'll close the issue
