### ISSUE TITLE
Plugin adding android:allowBackup="true" to AndroidManifest.xml

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-plugin-barcodescanner#648]
Whenever I add the shown code to my `config.xml` to **prevent the automatic backup feature** from Android 6.0, the app **fails to compile** due to this error:

![barcodescanner](https://user-images.githubusercontent.com/10298071/38835569-f7b0abe8-41a1-11e8-9801-686ffbb74092.png)

It turns out that somehow this barcodescanner plugin sets the `allowBackup="true"` option for app [auto backup in Android 6](https://stackoverflow.com/questions/33169618/an-android-app-remembers-its-data-after-uninstall-and-reinstall).

**Each developer should be allowed to set this option manually according to his convenience, instead of the plugin deciding for us by touching these settings.**

This is located at AndroidManifest.xml from [/src/android/barcodescanner-release-2.1.5.aar](https://github.com/phonegap/phonegap-plugin-barcodescanner/tree/master/src/android)

![barcodescanner_androidmanifest](https://user-images.githubusercontent.com/10298071/38835813-918de334-41a2-11e8-93c6-129feee97f86.png)

**Question to anyone:** what's the purpose of that **.aar** (which is a ZIP) file? This is the first plugin I found that features such file. Can it be deleted safely? Thanks.

**Comment by jcesarmobile** [comment]
That is from zxing library (the one that the plugin uses for scanning) https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L45
the .aar is just the library compiled.

Try reporting the issue on their issue tracker, maybe they remove it or give you an explanation about why it's needed.
