### ISSUE TITLE
iPhone / iPod won't scan barcodes

### ISSUE THREAD

**Issue by olimortimer** [phonegap/phonegap-plugin-barcodescanner#65]
Testing the barcode scanning on Code 39 barcodes from my project, with the following devices:

* iPad Mini
* iPhone 5S
* iPod Touch

The iPad Mini successfully scans sample Code 39 (and Code 128) in low density, but the iPhone and iPod don't.  It's as if they can't 'see' the barcode.  The iPhone / iPod has to be approx 40mm higher than the iPad for the barcode to fill the green square, but still it doesn't pick it up.

This is a sample of a barcode I'm testing it against:

![barcode](https://cloud.githubusercontent.com/assets/1190115/9545257/9c2fbfca-4d7f-11e5-8519-30de3a5941e1.jpg)

I'm also seeing the same issue on these samples:

![](http://www.barcodehq.com/images/BARCODES/barcodechart.gif)

**Comment by olimortimer** [comment]
Further investigation shows that the iPhone / iPod can scan Code39 barcodes ok, as long as they are under 9 characters long - 8 characters does scan, but can be a bit sporadic.

![barcode7](https://cloud.githubusercontent.com/assets/1190115/9545638/b2992bc6-4d83-11e5-9858-235f736370e0.jpg)
![barcode8](https://cloud.githubusercontent.com/assets/1190115/9545640/b4a4407c-4d83-11e5-8e92-01728c8d46fa.jpg)
![barcode9](https://cloud.githubusercontent.com/assets/1190115/9545642/b817069a-4d83-11e5-9c57-9481a010fc67.jpg)
![barcode10](https://cloud.githubusercontent.com/assets/1190115/9545645/b9977770-4d83-11e5-95a2-bc65319583fe.jpg)

**Comment by olimortimer** [comment]
It seems like setting `AVCaptureSessionPresetMedium` to `AVCaptureSessionPresetHigh` in `CDVBarcodeScanner.mm` (two places) solves the issue, and initial testing looks like it now captures fine.

**Comment by jhuggart** [comment]
@olimortimer awesome! I'll give it a try later today.

**Comment by Delagen** [comment]
Call scan and image hang and never updates

**Comment by sarangan12** [comment]
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it
