### ISSUE TITLE
Plugin crashes when edit-config data is added to config.xml

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-plugin-barcodescanner#650]
### Expected Behaviour

Scan code normally.
It works until I add certain `<edit-config>` tags to my `config.xml`.

### Actual Behaviour

App crashes on scan attempt.

### Reproduce Scenario (including but not limited to)

Add this code to your `config.xml` file (to prevent Android M from persisting data after uninstall)
Probably any `edit-config` will crash the plugin, as [reported earlier](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/638)

```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
      <application android:allowBackup="false" android:fullBackupOnly="false" />
</edit-config>
```

#### Steps to Reproduce

- Create new app
- Add the plugin with `ANDROID_SUPPORT_V4_VERSION = 13.+`
- Add default scan methods from the plugin
- Add the previous `edit-config` XML to your `config.xml`
- Deploy to device
- Try to invoke the scan method

**Notice:** Simply removing the `edit-config` section to restore your `config.xml` will NOT solve the problem now. The entire `android` platform folder must be deleted to make the plugin work again.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 4.4.2
Android 5.1
Android 6.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung Galaxy S4 mini
BLU Energy Diamond
BLU Vivo 5 mini

#### Cordova CLI version and cordova platform version

    cordova --version 7.1.0 <-- tried both CLI versions, same result
    cordova --version 6.5.0 <-- tried both CLI versions, same result
    cordova-android 6.3.0 <-- I cannot update this one, and surely it won't fix anything

#### Plugin version

    phonegap-plugin-barcodescanner 7.1.1 <-- latest version I'm using
    phonegap-plugin-barcodescanner 6.0.8 <-- 90% sure the same error happened with this one

#### Logs taken while reproducing problem

Here is the Visual Studio output log, only the sections with fatal errors or related to the plugin are here.
All I can guess from this and other reports is that the activity `com.google.zxing.client.android.CaptureActivity` seems to be the cause.

```
...
E/AndroidRuntime(20238): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime(20238): Process: clientes.test.app, PID: 20238
E/AndroidRuntime(20238): android.content.ActivityNotFoundException: Unable to find explicit activity class {clientes.test.app/com.google.zxing.client.android.CaptureActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime(20238): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1788)
E/AndroidRuntime(20238): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
E/AndroidRuntime(20238): 	at android.app.Activity.startActivityForResult(Activity.java:3810)
E/AndroidRuntime(20238): 	at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
E/AndroidRuntime(20238): 	at android.app.Activity.startActivityForResult(Activity.java:3761)
E/AndroidRuntime(20238): 	at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:66)
E/AndroidRuntime(20238): 	at com.phonegap.plugins.barcodescanner.BarcodeScanner$1.run(BarcodeScanner.java:204)
E/AndroidRuntime(20238): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(20238): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(20238): 	at java.lang.Thread.run(Thread.java:818)
...
W/cr_AwContents(20238): Application attempted to call on a destroyed WebView
W/cr_AwContents(20238): java.lang.Throwable
W/cr_AwContents(20238): 	at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:349)
W/cr_AwContents(20238): 	at org.chromium.android_webview.AwContents.isDestroyedOrNoOperation(AwContents.java:321)
W/cr_AwContents(20238): 	at org.chromium.android_webview.AwContents.getTitle(AwContents.java:576)
W/cr_AwContents(20238): 	at org.chromium.android_webview.AwWebContentsDelegateAdapter.loadingStateChanged(AwWebContentsDelegateAdapter.java:132)
W/cr_AwContents(20238): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/cr_AwContents(20238): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
W/cr_AwContents(20238): 	at android.os.Handler.dispatchMessage(Handler.java:111)
W/cr_AwContents(20238): 	at android.os.Looper.loop(Looper.java:194)
W/cr_AwContents(20238): 	at android.app.ActivityThread.main(ActivityThread.java:5637)
W/cr_AwContents(20238): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(20238): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/cr_AwContents(20238): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
W/cr_AwContents(20238): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
...
```
Full log file here:
[barcodescannerlog.txt](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/1920476/barcodescannerlog.txt)
Just in case here is my AndroidManifest.xml:
[AndroidManifest.zip](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/1920553/AndroidManifest.zip)

**Comment by jcesarmobile** [comment]
The problem is cordova-android, it's been reported already https://issues.apache.org/jira/browse/CB-13514
