### ISSUE TITLE
Plugin doesn't support this project's cordova version. cordova: 7.0.2, failed version requirement: >=7.1.0

### ISSUE THREAD

**Issue by ipehimanshu** [phonegap/phonegap-plugin-barcodescanner#652]
i am using 
`<preference name="phonegap-version" value="cli-7.1.0" />`

and 

`<plugin name="phonegap-plugin-barcodescanner" spec="^7.1.1" source="npm">`
        `<variable name="CAMERA_USAGE_DESCRIPTION" value="To scan barcodes." />`
		`<variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />`
    `</plugin>`

`<platform name="winphone">`
       `<preference name="windows-appx-target" value="8.1-phone"/>`
       `<preference name="windows-arch" value="x86" /> <!-- anycpu, arm, x86, and x64 -->  `
    `</platform>`

Here is log from phonegap build site 

`
Fetching plugin "phonegap-plugin-barcodescanner@7.1.1" via npm
Installing "phonegap-plugin-barcodescanner" at "7.1.1" for windows
Plugin doesn't support this project's cordova version. cordova: 7.0.2, failed version requirement: >=7.1.0
Skipping 'phonegap-plugin-barcodescanner' for windows`

**Comment by jcesarmobile** [comment]
Looks like a PGB error, report it to them
