### ISSUE TITLE
Can't install Cordova Plugin Barcodescanner - Phonegap (mac)

### ISSUE THREAD

**Issue by paulamourad** [phonegap/phonegap-plugin-barcodescanner#653]
### I get the following error:
`(node:1815) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin cordova-plugin-barcodescanner via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm WARN checkPermissions Missing write access to /Users/DevCore/Desktop/vpay phonegap/Vpay Test/node_modules/cordova-plugin-barcodescanner
npm WARN enoent ENOENT: no such file or directory, open '/Users/DevCore/Desktop/vpay phonegap/Vpay Test/package.json'
npm WARN Vpay Test No description
npm WARN Vpay Test No repository field.
npm WARN Vpay Test No README data
npm WARN Vpay Test No license field.

npm ERR! path /Users/DevCore/Desktop/vpay phonegap/Vpay Test/node_modules/cordova-plugin-barcodescanner
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/DevCore/Desktop/vpay phonegap/Vpay Test/node_modules/cordova-plugin-barcodescanner'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/DevCore/.npm/_logs/2018-04-23T20_07_00_690Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:1815) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1815) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

#### Cordova CLI version and cordova platform version

    cordova 8.0.0
    cordova platforms (what?)

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by sfaizanh** [comment]
Wrong Plugin :) `cordova-plugin-barcodescanner` is different from `phonegap-plugin-barcodescanner`
