### ISSUE TITLE
iOS Camera can no longer auto-focus after scanning barcode

### ISSUE THREAD

**Issue by wolfg1969** [phonegap/phonegap-plugin-barcodescanner#654]
### Expected Behaviour
Can auto-focus normally, take clear photos.

### Actual Behaviour

Failed to auto-focus on normal  or long distance object, photos are blurry.

### Reproduce Scenario (including but not limited to)

We have a camera feature in our app to take photos as well as barcode scanner functionality to scan barcodes. (barcode scanner: this plugin, taking photos: cordova-plugin-camera) As long as one does not scan any barcodes the camera is working fine. When you open the barcode scanner and close it again (doesn't matter if it scanned something or you cancel out) the camera feature in our app is no longer able to auto-focus. Therefore all images are blurry. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 11.3
#### Cordova CLI version and cordova platform version

    cordova --version

8.0.0

    cordova platforms

  android 7.0.0
  ios 4.5.4

#### Plugin version

    phonegap-plugin-barcodescanner 7.1.1 "BarcodeScanner"

**Comment by jcesarmobile** [comment]
Closed by #655
