### ISSUE TITLE
Unable to scan EAN+5

### ISSUE THREAD

**Issue by dbeckett-salk** [phonegap/phonegap-plugin-barcodescanner#665]
This plugin works amazingly well, but I can't find a way to scan the EAN+5 barcodes. I've attached an example. 
![54706498051__8d19977e-f7ad-4a06-ad6d-e403bf21c648](https://user-images.githubusercontent.com/22084685/39761153-2e3b8cfa-528c-11e8-90bd-5e4c94a7de34.jpeg)

**Comment by SimoneMSR** [comment]
I guess [this issue](https://github.com/zxing/zxing/issues/217#issuecomment-54818496) can help.
You would have to add an additional barcode format, say EAN13+5 on the zxing lib, and play with the code.
