### ISSUE TITLE
Android: Build failed after adding the plugin

### ISSUE THREAD

**Issue by HaiderSahib** [phonegap/phonegap-plugin-barcodescanner#667]
Hello,
When I build the project after adding the plugin, I received the following error:

path_to_my_project/platforms/android/build/intermediates/res/merged/debug/values/values.xml:218: error: Attribute "layout_anchorGravity" already defined with incompatible format.
path_to_my_project/platforms/android/build/intermediates/res/merged/debug/values/values.xml:158: Original attribute defined here.

Please help!

**Comment by sbhandary** [comment]
I am having the same issue. Did this get resolved?

**Comment by jcesarmobile** [comment]
This is because of conflicts on the support v4 versions.
This plugin can be configured to select the desired support v4 version so it makes easier to handle those conflicts by using ANDROID_SUPPORT_V4_VERSION variable. (See readme).
Other plugins should do the same.
