### ISSUE TITLE
Allow EAN_EXTENSIONS on Android and iOS

### ISSUE THREAD

**Issue by SimoneMSR** [phonegap/phonegap-plugin-barcodescanner#669]
Sorry, this is not an issue, but I would like to say something. I am writing a pull request for enabling EAN extensions in Android and iOS. At the Android side the work is done, but I do not understand what should I do for iOS.  The `CDVBarcodeScanner.mm` does not seem to do all the job. Is there an _hidden_ library that I have not seen?

**Comment by jcesarmobile** [comment]
`AVFoundation`frameworks does the job and returns the results to `CDVBarcodeScanner.mm` on `- (void)captureOutput:(AVCaptureOutput *)output 
didOutputMetadataObjects:(NSArray<__kindof AVMetadataObject *> *)metadataObjects 
       fromConnection:(AVCaptureConnection *)connection;` method

**Comment by SimoneMSR** [comment]
Thank you very much for replying. 
I wonder whether the `AVFoundation` could be replaced by [this](https://github.com/TheLevelUp/ZXingObjC/) ObjC Zxing port. Would it be a HUGE work? I need some feature from Zxing, but I have never had hands on a plugin for iOS...
