### ISSUE TITLE
Unsupported via PhoneGap build

### ISSUE THREAD

**Issue by TylerBrinks** [phonegap/phonegap-plugin-barcodescanner#67]
The plugin works great locally, but it doesn't seem to be allowed when uploading to Adobe PhoneGap build.  The message isn't very descriptive: "plugin unsupported: phonegap-plugin-barcodescanner:

Any idea why?

**Comment by SingleID** [comment]
using this I have no problem like your
```
<gap:plugin name="com.phonegap.plugins.barcodescanner" source="npm" />

```

But I'm now fighting with a windowsphone and I'm not sure that the barcode reader works well. More on the next days.

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
