### ISSUE TITLE
Get barcodescanner-release-2.1.5.aar from a Maven repository?

### ISSUE THREAD

**Issue by Rudloff** [phonegap/phonegap-plugin-barcodescanner#670]
Hello,

I'm an [F-Droid](https://f-droid.org/) maintainer.
We [recently packaged](https://gitlab.com/fdroid/fdroiddata/merge_requests/3144) an app that uses this plugin.

One issue that we had is that the `barcodescanner-release-2.1.5.aar` binary is included in the repository.
Our policy is to build everything from source or get it from a trusted repository like Maven Central or jCenter.
So for now we are rebuilding `barcodescanner` from source but it would be easier to get it from a trusted repository with Gradle.

Do you think that is something that could be done?

**Comment by jcesarmobile** [comment]
If ZXing or somebody else took care of that, we would be happy to drop the .aar and just use gradle. 
As far as I know, that's not the case, so closing the issue for now.

**Comment by Rudloff** [comment]
I see some zxing libraries on Maven Central but I'm not sure that is what you need: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.zxing%22
