### ISSUE TITLE
Android build issue

### ISSUE THREAD

**Issue by xale76** [phonegap/phonegap-plugin-barcodescanner#671]
cordova   CLI 7.1.0 built on PhoneGap site

Latest version of this plugin.

in my config.xml MinSdkVersion was 15.
The build was successful.

I just changed MinSdkVersion to 26 and now the build fails.
the error is

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class

I've found that with 26 in config.xml there something in conflict with cordova-facebook-plugin4 (I forked it because I needed to change minSdkVersion in the plugin.xml to 26)

Please help

**Comment by jcesarmobile** [comment]
MinSdkVersion 26 means your app only supports Android O. Android O has ~5% of the market share. Are you sure you want that?

**Comment by xale76** [comment]
Hello and thanks!
Googles stated that starting from August it will be mandatory for new apps and starting from November for every app. So what could be the solution?

**Comment by jcesarmobile** [comment]
they are probably talking about the target SDK, not the min SDK.
cordova-android 6.3.0 uses target SDK 26. (And default min SDK 16)
cordova-android 7.0.0 or greater uses target SDK 27. (And default min SDK 19)

**Comment by xale76** [comment]
I tried, and I've read minsdk and target. New App minsdk=26 (so the target would be greater isn't it?), Update App, target=26 (what it means? that min sdk could be still 15?)

**Comment by jcesarmobile** [comment]
target can be >= than min
Facebook allows any min SDK, because they want people to support old devices.
But you are tied to the min SDK Cordova supports, you can't use a lower version than the supported by your Cordova version (see my previous comment for Cordova min SDKs based on versions)
