### ISSUE TITLE
Visual Studio 2015 cordova 6.1.1 error

### ISSUE THREAD

**Issue by Dkurt9000** [phonegap/phonegap-plugin-barcodescanner#678]
**Expected Behaviour**
Open the Camera and scan the barcode.

**Actual Behaviour**
can't open the Camera.

Reproduce Scenario (including but not limited to)
When I adding the plugin,I don't type anything in the ANDROID_SUPPORT_V4_VERSION.
and go to compiler Cordova.
Here is the Error Message:
1>  :processReleaseResources FAILED
1>
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>  FAILURE: Build failed with an exception.
1>
1>MSBUILD : cordova-build error : * What went wrong:
1>  * What went wrong:
1>MSBUILD : cordova-build error : Execution failed for task ':processReleaseResources'.
1>  Execution failed for task ':processReleaseResources'.
1>MSBUILD : cordova-build error : > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\27.0.3\aapt.exe'' finished with non-zero exit value 1
1>  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\27.0.3\aapt.exe'' finished with non-zero exit value 1
1>
1>MSBUILD : cordova-build error : * Try:
1>  * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>
1>  BUILD FAILED
1>
1>  Total time: 13.222 secs
1>MSBUILD : cordova-build error : Error code 1 for command: cmd with args: /s,/c,""C:\Users\daniele\Desktop\075_appWarehouseLight - Copia\platforms\android\gradlew" cdvBuildRelease -b "C:\Users\daniele\Desktop\075_appWarehouseLight - Copia\platforms\android\build.gradle" -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
1>  Error code 1 for command: cmd with args: /s,/c,""C:\Users\daniele\Desktop\075_appWarehouseLight - Copia\platforms\android\gradlew" cdvBuildRelease -b "C:\Users\daniele\Desktop\075_appWarehouseLight - Copia\platforms\android\build.gradle" -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"

Steps to Reproduce
Platform and Version (eg. Android 5.0 or iOS 9.2.1)
(Android) What device vendor (e.g. Samsung, HTC, Sony...)
Cordova CLI version and cordova platform version
**I using Visual Studio 2015.**
**Cordova CLI 6.1.1.**
**Cordova Android 5.1.1**

Plugin version
6.0.8 phonegap-plugin-barcodescanner

I must use this version of cordova, there is a solution for this problem? which version of phonegap plugin barcodescanner can i use? i tried old and new version but i have the same error.

Thank You
Daniel

**Comment by jcesarmobile** [comment]
Sorry, latest plugin requires cordova-android >= 6.3.0 and cordova >=7.1.0.

What you describe doesn't happen on latest version of the plugin and we can't backport everything to older versions.
