### ISSUE TITLE
pdf417 not working in android

### ISSUE THREAD

**Issue by sruthy1991** [phonegap/phonegap-plugin-barcodescanner#68]
hi,my barcode scanner need to only scan barcodes of pdf417 type.so i set scan format to PDF417.but I found out that the type of the scanned result is not pdf417.do you have any fix for this?

**Comment by just4give** [comment]
@sruthy1991 have you got it working? I tested on iPhone but could not scan US Driver license (PDF417)

**Comment by JoyceYy** [comment]
Default,scanner list does not include pdf417,have to  add : intentScan.putExtra(Intents.Scan.FORMATS,BarcodeFormat.PDF_417.toString());  
--at scan() method in Class BarcodeScanner.java ,it does work for me.

**Comment by multilexus** [comment]
Hi JoyceYy,

I'm new to cordova. Could you please be a little more specific? Where exactly to add this line? Do I need to change anything else? I tried adding this line as a 3rd line, right after

        Intent intentScan = new Intent(SCAN_INTENT);
        intentScan.addCategory(Intent.CATEGORY_DEFAULT);

in the scan method in the BarcodeScanner.java of this plugin, but it had no effect. Still won't read pdf417. Thanks in advance!

**Comment by JoyceYy** [comment]
Hi multilexus,


I add this two line ,and it work in barcodescanner version 2.0.1.And in version 4.0.1,add 
line below in you scan function.
SCAN_FORMATS:"PDF_417"


Following picture show what I write in my code,and it can scan PDF_417 and QR_CODE.What version you use?Maybe different version have different way.You can have a try.
    


------------------ 原始邮件 ------------------
发件人: "multilexus";<notifications@github.com>;
发送时间: 2016年2月10日(星期三) 晚上11:20
收件人: "phonegap/phonegap-plugin-barcodescanner"<phonegap-plugin-barcodescanner@noreply.github.com>; 
抄送: ""<572333564@qq.com>; 
主题: Re: [phonegap-plugin-barcodescanner] pdf417 not working in android(#68)




Hi JoyceYy,
 
I'm new to cordova. Could you please be a little more specific? Where exactly to add this line? Do I need to change anything else? I tried adding this line as a 3rd line, right after
     Intent intentScan = new Intent(SCAN_INTENT);     intentScan.addCategory(Intent.CATEGORY_DEFAULT);  
in the scan method in the BarcodeScanner.java of this plugin, but it had no effect. Still won't read pdf417. Thanks in advance!

**Comment by multilexus** [comment]
Hi,
Eventually I got it to work by adding the following line in my plugin's BarcodeScanner.java file:
intentScan.putExtra("SCAN_FORMATS","CODE_39,CODE_93,CODE_128,DATA_MATRIX,ITF,CODABAR,EAN_13,EAN_8,UPC_A,QR_CODE,PDF_417");

after that i had to recompile the android platform code. easy way to do it is to remove platform, then add platform and rebuild.
Thanks for your help!
Alex

**Comment by multilexus** [comment]
Hi Joyce! Thanks for your help!

Eventually, I got it to work on Android with PDF417 by adding the following line in my plugin's BarcodeScanner.java file:

intentScan.putExtra("SCAN_FORMATS","CODE_39,CODE_93,CODE_128,DATA_MATRIX,ITF,CODABAR,EAN_13,EAN_8,UPC_A,QR_CODE,PDF_417");

After that i had to recompile the android platform code. Easy way to do it is to remove platform, then add platform and rebuild.

Cheers,
Alex $

**Comment by mbellotto** [comment]
Alex (@multilexus),

Exactly, where did you put intentScan code? An how did you recompile the android platform? Be aware I don't know anything of java.

Thanks

**Comment by macdonst** [comment]
PDF 417 is supported in 6.0.6
