### ISSUE TITLE
Plugin doesnt work after converting to .apk

### ISSUE THREAD

**Issue by luminouszk** [phonegap/phonegap-plugin-barcodescanner#681]
Hello, I'm new to cordova so I might have done a simple mistake which I don't know. Anyway thanks in advance for helping.

**Expected Behaviour**
PhoneGap Desktop:
Barcode Scanner open when the button is click

Convert to .apk:
Barcode Scanner open when the button is click

 **Actual Behaviour**
PhoneGap desktop:
Barcode Scanner open when the button is click

Convert to .apk:
Barcode Scanner is not open when the button is click

**Platform and Version (eg. Android 5.0 or iOS 9.2.1)**

Android 6.0.1

**(Android) What device vendor (e.g. Samsung, HTC, Sony...)**

RedMi 3s

**Cordova CLI version and cordova platform version**

    cordova --version: **8.0.0**
    cordova platforms: none

**Plugin version**

    cordova plugin version | phonegap-plugin-barcodescanner 8.0.0

**Sample Code that illustrates the problem**

- **config.xml**

`<plugin name="phonegap-plugin-barcodescanner" source='npm' spec="~8.0.0"/>`

- **index.html** 

`<button id = "scanner">TAKE PICTURE</button>`

- **index.js**

```
document.getElementById("scanner").addEventListener ("click", scan); 

function scan()
            {
                alert("Done");
                cordova.plugins.barcodeScanner.scan (
                    
                    
                    function (result){
                    alert("Testing");
                    
                    },
                    function (error) {
                        alert("Scanning failed: " + error);
                    },
                    {
          preferFrontCamera : false, // iOS and Android
          showFlipCameraButton : false, // iOS and Android
          showTorchButton : false, // iOS and Android
          torchOn: false, // Android, launch with the torch switched on (if available)
          saveHistory: false, // Android, save scan history (default false)
          prompt : "Scan Merchant QR Code", // Android
          resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
          formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          orientation : "portrait", // Android only (portrait|landscape), default unset so it rotates with the device
          disableAnimations : true, // iOS
          disableSuccessBeep: true // iOS and Android
      }
               );
            }
```

**Comment by jcesarmobile** [comment]
Can you check if is it showing some js error on the chrome developer tools?
Also, can you check if some native error is show on logcat?

**Comment by luminouszk** [comment]
At first, I thought cordova.js was the problem since my project file does not come with cordova.js. But after installing cordova.js still, have the same problem.

`Uncaught TypeError: Cannot read property 'barcodeScanner' of undefined
    at HTMLButtonElement.scan`

**Comment by kingdorad** [comment]
try this:

change 
`<plugin name="phonegap-plugin-barcodescanner" source='npm' spec="~8.0.0"/>`
to
` <plugin name="phonegap-plugin-barcodescanner" spec="https://github.com/jrontend/phonegap-plugin-barcodescanner" />`

I have similar question and I change barcodescanner plugin to solve it

**Comment by luminouszk** [comment]
After changing to 
`<plugin name="phonegap-plugin-barcodescanner" spec="https://github.com/jrontend/phonegap-plugin-barcodescanner" />`
it works. 

Thanks!
