### ISSUE TITLE
IOS - Error building CDVBarcodescanner.mm

### ISSUE THREAD

**Issue by danilocecilia** [phonegap/phonegap-plugin-barcodescanner#682]
### Expected Behaviour
Successfull building on IOS
### Actual Behaviour
Error building on IOS retrieving the error:  

/Users/danielscarpim/Projetos/IonicLMS/Ionic/platforms/ios/MSX Learn/Plugins/phonegap-plugin-barcodescanner/CDVBarcodeScanner.mm:1028:146: Property 'safeAreaLayoutGuide' not found on object of type 'UIView *'

**Comment by jcesarmobile** [comment]
What's your Xcode version?

**Comment by AskmiLeitr** [comment]
I'm getting the same error.

I also get one that says `Unexpected '@' in program`
It doesn't like `if (@available(iOS 11.0, *))`

Both errors are in a function called resizeElements in the CDVBarcodeScanner.mm file.

I'm using xCode 8.2.1.

**Comment by jcesarmobile** [comment]
Since 1st of April, Xcode 9 is required to submit the apps to the App Store.
If you want to use Xcode 8 you can put that part of the code inside a `#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000`
