### ISSUE TITLE
Plugin fails to return information

### ISSUE THREAD

**Issue by emilioidk** [phonegap/phonegap-plugin-barcodescanner#685]
### Expected Behaviour
When scanning a bar code, return the information from the scan or error information

### Actual Behaviour
Callback functions are not called after scan

### Reproduce Scenario (including but not limited to)
App from scratch with some fixed dependencies. I have created a repository to show it https://github.com/emilioidk/TestBarcodeScanner

#### Steps to Reproduce
It is listed in the repository how to reproduce but basically running `cordova.plugins.barcodeScanner.scan(console.log, console.log)` and scanning a barcode does not log any information. I have successfully used this in the past to test the barcode scanner was working fine and the information got logged successfully. It seems as if the app is "refreshing" the view when returning from scan.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version

    cordova --version
        6.5.0
    cordova platforms
        Installed platforms:
            android 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner
        phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"

#### Sample Code that illustrates the problem
Please check https://github.com/emilioidk/TestBarcodeScanner

#### Logs taken while reproducing problem
None. App does not preserve any log or anything

**Comment by jcesarmobile** [comment]
Sorry, I can't run Cordova 6.5.0 projects anymore, and even if I could, the bug is probably fixed in current version and we don't backport fixes to old versions.

Anyway, I think your problem is Cordova is downloading the unmodified plugin again and not using your changes, try committing also android platform as it will contain the changes, and then configure docker to build that instad of recreating.

**Comment by emilioidk** [comment]
Thanks for your answer, I will check how to update my dependencies.
