### ISSUE TITLE
Android build error when include old vertsion plugin

### ISSUE THREAD

**Issue by YaroslavG** [phonegap/phonegap-plugin-barcodescanner#686]
hello guys, 
I used this plugin earlier and it worked fine! But since recently when I removed the plugin and tried to connect it to me, I can not make a build of the android platform. When I add command 
phonegap plugin add phonegap-plugin-barcodescanner@6.0.0 then cordova run android I have this errors all time. Please help
#### Cordova CLI version and cordova platform version
    cordova --version
    6.5.0
    cordova platforms
    5.0.0
#### Plugin version
    cordova plugin version 6.X.X

#### Logs taken while reproducing problem
:processDebugManifest

:processDebugResources
/Users/newuser/Sites/IonicProjects/test/project/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:44: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'

FAILED

FAILURE: 
Build failed with an exception.

* What went wrong:

Execution failed for task ':processDebugResources'.

> 
com.android.ide.common.internal.LoggedErrorException: Failed to run command:

  	/Users/newuser/Library/Android/sdk/build-tools/27.0.0/aapt package -f --no-crunch -I /Users/newuser/Library/Android/sdk/platforms/android-23/android.jar -M /Users/newuser/Sites/IonicProjects/test/project/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/newuser/Sites/IonicProjects/test/project/platforms/android/build/intermediates/res/debug -A /Users/newuser/Sites/IonicProjects/test/project/platforms/android/build/intermediates/assets/debug -m -J /Users/newuser/Sites/IonicProjects/test/project/platforms/android/build/generated/source/r/debug -F /Users/newuser/Sites/IonicProjects/test/project/platforms/android/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package com.App4biz.meetPro -0 apk --output-text-symbols /Users/newuser/Sites/IonicProjects/test/project/platforms/android/build/intermediates/symbols/debug

  Error Code:

  	1

  Output:

 /Users/newuser/Sites/IonicProjects/test/project/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:44: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'

* Try:

Run with 
--stacktrace option to get the stack trace. Run with --info or --debug
 option to get more log output.

BUILD FAILED

Total time: 18.385 secs

Error: 
/Users/newuser/Sites/IonicProjects/test/project/platforms/android/gradlew: Command failed with exit code 1

**Comment by jcesarmobile** [comment]
Sorry, latest version is 8.0.0. 
6.0.0 is 2 year old and we don't backport fixes to old versions. Try updating everything and if you still face this problem create a new issue.
