### ISSUE TITLE
Barcode Scanner 8.0.0 not working on Cordova 6.3.1

### ISSUE THREAD

**Issue by bandeto45** [phonegap/phonegap-plugin-barcodescanner#687]
I'm looking for the solution to my problem, my created application that integrated with barcode scanner plugin-was not working although the installation of the plugin is successful. Please help me to resolve this. :-(

**Comment by jcesarmobile** [comment]
Sorry, when creating an issue you have to fill the template with all the required information, we can't help you with this little information
