### ISSUE TITLE
No callback of success or error

### ISSUE THREAD

**Issue by emb715** [phonegap/phonegap-plugin-barcodescanner#691]
Follow the sample code with the last version of cordova, scanning a PDF417 code

### Expected Behaviour
On successCallback return result in a alert

### Actual Behaviour
successCallback function is not working, no result, no alert, nothing.

#### Cordova CLI version and cordova platform version

    cordova --version
              8.0.0
    cordova platforms
           android

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner
          phonegap-plugin-barcodescanner 8.0.0 "BarcodeSc

#### Sample Code that illustrates the problem
sample code from readme

**Comment by jcesarmobile** [comment]
what's your cordova-android version?

Even if using "readme code", it's better if you provide your actual code as README can have multiple examples and/or change over time

**Comment by emb715** [comment]
Hi, thank you for the quick awnser.

Im using a Samsung Galaxy S4 GT-i9500, android version 5.0.1

Then i try with another phone and it work fine. Samsung Galaxy A3 SM-A300M, android version 5.0.2 

code:
`cordova.plugins.barcodeScanner.scan(
        function (result) {
            alert('alert success');
            alert("We got a barcode\n" +
                  "Result: " + result.text + "\n" +
                  "Format: " + result.format + "\n" +
                  "Cancelled: " + result.cancelled);
        },
        function (error) {
            alert('alert error');
            alert("Scanning failed: " + error);
        },
        {
            preferFrontCamera : true, // iOS and Android
            showFlipCameraButton : true, // iOS and Android
            showTorchButton : true, // iOS and Android
            torchOn: false, // Android, launch with the torch switched on (if available)
            saveHistory: true, // Android, save scan history (default false)
            prompt : "Place a barcode inside the scan area", // Android
            resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
            formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
            orientation : "portrait", // Android only (portrait|landscape), default unset so it rotates with the device
            disableAnimations : true, // iOS
            disableSuccessBeep: false // iOS and Android
        }
     );`

**Comment by jcesarmobile** [comment]
I mean the cordova-android version
run `cordova platforms` and it will show android and a version number

So you say it only fails on Samsung Galaxy S4 GT-i9500 but works fine on Samsung Galaxy A3 SM-A300M?

**Comment by emb715** [comment]
cordova android version
    android 6.3.0

Yes, it fails on S4 but works fine on A3. For the moment i dont have more phones to test on.
