### ISSUE TITLE
Not found en iOS 11

### ISSUE THREAD

**Issue by naviegodenavia** [phonegap/phonegap-plugin-barcodescanner#696]
In android I'm perfect but instead I opened the camera and did not read any type of QR code. to what is due?? I do not see any error in the log, I have given it camera permissions and installed the extension

http://cordobo.com/2269-cordova-plugin-for-nscamerausagedescription-in-ios-10/ç

any ideas?

**Comment by jcesarmobile** [comment]
Please, when creating issues fill the template and provide all the requested information.
