### ISSUE TITLE
App crarshes on load.

### ISSUE THREAD

**Issue by jeevan-raj** [phonegap/phonegap-plugin-barcodescanner#699]
Expected Behaviour: App should load and onclick of a button, barcode scanner should start scan.

Actual Behaviour: App crashes as soon as the app is loaded/launched.

#### Steps to Reproduce

Platform and Version (eg. Android 5.0 or iOS 9.2.1) : Android 8.0.0

 (Android) What device vendor (e.g. Samsung, HTC, Sony...) : Oneplus 3T

 Cordova CLI version and cordova platform version

    cordova --version: 8.0.0
    cordova platforms: Android 6.0.3

Plugin version: 6.0.5

    cordova plugin version | grep phonegap-plugin-barcodescanner

#### Sample Code that illustrates the problem

 Logs taken while reproducing problem
--------- beginning of crash
07-04 21:11:15.071 19098 19098 E AndroidRuntime: FATAL EXCEPTION: main
07-04 21:11:15.071 19098 19098 E AndroidRuntime: Process: lucian.test.push, PID: 19098
07-04 21:11:15.071 19098 19098 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at yk.h(PG:625)
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at alE.run(Unknown Source:2)
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-04 21:11:15.071 19098 19098 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: FATAL EXCEPTION: main
07-04 21:12:25.058 19667 19667 E AndroidRuntime: Process: lucian.test.push, PID: 19667
07-04 21:12:25.058 19667 19667 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at yk.h(PG:625)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at alE.run(Unknown Source:2)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-04 21:12:25.058 19667 19667 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-04 21:12:25.061   461   461 E SELinux : avc:  denied  { find } for service=opdiagnose pid=19667 uid=10284 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager
07-04 21:12:25.066   461   461 E SELinux : avc:  denied  { find } for service=opdiagnose pid=19667 uid=10284 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager
07-04 21:12:25.067 19667 19667 W OPDiagnose: getService:OPDiagnoseService NULL
07-04 21:12:25.069   461   461 E SELinux : avc:  denied  { find } for service=opdiagnose pid=19667 uid=10284 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager
07-04 21:12:25.070 19667 19667 W OPDiagnose: getService:OPDiagnoseService NULL
07-04 21:12:25.073 19667 19667 D OSTracker: OS Event: crash

**Comment by jcesarmobile** [comment]
Latest plugin version is 8.0.0, try with that version.

If problem persists create a new issue and provide the code your are using.
