### ISSUE TITLE
RESULT_DISPLAY_DURATION_MS

### ISSUE THREAD

**Issue by ball-hayden** [phonegap/phonegap-plugin-barcodescanner#70]
I'm trying to pass `RESULT_DISPLAY_DURATION_MS` using the 3rd argument to scan. However, the zxing documentation specifies that the value must be presented as a `Long`.

I've made the following changes which allow this to work for me (and I'm happy to open a PR), but I wonder if there might be a better way, as this prevents passing `Integer` values such as `WIDTH` and `HEIGHT`?

https://github.com/phonegap/phonegap-plugin-barcodescanner/compare/master...SparkSeat:master

**Comment by FabryB** [comment]
How are you sending parameters with third option?

I tried option name and Intent,Scan.option_name and nothing...

**Comment by ball-hayden** [comment]
```
cordova.plugins.barcodeScanner.scan (result) =>
          # Success
        , ->
          # Errback
        , {
          RESULT_DISPLAY_DURATION_MS: 0,
          SCAN_FORMATS: 'QR_CODE',
          PROMPT_MESSAGE: 'Present QR Code'
        }
```

**Comment by FabryB** [comment]
it works, ty!

For your problem I suggest you add an
IF key is RESULT_DISPLAY_DURATION_MS inside the IF integer, so you can have both working
