### ISSUE TITLE
Invalid usage description check

### ISSUE THREAD

**Issue by oliversalzburg** [phonegap/phonegap-plugin-barcodescanner#700]
At https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/src/ios/CDVBarcodeScanner.mm#L142 you're checking if the `NSCameraUsageDescription` key is present in the plist.

This will fail if the key is translated and your plugin will abort for no good reason.

You need to look up the localized version as well if you feel like you need to make this check at all:
`[[NSBundle mainBundle] localizedStringForKey: @"NSCameraUsageDescription" value: nil table: @"InfoPlist"]`

**Comment by oliversalzburg** [comment]
You can cherry-pick 73d0f497b242627b33dcd6fbfb32d0d14501b100 if you want. Seems to work fine.

**Comment by oliversalzburg** [comment]
lol

**Comment by oliversalzburg** [comment]
You should rename **wontfix** to **dontcare** ;D

**Comment by purplecabbage** [comment]
cherry-picked, thanks for contributing.
