### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'barcodeScanner' of undefined"

### ISSUE THREAD

**Issue by ahsan154** [phonegap/phonegap-plugin-barcodescanner#707]
It should open barcode popup and allow to read barcode

"Uncaught TypeError: Cannot read property 'barcodeScanner' of undefined"

I  just created a fresh project, installed plugin and execute it. but i got above error

android 7.1.1 api 25

Samsung

Phonegap version 8.0.0
android 7.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner 8.0.0

     cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      },
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          preferFrontCamera : true, // iOS and Android
          showFlipCameraButton : true, // iOS and Android
          showTorchButton : true, // iOS and Android
          torchOn: true, // Android, launch with the torch switched on (if available)
          saveHistory: true, // Android, save scan history (default false)
          prompt : "Place a barcode inside the scan area", // Android
          resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
          formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          orientation : "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
          disableAnimations : true, // iOS
          disableSuccessBeep: false // iOS and Android
      }
   );

**Comment by jcesarmobile** [comment]
For some reason the plugin is not installed, uninstall, reinstall or even remove and re add the platform
