### ISSUE TITLE
Why plugin need allow permission to change system settings and how to avoid this?

### ISSUE THREAD

**Issue by transoceanic** [phonegap/phonegap-plugin-barcodescanner#709]
### Actual Behaviour
users are afraid to give permission for this
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by jcesarmobile** [comment]
Those are the permissions required by the plugin itself
https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/plugin.xml#L37-L39

We don't require that permission, it might come from zxing library that the plugin uses, but if that's the case, please, report it to zxing
