### ISSUE TITLE
Windows Phone 8.1 and Phonegap build

### ISSUE THREAD

**Issue by SingleID** [phonegap/phonegap-plugin-barcodescanner#71]
Does anyone have a working example of this plugin in a project made with PhoneGap build for Windows 8.1?

thanks

**Comment by ClaudeVernier** [comment]
Hi!  I would also love to see that !!!!!  
Thank you for asking.  :-)

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
