### ISSUE TITLE
Decoder function

### ISSUE THREAD

**Issue by realivanjx** [phonegap/phonegap-plugin-barcodescanner#714]
There must be a function to just decode the image (base64 if supported). I need to know what it is because I already use cordova camera preview plugin to get image and I don't want to use this plugin's camera.

Any help is highly appreciated!

**Comment by K68** [comment]
Maybe you can try this, https://github.com/cozmo/jsQR

A pure javascript QR code reading library. This library takes in raw images and will locate, extract and parse any QR code found within.
