### ISSUE TITLE
Use RSS_14 with iOS

### ISSUE THREAD

**Issue by Topheur** [phonegap/phonegap-plugin-barcodescanner#716]
Hello,

I would like to know if one day the scan of RSS_14 barcode will be implemented for iOS ? There is another way to scan this kind of barcode with iOS ?

Thanks

**Comment by jcesarmobile** [comment]
Those are the available types in the iOS sdk, I don’t see it
https://developer.apple.com/documentation/avfoundation/avmetadataobjecttype?language=objc
