### ISSUE TITLE
Barcode scan appears to block other plugins

### ISSUE THREAD

**Issue by mcosta53** [phonegap/phonegap-plugin-barcodescanner#721]
I'm trying to capture a geolocation on the spot where the the barcode is scanned; however, it appears the plugin blocks geolocation.watch and other plugins while scanning. Works perfectly okay on IOS but not on Android.

Accuracy is very bad on "GetCurrentPosition" right after a scan so a "Watch" while waiting on a scan is required; otherwise a delay must be added to improve accuracy, which is not the best way.

Is there a reason for blocking other plugins while scanning?

**Comment by jcesarmobile** [comment]
This is how some Android versions work, when you present an Intent (as this plugin does), the app launching the Intent gets paused until the Intent returns the result.
So this can't really be fixed on the plugin, check if you can enable your app to work in background somehow.
