### ISSUE TITLE
how to use with cordova

### ISSUE THREAD

**Issue by ledarky** [phonegap/phonegap-plugin-barcodescanner#723]
hello i want to know how to install this plugin on cordova project
when i try with cordova plugin add plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner.git it doesn't work

thanks

**Comment by jcesarmobile** [comment]
What’s the error? Cordova version?

**Comment by ledarky** [comment]
> Doesn't this work?
> cordova plugin add phonegap-plugin-barcodescanner

it doesn't work

**Comment by jcesarmobile** [comment]
If it fails to install it’s a Cordova problem or npm problem

**Comment by jcesarmobile** [comment]
If it fails to install it’s a Cordova problem or npm problem
