### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by SainathThota** [phonegap/phonegap-plugin-barcodescanner#724]
when app is jarsigned it crashes after we accept camera permission saying 

Error 👍  android.content.res.Resources$NotFoundException: File res/raw/beep.ogg

this does not happen before signing

**Comment by Bezlepkin** [comment]
I have the same problem....

**Comment by SainathThota** [comment]
@Bezlepkin  Did you find any solution for this

**Comment by Bezlepkin** [comment]
> @Bezlepkin Did you find any solution for this

Yes! I uncommented two lines in params:
prompt : "Place a barcode inside the scan area", // Android
formats : "QR_CODE", // default: all but PDF_417 and RSS_EXPANDED

Which line helped I did not check :)

**Comment by nelson-dt** [comment]
At my company we have an app using this plugin and the workaround posted by @Bezlepkin did not work for us. 

For us the plugin only causes a crash if the ringtone/notification volume is turned up. If all sounds are muted, the barcode scanner opens without issues.

**Comment by cheikhshift** [comment]
This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

In short, check if NSCameraUsageDescription is set...

**Comment by Bezlepkin** [comment]
> NSCameraUsageDescription

NSCameraUsageDescription it is key for IOS.

**Comment by JuliaRakitina** [comment]
> At my company we have an app using this plugin and the workaround posted by @Bezlepkin did not work.
> 
> For us the plugin only causes a crash if the ringtone/notification volume is turned up. If all sounds are muted, the barcode scanner opens without issues.
> 
> Edit: The app I'm building is only for Android, not iOS.
Same issue, mute works ok

**Comment by nelson-dt** [comment]
We solved this issue at my company by changing our build/release pipelines. We use Azure DevOps (formerly VSTS) and were zipping and unzipping the APK twice before signing it. We fixed the issue by changing the pipelines to no longer do the excessive zipping, and the issue went away. So it's not the jarsign step itself, but the combination of zipping/unzipping and THEN signing that was causing issues for us.

**Comment by JuliaRakitina** [comment]
Oh yes! I do the same zip/unzip twice. because of warning, I am cleaning META-INF folder
https://www.clemdesign.fr/en/blog/ionic-3-fix-warnings-about-version-files-in-meta-inf-of-apk-package

so have to find a way get rid of this warning not unzipping apk

**Comment by CheetahDev** [comment]
Had the same painful and anoying issue. We also have an additional process that includes post signing and compression.

As @nelson-dt said, the issue is not caused by the jarsign, but by the ressource compression. We turned off compression for the moment: jar cf --> jar cf0.

App size has trippled.
