### ISSUE TITLE
Crashed (closing) app after allow to camera on Android

### ISSUE THREAD

**Issue by Bezlepkin** [phonegap/phonegap-plugin-barcodescanner#725]
Hi! I testing barcodescanner on emulator and device, everywhere app closing after allow camera.
Pls HELP!

**Comment by jcesarmobile** [comment]
Provide all the data requested on the template

**Comment by Bezlepkin** [comment]
> Provide all the data requested on the template

hhhmmmm... i dont't understand.

`export default {
  name: 'app',
  components: {
    HelloWorld
  },
  methods: {
    scan() {
      // eslint-disable-next-line
      cordova.plugins.barcodeScanner.scan(
        function (result) {
            alert("We got a barcode\n" +
                  "Result: " + result.text + "\n" +
                  "Format: " + result.format + "\n" +
                  "Cancelled: " + result.cancelled);
        },
        function (error) {
            alert("Scanning failed: " + error);
        },
        {
            // preferFrontCamera : true, // iOS and Android
            // showFlipCameraButton : true, // iOS and Android
            // showTorchButton : true, // iOS and Android
            // torchOn: true, // Android, launch with the torch switched on (if available)
            // saveHistory: true, // Android, save scan history (default false)
            // prompt : "Place a barcode inside the scan area", // Android
            // resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
            // formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
            // orientation : "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
            // disableAnimations : true, // iOS
            // disableSuccessBeep: false // iOS and Android
        }
      );
    }
  }
}
</script>
`

Please, give example

**Comment by jcesarmobile** [comment]
When you create the issue, a template appears asking for things like Cordova version, plugin version, etc. You have to provide all the data, not delete it. So I’m going to close the issue. Create a new one and don’t delete the template this time
