### ISSUE TITLE
Searched in the following locations:       https://jcenter.bintray.com/com/android/support/support-v4/27.1.1/support-v4-27.1.1.jar

### ISSUE THREAD

**Issue by ylwhlhp** [phonegap/phonegap-plugin-barcodescanner#731]
cordova 7.1.0
  cordova platforms

Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-v4/27.1.1/support-v4-27.1.1.jar

**Comment by jcesarmobile** [comment]
This is a problem on bintray, the solution is to put google over bintray in the Cordova gradle files
