### ISSUE TITLE
Translation for errors

### ISSUE THREAD

**Issue by sjoerdloeve** [phonegap/phonegap-plugin-barcodescanner#732]
### Expected Behaviour
Translated error message

### Actual Behaviour
English error message

### Reproduce Scenario (including but not limited to)
Set localization to FR, NL, anything but EN and reject camera access to your app

#### Steps to Reproduce
Go to the settings app, scroll down for your app and disable camera access. No open your app and click the scan button. You get an Engligh error message, no matter what localization you did provide in *.plist

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 12

#### Cordova CLI version and cordova platform version
8.0.0

#### Plugin version
8.0.0

Ps. the 'close' button is correct translated to the chosen language.

**Comment by jcesarmobile** [comment]
The error messages are NSLocalizedString, but we don't provide translations, just the english default value
If you want to translate it you have to create the strings files and translate yourself.

**Comment by sjoerdloeve** [comment]
You are right about the text strings. But I can not find a possibility to translate the title "Scanning failed".
