### ISSUE TITLE
Android 9 clicking back while scanning exits app

### ISSUE THREAD

**Issue by AnupNair91** [phonegap/phonegap-plugin-barcodescanner#738]
### Expected Behaviour
clicking back button should go back to the previous page
### Actual Behaviour
exits app

tested on android 9
cordova cli 7.1.0

**Comment by hoshauch** [comment]
maybe the same issue like this: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/717

**Comment by AnupNair91** [comment]
Using Ionic's ionViewCanLeave lifecycle event seems to work in preventing the view from exiting.

**Comment by AnupNair91** [comment]
Within IonViewCanLeave() method we can either return true or false depending on if we want to leave that view, I am setting a boolean variable to false before the barcode.scan() method is called, now when the user  tries to exit while barcode scanner is on it wont exit the view as the ionViewCanLeave() returns that boolean false.

**Comment by swapnilp0x00** [comment]
That will prevent leaving of current page and fix the issue. But wouldn't it also prevent any navigation to other pages after setting that boolean to 'false'.

**Comment by jcesarmobile** [comment]
I think the idea is to set it to false when you call scan, and then set it to true once you receive the success or error callback

**Comment by swapnilp0x00** [comment]
Variable did not work for me.
This is the work around i came up with.

In scanner page 

```javascript 
ionViewCanLeave() {
    let canGoBack = this.canGoBackService.getValue();
    this.canGoBackService.setValue(true);
    return canGoBack;
  }```

And in cancellation of scan block i wrote

```javascript
if(barcodeData.cancelled) {
 if(this.platform.is('android'))
          this.canGoBackService.setValue(false);
}```

Dedicated service to maintain the boolean.

```javascript
import { Injectable } from '@angular/core';
@Injectable()
export class CanGoBackService {
	private canGoBack = true;
	constructor() {}
  
  public setValue(value: boolean) {
    this.canGoBack = value;
  }
  
  public getValue(): boolean {
    return this.canGoBack;
  } 
}```


And before all the transition from scan page i had manually set boolean to true.
```javascript
this.canGoBackService.setValue(true);
this.nav.push(MyPage)
```

This worked fine for me.
Still trying to find out better way.
