### ISSUE TITLE
Error configuring android:allowBackup on confix.xml

### ISSUE THREAD

**Issue by GiuDoxi** [phonegap/phonegap-plugin-barcodescanner#742]
Hi,

We are experiencing a problem on an Android system, configuring the config.xml with:
```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
       <application android:allowBackup="false" />
</edit-config>
```
With this configuration the AndroidManifest.xml file isn't built correctly, it hasn't references for the ZXing Activity and the app crash when we try to read a barcode, missing references are:
```
<activity android:clearTaskOnLaunch="true" android:configChanges="orientation|keyboardHidden|screenSize" android:exported="false" android:name="com.google.zxing.client.android.CaptureActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:windowSoftInputMode="stateAlwaysHidden" />
<activity android:label="Share" android:name="com.google.zxing.client.android.encode.EncodeActivity" />
```
But if we remove phonegap-plugin-barcodescanner and then add it again, AndroidManifest is built correctly.

cordova --version is 8.1.2 (cordova-lib@8.1.1)
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

Thanks for your time.

**Comment by GiuDoxi** [comment]
Hi,

We are experiencing a problem on an Android system, configuring the config.xml with:
```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
       <application android:allowBackup="false" />
</edit-config>
```
With this configuration the AndroidManifest.xml file isn't built correctly, it hasn't references for the ZXing Activity and the app crash when we try to read a barcode, missing references are:
```
<activity android:clearTaskOnLaunch="true" android:configChanges="orientation|keyboardHidden|screenSize" android:exported="false" android:name="com.google.zxing.client.android.CaptureActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:windowSoftInputMode="stateAlwaysHidden" />
<activity android:label="Share" android:name="com.google.zxing.client.android.encode.EncodeActivity" />
```
But if we remove phonegap-plugin-barcodescanner and then add it again, AndroidManifest is built correctly.

cordova --version is 8.1.2 (cordova-lib@8.1.1)
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

Thanks for your time.

**Comment by ljudbane** [comment]
Check the similar issue: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/743

The problem is that if you modify the same file (ex. AndroidManifest.xml) with <edit-config> in different plugins, then it won't properly resolve all the edits and only apply changes from one plugin.
Learned that the hard way when i deployed an application without proper permissions. I used similar solution to the one in above linked issue by using cordova hooks and modifying AndroidManifest.xml with scripts.
