### ISSUE TITLE
Failed to install my custom plugin, Error: There was a conflict trying to modify attributes with <edit-config> in my plugin

### ISSUE THREAD

**Issue by JackRo** [phonegap/phonegap-plugin-barcodescanner#743]
### my custom plugin's plugin.xml is like below:

    `<?xml version="1.0" encoding="utf-8"?>
    <plugin id="com-flux-location" version="1.0.0" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android">
	<name>
		com-flux-location
	</name>
	<js-module name="fluxLocation" src="www/location.js">
		<clobbers target="fluxLocation" />
	</js-module>
	<platform name="android">
		<preference name="GAODE_API_KEY_FOR_ANDROID" />
		<config-file parent="/*" target="res/xml/config.xml">
			<feature name="GaodeLocation">
				<param name="android-package" value="com.flux.location.GaodeLocation" />
			</feature>
		</config-file>
		<config-file parent="/manifest/application" target="AndroidManifest.xml">
			<meta-data android:name="com.amap.api.v2.apikey" android:value="$GAODE_API_KEY_FOR_ANDROID" />
			<service android:name="com.amap.api.location.APSService" android:enabled="true" />
			<service android:name="com.flux.location.service.LocationService" android:enabled="true" android:process=":remote" />
			<receiver android:name="com.flux.location.service.AlarmReceiver" android:exported="false">
				<intent-filter>
					<action android:name="android.intent.action.BOOT_COMPLETED" />
					<action android:name="android.intent.action.USER_PRESENT" />
					<action android:name="android.intent.action.ACTION_POWER_CONNECTED" />
					<action android:name="android.intent.action.ACTION_POWER_DISCONNECTED" />
				</intent-filter>
				<intent-filter>
					<action android:name="android.intent.action.PACKAGE_ADDED" />
					<action android:name="android.intent.action.PACKAGE_REMOVED" />
					<data android:scheme="package" />
				</intent-filter>
			</receiver>
		</config-file>
		<edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">
			<application android:name="com.flux.location.MyApp" />		
		</edit-config>
		<config-file parent="/*" target="AndroidManifest.xml">
			<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
			<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
			<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
			<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
			<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
			<uses-permission android:name="android.permission.INTERNET" />
			<uses-permission android:name="android.permission.READ_PHONE_STATE" />
			<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
			<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
			<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
		</config-file>

	</platform>
</plugin>
`

#### Cordova CLI version and cordova platform version

    cordova --version 8.0.0
    cordova platforms android 7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

    8.0.1

#### Sample Code that illustrates the problem

    i have no idea

#### Logs taken while reproducing problem

    Failed to install 'com-flux-location': Error: There was a conflict trying to modify attributes with <edit-config> in plugin com-flux-location. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before com-flux-location can be added. You may use --force to add the plugin and overwrite the conflicting attributes.
    at PlatformMunger.add_plugin_changes (/Users/jack/Desktop/demo/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:148:19)
    at /Users/jack/Desktop/demo/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:123:29
    at _fulfilled (/Users/jack/Desktop/demo/platforms/android/cordova/node_modules/q/q.js:854:54)
    at /Users/jack/Desktop/demo/platforms/android/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/jack/Desktop/demo/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/jack/Desktop/demo/platforms/android/cordova/node_modules/q/q.js:877:14
    at runSingle (/Users/jack/Desktop/demo/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/jack/Desktop/demo/platforms/android/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by manjunath143** [comment]
I am also facing same issue ,were you able to fix this issue ?

**Comment by JackRo** [comment]
> I am also facing same issue ,were you able to fix this issue ?

I have been able to fix this issue, but I fixed this issue by Cordova Hook mechanism. 

I removed the `edit-config` from my custom plugin's plugin.xml, then I used the Cordova Hook mechanism to add My MyApp class to add to my Cordova Project.

If you want to fix this issue, you also could see [Cordova Hook Guide](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/index.html) first.

**Comment by videmort** [comment]
@JackRo Can you provide your hook example?

**Comment by JackRo** [comment]
@videmort The hook example like this: 

the plugin.xml like below:

`<platform name="android">
		<hook type="after_plugin_install" src="scripts/afterPluginInstall.js" />
		<hook type="before_plugin_uninstall" src="scripts/beforePluginUninstall.js" />`

the afterPluginInstall.js like below:

`#!/usr/bin/env node

module.exports = function(context) {
  let fs = context.requireCordovaModule('fs'),
    path = context.requireCordovaModule('path');

  // android项目目录
  let platformAndroidDir = path.join(context.opts.projectRoot, 'platforms/android');

  // android项目的app module目录
  let platformAndroidAppModuleDir = path.join(platformAndroidDir, 'app');

  // android项目的manifest文件
  let androidManifestFile = path.join(platformAndroidAppModuleDir, 'src/main/AndroidManifest.xml');

  if (fs.existsSync(androidManifestFile)) {

    fs.readFile(androidManifestFile, 'UTF-8', function(err, data) {
      if (err) {
        throw new Error('Unable to find AndroidManifest.xml: ' + err);
      }

      // 要配置到Android manifest文件的Android Application类
      let applicationClassName = 'com.jackro.example.MyApp';

      if (data.indexOf(applicationClassName) === -1) {

        let result = data.replace(/<application/g, '<application android:name="' + applicationClassName + '"');

        fs.writeFile(androidManifestFile, result, 'UTF-8', function(err) {
          if (err)
            throw new Error('Unable to write into AndroidManifest.xml: ' + err);
        })
      }
    });
  }
};`

the beforePluginUninstall.js like below:

`#!/usr/bin/env node

module.exports = function(context) {

  let fs = context.requireCordovaModule('fs'),
    path = context.requireCordovaModule('path');

  // android项目目录
  let platformAndroidDir = path.join(context.opts.projectRoot, 'platforms/android');

  // android项目的app module目录
  let platformAndroidAppModuleDir = path.join(platformAndroidDir, 'app');

  // android项目的manifest文件
  let androidManifestFile = path.join(platformAndroidAppModuleDir, 'src/main/AndroidManifest.xml');

  // android app module的gradle文件
  let androidAppModuleGradleFile = path.join(platformAndroidAppModuleDir, 'build.gradle');

  if (fs.existsSync(androidManifestFile)) {

    fs.readFile(androidManifestFile, 'UTF-8', function(err, data) {
      if (err) {
        throw new Error('Unable to find AndroidManifest.xml: ' + err);
      }

      // Android manifest文件中要删除的Android Application配置
      let applicationClassConfig = 'android:name="com.jackro.example.MyApp"';

      if (data.indexOf(applicationClassConfig) !== -1) {

        let result = data.replace(applicationClassConfig, '');

        fs.writeFile(androidManifestFile, result, 'UTF-8', function(err) {
          if (err)
            throw new Error('Unable to write into AndroidManifest.xml: ' + err);
        })
      }
    });
  }
  if (fs.existsSync(androidAppModuleGradleFile)) {

    fs.readFile(androidAppModuleGradleFile, 'UTF-8', function(err, data) {
      if (err) {
        throw new Error('Unable to find build.gradle: ' + err);
      }

      // 卸载插件时android项目的app module gradle配置文件里要删除的一行配置
      let androidAppModuleGradleConfigLine = 'apply from: "../com-jackro-location/app-jackrolocation.gradle"';

      if (data.indexOf(androidAppModuleGradleConfigLine) !== -1) {

        let result = data.replace(androidAppModuleGradleConfigLine, '');

        fs.writeFile(androidAppModuleGradleFile, result, 'UTF-8', function(err) {
          if (err)
            throw new Error('Unable to write into build.gradle: ' + err);
        })
      }
    });
  }
};`
