### ISSUE TITLE
Failed to build in Phonegap with cordova-plugin-facebook4

### ISSUE THREAD

**Issue by xale76** [phonegap/phonegap-plugin-barcodescanner#745]
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by jcesarmobile** [comment]
Duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/535
