### ISSUE TITLE
Unable to build my Phonegap Android App for com.android.build.api.transform.TransformException

### ISSUE THREAD

**Issue by xale76** [phonegap/phonegap-plugin-barcodescanner#746]
Cordova CLI 7.1.0

I'm stuck from days in this problem and nobody helps me.
I build with Phonegap and I need to use facebook4 plugin ( facebook site tells me to update to Facebook SDK for iOS v4.39.0, is it mandatory? I don't know).

So I updated facebook4 plugin to latest version and now I got error :
`com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class`

I know that is for same library blablabla but no solution. It's phonegap, so I cannot change plugins, just change config. I tried with 

```
<platform name="android">
    <framework src="com.facebook.android:facebook-android-sdk:4.25.0" />
</platform>
```

in config.xml but nothing changes. Please I need to release the app

**Comment by viking2917** [comment]
@xale76, I have not seen that particular error, but check out these threads, about the various issues/versions when using this plugin with Facebook4 plugin: 

https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/535.
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/606

I use 

phonegap-plugin-barcodescanner 7.0.2 "BarcodeScanner"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"

together and have gotten it work following comments in the above bug threads
