### ISSUE TITLE
Can't close scanner within a service

### ISSUE THREAD

**Issue by l3vick** [phonegap/phonegap-plugin-barcodescanner#747]
I am using barcode scanner to read QR while a service is running on background to receive instant payments.

I am receiving the payment and I thought I could fire an event subscribed in the page where the barcode is scanning. The event is also correctly fired but the camera is not closed with this.navCtrl.pop(). and if I alert something is displayed behind the CaptureActivity

Is there any way to close the Scanner without "scanning" ?

Thanks in advance.

**Comment by PimentelKJ** [comment]
I also would like to be able to do this.

**Comment by cbxp** [comment]
+1

We also need to close barcode scanner automatically when user session expires.
