### ISSUE TITLE
barcode data 'undefined'

### ISSUE THREAD

**Issue by ashtonsmith** [phonegap/phonegap-plugin-barcodescanner#75]
Hi - great plugin - works awesome in android - just got a little problem when running on a blackberry10 device, where the barcode is returned as undefined 

see code extract below

![image](https://cloud.githubusercontent.com/assets/7677767/9864478/31cdeb48-5b9e-11e5-8a8d-d1588b7e2a88.png)

On android this returns a valid barcode value, and the application continues happily

![image](https://cloud.githubusercontent.com/assets/7677767/9864505/85455176-5b9e-11e5-91af-c8a9147f2073.png)

However on blackberry 10, the scanner isnt returning a valid result

![image](https://cloud.githubusercontent.com/assets/7677767/9864544/c6575254-5b9e-11e5-82fb-f8f83ce2382b.png)

can you help me / tell me what im doing wrong?? Thanks heaps

**Comment by timwindsor** [comment]
I'll take a look - it might be returning slightly different data, though I thought I had matched it up. It may help to have a small sample to reproduce it.

**Comment by ashtonsmith** [comment]
sure thing, Thanks, let me know what you need.

basically im just trying to get the barcode data, then pass that an http.get request to get some information on that barcode, for use at a expo, thanks

**Comment by ashtonsmith** [comment]
Any luck? sorry to hassle - im meant to have this app working for an event tomorrow..i tried building from scratch in webworks, but it behaved exactly the same.Thanks

**Comment by ashtonsmith** [comment]
Think i've found the issue, for some reason in blackberry result.text doesnt return the string, however just result returns the whole array.

Heres a copy of the code:
![image](https://cloud.githubusercontent.com/assets/7677767/9890169/66f40762-5c52-11e5-9202-f15751677be8.png)


and heres a copy of the log on bb10 device:
![image](https://cloud.githubusercontent.com/assets/7677767/9890263/1668e2f8-5c53-11e5-98c1-58e922a119e3.png)

does this make sense? 
Thanks

**Comment by timwindsor** [comment]
Right. It's expecting a JSON.parse to be done on the result first. I must have misread the implementation on the other platforms.

**Comment by timwindsor** [comment]
This is fixed in #78.
It's only really a couple lines so you can drop it in place if you want.

**Comment by ashtonsmith** [comment]
Thanks for that - yeah ive done it in app - something else im coming across is that there is quite a wait for the scanner after the barcode is scanned before the next thing can happen - once again its fine in android.

its causing about a 30-40second wait each time a code is scanned, and returning a nasty error:
XMLHttpRequest Exception 101
then the http.get request succeeds, and continues
See error Message below:

![image](https://cloud.githubusercontent.com/assets/7677767/9895068/5392ef1c-5c7f-11e5-8670-ce7978f43228.png)

this doesnt happen if i comment out the barcode scanner part, and just feed some fake data to a variable into the get request.

i was wondering if it had to do this this - the barcode scanner staying as "pending" in the network tab (see the timeline extending onwards upwards of 1 minute)

![image](https://cloud.githubusercontent.com/assets/7677767/9895104/c9bb0ef4-5c7f-11e5-9224-f40159090fca.png)


Thanks, i really appreciate your help on this

**Comment by timwindsor** [comment]
Yeah, I've been seeing that too. There's something weird going on there that I'll have to look into. I didn't notice it before I merged the code in, so i think something happened in the merge.

**Comment by ashtonsmith** [comment]
Thansk - i tried moving the this.stopRead inside the reveivedevent handler, but im afraid im a bit out of my league here :)

**Comment by timwindsor** [comment]
Think I've found it - I had a workaround in for an older issue with the platform, but that's fixed now. Just update this line: https://github.com/timwindsor/phonegap-plugin-barcodescanner/blob/master/src/blackberry10/index.js#L42

**Comment by ashtonsmith** [comment]
so basically just uncomment line 42 in blackberry10/index.js ?

Thanks

**Comment by timwindsor** [comment]
Yeah, that's it

**Comment by ashtonsmith** [comment]
still got the delay.. , please see below

![image](https://cloud.githubusercontent.com/assets/7677767/9918262/e5826fca-5d19-11e5-9c15-62e9be5cbed3.png)


any thoughts?

**Comment by timwindsor** [comment]
I'm not seeing it here, but I bet that you are on 3.7.0 of cordova-blackberry, and I'm testing with 3.8.0. Can you try updating the platform (ionic platform update blackberry10) and you probably also need to be on cordova 5.3.1

**Comment by ashtonsmith** [comment]
thanks - its better - now i get this-- any other thoughts?
![image](https://cloud.githubusercontent.com/assets/7677767/9919290/fe802d86-5d1f-11e5-8d7b-89dc26ab8bf4.png)

**Comment by timwindsor** [comment]
So it's working better, but you're still getting that exception?
I'm not longer able to reproduce the issue here, and I'm not sure what the difference could be between my sample and yours.

Can you confirm the version of your blackberry10 platform, cordova, and the OS of the device you're running on? Is your sample something that you can send me, or is it something you can strip out into a minimal sample to send?

**Comment by ashtonsmith** [comment]
Sure - im working on Windows 8.1, blackberry 10.3.2, cordova 5.3.1, blackberry10 3.8.0-dev

heres a minimalised copy of the code (the scanbarcode function, and the getvisitor function)


---scan barcode function ---

$scope.visitordata = [];
          $scope.scanBarcode = function() {
            cordova.plugins.barcodeScanner.scan(
                function (result) {
                    $scope.barcode = JSON.parse(result);
                    console.log('Found a barcode, the value is ' +$scope.barcode.text);
                    var barcode = $scope.barcode.text;
                    var barCode =  barcode.toString();
                 $scope.getVisitor(barCode);
                                    
                });

--end scan function ---

--- begin getvisitor function ---
   $scope.getVisitor = function(barCode) {
        console.log('getVisitor has been passed a barcode: ' + barCode);
                $http({
                url: '***url to api here ***',
                method: 'GET',
                async: 'false',
                datatype: 'JSON',
                headers: {
                        'Content-type': 'application/json'
                        },
                params: {
                    apiKey: '***Secret***',
                    method: 'getVisitor',
                    event: '12125',
                    barcode: barCode,
                      }   
            }).success(function(data){
                $scope.visitordata = data;
                console.log($scope.visitordata);
                $scope.openModal();
            });
    }



---end getvisitor function ---

**Comment by ashtonsmith** [comment]
didnt mention the devices are in workspace only mode on a BES12 server. the event is due to start in 30 minutes, so might just have to grin and bear it for now...

Thanks for all your help.

**Comment by timwindsor** [comment]
I hope your event went well despite not having this all worked out. I've been testing in the work perimeter on my device and I can't reproduce this issue. I'm wondering if it may be due to the way that your scanBarcode function is getting called. I'm not sure about that, cause it does seem to have the cordova calls in the stack.

**Comment by ashtonsmith** [comment]
Thanks - would you mind sharing how you call the scanBarcode function, so i can adjust and try?

Thanks

**Comment by timwindsor** [comment]
I just modified the standard Cordova default app to add a button and output div, and add this to index.js:

```javascript
scan: function () {
    	cordova.plugins.barcodeScanner.scan(
    		function (result) {
    			console.log(result);
    			document.getElementById('output').innerText += JSON.stringify(result);
    		},
    		function (error) {
    			console.log(error);
    			document.getElementById('output').innerText += error;
    		});
    }
```

**Comment by ashtonsmith** [comment]
Hello Tim, Ive got back ontot his project again, and started a completely new cordova project.

See below

app.js
----------------------------
```
//set up the app
var app = angular.module('checkIN', ['ionic']);
//set up the main controller
app.controller("MainCtrl", function($scope) {
    //setup scanbarcode function
    $scope.scanBarcode = function() {
        cordova.plugins.barcodeScanner.scan(
            function(result) {
                $scope.barCode = result.text
                barCode = result.text
                alert(barCode)
            });
    }
    
})
```

this is an extract from my index.html

index.html
--------------------------------
```
  <body ng-app="checkIN">

    <ion-pane>
      <ion-header-bar class="bar-stable">
        <h1 class="title">checkIN</h1>
      </ion-header-bar>
      <ion-content class = "page" ng-controller = "MainCtrl">
          <button class = "button button-full button-positive scan-button" ng-click = "scanBarcode()">Scan</button>
      </ion-content>
    </ion-pane>
  </body>
```


The alert pops up in good time, (instantly) however after the alert is dismissed (OK is tapped), the button will not respond again, and after a minute or so, this show up in the webinspector console.

Web Inspector Console message
-------------------------------------------
```
makeSyncCall failed 
XMLHttpRequestException {code: 101, message: "NETWORK_ERR: XMLHttpRequest Exception 101", name: "NETWORK_ERR", stack: "send@[native code]↵makeSyncCall@local:///cordova.j…End@local:///lib/ionic/js/ionic.bundle.js:2977:12", line: 886…}
code: 101
constructor: XMLHttpRequestExceptionConstructor
line: 886
message: "NETWORK_ERR: XMLHttpRequest Exception 101"
name: "NETWORK_ERR"
sourceURL: "local:///cordova.js"
stack: "send@[native code]↵makeSyncCall@local:///cordova.js:886:24↵exports@local:///cordova.js:932:39↵scan@local:///plugins/phonegap-plugin-barcodescanner/www/barcodescanner.js:99:8↵scanBarcode@local:///js/app.js:8:43↵fn↵local:///lib/ionic/js/ionic.bundle.js:57514:20↵$eval@local:///lib/ionic/js/ionic.bundle.js:24673:27↵$apply@local:///lib/ionic/js/ionic.bundle.js:24772:27↵local:///lib/ionic/js/ionic.bundle.js:57513:18↵eventHandler@local:///lib/ionic/js/ionic.bundle.js:12098:24↵dispatchEvent@[native code]↵triggerMouseEvent@local:///lib/ionic/js/ionic.bundle.js:2865:19↵tapClick@local:///lib/ionic/js/ionic.bundle.js:2854:19↵tapTouchEnd@local:///lib/ionic/js/ionic.bundle.js:2977:12"
__proto__: XMLHttpRequestExceptionPrototype
 console-via-logger.js:173
(anonymous function) console-via-logger.js:173
makeSyncCall cordova.js:889
exports cordova.js:932
scan barcodescanner.js:99
scanBarcode app.js:8
fn
(anonymous function) ionic.bundle.js:57514
$eval ionic.bundle.js:24673
$apply ionic.bundle.js:24772
(anonymous function) ionic.bundle.js:57513
eventHandler ionic.bundle.js:12098
dispatchEvent
triggerMouseEvent ionic.bundle.js:2865
tapClick ionic.bundle.js:2854
tapTouchEnd
```

screenshot below

![image](https://cloud.githubusercontent.com/assets/7677767/10497986/94e34388-7325-11e5-89eb-9b966a0af7fd.png)


Appreciate any further thoughts.

Thanks

**Comment by timwindsor** [comment]
I tried with a new ionic project and inserted your code. It seems to work fine on my device. Make sure you're using the latest code from GitHub - I don't think they've published the changes I've made to NPM yet. You'll need to remove the plugin and add it either from the repo link, or by cloning it locally and using the file path.

Here's my test project if you want to compare: https://app.box.com/s/2m491wg8o5g3hxwao709sf9mger3hwga

**Comment by stevengill** [comment]
@timwindsor just published latest to npm and gave you access to publish :)

**Comment by ashtonsmith** [comment]
Thanks very much guys, its much better :)

**Comment by timwindsor** [comment]
Awesome! Thanks for helping me track down those issues :smiley:
