### ISSUE TITLE
Using cordova prepare windows fails to put zxing in Extensions of AppxManifest

### ISSUE THREAD

**Issue by cdipierr** [phonegap/phonegap-plugin-barcodescanner#751]
### Expected Behaviour
When the plugin is removed and re-added, an extension is created in AppxManifest.xml built files and all works as expected. I would expect the same behavior after subsequent cordova prepare windows

### Actual Behaviour
cordova prepare windows removes those extensions

### Reproduce Scenario (including but not limited to)
Add plugin to project, build and run (works ok), run cordova prepare windows, access to barcode scanner fails with a class not registered error

#### Steps to Reproduce
Add plugin to project, build and run (works ok), run cordova prepare windows, access to barcode scanner fails with a class not registered error

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Windows 10

#### Cordova CLI version and cordova platform version

Cordova 8.0.0
Windows platform 4.4.3

#### Plugin version
8.0.1

**Comment by ccalloway-irespond** [comment]
I'm also experiencing a very similar issue (or maybe the same...) when building for Android.  The following lines are added to the AndroidManifest.xml on the initial build (or adding the plugin) and removed on subsequent builds:

`<activity android:clearTaskOnLaunch="true" android:configChanges="orientation|keyboardHidden|screenSize" android:exported="false" android:name="com.google.zxing.client.android.CaptureActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:windowSoftInputMode="stateAlwaysHidden" />
        <activity android:label="Share" android:name="com.google.zxing.client.android.encode.EncodeActivity" />`

This causes the my app to crash when attempting to launch the barcode scanner.

As a workaround I'm manually adding these lines using the <edit-config> tag in my config.xml.

`<edit-config file="AndroidManifest.xml" mode="replace" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <activity android:clearTaskOnLaunch="true" android:configChanges="orientation|keyboardHidden|screenSize" android:exported="false" android:name="com.google.zxing.client.android.CaptureActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:windowSoftInputMode="stateAlwaysHidden" />
            <activity android:label="Share" android:name="com.google.zxing.client.android.encode.EncodeActivity" />
        </edit-config>`

**Comment by mac89** [comment]
I get the same `class not registered` error on subsequent builds on the Windows platform. Using Visual Studio 2017.
