### ISSUE TITLE
Plugin not working in case of IOS 

### ISSUE THREAD

**Issue by Rajivsareddy** [phonegap/phonegap-plugin-barcodescanner#759]
### Expected Behaviour
Open Scanner plugin 
Plugin ask for camera permission
User selects denied
The plugin should fall back to fail method

### Actual Behaviour
Open Scanner plugin 
Plugin ask for camera permission
User selects denied
![img_3813](https://user-images.githubusercontent.com/18317786/51153167-1bccf780-183d-11e9-9c57-aebd8205e1b7.jpeg)
Plugin opens with no camera view
![img_3804](https://user-images.githubusercontent.com/18317786/51153192-3606d580-183d-11e9-8321-ae103c671f67.jpeg)
The user needs to click on the cancel button
Plugin calls success method with the response as canceled true.

### Reproduce Scenario (including but not limited to)
{code}
var barCodeConfig = {
  preferFrontCamera: false, // iOS and Android
  showFlipCameraButton: true, // iOS and Android
  showTorchButton: true, // iOS and Android
  torchOn: false, // Android, launch with the torch switched on (if available)
  saveHistory: false, // Android, save scan history (default false)
  prompt: 'Place the barcode inside the scan area', // Android
  resultDisplayDuration: 0, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
  orientation: 'portrait', // Android only (portrait|landscape), default unset so it rotates with the device
  disableAnimations: true, // iOS
  disableSuccessBeep: false // iOS and Android
}

cordova.plugins.barcodeScanner.scan(
    function (result) {
      sucess(result)
    },
    function () {
      failure({cameraAccess: false})
    }, barCodeConfig
  )
{code}
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iPhone 7Plus(12.1.2)
#### Cordova CLI version and cordova platform version

8.1.2 (cordova-lib@8.1.1)
Installed platforms:
  android 7.1.4
  ios 4.5.5

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner
    phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

**Comment by aradjdi** [comment]
+1
