### ISSUE TITLE
Plugin unable to scan PDF417 driving license

### ISSUE THREAD

**Issue by gilbertngandu** [phonegap/phonegap-plugin-barcodescanner#760]
### Expected Behaviour
Drivers license scan should return the data
### Actual Behaviour
Unable to scan PDF417. The plugin works well with vehicle license disk but it struggling with more dense PDF417 like the driving license in the picture below. Plugin such as https://github.com/manateeworks/phonegap-manateeworks-v3 are able to read the content of the image below:
https://user-images.githubusercontent.com/968412/37446065-e0878f0a-2823-11e8-9542-9af11132852c.png
### Reproduce Scenario (including but not limited to)
Try scanning the following image 
https://user-images.githubusercontent.com/968412/37446065-e0878f0a-2823-11e8-9542-9af11132852c.png
#### Steps to Reproduce
Try scanning the following image 
https://user-images.githubusercontent.com/968412/37446065-e0878f0a-2823-11e8-9542-9af11132852c.png
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

#### Sample Code that illustrates the problem
this.barcodeScanner.scan({formats: "PDF_417", showTorchButton:true}).then(barcodeData => { });

**Comment by jcesarmobile** [comment]
The plugin just uses zxing, so you should report it to them, unless they already improved it and our version didn’t include those changes
