### ISSUE TITLE
PhoneGap Build - Android wont build

### ISSUE THREAD

**Issue by AlexPashley** [phonegap/phonegap-plugin-barcodescanner#763]
### Expected Behaviour

Android build succesfully

### Actual Behaviour

android fails to build

#### Cordova CLI version and cordova platform version

    cordova --version 8.0.0

#### Plugin version
I think I've tried every possible barcodescanner version with every possible ANDROID_SUPPORT_V4_VERSION version 

#### Sample Code that illustrates the problem

<variable name="ANDROID_SUPPORT_V4_VERSION" value="24+" />
<plugin name="cordova-plugin-device" source="npm" />
<plugin name="cordova-plugin-whitelist" source="npm" />
<plugin name="cordova-plugin-dialogs" source="npm" />
<plugin name="cordova-plugin-inappbrowser" source="npm" />
<plugin name="cordova-plugin-x-socialsharing" spec="5.4.0" />
<plugin name="cordova-plugin-statusbar" spec="2.4.2" />
<plugin name="phonegap-plugin-push" spec="2.1.3" />
<plugin name="cordova-plugin-console" />
<plugin name="phonegap-plugin-barcodescanner" spec="6.0.8" />
<plugin name="cordova-plugin-camera" spec="2.4.1" />
<plugin name="cordova-plugin-geolocation" spec="2.4.3" />

#### Logs taken while reproducing problem

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:app:processDebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 18 cannot be smaller than version 19 declared in library [:CordovaLib] /CordovaLib/build/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 18
  	Suggestion: use a compatible library with a minSdk of at most 18,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
24 actionable tasks: 24 executed
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/app/src/main/AndroidManifest.xml:39:5-74 Error:
	uses-sdk:minSdkVersion 18 cannot be smaller than version 19 declared in library [:CordovaLib] /CordovaLib/build/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 18
	Suggestion: use a compatible library with a minSdk of at most 18,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 18 cannot be smaller than version 19 declared in library [:CordovaLib] /CordovaLib/build/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 18
  	Suggestion: use a compatible library with a minSdk of at most 18,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

### Help with PhoneGap Build
I've seen theres endless topics and discussions about using this plugin with the cli and nothing really with phonegap build. Some help here would be most appreciated.

I can confirm its barcode scanner because as soon as I remove plugin, everything builds succesfully

**Comment by jcesarmobile** [comment]
That error is telling you that you are setting the min SDKs to 18 but the Cordova version you use requires 19.
This plugin doesn’t set that preference, so not sure why it works when you remove it, but you are probably doing something else wrong

**Comment by AlexPashley** [comment]
I have changed the misdk version to 19 and still receiving similar error
