### ISSUE TITLE
IONIC ERROR: Object(..) is not a function! BarcodeScanner.scan()

### ISSUE THREAD

**Issue by caioshing1** [phonegap/phonegap-plugin-barcodescanner#766]
Hello,
 I was having a problem with the BarcodeScanner in my Ionic project so I created other application and I created another simple project that only contains one button that calls BarcodeScanner.scan() but it gave the same problem:

> ERROR TypeError: Object(...) is not a function
>     at QRScanner.prepare (index.js:28)
>     at HomePage.webpackJsonp.340.HomePage.scanCode (home.ts:15)
>     at Object.eval [as handleEvent] (HomePage.html:14)
>     at handleEvent (core.js:13589)
>     at callWithDebugContext (core.js:15098)
>     at Object.debugHandleEvent [as handleEvent] (core.js:14685)
>     at dispatchEvent (core.js:10004)
>     at core.js:10629
>     at HTMLButtonElement.<anonymous> (platform-browser.js:2628)
>     at t.invokeTask (polyfills.js:3)

This occurs when I click in this button:
`<button ion-button full (click)="scanCode()"><ion-icon name="qr-scanner"></ion-icon>ScanCode</button>`
That calls this simple function:
```
scanCode(){
  	this.barcodeScanner.scan().then(barcodeData =>{
  		this.scannedCode = barcodeData.text;
  	})
  }
```
All imports are corrects:
home.ts: 
```
import {BarcodeScanner} from '@ionic-native/barcode-scanner/ngx';
constructor(public navCtrl: NavController, private barcodeScanner:BarcodeScanner) {

  }
```
app.module.ts:
```
import {BarcodeScanner} from '@ionic-native/barcode-scanner/ngx';
providers: [
    ...
    BarcodeScanner
  ]
```
Ionic version: 4.8.2 I then upgraded to 4.10.3 and continued giving error

Please someone help me I already searched for this problem but I never saw the answer;
Ty

**Comment by jcesarmobile** [comment]
Can you provide the sample project you created?

**Comment by caioshing1** [comment]
The project only has the home page with the button described and one function in home.ts which calls the BarcodeScanner.scan(). And,  of course, the plugin BarcodeScanner but i can provide the project
[project.zip](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/2910568/project.zip)

**Comment by jcesarmobile** [comment]
You are using Ionic 3, I don't think it's compatible with ngx
Check the docs about how to use ionic native with ionic 3
https://ionicframework.com/docs/v3/native/barcode-scanner/

**Comment by caioshing1** [comment]
Thank you very much. You solved my problem.
