### ISSUE TITLE
EXC_BAD_INSTRUCTION when running plugin in iOS simulator

### ISSUE THREAD

**Issue by gregorwolf** [phonegap/phonegap-plugin-barcodescanner#767]
### Expected Behaviour

When triggering the scan function also in the iOS simulator the camera should appear

### Actual Behaviour

When triggering the scan function the method barcodeScanFailed in CDVBarcodeScanner.mm is triggered and Xcode shows this error message:
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

#### Steps to Reproduce

Run any app including this plugin in the iOS Simulator.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 12.1

#### Cordova CLI version and cordova platform version

    cordova --version
8.1.2 (cordova-lib@8.1.1)
    cordova platforms
Installed platforms:
  android 7.1.4
  ios 4.5.5

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

#### Sample Code that illustrates the problem

Just trigger scan.

#### Logs taken while reproducing problem

see before.

**Comment by gregorwolf** [comment]
Seems to be the same issue as reported in #628

**Comment by dingezzz** [comment]
Same issue here. Installed a new cordova project and this issue is still present

**Comment by JavierPAYTEF** [comment]
This is happenning to me as well when running it in the Simulator. The plugin is trying to return the message "unable to obtain video capture device", which is fine since the camera is not available in the Simulator.
The error is thrown in the call to "dispatch_sync" within "barcodeScanFailed". I don't quite understand dispatch_sync but I'm guessing is something to do with the thread or the queue being wrong, since this error is generated way before starting the actual scan process.
The error is returned in setUpCaptureSession line 489:
```Ojective-C
device = [AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo];
if (!device) return @"unable to obtain video capture device";
```

This is the Stack Trace:
> #0	0x0000000114e8ea19 in __DISPATCH_WAIT_FOR_QUEUE__ ()
> #1	0x00007ffee0b56cf0 in 0x7ffee0b56cf0 ()
> #2	0x0000000114e8e3f0 in _dispatch_sync_f_slow ()
> #3	0x000000010f0c25fa in ::-[CDVbcsProcessor barcodeScanFailed:](NSString *) at /.../platforms/ios/Project/Plugins/phonegap-plugin-barcodescanner/CDVBarcodeScanner.mm:431
> #4	0x000000010f0c117e in ::-[CDVbcsProcessor scanBarcode]() at /.../platforms/ios/Project/Plugins/phonegap-plugin-barcodescanner/CDVBarcodeScanner.mm:347
> #5	0x000000010ff70431 in __NSFireDelayedPerform ()
> #6	0x0000000112e33f34 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
> #7	0x0000000112e33b32 in __CFRunLoopDoTimer ()
> #8	0x0000000112e3339a in __CFRunLoopDoTimers ()
> #9	0x0000000112e2da1c in __CFRunLoopRun ()
> #10	0x0000000112e2ce11 in CFRunLoopRunSpecific ()
> #11	0x000000011b4e81dd in GSEventRunModal ()
> #12	0x0000000121fcc81d in UIApplicationMain ()
> #13	0x000000010f0a71f1 in main at /.../platforms/ios/Project/main.m:32
