### ISSUE TITLE
Camera doesn't focus (Android 5.0.1, LG Leon)

### ISSUE THREAD

**Issue by invalidusernam3** [phonegap/phonegap-plugin-barcodescanner#77]
When scanning, the camera doesn't auto focus well and touching the screen doesn't set the focus of the camera making it virtually impossible to scan. The normal camera application on the device does auto and manual focus.

Is there a way to manually call the focus in a timeout?
Is there a way to enable touch to focus?

Android 5.0.1
LG Leon
Cordova 5.3.1

**Comment by xAlexo** [comment]
+1

**Comment by invalidusernam3** [comment]
@xAlexo I never found a solution to this, but I did find that turning the flashlight on (volume up button) made quite a big difference. But in the end we switched to using QR codes instead of barcodes, which were far easier to read
