### ISSUE TITLE
Support cordova-cli 9.0.0 - requireCordovaModule deprecation

### ISSUE THREAD

**Issue by josersleal** [phonegap/phonegap-plugin-barcodescanner#775]
### Expected Behaviour
The use of context.requireCordovaModule for non-cordova dependencies has been removed, and suggests you now add the dependency to the plugins package.json and require'd normally.

[apache/cordova-lib#707](https://github.com/apache/cordova-lib/pull/707)
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by stevesum** [comment]
Anything about this pull request? When will be merged?
