### ISSUE TITLE
Build getting Failed: Support cordova-cli 9.0.0 - requireCordovaModule deprecation

### ISSUE THREAD

**Issue by vinayak-dataman** [phonegap/phonegap-plugin-barcodescanner#779]
I am getting following error when creating build for android and ios
Installing "phonegap-plugin-barcodescanner" for android
Subproject Path: CordovaLib
Subproject Path: app
Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by stevesum** [comment]
Anything with this pull request?
