### ISSUE TITLE
Not able to scan some PDF_417 barcodes on IOS devices

### ISSUE THREAD

**Issue by yashdeeppatidar** [phonegap/phonegap-plugin-barcodescanner#783]
### Expected Behaviour
Should scan all the PDF_417 barcodes on Android and IOS

### Actual Behaviour

Not able to scan some PDF_417 barcodes on IOS devices using Ionic 3 application. 
Works fine on Android devices.

### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 12.1.4

#### Cordova CLI version and cordova platform version

"Cordova CLI": "8.0.0"
"cordova-android": "~7.1.4",
"cordova-ios": "4.5.5",

#### Plugin version

"phonegap-plugin-barcodescanner": "^8.0.1"

**Comment by jcesarmobile** [comment]
can you show your code? And provide a sample PDF_417 image?
I've just tested with one of the PDF_417 google results and worked fine.
