### ISSUE TITLE
Barcode scanner working fine Phonegap Developer but after build not open camera.

### ISSUE THREAD

**Issue by emreoz** [phonegap/phonegap-plugin-barcodescanner#789]
I use phonegap-plugin-barcodescanner   8.0.0. and ı have developed apps on phonegap-developer successfully. But when i after build it not open camera therefore i cant read barcode. I builded on adobe cloud system. What is my problem ? Thank you.

**Comment by jcesarmobile** [comment]
I can't reproduce locally, so it's probably a phonegap build service bug ( or as you call it, adobe cloud system)
