### ISSUE TITLE
Android APK not working, Phonegap Server works

### ISSUE THREAD

**Issue by flo1810** [phonegap/phonegap-plugin-barcodescanner#792]
Hello,

I am new to phonegap.
I followd the instructions of this plugin.

My steps are:

1.) Create a new blank Project in the windows phonegap Application
2.) In Windows Shell I run "phonegap plugin add phonegap-plugin-barcodescanner"

This returns Error: 
Unable to load PlatformApi from platform. Error: Cannot find module 'Z:\barcodetest\test\platforms\browser\cordova\Api.js'

I found i have to make a "phonegap platform remove browser" than install brwoser again. Now it installs the Plugin.

Than I add the JavaScript Code in the index.html.

When I open my Phonegap App on my android and connect to the Phonegap Server, the app runs and the barcode scanner opens.

When I make a ZIP of the folder and upload it to build.phonegap.com I get a APK.
When Installing theese APK I am not aksed for the Camera, and the App opens but the camera is not working.

Whats wrong there? What did I forget?

**Comment by terranmarine** [comment]
Are you asking the user for permissions to use the camera?

**Comment by flo1810** [comment]
> 
> 
> Are you asking the user for permissions to use the camera?

No there is no such question when installing or starting the app

**Comment by terranmarine** [comment]
It should e popup when u trigger the plugin. Goes along the way like : AppName wants to use your camera.
Do you have this popup?

**Comment by jcesarmobile** [comment]
Doesn't look like the plugin was correctly installed, so it's probably a phonegap app bug.
