### ISSUE TITLE
Build failing in XCode 10.2.1 / cordova 7.1.0 / ios 5.0.1

### ISSUE THREAD

**Issue by halindrome** [phonegap/phonegap-plugin-barcodescanner#795]
### Expected Behaviour

The build should complete in XCode.   It worked with the previous version (10.1.x)

### Actual Behaviour

The build fails with the error:

    platforms/ios/Corvex/Resources/scannerOverlay.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7f8582042c50> System content for IBCocoaTouchFramework-ElevenAndLater <IBScaleFactorDeviceTypeDescription: 0x7f858562ead0> scaleFactor=2x'. These intermediate objects were non-nil: (

#### Steps to Reproduce

Take any project that was working when building under XCode 10.1, upgrade to XCode 10.2, and attempt the build. 

Unfortunately, I am not familiar enough with how xib works to suggest a work around at this time.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Not really relevant, but I am building for iOS 11 in this case.

#### Cordova CLI version and cordova platform version

    cordova --version = 7.1.0
    cordova platforms

        Installed platforms:
        android 6.3.0
        ios 5.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

    phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

**Comment by jcesarmobile** [comment]
I can't reproduce, can you try removing ios platform and adding it back?

**Comment by jpangburn** [comment]
This solved it on my machine with XCode 10.3:
sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService
