### ISSUE TITLE
conflict with Facebook SDK 4.38.1

### ISSUE THREAD

**Issue by xale76** [phonegap/phonegap-plugin-barcodescanner#798]
Hello Facebook warnes us to use latest SDK version (4.38.1).
If I change my SDK version in cordova-plugin-facebook4 from 4.25.0 to 4.38.1 build in PhoneGap fails with error:

duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class

How to fix this? Thank You

**Comment by emmanuelcohenlaroque** [comment]
Same problem here...
