### ISSUE TITLE
It would be nice to be able to add a cancel button on Android

### ISSUE THREAD

**Issue by halindrome** [phonegap/phonegap-plugin-barcodescanner#799]
### Expected Behaviour

When selected, show a cancel button on the bottom of the camera view on Android.  Bonus if it is customizable.

### Actual Behaviour

The only way to exit on android is to scan a code or press the hardware back button.

### Reproduce Scenario (including but not limited to)

Open up a scanning window on Android

#### Steps to Reproduce

See above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 8.0.0, Android 7, others

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

LG, but also Blackview and others

#### Cordova CLI version and cordova platform version

    cordova --version

7.1.0

    cordova platforms

Installed platforms:
  android 6.4.0
  ios 5.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

8.0.1

**Comment by purplecabbage** [comment]
The UI portions are completely defined in the Scan module that is being used.
It would need to be done upstream.
You can try with https://github.com/zxing/zxing

**Comment by halindrome** [comment]
Thank you for that information.  Unfortunately, it looks like that project is in maintenance mode now.  Feels hard to get them to change anything.  I will see about pushing a PR to them, but I don't hold out a lot of hope :/
