### ISSUE TITLE
error build release

### ISSUE THREAD

**Issue by ludo012** [phonegap/phonegap-plugin-barcodescanner#80]
I can't build a android release version of my cordova project due to barcodescanner errors:

C:\Users\idnext\Desktop\projet_idnext\Iknauf_all\CordovaProduction\iknauf\platforms\android\res\values\arrays.xml:3: Error
: "country_codes" is not translated in "ar" (Arabic), "bg" (Bulgarian), "ca" (Catalan), "cs" (Czech), "da" (Danish), "de"
(German), "el" (Greek), "es" (Spanish), "eu" (Basque), "fi" (Finnish), "fr" (French), "he" (Hebrew), "hi" (Hindi), "hu" (H
ungarian), "id" (Indonesian), "it" (Italian), "iw" (Hebrew), "ja" (Japanese), "ko" (Korean), "nl" (Dutch), "pl" (Polish),
"pt" (Portuguese), "ru" (Russian), "sk" (Slovak), "sl" (Slovene), "sv" (Swedish), "tr" (Turkish), "zh-rCN" (Chinese: China
), "zh-rTW" (Chinese: Taiwan, Province of China) [MissingTranslation]
  <string-array name="country_codes">
                ~~~~~~~~~~~~~~~~~~~~
C:\Users\idnext\Desktop\projet_idnext\Iknauf_all\CordovaProduction\iknauf\platforms\android\res\values\strings.xml:3: Erro
r: "app_name" is not translated in "ar" (Arabic), "bg" (Bulgarian), "ca" (Catalan), "cs" (Czech), "da" (Danish), "de" (Ger
man), "el" (Greek), "es" (Spanish), "eu" (Basque), "fi" (Finnish), "fr" (French), "he" (Hebrew), "hi" (Hindi), "hu" (Hunga
rian), "id" (Indonesian), "it" (Italian), "iw" (Hebrew), "ja" (Japanese), "ko" (Korean), "nl" (Dutch), "pl" (Polish), "pt"
 (Portuguese), "ru" (Russian), "sk" (Slovak), "sl" (Slovene), "sv" (Swedish), "tr" (Turkish), "zh-rCN" (Chinese: China), "
zh-rTW" (Chinese: Taiwan, Province of China) [MissingTranslation]
    <string name="app_name">iknauf</string>
            ~~~~~~~~~~~~~~~
C:\Users\idnext\Desktop\projet_idnext\Iknauf_all\CordovaProduction\iknauf\platforms\android\res\values\strings.xml:4: Erro
r: "launcher_name" is not translated in "ar" (Arabic), "bg" (Bulgarian), "ca" (Catalan), "cs" (Czech), "da" (Danish), "de"
 (German), "el" (Greek), "es" (Spanish), "eu" (Basque), "fi" (Finnish), "fr" (French), "he" (Hebrew), "hi" (Hindi), "hu" (
Hungarian), "id" (Indonesian), "it" (Italian), "iw" (Hebrew), "ja" (Japanese), "ko" (Korean), "nl" (Dutch), "pl" (Polish),
 "pt" (Portuguese), "ru" (Russian), "sk" (Slovak), "sl" (Slovene), "sv" (Swedish), "tr" (Turkish), "zh-rCN" (Chinese: Chin
a), "zh-rTW" (Chinese: Taiwan, Province of China) [MissingTranslation]
    <string name="launcher_name">@string/app_name</string>
            ~~~~~~~~~~~~~~~~~~~~
C:\Users\idnext\Desktop\projet_idnext\Iknauf_all\CordovaProduction\iknauf\platforms\android\res\values\strings.xml:5: Erro
r: "activity_name" is not translated in "ar" (Arabic), "bg" (Bulgarian), "ca" (Catalan), "cs" (Czech), "da" (Danish), "de"
 (German), "el" (Greek), "es" (Spanish), "eu" (Basque), "fi" (Finnish), "fr" (French), "he" (Hebrew), "hi" (Hindi), "hu" (
Hungarian), "id" (Indonesian), "it" (Italian), "iw" (Hebrew), "ja" (Japanese), "ko" (Korean), "nl" (Dutch), "pl" (Polish),
 "pt" (Portuguese), "ru" (Russian), "sk" (Slovak), "sl" (Slovene), "sv" (Swedish), "tr" (Turkish), "zh-rCN" (Chinese: Chin
a), "zh-rTW" (Chinese: Taiwan, Province of China) [MissingTranslation]
    <string name="activity_name">@string/launcher_name</string>

I can force compilation with add this extra gradle file:

lintOptions { disable 'MissingTranslation' disable 'ExtraTranslation' }

but the apk doesn't works and can't be install on smartphone

what can i do?

**Comment by defacto133** [comment]
In `platforms\android\res\values\arrays.xml` add the attribute `translatable="false"` to the tag `string-array`.
In `platforms\android\res\values\strings.xml` add the attribute `translatable="false"` to the tags `string` which have the value `app_name`, `launcher_name` and `activity_name` as `name` attribute.

**Comment by DavidePastore** [comment]
+1

**Comment by riddler2kone** [comment]
If you build with the adobe cloud service "adobe phonegap build", you can not edit the lines defacto133 mentioned. How can we get the plugin working with adobe phonegap build again? Thank you!

**Comment by andreszs** [comment]
I'm sure this is a very easy to fix error, why do we still have to deal with it? Why does a barcode scan plugin need translations in the first place?

**Comment by raymondelferink** [comment]
Would this pull request solve the issue?
https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/145

I don't think it has been picked up by the developers, but I don't know why. In the meantime we are stuck with a non gradle build using version 4.1.0
