### ISSUE TITLE
Android - PDF417 Encrypted Barcodes not being Scanned

### ISSUE THREAD

**Issue by Manickum** [phonegap/phonegap-plugin-barcodescanner#805]
### Actual Behaviour

The Image for the bardcode is in the display block, the red line hovers over it, there is no trigger for the code that says it is scanned.

### Expected Behaviour
The image gets scanned and the promise gets called

### Reproduce Scenario (including but not limited to)
Test with 
https://www.autotrader.co.za/cars/news-and-advice/automotive-news/can-you-convert-your-automatic-license-to-a-manual-drivers-license/2559

#### Plugin version
    "@ionic-native/barcode-scanner": "^5.10.0",

**Comment by greggreenhaw** [comment]
Yeah it takes a long time to recognize the barcode for pdf417. It can scan it fine but people give up before it can.
