### ISSUE TITLE
Super slow to initialise

### ISSUE THREAD

**Issue by oliverandersencox** [phonegap/phonegap-plugin-barcodescanner#806]
### Expected Behaviour
When executing the code it should open right away

### Actual Behaviour
It does nothing for 3-4 seconds and then opens the scanner

### Reproduce Scenario (including but not limited to)
simply followed the install instructions and then added the code to a button call

#### Cordova CLI version and cordova platform version

Most recent version + capacitor. 

I have seen another issue with this problem, however there seems to be no light shed on an answer.

**Comment by HamzaLJ** [comment]
I agree I am facing the same problem, it takes like 4 seconds to open the scanner.

**Comment by CeloGomesBR** [comment]
Yeah, me too.  And not work on Android 6.  It´s really bad! :(
