### ISSUE TITLE
Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

### ISSUE THREAD

**Issue by akashdeepsharma1991** [phonegap/phonegap-plugin-barcodescanner#813]
### Expected Behaviour
plugin get install without error using cordova 9

### Actual Behaviour
plugin throwing error Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

### Reproduce Scenario (including but not limited to)
install the plugin in cordova using version 9
#### Steps to Reproduce
install the plugin in cordova using version 9
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
android:6
ios:12
#### Cordova CLI version and cordova platform version

    cordova --version - 9.0
    cordova platforms - android-8.0.0 and ios-5.0.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner
latest

#### Logs taken while reproducing problem

Note: i cannot downgrade the cordova version since i want to use firebase messaging plugin which require cordova 9.0. Waiting for a quick response

**Comment by satbir90** [comment]
Me too.. Im facing the same issue. Using the Firebase messaging plugin which requires Cordova 9.0. Any Sollutions??

**Comment by ChrisTomAlx** [comment]
Any updates ??

**Comment by AsimShakour** [comment]
I am having a similar issue. This helped me fix it, thanks to github - https://stackoverflow.com/questions/56949539/issue-with-adding-ios-platform-into-ionic-cordova-project

npm install -g cordova@8.1.1
