### ISSUE TITLE
Issue regarding ionic 4 barcode scanner

### ISSUE THREAD

**Issue by mitesh-shah** [phonegap/phonegap-plugin-barcodescanner#817]
The code works fine, but when I click on scan data and without scanning if I press hardware back button then app goes 2 step back.

Any suggestion on this please?

**Comment by mitesh-shah** [comment]
In iOS, the plugin provides CANCEL button. The issue is with Android

**Comment by Plackpegasus** [comment]
Same here, also with android.  Could this be an android bug?
There are many open issues on github and other forums regarding this problem...

**Comment by HamzaLJ** [comment]
I have the same issue here

**Comment by shubhamappstec** [comment]
I have the same issue here

**Comment by shubhamkhuva** [comment]
I am facing the same issue, help!!!

**Comment by shubhamkhuva** [comment]
This is how I Handled,
```
this.platform.pause.subscribe((e) => {
      this.backButtonOff = false
    }) 
    this.platform.ready().then(() => {
      this.platform.backButton.subscribeWithPriority(99999, () => {
        if(this.backButtonOff){
          this.goBack()
        }else{
          this.backButtonOff = true
          return;
        }
      })
    })
```
