### ISSUE TITLE
iOS front camera causes cancel

### ISSUE THREAD

**Issue by kbaert** [phonegap/phonegap-plugin-barcodescanner#82]
Switching to the front camera in iOS, the cancel is triggered.
The front camera view is shown and scanning seems to continue but the success callback has already been called with result.cancelled = true. This doesn't seem to happen with stable v2.0.1

**Comment by livingos** [comment]
+1 

The older 2.0.1 works.

**Comment by brandonros** [comment]
This occurred for me as well.

**Comment by archer-zhn** [comment]
+1
Happen to me on iOS 9.2
