### ISSUE TITLE
How to solve Program type already present: com.google.zxing.BarcodeFormat in ionic 4

### ISSUE THREAD

**Issue by Silerqin** [phonegap/phonegap-plugin-barcodescanner#820]
I am using ionic 4. When my project have facebook plugin and BarcodeScanner plugin and type ionic cordova run android, it will come out this error:

```
Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Program type already present: com.google.zxing.BarcodeFormat
```

```
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Program type already present: com.google.zxing.BarcodeFormat
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
```

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
I download both plugin using these command:

```
```
ionic cordova plugin add phonegap-plugin-barcodescanner
npm install @ionic-native/barcode-scanner

ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID="app_id" --variable APP_NAME="app_name"
npm install --save @ionic-native/facebook
```

**Comment by amonam** [comment]
Exactly the same issue. How can I deactivate the zxing in this plugin?

**Comment by maateusx** [comment]
Same issue here

**Comment by sharatchandra99** [comment]
Same issue. Please respond

**Comment by satyasaini** [comment]
Same here....
---------------------------------------------------------------------------------------------------------------

D8: Program type already present: com.google.zxing.BarcodeFormat

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Program type already present: com.google.zxing.BarcodeFormat

**Comment by Mitnick21** [comment]
En mi caso descubrimos junto a un amigo que el conflicto lo genera un plugin, seguramente tienen mas de un plugin instalado. en mi caso era que tenia este npm uninstall cordova-plugin-facebook4 que no lo estaba usando...

**Comment by leabdalla** [comment]
@Mitnick21 yes I've just found the same problem. it's conflict with cordova-plugin-facebook4.
I tried to solve it for 3 days but it seems impossible.

**Comment by zahorjana** [comment]
Hi,
I've just found the same problem. I found a plugin that works well with phonegap-plugin-barcodescanner. This is: [cordova-plugin-facebook4-no-zxing](https://www.npmjs.com/package/cordova-plugin-facebook4-no-zxing)
I hope it helps.

**Comment by Mitnick21** [comment]
Gente no deben usar  cordova-plugin-facebook4-no-zxing por algun motivo no funciona yo segui este tutorial y no tuve problemas https://www.npmjs.com/package/angularx-social-login  deben desinstalar el facebook4 con el comando npm uninstall cordova-plugin-facebook4

espero sirva...

**Comment by ngongocdung** [comment]
here ist another solution if you don't want to install cordova-plugin-facebook4-no-zxing https://www.gitmemory.com/issue/jeduan/cordova-plugin-facebook4/777/517428763

1.Remove android platform.
2.Install cordova-plugin-facebook4
3.Create build.gradle in /plugins/cordova-plugin-facebook4/
4.Copy this
`
dependencies {
    compile("com.facebook.android:facebook-android-sdk:4.37.0") {
        exclude group: 'com.google.zxing'
    }
}
`
to ../plugins/cordova-plugin-facebook4/build.gradle
5.Edit ../plugins/cordova-plugin-facebook4/plugins.xml change 
`<framework src="com.facebook.android:facebook-android-sdk:$FACEBOOK_ANDROID_SDK_VERSION"/>`
 to 
`<framework src="build.gradle" custom="true" type="gradleReference"/>`
6.Add platform android and build

**Comment by Silerqin** [comment]
@ngongocdung Thank you for your reply. I will try it

**Comment by NLueg** [comment]
> here ist another solution if you don't want to install cordova-plugin-facebook4-no-zxing https://www.gitmemory.com/issue/jeduan/cordova-plugin-facebook4/777/517428763
> 
> 1.Remove android platform.
> 2.Install cordova-plugin-facebook4
> 3.Create build.gradle in /plugins/cordova-plugin-facebook4/
> 4.Copy this
> `dependencies { compile("com.facebook.android:facebook-android-sdk:4.37.0") { exclude group: 'com.google.zxing' } }`
> to ../plugins/cordova-plugin-facebook4/build.gradle
> 5.Edit ../plugins/cordova-plugin-facebook4/plugins.xml change
> `<framework src="com.facebook.android:facebook-android-sdk:$FACEBOOK_ANDROID_SDK_VERSION"/>`
> to
> `<framework src="build.gradle" custom="true" type="gradleReference"/>`
> 6.Add platform android and build

@ngongocdung  Thank you so much, it worked without problems! I Searched for hours before ...
