### ISSUE TITLE
No camera permission requested on iOS

### ISSUE THREAD

**Issue by Jonkat323** [phonegap/phonegap-plugin-barcodescanner#821]
### Expected Behaviour

I have added the provided usage description required by iOS inside the iOS platform tag of the config.xml file:

`<edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
    <string>To scan barcodes</string>
</edit-config>`

### Actual Behaviour

Scanner works as intended on Android, but not on iOS. Scanner launches but the background is black. Launching the scanner function again then results in a popup stating that camera access is  prohibited and access must be granted in settings. The only permission available in settings is mobile data.

### Additional code

This is my content policy of the index.html file if relevant

`<meta http-equiv="Content-Security-Policy" content="default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:">`

**Comment by Jonkat323** [comment]
I updated to..

`<gap:config-file platform="ios" parent="NSCameraUsageDescription" overwrite="true">
      <string>To scan barcodes</string>
 </gap:config-file> `

..and now the app asks for camera access permission when launching the scan function for the first time. Any ideas why this is?

**Comment by macirex** [comment]
@Jonkat323 I have the same problem, when you updated the config file and added: 

<gap:config-file platform="ios" parent="NSCameraUsageDescription" overwrite="true"> <string>To scan barcodes</string> </gap:config-file> 

did you solve the black screen problem?

**Comment by Jonkat323** [comment]
@macirex Yes, this solved the black screen issue on iOS as the app now has access to the camera. It should now ask for permission the first time you try use the barcode scanner function.

**Comment by macirex** [comment]
@Jonkat323 Where did you put that line on the config.xml? I tried putting it on platform but the scanner app still opens before requesting permission and it still remains in black after not allowing it the permission.

This is where I put it:
`    <platform name="ios">
        <icon height="57" platform="ios" src="www/res/icon/ios/icon.png" width="57" />
        <icon height="114" platform="ios" src="www/res/icon/ios/icon@2x.png" width="114" />
        <icon height="40" platform="ios" src="www/res/icon/ios/icon-40.png" width="40" />
        <icon height="80" platform="ios" src="www/res/icon/ios/icon-40@2x.png" width="80" />
        <icon height="50" platform="ios" src="www/res/icon/ios/icon-50.png" width="50" />
        <icon height="100" platform="ios" src="www/res/icon/ios/icon-50@2x.png" width="100" />
        <icon height="60" platform="ios" src="www/res/icon/ios/icon-60.png" width="60" />
        <icon height="120" platform="ios" src="www/res/icon/ios/icon-60@2x.png" width="120" />
        <icon height="180" platform="ios" src="www/res/icon/ios/icon-60@3x.png" width="180" />
        <icon height="72" platform="ios" src="www/res/icon/ios/icon-72.png" width="72" />
        <icon height="144" platform="ios" src="www/res/icon/ios/icon-72@2x.png" width="144" />
        <icon height="76" platform="ios" src="www/res/icon/ios/icon-76.png" width="76" />
        <icon height="152" platform="ios" src="www/res/icon/ios/icon-76@2x.png" width="152" />
        <icon height="29" platform="ios" src="www/res/icon/ios/icon-small.png" width="29" />
        <icon height="58" platform="ios" src="www/res/icon/ios/icon-small@2x.png" width="58" />
        <icon height="87" platform="ios" src="www/res/icon/ios/icon-small@3x.png" width="87" />
        <splash src="www/res/screen/ios/Default@2x~universal~anyany.png" />
        <resource-file src="www/GoogleService-Info.plist" />
        <gap:config-file platform="ios" parent="NSCameraUsageDescription" overwrite="true"> <string>To scan barcodes</string> </gap:config-file> 
    </platform>`

Any insights will be appreciated, thanks

**Comment by Jonkat323** [comment]
No not inside the iOS platform. I put it after the list of plugins and before the platforms.

**Comment by macirex** [comment]
Okay, Thanks! I'll try again!

**Comment by macirex** [comment]
I couldn't make it work, I think the problem is that I'm using cordova and not phonegap and I don't know if this fix works on the config.xml of cordova

**Comment by Jonkat323** [comment]
I am using Cordova too! So my plugin is

`<plugin name="cordova-plugin-barcodescanner" version="0.7.4"/> `

Then afterwards I have the following for Android:

```
<config-file target="AndroidManifest.xml" parent="/*" mode="merge">
    <uses-permission name="android.permission.CAMERA" />
    <uses-feature name="android.hardware.camera" />
    <uses-feature name="android.hardware.camera.autofocus" />
</config-file> 
```

And then this for iOS:

```
<gap:config-file platform="ios" parent="NSCameraUsageDescription" overwrite="true">
    <string>To scan barcodes</string>
</gap:config-file> 
```
