### ISSUE TITLE
How can i change text cancel button in ios?

### ISSUE THREAD

**Issue by stromwid** [phonegap/phonegap-plugin-barcodescanner#822]
Hello,

How can i change text cancel button in ios?

Version plugin 8.0.0
iOS version 11.2.5

![github1](https://user-images.githubusercontent.com/34936675/66117405-40d8e480-e5dd-11e9-8ba0-f612b6262584.png)

**Comment by phikes** [comment]
I am not sure if this still applies, but the issue search yield this: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/107

> In your Info.plist you have to include something like this:

    <key>CFBundleLocalizations</key>
    <array>
      <string>en</string>
      <string>de</string>
    </array>

You can easily search the issue tracker using the search bar above ;-).
