### ISSUE TITLE
Cancel button for android device

### ISSUE THREAD

**Issue by Rudra-Basu** [phonegap/phonegap-plugin-barcodescanner#828]
### Expected Behaviour
Cancel button on the scan screen at the bottom and even better if it could be customized
### Actual Behaviour
No cancel button, user has to click the hardware back button to cancel the scanner
### Reproduce Scenario (including but not limited to)
Open the scanner on android
#### Steps to Reproduce
Create an app and install and use barcode scanner on the app. 
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7 and above
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Oppo
#### Cordova CLI version and cordova platform version

    cordova --version
8.0.0

    cordova platforms
android

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner
8.0.1

**Comment by ayubUOL** [comment]
@Rudra-Basu any luck in finding solution ?

**Comment by Rudra-Basu** [comment]
@ayubUOL Not yet. However, I was advised to try QR scanner and change the scanning type to barcode. Need to try it before confirming.
