### ISSUE TITLE
iOS9 scanner locking up

### ISSUE THREAD

**Issue by jcrawford** [phonegap/phonegap-plugin-barcodescanner#83]
In IOS9 the scanner seems to open and instantly freeze.  I can tap the camera icon to bring up the front facing camera and that works just fine without any freezing.  I can also click cancel and have that close the scanner window.  However as stated the camera locks up at a black screen (before camera opens) or right after the camera screen shows the image.

**Comment by Delagen** [comment]
On ios 8.4 was the same

**Comment by Delagen** [comment]
Version 3.0 works

**Comment by jcrawford** [comment]
I am using build.phonegap.com aside from adding this to my config.xml file I haven't had to do any other installation.  The line in the config file is solely this.

```<gap:plugin name="com.phonegap.plugins.barcodescanner" />```

How would I tell the system I want to use v3.0?

**Comment by jcrawford** [comment]
I tried the following and it is still freezing on my iPhone 4s

```<gap:plugin name="net.roughshod.plugins.barcodescanner" version="3.0.0" />```

**Comment by sergeifedorenko** [comment]
I also have same problem with version of plugin 4.0.1
Same time application have crash after freezing.

**Comment by sergeifedorenko** [comment]
I have Cordova IOS 3.9.1, XCode 7.0
By my opinion problem appears after changing  XCode 6 to  XCode 7

**Comment by sergeifedorenko** [comment]
Version 3 also have freezing 
I use "ionic plugin add phonegap-plugin-barcodescanner@3.1.2"

**Comment by jcrawford** [comment]
Anyone going to be able to look at this sometime soon?  This is a detrimental feature for the phonegap build we are making.  Without it we may as well not have the need for phonegap :)

There are several people experiencing the issue and I would prefer to use this plugin than seeking around for another scanning plugin (if any even exist).

**Comment by graphicgeek** [comment]
@jcrawford I'm not sure what you mean. Did you just put a script tag in your index.html to include barcodescanner.js? I didn't see anything in the docs about doing that.

**Comment by jcrawford** [comment]
@graphicgeek yes all I did was add the script tag right after the one for phonegap.js and all started working perfect.  I recall seeing this in one of their demo examples and nothing about it in the docs so I tried it and it solved the issue.

**Comment by jcrawford** [comment]
@graphicgeek this is the example where I saw them using the barcodescanner.js inclusion which gave me the idea to try it and again it solved my lock-up issues.

https://github.com/wildabeast/BarcodeDemo/blob/master/index.html

**Comment by graphicgeek** [comment]
@jcrawford Thanks, but that fix didn't work for me unfortunately. But I'm using Cordova rather than phonegap build. That example is also for an older version of the plugin.

I've also tried older versions (3.0.0 and 2.2.0) but no luck. Every time I launch the scanner in (iOS 9) it just freezes.

**Comment by jcrawford** [comment]
I am using this specific plugin with that inclusion for the scanner and it works fine for me.

```
<gap:plugin name="net.roughshod.plugins.barcodescanner" version="3.0.0" />
```

**Comment by graphicgeek** [comment]
I'm using Cordova, not Phonegap Build. 

I think I've narrowed this to a permissions issue with my app. For some reason, the app isn't asking for permission to use the camera.

I installed a fresh "hello world" app, that did nothing but launch the scanner. When it launches it asks for permission to use the camera, and it works fine. So time to comb through my code and figure out why my  app isn't asking for permission.

**Comment by tomandhisjones** [comment]
I'm having the same issue. Running IOS 9 and the newest version of the plugin, on Cordova 5.3.1

**Comment by sergeifedorenko** [comment]
By my opinion this problem appears after switching to XCode 7.0.
I'm had trying to run build of program on IOS 8 and also have similar problem.
But before switching from XCode6 to XCode7 all works fine!

**Comment by tomandhisjones** [comment]
unfortunately, one of the other plugins gives me a linker error when I try to build in xcode 7, that I spent days trying to diagnose before switching back to xcode 6.4.

**Comment by olimortimer** [comment]
I was finding that the camera on iOS 8 occasionally froze when the barcode scanner was called - I was using the latest PhoneGap Barcodescanner (4.0.2).

However, upgrading the iOS device to iOS 9 solved this issue.

Have you tried upgrading your 3.0.0 PhoneGap Barcodescanner to the latest version (4.0.2)?

**Comment by sergeifedorenko** [comment]
@olimortimer Yes I had version 4.0.2 problem not solved
But my colleagues it seems resolved this issue In the near future I will tell about decision

**Comment by Grutulru** [comment]
We switch to another plugin, works perfectly on iOS9 (not tested with Android or Windows).
Also launches faster than the phonegap one.

https://github.com/tjwoon/csZBar

**Comment by benjammin9** [comment]
Same problem here. Camera goes black and I see the following in the Xcode console: "...whose view is not in the window hierarchy!" I'm using iOS 9.2 and Xcode 7.2. However, whenever I launch the scanner from a button WITHIN the <ion-content></ion-content> tags, it works fine. Is this useful insight? Any thoughts?
