### ISSUE TITLE
Cannot reinitialize scan on iOS 13

### ISSUE THREAD

**Issue by salvobunetto** [phonegap/phonegap-plugin-barcodescanner#833]
When camera is viewing and slide down without press cancel button, cannot reinitialize scan

iPhone xR iOS 13.2.2

9.0.0 (cordova-lib@9.0.1)
Platform: iOS

@ionic-native/barcode-scanner 5.16.0
phonegap-plugin-barcodescanner 8.1.0 (latest)

**Comment by bronxyHD** [comment]
I have the same issue, is there already a fix?

**Comment by divyasri93** [comment]
Try checking this https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/814
