### ISSUE TITLE
Interleaved barcode 2 of 5 - Brazilian barcode type (47 digits)

### ISSUE THREAD

**Issue by fredroo** [phonegap/phonegap-plugin-barcodescanner#836]
# Expected Behaviour
Return 47 digits of ITF barcode
### Actual Behaviour
not return the Barcode correctly - INTERLEAVED 2 of 5 (Brazilian type) (47 digits)
### Reproduce Scenario (including but not limited to)
Try to use this bar code, please
![image](https://user-images.githubusercontent.com/6863089/69497367-76e66680-0eb2-11ea-947f-8ba88c1c7ddc.png)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8
#### Cordova CLI version and cordova platform version

    cordova --version

9.0.0 (cordova-lib@9.0.1)

    cordova platforms

Installed platforms:
  android 8.1.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

 "phonegap-plugin-barcodescanner": "^8.1.0",

#### Sample Code that illustrates the problem

```
  scanCode() {
    this.barcodeScanner.scan(this.barcodeScannerOptions).then(barcodeData => {
      alert('Barcode data ' + JSON.stringify(barcodeData));
      this.scannedData = barcodeData;
    }).catch(err => {
      console.log('Error', err);
    });
  }
```

**Comment by fredroo** [comment]
@rdesimone can you help me?

**Comment by fredroo** [comment]
@jcesarmobile can you help me?

**Comment by flavianoredressa** [comment]
I also have this problem

**Comment by jcesarmobile** [comment]
Please, don’t ping me, I don’t work for Adobe

**Comment by diogoucg** [comment]
@flavianoredressa o número retornado ao ler um código de barras é diferente da linha digitável viu?!

Eu testei esse plugin e ele funcionou para alguns boletos bancários, mas não para todos,

**Comment by fredroo** [comment]
@skaman can you help me?

**Comment by jesobreira** [comment]
Note that the Boleto barcode (44 chars) is not the same as the digitable line (47 chars) but it’s possible to calculate one from another. You can use this lib for this: https://www.npmjs.com/package/@mrmgomes/boleto-utils

**Comment by fredroo** [comment]
@jesobreira thanks a lot, works very fine your tip
