### ISSUE TITLE
 ['BarcodeScanner'] took '13.405762' ms. Plugin should use a background thread.

### ISSUE THREAD

**Issue by thameurr** [phonegap/phonegap-plugin-barcodescanner#842]
#### Platform and Version:
IOS 13
#### Cordova CLI version and cordova platform version
Apache Cordova native platform version 5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner: latest version 

#### Logs taken while reproducing problem
THREAD WARNING: ['BarcodeScanner'] took '12.704834' ms. Plugin should use a background thread.

**Comment by sandrafreihofer** [comment]
@thameurr I had the same issue. Have you checked your `config.xml`? You need to tell iOS to ask the user for camera permission. You can find the instructions [here](https://github.com/phonegap/phonegap-plugin-barcodescanner#ios-quirks).

**Comment by gregtzar** [comment]
I have confirmed the `NSCameraUsageDescription` property is being included and I'm still getting the same warning.
