### ISSUE TITLE
[BARCODE SCANNER] SD CARD IS NOT ACCESIBLE 

### ISSUE THREAD

**Issue by AdrianVillamar743** [phonegap/phonegap-plugin-barcodescanner#843]
### Expected Behaviour
Can share the enconded qr code from the share button
### Actual Behaviour
The share button doesn't work showing the message "Sorry, the SD card isn't accesible"
### Reproduce Scenario (including but not limited to)
Ionic:

   Ionic CLI                     : 5.4.9 (C:\Users\avill\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 7 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.2.9

System:

   NodeJS : v12.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.0
   OS     : Windows 10
#### Steps to Reproduce
I've installed the plugin like the official documentation express
ionic cordova plugin add cordova-plugin-qrscanner
npm install @ionic-native/qr-scanner
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android  8.1.0
#### Cordova CLI version and cordova platform version
9.0.0 (cordova-lib@9.0.1) Android
#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner
        phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
#### Sample Code that illustrates the problem
import { Component } from '@angular/core';
import { BarcodeScanner } from "@ionic-native/barcode-scanner/ngx";
import { Alert } from 'selenium-webdriver';
import { Base64 } from '@ionic-native/base64/ngx';
import { EmailComposer } from '@ionic-native/email-composer/ngx';
import { SocialSharing } from '@ionic-native/social-sharing/ngx';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  datocodificado: any;
enviar:any;
  datoscaneado: {};

  constructor(
    private base64: Base64,
    private barcodeScanner: BarcodeScanner,
    private emailComposer: EmailComposer,
    private socialSharing: SocialSharing
    ) {

  }

   generarcodigo(texto){
    alert(texto);
      // Example for a string QR code (TEXT_TYPE)
  
  this.barcodeScanner.encode(this.barcodeScanner.Encode.TEXT_TYPE,texto).then(
    encodedData => {
      this.datocodificado = encodedData;
    },
    err => {
      console.log("Un error ha ocurrido: " + err);
    }
  );

 

}

#### Logs taken while reproducing problem
My SD card works perfectly, is 10 class and has 32gb
![Screenshot_20191207-154424_QR](https://user-images.githubusercontent.com/58639601/70380387-a6608e80-1908-11ea-99d9-f479bda643cb.jpg)
![Screenshot_20191207-154430_QR](https://user-images.githubusercontent.com/58639601/70380388-a95b7f00-1908-11ea-9ac6-b23cbd7ff6ce.jpg)
![Screenshot_20191207-154433_QR](https://user-images.githubusercontent.com/58639601/70380389-abbdd900-1908-11ea-91c7-2e0c07fcd38e.jpg)

**Comment by avilac3** [comment]
the same problem bro,  can be permissions
