### ISSUE TITLE
How we can make Continues scanning 

### ISSUE THREAD

**Issue by satishtaluru** [phonegap/phonegap-plugin-barcodescanner#848]
Actually we need to develop continues scanning(Barcode and QR code) with out closing the camera.

**Comment by THARUE** [comment]
yes, on iOS 13 it allows you to swipe down to close the scanner but when trying to reopen it displays a toast that says `scan is already in progress`.  The (qrdata) => qrdata.cancelled is still set to false but I can't find a way to reopen the scanner modal to finish scan.

**Comment by geoorg30** [comment]
Developed continuous scanning for android... anyone interested?

**Comment by DorianLovera** [comment]
> Developed continuous scanning for android... anyone interested?

I am ! Can you please share this with us ?
