### ISSUE TITLE
[iOS] XCode warning: [LayoutConstraints] Unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by jospete** [phonegap/phonegap-plugin-barcodescanner#850]
### Expected Behaviour

When the scan overlay view gets presented, no warnings should be shown.

### Actual Behaviour

iOS's layout manager shows these warnings about the scan overlay view:

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x28272a260 h=--& v=--& _UIToolbarContentView:0x105841120.width == 0   (active)>",
    "<NSLayoutConstraint:0x282728f00 H:|-(0)-[_UIButtonBarStackView:0x105824000]   (active, names: '|':_UIToolbarContentView:0x105841120 )>",
    "<NSLayoutConstraint:0x282728ff0 _UIButtonBarStackView:0x105824000.trailing == _UIToolbarContentView:0x105841120.trailing   (active)>",
    "<NSLayoutConstraint:0x282726bc0 'IB_Leading_Leading' H:|-(0)-[_UIModernBarButton:0x104745c30]   (active, names: '|':_UIButtonBarButton:0x105851730 )>",
    "<NSLayoutConstraint:0x282726c60 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x104745c30]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x105851730 )>",
    "<NSLayoutConstraint:0x28272c320 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x10475a620'Cancel']   (active, names: '|':_UIButtonBarButton:0x10475c270 )>",
    "<NSLayoutConstraint:0x28272c370 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x10475a620'Cancel']-(8)-|   (active, names: '|':_UIButtonBarButton:0x10475c270 )>",
    "<NSLayoutConstraint:0x282728500 'UISV-canvas-connection' UILayoutGuide:0x283d63100'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x105851730.leading   (active)>",
    "<NSLayoutConstraint:0x282728550 'UISV-canvas-connection' UILayoutGuide:0x283d63100'UIViewLayoutMarginsGuide'.trailing == UIView:0x104710d70.trailing   (active)>",
    "<NSLayoutConstraint:0x2827285a0 'UISV-spacing' H:[_UIButtonBarButton:0x105851730]-(0)-[UIView:0x10475a4b0]   (active)>",
    "<NSLayoutConstraint:0x282728460 'UISV-spacing' H:[UIView:0x10475a4b0]-(0)-[_UIButtonBarButton:0x10475c270]   (active)>",
    "<NSLayoutConstraint:0x2827284b0 'UISV-spacing' H:[_UIButtonBarButton:0x10475c270]-(0)-[UIView:0x104710d70]   (active)>",
    "<NSLayoutConstraint:0x2827291d0 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x283d63100'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x105824000 )>",
    "<NSLayoutConstraint:0x282729130 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x283d63100'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x105824000 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x282726c60 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x104745c30]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x105851730 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

#### Steps to Reproduce

Initialize a new project and on iOS build call:

cordova.plugins.barcodeScanner.scan();

The warning will display immediately in xcode

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 13.3.1

#### Cordova CLI version and cordova platform version

cordova --version

9.0.0 (cordova-lib@9.0.1)

cordova platforms

Installed platforms:
  android 8.1.0
  ios 5.1.1

#### Plugin version

cordova plugin version | grep phonegap-plugin-barcodescanner

phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"

#### Sample Code that illustrates the problem

cordova.plugins.barcodeScanner.scan();

#### Logs taken while reproducing problem

See "Actual Behaviour" section

**Comment by jospete** [comment]
Upon further inspection, it looks like the dynamic button constraints are what's causing this

![Screen Shot 2020-01-29 at 1 34 55 PM](https://user-images.githubusercontent.com/17754439/73671260-36ecee00-4670-11ea-9e5f-80970aa81756.png)

**Comment by jospete** [comment]
The initial screenshot was with the torch option enabled, here's a screenshot with no options passed in to the scan() call

![Screen Shot 2020-02-03 at 11 00 12 AM](https://user-images.githubusercontent.com/17754439/73673719-c2687e00-4674-11ea-92ea-19a6612ccd68.png)

**Comment by KiranSuresha** [comment]
+1

<img width="1411" alt="Screen Shot 2020-03-05 at 4 59 40 PM" src="https://user-images.githubusercontent.com/16533062/76029694-ff898f80-5f02-11ea-8705-78ab37daaaea.png">
