### ISSUE TITLE
What do you use for resolving barcodes

### ISSUE THREAD

**Issue by ClaudeVernier** [phonegap/phonegap-plugin-barcodescanner#86]
Hello, 

This is not linked directly to using the plugin but I am looking for help that could get me to use it.

I wanted to write a small (free?) app for all targeted devices but firstly, for Windows Phones that holds a library of all the DVDs I own, or comic books or any other media...  I wanted to scan the barcode, get all information concerning the product and store it into a database, including the image and also other linked products, store them all in a local database and being able to show all of this,  offline.

The usage scenario would be...  I scan all of my DVDs, like the first four seasons of "The Simpsons" and the application finds that I am missing all the more recent seasons, so it shows the images of the first four seasons and greyed-out versions of the images of the seasons I don't own along with all the information on the editor, the year, the barcodes... then, when I am in a store, I can look in my app and see what I am missing !!!

I have just found out that the Amazon web service can't be use on a mobile, according to the  "Amazon EU Product Advertising API Licence Agreement"...  So, would anyone have recommendation on web services I could use to find and store all the information I need for the scenario above ?

I am starting to feel that this is not possible to achieve...  so many thanks for any help you could provide,  

Regards, 
Claude

**Comment by olimortimer** [comment]
A quick Google for 'barcode lookup api' has a couple of results:

http://www.scandit.com/product-api/
http://upcdatabase.org/code/5039036006231
https://www.barcodelookup.com/5039036006231
