### ISSUE TITLE
iOS Camera Delay

### ISSUE THREAD

**Issue by olimortimer** [phonegap/phonegap-plugin-barcodescanner#89]
Our users are finding that there's a bit of a delay opening the PhoneGap Barcodescanner when a button is pressed to call it.

Is there any way of speeding up the time that the scanner is loaded?

iOS 9 with PhoneGap Barcodescanner 4.0.2 and PhoneGap 5.3.6

**Comment by dabontv** [comment]
+1. I see about a 1-2 second delay

**Comment by matiu** [comment]
+1, we also see a delay. It seems it started on iOS 9.

**Comment by poshaughnessy** [comment]
+1

**Comment by gabrielsme** [comment]
+1

**Comment by lcya86** [comment]
+1

**Comment by martinamw** [comment]
The 1 second delay was presumably a bug fix.

// delayed [self openDialog];
    [self performSelector:@selector(openDialog) withObject:nil afterDelay:1];

**Comment by olimortimer** [comment]
So does that mean it's fixed?

**Comment by sriram6781** [comment]
Change the delay from 1 second to 0 seconds fixed the issue for me. 
[self performSelector:@selector(openDialog) withObject:nil afterDelay:0];

**Comment by jkobylec** [comment]
Why is this closed? It seems that without either pulling in the above change if it's acceptable, or providing a concrete reason why that delay needs to remain in place unconditionally for all platform versions etc., this should remain open?

**Comment by sriram6781** [comment]
Hi jkobylec, this is just a workaround that I am using for now. I am not sure why the issue is closed.

**Comment by sriram6781** [comment]
Also i have issues in reading barcodes on IOS device with this scanner. It reads correctly most of the times but it reads incorrectly as well. I know that it is not related to the original issue here.

**Comment by olimortimer** [comment]
@sarangan12 can you advise why it has been closed please?  See comment from @jkobylec

**Comment by sriram6781** [comment]
I agree with @jkobylec that this issue should remain open.
