### ISSUE TITLE
Potentially excessive permissions for android

### ISSUE THREAD

**Issue by anchann** [phonegap/phonegap-plugin-barcodescanner#91]
Hello!

I may be naive, but I can't intuitively understand, nor, do I expect, will my users, why a barcode scanner needs

uses-permission android:name="android.permission.INTERNET"
uses-permission android:name="android.permission.VIBRATE"
uses-permission android:name="android.permission.READ_CONTACTS"
uses-permission android:name="com.android.browser.permission.READ_HISTORY_BOOKMARKS"
uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
uses-permission android:name="android.permission.CHANGE_WIFI_STATE"
uses-permission android:name="android.permission.ACCESS_WIFI_STATE"

Are these actually necessary? If not, can you please remove them?

**Comment by anchann** [comment]
I took a quick look at the code (never done Android development, so may be way off here), and got the impression that the android part of this plugin is implemented by more or less embedding a standalone barcode scanner from here https://github.com/zxing/zxing, and probably tweaking it slightly to convert from a standalone app into a plugin, but all the permissions that used to be necessary for whatever functionality the app provides got inherited as is.

**Comment by vypah** [comment]
Any update on this ?

**Comment by macdonst** [comment]
Plugin has been updated only to require camera and flashlight. Anything else being pulled in must be from ZXing.
