### ISSUE TITLE
iOS Camera Crashing

### ISSUE THREAD

**Issue by olimortimer** [phonegap/phonegap-plugin-barcodescanner#92]
Our users are finding that the camera sometimes crashes as soon as the barcode scanner is opened.  A force close and open of the app allows it to work correctly again.

iOS 9 with PhoneGap Barcodescanner 4.0.2 and PhoneGap 5.3.6

**Comment by dahei** [comment]
+1 

Yes, I can confirm this. Only completely "killing" the app helps in these cases.

iPhone 6
iOS 9.1
Cordova 5.3.3.
Scanner: 4.1.0

I think this is **serious** bug, which could prevent us from using the plugin in production. 

at other devs:

Please comment, if you experience this issue as well to raise awareness for this.

**Comment by Grutulru** [comment]
We switch to another plugin, works perfectly on iOS9 (not tested with Android or Windows).
Also launches faster than the phonegap one.

https://github.com/tjwoon/csZBar

**Comment by dahei** [comment]
Thanks for the hint! Hopefully the official plugin gets fixed, too.

**Comment by Grutulru** [comment]
Launch is faster and also recognition!
Tested on both ipod and iphone (9.1), everything ok
Need to test with 9.2 now...

**Comment by dahei** [comment]
It also has to work on Android for me - but I will give it a try, if this one here doesn't get fixed.

**Comment by WebeWizard** [comment]
Seeing the same thing after an upgrade to our cordova project.

iPad mini, iOS 9
Cordova 6.0.0
Barcodescanner 4.1.0 (upgraded from 2.0.1)

**Comment by MaicolBen** [comment]
+1 

iPhone 6
iOS 9.1
Cordova 5.3.3.
Plugin version: 4.1.0

**Comment by MaicolBen** [comment]
@sarangan12 It is still happening with version 5, the Telerik plugin doesn't have that bug

**Comment by nikhilkh** [comment]
Can you provide logs from the crash?

**Comment by MaicolBen** [comment]
@nikhilkh Maybe my issue was #30 , this workaround fixed my issue on iOS https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/30#issuecomment-121513124

**Comment by WebeWizard** [comment]
An update from my experience.

My crashes seem to be caused by running out of memory on the device.  I especially noticed the crashes on older devices.  Some of these older devices only have 500MB of available ram which is easily consumed by cordova, maybe a single browser tab, and a native calendar app for example.  Opening the camera + scanner plugin consumes another 100MB+.

When iOS detects you only have 50MB or so free ram, it starts killing apps to free memory for the current app.  Since the current app is technically the camera now, and not the cordova app, iOS will gladly kill your app for the sake of the camera.

I hope someone else finds this useful.  Learning to profile cpu/memory iOS helped a lot.

**Comment by taogogo** [comment]
+1
crashed on my iphone ce.
hope to fix this bug

**Comment by FlummoxNL** [comment]
same problem with iPad running 9.3.5. Also crashing on iPhone 5 & 7.

**Comment by EddyVerbruggen** [comment]
Using plugin 6.0.3?

**Comment by FlummoxNL** [comment]
Intel XDK; Cordova CLI v6.2.0, phonegap-plugin-barcodescanner v4.1.0.

This is how I have it working now, with the Options commented out.
`function startScan() {
    cordova.plugins.barcodeScanner.scan(
        function ( result ) {
            
            if ( !result.cancelled ) {
                createPopup( 
                language.scannedcontest, 
                function() { parseScanResult( result );}, 
                language.scansucces, 
                [language.buttonpos] );
                
            } else {
                createPopup( 
                language.scanerror, 
                function() { console.log( result );}, 
                language.scancancelled, 
                [language.buttonpos] );
            }         
        },
        
        function ( error ) {
            createPopup( 
                language.scanerror + error, 
                function() { console.log( error );}, 
                language.scanerror + error, 
                [language.buttonpos] );
            } /*,
        {
            "preferFrontCamera" : true, // iOS and Android 
            "showFlipCameraButton" : true, // iOS and Android 
            "prompt" : "Place a barcode inside the scan area", // supported on Android only 
            "formats" : "QR_CODE", // default: all but PDF_417 and RSS_EXPANDED 
            "orientation" : "landscape" // Android only (portrait|landscape), default unset so it rotates with the device 
      }*/);
}`
