### ISSUE TITLE
Is editing the plugin the only way to customize the scanner UI?

### ISSUE THREAD

**Issue by danielnbarros** [phonegap/phonegap-plugin-barcodescanner#93]
Is editing the plugin the only way to customize the scanner UI?

What is the recommended way to modify the UI?

**Comment by jaredgreener** [comment]
Would love a way to customize the UI overlay. Thanks!

**Comment by pke** [comment]
It seems there is no way to customize anything. I would be nice to really embed the preview mask into an existing view. So far I have only successfully done that in Windows apps.
All the mask and strings come from the zxing library used here.

**Comment by macdonst** [comment]
@danielnbarros currently yes it is. There are enhancement issues open to add customization.
