### ISSUE TITLE
Cannot read property 'barcodeScanner' of undefined

### ISSUE THREAD

**Issue by auchri** [phonegap/phonegap-plugin-barcodescanner#94]
I've added the plugin to my phonegap project with 

```
phonegap plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner.git
```

And then I would like to scan a qr-code after I click on a button:

```
onDeviceReady: function () {
    $('#scanButton').click(function () {
        cordova.plugins.barcodeScanner.scan(
            function (result) {
                alert("We got a barcode\n" +
                    "Result: " + result.text + "\n" +
                    "Format: " + result.format + "\n" +
                    "Cancelled: " + result.cancelled);
            },
            function (error) {
                alert("Scanning failed: " + error);
            }
        );
    });
}
```

But when I click on the button, I get this javascript error:

```
Cannot read property 'barcodeScanner' of undefined
```

Do I miss something?

**Comment by Shivaraman-iyer** [comment]
I am getting the same problem and am not able to use the scanner. On doing a 
````
console.log(cordova.plugins)
````
I get `null`. What might be the issue?

**Comment by hsmith825** [comment]
I am getting a similar problem on Android.  "Cannot call method 'scan' of undefined".  The plugin (earlier version) works on IOS.

Help???

**Comment by JeremyBuchmann** [comment]
I'm having the same problem on Android 5.1 and 4.1. The cordova.plugins object doesn't exist.

**Comment by JeremyBuchmann** [comment]
I found what was causing my problem. Apparently, the Adobe PhoneGap app which I was using for testing doesn't support third-party plugins like this barcode scanner. I built an actual Android apk and installed it on the device, and the barcode scanner works fine.

I reeeeeeeaaally wish that limitation of the PhoneGap app was documented more obviously.

**Comment by auchri** [comment]
@JeremyBuchmann if I build my app with the command line, it should support plugins?

**Comment by JeremyBuchmann** [comment]
@auchri that's what worked for me. I only found that bit of information way down on a Stackoverflow comment. Give it a try and let us know if it works for you.

**Comment by andreadompe** [comment]
Hey guys i had the same problem, i found GapDebug
https://www.genuitec.com/products/gapdebug/
i think is the better solution for debugging an app.

Obviusly it support third-party plugins

**Comment by auchri** [comment]
@JeremyBuchmann I already tried that, but it's not working :/

maybe you can send me your working project?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by vikramIde** [comment]
Same issue here tried using it in my vue project

**Comment by fihamzuher** [comment]
I am getting a similar problem on Android. "Cannot call method 'scan' of undefined".

**Comment by rkeene** [comment]
I also get this when creating an APK using the PhoneGap Build service
