### ISSUE TITLE
WinRTBarcodeScanner undefined - windows 10 app

### ISSUE THREAD

**Issue by numericgraphics** [phonegap/phonegap-plugin-barcodescanner#95]
Hello,
I realize an ionic application with the PhoneGap Plugin BarcodeScanner.
The application is intended to be used on windows 10.
I tested my code on android without any worries.
On windows 10 I get an error: WinRTBarcodeScanner is undefined in the developer console.
I installed the plugin with CLI cordova.
I use for testing DELL VENUE PRO 11 with windows 10.
The plugin is installed correctly, the Reader.cs file is present.
The error occurs when calling the startBarcodeSearch function.
do u have an idea or a solution to this problem,
thank you in advance and thank you for your work.

**Comment by SunboX** [comment]
Windows 10 seems not to be supported yet: https://github.com/phonegap/phonegap-plugin-barcodescanner#supported-platforms :cry:

**Comment by rolandoldengarm** [comment]
Subscribed, we really need this :(

**Comment by SunboX** [comment]
There's someone from Xamarin working on the ZXing.NET Windows Universal sample. This may help implementing the Cordova plugin: https://github.com/Redth/ZXing.Net.Mobile/tree/master/Samples/WindowsUniversal

**Comment by vladimir-kotikov** [comment]
This doesn’t mentioned in plugin’s README, but plugin works fine with Windows 10 apps. The only thing, one of ARM, x86 or x64 target architectures must be specified explicitly, since Windows 10 apps can’t be built for AnyCPU.

**Comment by konradhalas** [comment]
@vladimir-kotikov thank you for your comment, you saved my day! :1st_place_medal: :
